### ISSUE TITLE
Only one bank of PCRs returned from the TPM_PCR_Read

### ISSUE THREAD

**Issue by wojciechozga** [stefanberger/swtpm#101]
Hello Stefan!       

I send TPM_PCR_Read command to the swtpm in which I want to get PCRs[0-23] for both Sha1 and Sha256. This ends up in something like this:
```
unsigned char read_pcr[] = {
                0x80, 0x01,             // 2 bytes, TPM_ST_NO_SESSIONS
                0x00, 0x00, 0x00, 0x1a, // 4 bytes, command size = 10 + 4 + 6*2
                0x00, 0x00, 0x01, 0x7e, // 4 bytes, Command code of TPM_CC_PCR_Read = 0x0000017E
                0x00, 0x00, 0x00, 0x02, // TPML_PCR_SELECTION
                0x00, 0x0b,             // 2 bytes, TPMI_ALG_HASH, SHA1=4
                0x03,                   // 1 bytes, size of the select
                0xff, 0xff, 0xff,       // 3x1byte, pcrSelect
                0x00, 0x04,             // 2 bytes, TPMI_ALG_HASH, SHA256=11
                0x03,                   // 1 bytes, size of the select
                0xff, 0xff, 0xff        // 3x1byte, pcrSelect
};
res = TPMLIB_Process(&rbuffer, &rlength, &rtotal, read_pcr, sizeof(read_pcr));
```

The swtpm returns, however, only the first bank of the first algorithm requested. So, the response contains the following:
```
...
0x00, 0x00, 0x00, 0x02, // TPML_PCR_SELECTION
0x00, 0x0b,             // 2 bytes, TPMI_ALG_HASH, SHA1=4
0x03,                   // 1 bytes, size of the select
0xff, 0x00, 0x00,       // 3x1byte, pcrSelect
0x00, 0x04,             // 2 bytes, TPMI_ALG_HASH, SHA256=11
0x03,                   // 1 bytes, size of the select
0x00, 0x00, 0x00        // 3x1byte, pcrSelect
...
```

Is this a misbehaviour of the swtpm or I missed something in the TPM2.0 spec [1]? 

[1]: https://www.trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf

**Comment by stefanberger** [comment]
Which version of libtpms are you using? Recent versions of libtpms should have 4 PCR banks.

**Comment by stefanberger** [comment]
If you are using `TPMLIB_Process` you are not using swtpm but libtpms directly.

**Comment by wojciechozga** [comment]
I use libtpms from branch tpm2-preview.rev146.v2 since it worked with swtpm from branch tpm2-preview.v2 (I followed https://github.com/stefanberger/swtpm/issues/4#issuecomment-385998296).  

Sha1 and Sha256 banks are supported -- I can query each bank separately and get correct digests. However, when I request both banks within a single TPM_PCR_Read command, I get only digests from the bank specified as a first one in the TPML_PCR_SELECTION.

**Comment by stefanberger** [comment]
With this input:

```
    unsigned char tpm2_pcr_read[] = {
                0x80, 0x01,             // 2 bytes, TPM_ST_NO_SESSIONS
                0x00, 0x00, 0x00, 0x1a, // 4 bytes, command size = 10 + 4 + 6*2
                0x00, 0x00, 0x01, 0x7e, // 4 bytes, Command code of TPM_CC_PCR_Read = 0x0000017E
                0x00, 0x00, 0x00, 0x02, // TPML_PCR_SELECTION
                0x00, 0x04,             // 2 bytes, TPMI_ALG_HASH, SHA1=4
                0x03,                   // 1 bytes, size of the select
                0x00, 0x00, 0xf0,       // 3x1byte, pcrSelect
                0x00, 0x0b,             // 2 bytes, TPMI_ALG_HASH, SHA256=11
                0x03,                   // 1 bytes, size of the select
                0x00, 0x00, 0xf0        // 3x1byte, pcrSelect
    };
```
I get the following mixed result, which seems correct. It may be due to limited buffer size for the response.

```
80 01 00 00 01 02 00 00 00 00 00 00 00 15 00 00
00 02 00>04 03 00 00 f0 00 0b 03 00 00 f0< 00 00                                                      
00 08 00 14 ff ff ff ff ff ff ff ff ff ff ff ff                                                      
ff ff ff ff ff ff ff ff 00 14 ff ff ff ff ff ff                                                      
ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 14                                                      
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                                                      
ff ff ff ff 00 14 00 00 00 00 00 00 00 00 00 00                                                      
00 00 00 00 00 00 00 00 00 00 00 20 ff ff ff ff                                                      
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                                                      
ff ff ff ff ff ff ff ff ff ff ff ff 00 20 ff ff                                                      
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                                                      
ff ff ff ff ff ff ff ff ff ff ff ff ff ff 00 20                                                      
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                                                      
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff                                                      
00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00                                                      
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00                                                     
00 00
```

TPM 2 src/tpm2/PCR.c states this:
```
/* 8.7.3.23 PCRRead() */                                                                             
/* This function is used to read a list of selected PCR.  If the requested PCR number exceeds the       maximum number that can be output, the selection is adjusted to reflect the actual output PCR. */
```

The code seems to return a maximum of 8 PCRs' values.

**Comment by wojciechozga** [comment]
ok, everything is clear now. Thanks!

**Comment by martingalvan** [comment]
Hi all, sorry for thread necromancy. I've read the TPM spec and saw that the TPM can return less PCRs than requested in two cases: if the output buffer size is limited (this issue), and if some PCR isn't implemented for a given hash algorithm. How does swtpm distinguish between both cases?

**Comment by stefanberger** [comment]
The general function to read the PCRs is here in libtpms: https://github.com/stefanberger/libtpms/blob/master/src/tpm2/PCR.c#L758

This one filters out unimplemented PCRs from the request: https://github.com/stefanberger/libtpms/blob/master/src/tpm2/PCR.c#L758

Does this answer your question?

**Comment by martingalvan** [comment]
Hi Stefan, thanks for the quick response. My question was more about how can a user of those functions distinguish between PCRs that are missing because they're not implemented vs missing PCRs because there's not enough buffer space.

**Comment by wojciechozga** [comment]
Hi Martin,

Not the most performant but reliable and simple solution would be to read each PCR within a separate `TPM2_PCR_Read` command.

**Comment by martingalvan** [comment]
Hi Wojciech, thanks for the response. I just noticed that the spec also mentions a `TPM_CAP_PCRS` capability that indicates which PCRs are implemented; maybe that would be the way to go.

**Comment by stefanberger** [comment]
GetCapability shows you which PCR banks are there and active and the mask of PCRs.
```
# ./getcapability -cap 5
4 PCR selections
    hash TPM_ALG_SHA1
    TPMS_PCR_SELECTION length 3
    ff ff ff 
    hash TPM_ALG_SHA256
    TPMS_PCR_SELECTION length 3
    ff ff ff 
    hash TPM_ALG_SHA384
    TPMS_PCR_SELECTION length 3
    00 00 00 
    hash TPM_ALG_SHA512
    TPMS_PCR_SELECTION length 3
    00 00 00 
```

**Comment by martingalvan** [comment]
Right, that was what I had in mind. Thanks!
