### ISSUE TITLE
Does not work if installed into /usr/local

### ISSUE THREAD

**Issue by Vogtinator** [stefanberger/swtpm#103]
It looks like it cannot deal with prefix being /usr/local - the configuration files are installed into /usr/local/etc and never read from there and swtpm_setup fails with `Error: Error running '/usr/share/swtpm/swtpm-localca`.

**Comment by stefanberger** [comment]
Thanks for reporting this problem. I just checked in a fix for it into master.next branch. Can you pull from this branch and start with `./autogen.sh --prefix=/usr/local ...` again and see whether this now fixes the problem?

**Comment by Vogtinator** [comment]
Does not work, I get

> Error: Cannot access config file NONE/etc/swtpm_setup.conf.

I think `Error: Error running '/usr/share/swtpm/swtpm-localca` would still be there, but I didn't uninstall my /usr installation yet to avoid breaking it.

**Comment by stefanberger** [comment]
I just did a (forced) update on master.next. Can you try again?

**Comment by stefanberger** [comment]
PR https://github.com/stefanberger/swtpm/pull/104 should fix this now and keep config files separate between `--prefix=/usr` and `--prefix=/usr/local`.

**Comment by Vogtinator** [comment]
> I just did a (forced) update on master.next. Can you try again?

I wiped my `/usr` installation and with `/usr/local` it works fine now out of the box.

Thanks!

**Comment by stefanberger** [comment]
Glad to hear. I will let you close the issue.
