### ISSUE TITLE
Cannot do anything with the vTPM on host and in VM because of weird TPM state

### ISSUE THREAD

**Issue by wbiker** [stefanberger/swtpm#11]
Hi,

I want to use the vTPM in a qemu Windows image. Unfortunately, I don't get it running.
First, the software:
Ubuntu 16.04.1
Qemu v2.6.0+tpm
libtpm
and swtpm.
I set-up the qemu and swtpm with ./configure, make and so on. 
Did not get swtpm running until I used the dep package.
Eventually, all works without errors. Create vtpm works with:
mkdir /tmp/myvtpm0
chown -R tss:root  /tmp/myvtpm0
swtpm_setup --tpm-state /tmp/myvtpm0  --createek

export TPM_PATH=/tmp/myvtpm0
swtpm_cuse -n vtpm0

and then start the Widnows image with:
qemu-system-x86_64 -vga qxl -spice port=5959 -machine accel=kvm -m 3G -nographic -bios /seabios-1.9.2/out/bios.bin
-tpmdev \
    cuse-tpm,id=tpm0,path=/dev/vtpm0 -device tpm-tis,tpmdev=tpm0 test.img

First it looks all fine. Windows booted up and in the TPM Administration window is the TPM ready. But if you want to do anything with it that fails and WIndows shows an error message like this:
Cannot change TPM owner password
The TPM may not be in the correct state to perform this action. An internal error has occurred within the Trusted Platform Module support program. Error code 0x80284001

I do not blame Windows because on the host I cannot initialize the vTPM as well. tpm_clear ask for the owner password but ooo is not accepted.
If I set another password with the swtpm_setup program it does not work neither :-(

So, what could be the problem?
Thanks,
Wolfgang

**Comment by stefanberger** [comment]
Do you have SeaBIOS with TPM support enabled running? If you activate the SeaBIOS menu using QEMU command line options (-boot menu=on I think should do that), do you see a menu option 't' for the TPM? If not, you may need to grab a newer version of SeaBIOS and compile it with TPM support. The firmware's job is to initialize the TPM and Windows may not be able to use it unless the firmware has initialized it.

**Comment by wbiker** [comment]
Thanks a lot. That was the hint I was needed. I already have seabios compiled, but obviously not with TPM support enabled. I will check that on Monday morning. 
Thanks a bunch!

**Comment by stefanberger** [comment]
Also: You may want to copy the SeaBIOS output file out/bios.bin to the QEMU git checkout file qemu.github/pc-bios/bios-256k.bin, essentially overwriting this file, and then run 'make install' on QEMU. QEMU will install the BIOS into the proper location from where it will later on pick it up. If you ever install QEMU again, it will install this BIOS then.

**Comment by wbiker** [comment]
That helps a lot! Many thanks for this tip!

**Comment by wbiker** [comment]
Hi Stefan,

Weird thing happened. Today I downloaded seabios 1.9.3 and checked with make menuconfig the TPM setting. It is enabled by default but after making the bin file and booting windows with it, suddenly Windows says there is not TPM hardware available. I thought that must be a problem with 1.9.3 and switched back to my old one 1.9.2. Checked here the TPM setting and it is enabled as well. Anyways, Windows no longer recognized the vTPM emulated hardware with the Seabios 1.9.2 neither. 
With qemu parameter "-bios menu=on" I just have the Boot Menu and can select the boot device. No other options shown, and after creating the vTPM and try to clear it with "tpm_clear /dev/vtpm0" I get a owner password prompt but ooo does not work.

I have no idea where or what the problem is. I hope you can help me again

**Comment by wbiker** [comment]
here the output when I create the vTPM:
255 root@LZ-QEMU1 ~ # ./createTPM                                                                                                  
Starting vTPM manufacturing as tss:tss @ Mon 08 Aug 2016 07:44:41 AM CEST
TPM is listening on TCP port 56795.
Successfully created EK.
Successfully authored TPM state.
Ending vTPM manufacturing @ Mon 08 Aug 2016 07:44:41 AM CEST
root@LZ-QEMU1 ~ # cat ./createTPM 
export TPM_PATH=/tpm/vtpm0
swtpm_setup --tpm-state /tmp/vtpm0 --createek
swtpm_cuse -n vtpm0

root@LZ-QEMU1 ~ # tpm_clear /dev/vtpm0 
Enter owner password: 
Tspi_TPM_ClearOwner failed: 0x00000001 - layer=tpm, code=0001 (1), Authentication failed

**Comment by wbiker** [comment]
ah, found the t. TPM Configuration menu. So, at least I have the appropriate Seabios. 
Unfortunately, if I enter "t" it says me: "TPM is not working correctly".

Do I initialize the vTPM wrong? See comment above.

**Comment by stefanberger** [comment]
Try using a clean directory for the state of the vTPM and start it without creating certificates etc. Then enter the SeaBIOS menu and see whether you get the appropriate menu.

**Comment by stefanberger** [comment]
So from the error message above you seem to be using tpm_clear that is a tool of the Trousers TSS. For this tool to work you would probably have to start the vTPM to provide /dev/tpm0 (which may clash with the name of the device of the hardware TPM of your system) and initialize it using swtpm_ioctl /dev/tpm0. Also see the discussion at https://github.com/stefanberger/swtpm/issues/5 for this. Then you would have to start the TSS and you should probably be able to use that tool then. It requires the TSS to be running and the TSS has to be able to talk to the TPM, in this case the vTPM.

**Comment by wbiker** [comment]
OK I cannot use the tpm_* tools without changes. I do not want to use them, a running vTPM chip inside my images is enough for me :-)
So, figuring out what I do wrong...
I removed and created the state folder again but the seabios TPM configuration says still TPM hardware not working correctly. :-( Tried it with and without --createek

**Comment by stefanberger** [comment]
When you built 'swtpm', did you run 'make check'? Did all of the tests pass ?

Try running only these commands here:

rm -rf /tmp/myvtpm0
mkdir /tmp/myvtpm0
export TPM_PATH=/tmp/myvtpm0
swtpm_cuse -n vtpm0

qemu-system-x86_64 -vga qxl -spice port=5959 -machine accel=kvm -m 3G -nographic -bios /seabios-1.9.2/out/bios.bin -boot menu=on -tpmdev cuse-tpm,id=tpm0,path=/dev/vtpm0 -device tpm-tis,tpmdev=tpm0 test.img

**Comment by wbiker** [comment]
Yes, I just invoked the tests with make check and all passed.

And I wrote what you list in your comment, but then qemu says /dev/vtpm0 does not exists.
Is the swtpm_setup line missing on purpose?

**Comment by stefanberger** [comment]
I left out the swtpm_setup line to find out why it may be failing for you. The 'swtpm_cuse -n vtpm0' should create the CUSE TPM providing /dev/vtpm0. Please try again with the following:

rm -rf /tmp/myvtpm0
mkdir /tmp/myvtpm0
export TPM_PATH=/tmp/myvtpm0
swtpm_ioctl -s /dev/vtpm0
swtpm_cuse -n vtpm0
swtpm_ioctl -i /dev/vtpm0

The 1st swtpm_ioctl shuts down a currently running CUSE TPM providing /dev/vtpm0. If it fails, then no such CUSE TPM was running, which would be ok.
swtpm_ioctl -i /dev/vtpm0 will try to send a TPM_INIT to the TPM and if that fails, there's another problem with the CUSE TPM not staying alive.

**Comment by wbiker** [comment]
Cool, thanks for your support, once more.
I tried your commands. 
swtpm_setup -s failed, because the qemu image shut down already and the vTPM was destroyed.
The swtpm_cuse and the swtpm_ioctl hav finished without errors

**Comment by stefanberger** [comment]
QEMU cleans up after itself and shuts down the vTPM. So you will have to try to restart the vTPM every time before starting QEMU.

**Comment by wbiker** [comment]
Of course. But Windows still cannot use the TPM. I tried it with W10 and W81 images.
Should it work when swtpm_ioctl -i does not report an error?

**Comment by stefanberger** [comment]
I never tried with Windows, so I cannot tell.  It could be related to a driver issue where the driver only reacts to certain IDs found in the ACPI table that describes the TPM device.

A related problem may have been the following one, but this particular problem should have been resolved in QEMU 2.6: https://bugzilla.redhat.com/show_bug.cgi?id=1281413

It should work when swtpm_ioctl -i did not report an error and if SeaBIOS does not report an error, either.

**Comment by wbiker** [comment]
OK, thanks for your help. 
I have got qemu 2.6 running and neither swtp_ioctl nor SeaBios show an error :-(
I think I have to give up. I have no idea what is the problem here.

**Comment by wbiker** [comment]
Probably a Windows issue :-(
