### ISSUE TITLE
swtpm and QEMU communicating over TCP

### ISSUE THREAD

**Issue by wojciechozga** [stefanberger/swtpm#112]
Hello Stefan,

I would like to configure swtpm in a way it is accessed by QEMU via a tcp socket. 

I run swtpm using the following configuration: 
```
swtpm socket --tpmstate dir=${VTPM_DIR_PATH} --ctrl type=tcp,port=10001 --log file=${VTPM_DIR_PATH}/vtpm.log,level=20  --tpm2
```

I run QEMU in the following way:
```
qemu-system-x86_64 
-chardev socket,id=chrtpm,host=localhost,port=10001 \
-tpmdev emulator,id=tpm0,chardev=chrtpm \
-device tpm-tis,tpmdev=tpm0  \
...
```

However, I get the following error:
```
 Ctrl Cmd: length 4
 00 00 00 10 
no valid data socket in message; cmsg = 0x10006ee470 Ctrl Rsp: length 4
 00 00 00 03 
 Ctrl Cmd: length 4
 00 00 00 03 
 Ctrl Rsp: length 4
 00 00 00 00
```

According to the documentation, PTM_CAP_SET_DATAFD applies only to UnixIO. 
```
PTM_CAP_SET_DATAFD (since v0.1)
The CMD_SET_DATAFD command is supported. This command only applies to UnixIO and there is no support for PTM_SET_DATAFD.
```

I am able to run swtpm over unixio and make Qemu using it. However, I have another use case in which I have to use the tcp protocol. 
1) Is it possible? 
2) Is there a plan to support TLS inside swtpm?

Thanks!

**Comment by stefanberger** [comment]
Using TCP is not possible since there is no support for it in QEMU. I also do not have plans to implement TLS support inside swtpm.

**Comment by stefanberger** [comment]
I updated above comment. I never tried with TCP.

**Comment by stefanberger** [comment]
Ah, we use Unix sockets for passing file descritors. This doesn't work with a TCP socket.

**Comment by wojciechozga** [comment]
Thank you for the information! For my experiments, I will have a look on how do it.

**Comment by caiqs-sys** [comment]
Hi, Have you implement the tcp channel between swtpm and QEMU? @wojciechozga

**Comment by stefanberger** [comment]
> Hi, Have you implement the tcp channel between swtpm and QEMU? @wojciechozga

Please don't use TCP if Unix sockets already works. We don't need unnecessary eavesdropping on a TCP channel.
