### ISSUE TITLE
no details in /sys/kernel/security/tpm0/ascii_bios_measurements

### ISSUE THREAD

**Issue by rangoe** [stefanberger/swtpm#12]
I have installed qemu, seabios and swtpm etc  in  host os,   and can see /dev/tpm0  in guest os.
IMA works well, cat /sys/kernel/security/tpm0/ascii_bios_measurements  can show  many details, 
however, there is nothing in /sys/kernel/security/tpm0/ascii_bios_measurements.
tpm_ command could be used too. Could you help me ? thanks

**Comment by stefanberger** [comment]
You need to run a firmware that has TPM support inside the GuestOS. Recent SeaBIOS has been extended with TPM support. Once you run SeaBIOS with TPM support inside the Guest then this will show log entries in /sys/kernel/security/tpm0/ascii_bios_measurements.

**Comment by rangoe** [comment]
I understand, but I do not know how or where to configure SeaBIOS. Do I need to configure inside qemu, can you figure out more technical details? thanks.

**Comment by stefanberger** [comment]
Are you using the QEMU in my git repository (this one: https://github.com/stefanberger/qemu-tpm)  or are you using QEMU that comes with your distribution ? For the SWTPM to work, you would have to use the QEMU from my git repository.

Ypu could clone the latest SeaBIOS repository and compile it. You may want to follow the instructions here: https://www.seabios.org/Download. Using 'make menuconfig' in the seabios directory you would then have to ensure that under 'BIOS Interfaces' the "TPM support and TCG BIOS extensions" are enabled. By default they should be. Then run 'make'. The resulting out/bios.bin is the firmware with TPM support that you would have to copy over the existing bios-256k.bin. You may want to copy the file to  /usr/share/seabios/bios-256k.bin or /usr/share/qemu/bios-256k.bin, or both, whatever exists, and then try running QEMU again. If the SeaBIOS menu is enabled, then there should be a menu item 't' for the TPM.

**Comment by rangoe** [comment]
Thanks a lot , Professor. Your suggestion works for me. I did not overwrite out/bios.bin , that is the reason of no measurements.  I appreciate your attention today, Looking forward your new research results.
