### ISSUE TITLE
There was error about loading policy configuration from tmp/swtpm_svirt.tmp  after "make" command in tag-v0.1.0.

### ISSUE THREAD

**Issue by Snoopywy** [stefanberger/swtpm#124]
Hi,
I had executed successfully the command $ ./autogen.sh
$ ./configure --prefix=/usr.
There was error when executing "make" as follow:

make[4]: Entering directory `/root/swtpm/src/selinux'
Compiling targeted swtpm_svirt module
/usr/bin/checkmodule:  loading policy configuration from tmp/swtpm_svirt.tmp
swtpm_svirt.te:19:ERROR 'permission map is not defined for class file' at token ';' on line 3514:
allow svirt_t swtpm_exec_t:file { entrypoint map };
allow svirt_t user_tmp_t:sock_file { create setattr };
swtpm_svirt.te:27:ERROR 'permission map is not defined for class file' at token ';' on line 3522:
allow svirt_tcg_t swtpm_exec_t:file { entrypoint map };
allow svirt_tcg_t virt_var_run_t:dir { write add_name remove_name };
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make[4]: *** [tmp/swtpm_svirt.mod] Error 1
make[4]: Leaving directory `/root/swtpm/src/selinux'
make[3]: *** [swtpm_svirt.pp] Error 2
make[3]: Leaving directory `/root/swtpm/src/selinux'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/swtpm/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/swtpm'
make: *** [all] Error 2

The version is tag-v0.1.0.  OS:CentOS Linux release 7.4.1708 (Core).

**Comment by stefanberger** [comment]
I have it compiling fine on CentOS 7.6.1810. You may want to update your host.

**Comment by stefanberger** [comment]
Does it work for you? The language seems to have been extended and updating to a later version of the OS should be ok. Other solution is to `./configure --without-selinux [...]`.
