### ISSUE TITLE
No errors while creating vtpm but bios says TPM is not working correctly

### ISSUE THREAD

**Issue by wbiker** [stefanberger/swtpm#13]
Hi Stefan,
I hope you can help me once more, because vtpm does not work and I have no idea where is the problem:
OS is ubuntu with your qemu-tpm running. Configure, building and make install worked fine.
Additionally, your swtpm is cloned and build as well and the qemu images uses the seabios-tpm binary as well.
There is no error if creating the vtpm, but other than that all communication failed.
Here is what I do:

root@LZ-QEMU1 ~ # cat createTPM 
export TPM_PATH=/tpm/vtpm0
rm -r /tmp/vtpm0
mkdir /tmp/vtpm0
chown -R tss:root /tmp/vtpm0
swtpm_setup --display --tpm-state /tmp/vtpm0 --createek
swtpm_cuse -n vtpm0
root@LZ-QEMU1 ~ # ./createTPM 
Starting vTPM manufacturing as tss:tss @ Mon 12 Sep 2016 10:09:53 AM CEST
TPM is listening on TCP port 42390.
Successfully created EK.
TSS is listening on TCP port 57035.
Successfully took ownership of the TPM.
Successfully gave up ownership of the TPM.
TPM is listening on TCP port 42128.
Successfully enabled and activated the TPM
Successfully authored TPM state.
Ending vTPM manufacturing @ Mon 12 Sep 2016 10:09:53 AM CEST

Looks ok so far, but neither qemu nor swtpm_bios can use the vTPM:
swtpm_bios --tpm /dev/vtpm0
TPM_Startup(0x01) returned error code 0x00000009
TSC_PhysicalPresence(CMD_ENABLE) returned error code 0x00000009
TSC_PhysicalPresence(PRESENT) returned error code 0x00000009
TPM_PhysicalEnable returned error code 0x00000009
TPM_PhysicalSetDeactivated returned error code 0x00000009

root@LZ-QEMU1 ~ # /repos/qemu-tpm/build/x86_64-softmmu/qemu-system-x86_64 -rtc base=localtime -net nic,macaddr=DE:AD:BE:EF:0A:B1 -net bridge,br=br0 -vga qxl -spice port=5804,disable-ticketing -machine accel=kvm -boot c -m 3G -bios /repos/seabios-tpm/out/bios.bin -nographic -hda /data/hdd/fedora42.img -boot menu=on -tpmdev cuse-tpm,id=tpm0,path=/dev/vtpm0 -device tpm-tis,tpmdev=tpm0

The bios has the t menu, but if I use it I only get the message TPM is not working correctly.
I build qemu-tpm again and installed it to be sure it is the proper qemu version.
Do you have an idea where could be the problem?

**Comment by stefanberger** [comment]
You have a  typo in your TPM_PATH variable. It should be /tmp/vtpm0 rather than /tpm/vtpm0.

The following script then works:

#!/bin/bash
[ -c /dev/vtpm0 ] && swtpm_ioctl -s /dev/vtpm0

export TPM_PATH=/tmp/vtpm0
rm -r ${TPM_PATH}
mkdir ${TPM_PATH}
chown -R tss:root /tmp/vtpm0
swtpm_setup --display --tpm-state /tmp/vtpm0 --createek

swtpm_cuse -n vtpm0
swtpm_ioctl -i /dev/vtpm0

# swtpm_bios --tpm-device /dev/vtpm0

**Comment by wbiker** [comment]
Sorry for this useless Question :-(
Now it works. At least I get some information, but I cannot clear the TPM in the Fedora 24 image. tpm_clear ask for the password but ooo is not accepted. Also tpm_getpubkey -u -z shows an error befor the public endorsement key is printed:
Tspi_TPM_GetPubEndorsementKey failed: 0x00000008 - layer=tpm, code=0008 (8), The TPM target command has been disabled.
Is that a configuration issue, or is there still something wrong?

**Comment by stefanberger** [comment]
The EK has been created but ownership of the TPM has not been taken by the setup script. So tpm_clear is not expected to work and this program always asks for the ownership password without first checking whether the TPM is actually owned. 

I don't have the command tpm_getpubkey. Is that a typing error and it should be tpm_getpubek. Try tpm_getpubek instead.
Can you try to run tpm_takeownership to take ownership of the TPM?

**Comment by wbiker** [comment]
Yes, typo, I meant tpm_getpubek.
the first time I tried tpm_takeownership -u -y -z nothing was printed. The next time the same error message is shown.
Tspi_TPM_GetPubEndorsementKey failed: 0x0000008 - layer=tpm, code=0008 (8), The TPM target command has been disabled.
So I assume the takeownership worked the first time.

**Comment by stefanberger** [comment]
The command

    tpm_takeownership -u -y -z

is completely silent when it succeeds. So, yes, it succeeded the first time you ran it. After that I can run 

    tpm_getpubek -z

and this then shows me the public EK with that special password (-z) that I wouldn't be able to enter  via keyboard.

**Comment by wbiker** [comment]
OK, then I think something is not working properly, because tpm_getpubek -z prints:
[root@localhost wolf]# tpm_getpubek -z
Tspi_TPM_GetPubEndorsementKey failed: 0x00000008 - layer=tpm, code=0008 (8), The TPM target command has been disabled
Public Endorsement Key:
  Version:   01010000
  Usage:     0x0002 (Unknown)
  Flags:     0x00000000 (!VOLATILE, !MIGRATABLE, !REDIRECTION)
  AuthUsage: 0x00 (Never)
  Algorithm:         0x00000020 (Unknown)
  Encryption Scheme: 0x00000012 (Unknown)
  Signature Scheme:  0x00000010 (Unknown)
  Public Key:
	c7a6cda8 d029f6d6 d8182c3b 30dd8939 ff7e70b6 1463986e 57734896 b6ad9d7e
	f64c36a4 288ab67c 1c26e8b0 935c06a8 5a6947dd a696e5c6 027e95c3 7ded3234
	9a7ea168 cad5ce61 963a81c5 21e437ff 9e866d1b d3e24e14 72eb080a b57f4f39
	451c387e 185da8ff 0b0a9547 d7e69833 820dbed8 5e95ea91 4772107b 72dc13e8
	cb4f393e bf2e200b 8764ef32 6ee8373d 3e36290a e457cfd1 af06771e cfa9707f
	086f92b9 e1e82df7 f8e0ad9e e3a90409 fe5935a2 8821900e c135eb04 6babf15b
	b4430eb6 c20e02c7 a723912a 7d8a6daa 18fe4800 3d2511e2 539f0501 58975b9a
	ad89d5ea 8212ed77 0cfdfee9 3f6c1521 7656002a 08788be4 171abf9b 26a8184d
Do you have a idea, whats/where is wrong?
Thanks

**Comment by stefanberger** [comment]
There's nothing wrong with the command. There is one command to retrieve the public EK **before** ownership of the TPM is taken and it's probably trying to use that command first. Since it fails, it then tries to use the command to retrieve the public EK with the owner password. The error output is misleading, but nothing is wrong.

**Comment by wbiker** [comment]
Ok, thx. You already recognized I have no glue about TPM stuff, but would verify that the Windows TPM problem is because of Windows and not from an misconfigured TPM.
 Anyway, thanks for your patient.

**Comment by stefanberger** [comment]
So you are also trying this on Windows ? Does Windows show the TPM in the device manager? Previously some of the issues with Windows and vTPM were related to ACPI tables, but this should now work in QEMU 2.6 and later.

**Comment by wbiker** [comment]
yes, actually I setup Qemu and vTPM for Windows tests. And yes the TPM is shown in Windows, but not working though. Windows says TPM is ready, but if I click on Change Owner Password or Clear TPM Windows prompts an error message: The TPM may not be in the correct state to perform this action. Error code: 0x80284001.
Before we have to switch to Windows Server with Hyper-V and its emulated TPM :-( I want to check whether the TPM works with Fedora. if yes, then Windows is to blame and we have to use Hyper-V. If not, and first I thought it looks like that (because of my lack of TPM knowledge), there is a bug in vTPM. But with your help, I think it is a Windows issue. So, I have no other choice than setup Windows with Hyper-V :-(

**Comment by stefanberger** [comment]
Dod you run the QEMU VM with a version of SeaBIOS that has TPM support ?

**Comment by wbiker** [comment]
Yes I did. I used your seabios-tpm project to compile a bios.bin file and used that with qemu. The BIOS shows the T menu and that prints some options. It says also that the TPM is enabled and active and that the ownership has been taken. Looks good until I try to use the TPM within Windows.
I tried to deactivate/activate the TPM in the BIOS, still Windows print the error.
