### ISSUE TITLE
Learn to read keyfile from passed FD

### ISSUE THREAD

**Issue by elmarco** [stefanberger/swtpm#140]
keyfile and passphrasefile arguments must be paths to file on disk. Instead, it should be possible to pass the keys from a given FD.

**Comment by stefanberger** [comment]
Correct.

**Comment by elmarco** [comment]
btw, have you looked at adding encrypted tpm state to libvirt? we had a discussion on irc, kayshap is supposed to open a libvirt bug, but in case he forgets, I thought I could mention here

**Comment by stefanberger** [comment]
I looked at it a long time ago. I had it based on virtSecrets that also need to be able to migrate. I would have to look for the code whether I still have it somewhere.

We'll have to scrape the help screen of swtpm if we want to pass the secret via fd, otherwise fall back to passing it via file that swtpm can remove if 'remove' is passed in the command line.

**Comment by elmarco** [comment]
it may be time to support --print-capabilities with some spec, similar to vhost-user:
https://git.qemu.org/?p=qemu.git;a=blob;f=docs/interop/vhost-user.rst;h=dc0ff9211ff520be10194dc2465f08d65b527627;hb=HEAD#l1307

and I started something similar for slirp-helper:
https://gitlab.freedesktop.org/slirp/libslirp-rs/blob/master/src/bin/README.rst

**Comment by stefanberger** [comment]
Even for this we will need a help screen scraper...

Here's the branch with the ancient vTPM state encryption support: https://github.com/stefanberger/libvirt-tpm/commits/v1.2.14-maint-vtpm

**Comment by elmarco** [comment]
Not necessarily, if --print-capabilites fails, we can assume some basic features.

**Comment by stefanberger** [comment]
Are you implementing the file descriptor support or should I do it ?

**Comment by elmarco** [comment]
I am not working on it right now, I'll tell you if I do, but there is a good chance you do it before :)

**Comment by stefanberger** [comment]
I think we can close this issue now... and work on the next.

**Comment by stefanberger** [comment]
@elmarco FYI: Libvirt patches for encrypted vTPM state support: https://github.com/stefanberger/libvirt-tpm/commits/vtpm_encrypted_state
