### ISSUE TITLE
Report capabilities like supported command line options, control channel commands etc. via command line option

### ISSUE THREAD

**Issue by stefanberger** [stefanberger/swtpm#143]
Report capabilities like supported command line options, control channel commands etc. via command line option `--print-capabilities`.

**Comment by stefanberger** [comment]
@elmarco Current prototype returns this here:
```
$ ./src/swtpm/swtpm socket --print-capabilities | jq
{
  "options": {
    "log": [
      "file",
      "fd",
      "level",
      "prefix",
      "truncate"
    ],
    "key": [
      "file",
      "mode",
      "format",
      "remove",
      "pwdfile",
      "kdf",
      "fd",
      "pwdfd"
    ],
    "migration-key": [
      "file",
      "mode",
      "format",
      "remove",
      "pwdfile",
      "kdf",
      "fd",
      "pwdfd"
    ],
    "pid": [
      "file",
      "fd"
    ],
    "tpmstate": [
      "dir",
      "mode"
    ],
    "ctrl": [
      "type",
      "path",
      "port",
      "bindaddr",
      "ifname",
      "fd",
      "clientfd",
      "mode",
      "uid",
      "gid"
    ],
    "server": [
      "type",
      "path",
      "port",
      "bindaddr",
      "ifname",
      "fd",
      "disconnect",
      "mode",
      "uid",
      "gid"
    ],
    "locality": [
      "reject-locality-4",
      "allow-set-locality"
    ],
    "flags": [
      "not-need-init"
    ],
    "seccomp": [
      "action"
    ]
  },
  "ctrlchannel": {
    "caps": 32767
  }
}
```

What it does not say s what actions are supported by for example `--seccomp action=none|kill|log`. I think this is the only one, though...

**Comment by elmarco** [comment]
I don't think you need to export all the command line arguments and values. Instead, you could specify what each capability gives you in general, including the command line arguments that are accepted. But if you want to be exhaustive like that, why not? Hopefully, the command line help should be enough to describe the associated capability.

what does ctrlchannel caps 32767 means btw?

It would be nicer if you had some libvirt patches to show this is ok btw.

(you may find vhost-user-gpu qemuVhostUserFillDomainGPU code interesting https://patchew.org/Libvirt/20190605103117.19047-1-marcandre.lureau@redhat.com/20190605103117.19047-13-marcandre.lureau@redhat.com/ )

**Comment by stefanberger** [comment]
I thought it would be better for higher layers, like libvirt, to parse the JSON and find out what command line parameters it supports rather than screen scrape the help screen. This way libvirt would learn that file descriptor passing for the keys and passwords is supported.

ctrlchannel caps 32767 (=0x7fff) is basically the value from this here: https://github.com/stefanberger/swtpm/blob/master.next/src/swtpm/ctrlchannel.c#L429  This value represents the flags that indicate what commands the control channel supports. For humans we could certainly enumerate it in this form as well ['PTM_CAP_INIT','PTM_CAP_GET_TPMESTABLISHED',...], but the number is enough for the machine.

Libvirt uses the swtpm v0.1 (basic) command line parameters and the flags in `caps` are only of interest to QEMU today. You mean for supporting encrypted state files it would be good to show patches that use the `--print-capabilities` ?

**Comment by elmarco** [comment]
libvirt capabilities for various commands (both for command line and runtime things) is generally implemented as an enum (after parsing help, QMP introspection, JSON caps etc).

Personally, I would have gone with a simple list of strings in --print-capabilities, but Daniel B. asked me to make it a JSON object instead.

But my point is that in general, libvirt takes capabilities to mean a bunch of things aggregated to a simple feature enum value. It can represent various command line options & runtime API.

I doubt having fine graine command line capabilities is really useful. I would aggregate capabilites, and expose them as simple list.

Yes, it would be better to have libvirt patch making use of whatever --print-capabilites you intend to add to show its usefulness.

**Comment by stefanberger** [comment]
Being able to pass a file descriptor for having swtpm read the key would be a capability like `ReadKeyFromFd` or `ReadPasswordFromFd`? Hm, wonder whether this is better than dumping just everything that's supported ?

**Comment by elmarco** [comment]
I think you should work on the libvirt patch to realize that it would be more convenient and less error-prone to have a single "keys-fd" caps.

**Comment by stefanberger** [comment]
... and only return new features in this short format ? ... and get rid of the verbose version altogether?

**Comment by elmarco** [comment]
As long as management needs a high-level feature representation, that's what I would recommend.

The day we need fine grained command line introspection, it can be added.

**Comment by stefanberger** [comment]
Revised it now to look like this:

```
./src/swtpm/swtpm socket --print-capabilities | jq
{
  "type": "swtpm",
  "features": [
    "cmdarg-seccomp",
    "cmdarg-key-fd"
  ]
}
```

**Comment by elmarco** [comment]
thanks, I think it will be more convenient this way. feel free to prove me wrong :)

**Comment by stefanberger** [comment]
Probably a difficult proof to make :-) 

... if you have time to look at the patches...

**Comment by stefanberger** [comment]
Clsoing this since it has been merged.
