### ISSUE TITLE
tpm tpm0: Operation Canceled and SWTPM_IO_Write: Error, writev() 5 Input/output error

### ISSUE THREAD

**Issue by kalloc** [stefanberger/swtpm#158]
Hi.

While I'm trying to play with vTPM using swtpm, I found strange problems.
My test environment is 4.20.17, but I have checked on 4.18 too.
After running swtpm, I always got the error:
```bash
root@sandbox:~# swtpm chardev --vtpm-proxy --tpm2 --tpmstate dir=/tmp/tpm2
New TPM device: /dev/tpm0 (major/minor = 10/224)
swtpm: SWTPM_IO_Write: Error, writev() 5 Input/output error
```

and in dmesg:
```dmesg
[  5259.267298] tpm tpm0: Operation Canceled
```

also, test_vtpm_proxy got error too:
```bash
root@sandbox:~/swtpm/tests# ./test_vtpm_proxy
Using /dev/tpm0.
Error: Chardev /dev/tpm0 did not appear
```

How to make /dev/tpm0 using swtpm in the right way?

**Comment by stefanberger** [comment]
Thanks for reporting this. There was a bug in swtpm. It cannot use writev() on the device but has to use write(). I'll apply the patch in this PR: https://github.com/stefanberger/swtpm/pull/159

**Comment by stefanberger** [comment]
It's now available in master and stable-0.2.0 branch.

**Comment by kalloc** [comment]
thanks!

**Comment by kalloc** [comment]
@stefanberger it is working
