### ISSUE TITLE
Qemu build vm with vtpm filed since there are two swtpm sockets that ctrl type and server type.

### ISSUE THREAD

**Issue by hioking** [stefanberger/swtpm#165]
Hi, Stefan

I encountered a question. 
`mkdir /tmp/mytpm1 `
`swtpm socket --tpmstate dir=/tmp/mytpm1   --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock  --server type=unixio,path=/tmp/mytpm1/swtpm-data-sock   --log level=20`

Then I saw two socks in path /tmp/mytpm1 . Next executed the line command below.

`qemu-system-x86_64  -accel kvm -m 4096 -boot d -bios /root/seabios/out/bios.bin -boot menu=on -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0  /root/test.img`

The error was reported. 
`qemu-system-x86_64: -tpmdev emulator,id=tpm0,chardev=chrtpm: tpm-emulator: Failed to send CMD_SET_DATAFD: Success`
At the same time , qemu-system-x86_64 exit.

Why does qemu can't load vtpm ?  Is that the reason there opened two socks (control  and data sock) ?

**Comment by stefanberger** [comment]
Yes, the reason is that you created two sockets. So, do not pass the '--server' parameter to 'swtpm' since QEMU will create the data channel by file descriptor passing over the control channel.

The instructions here: https://git.qemu.org/?p=qemu.git;a=blob;f=docs/specs/tpm.txt;h=5d8c26b1adba2fd22b8e96d1660ca0f2456d5da1;hb=3bd6cbbb181b6ae60a1d1f33ccd325b45f71aa2a#l275

**Comment by hioking** [comment]
Okay, I see. Thanks a lot.
Can I USE the '--server type' channel of 'swtpm' to transfer TPM data commands for a vm if don't use qemu's data channel ? Is it possible ?

**Comment by stefanberger** [comment]
You cannot use `--server type` because QEMU will trie to establish a data channel via file descriptor passing and fail if this doesn't work. It will not use the `server type` that you pass to `swtpm`.

**Comment by hioking** [comment]
Hi,
Could `swtpm` be changed the code to support data channel by fd passing over the control channel, like `qemu` ?
If so, could command `CMD_SET_DATAFD` be sent many times?  Because I noticed that the `CMD_SET_DATAFD` can be sent only once. 
Thank you, Stefan.

**Comment by stefanberger** [comment]
We only need one data channel...

**Comment by hioking** [comment]
Okay, I see.
Thanks, Stefan.
