### ISSUE TITLE
 Can other programs use vtpm data channel in addition to qemu?

### ISSUE THREAD

**Issue by xiaojunzhai** [stefanberger/swtpm#169]
Hi, Stefan
The CMD_SET_DATAFD can be sent only once by qemu, can other programs use this data channel in addition to qemu? If this data channel can be used by other programs, how can I use it?
If I have set up the data channel multiple times, will it affect the function of vtpm?

**Comment by stefanberger** [comment]
CMD_SET_DATAFD can only be used by one program. swtpm does not support multiple concurrent data channels.

**Comment by xiaojunzhai** [comment]
Can I modify swtpm to support multiple concurrent data channels？Will it affect the function of vtpm?

**Comment by stefanberger** [comment]
What is you use case?

**Comment by xiaojunzhai** [comment]
I want to use the data channel in addition to qemu,but I don't want to modify qemu.

**Comment by stefanberger** [comment]
Why do you need another data channel for another program to send TPM commands to the TPM? What's the use case for it? Why do you need multiple sources for sending commands to the TPM?

**Comment by xiaojunzhai** [comment]
Maybe my idea was wrong.I decided to give up the idea.

**Comment by stefanberger** [comment]
Ok.
