### ISSUE TITLE
Can't get swtpm to run on Fedora 23

### ISSUE THREAD

**Issue by gilhooleyd** [stefanberger/swtpm#17]
Hello! 

I am trying to install swtpm on Fedora 23 and I can't seem to get it to run or find help online. After building, the command 'make check' fails nearly everything. Additionally, 'modprobe cuse' doesn't work because cuse is not a module in 23, and I haven't been able to find documentation on what has replaced it.

Does anyone have experience with getting this library to work?

**Comment by stefanberger** [comment]
FreeBL currently doesn't work. See this issue here: https://github.com/stefanberger/swtpm/issues/15 . It's been reported to the maintainers, but they are slow to react. The only way around this is to compile libtpms with openssl support.

Did you install the kernel-modules-extra package? This one should provide the CUSE module.

**Comment by gilhooleyd** [comment]
Thanks for the response! I've gone through and compiled libtpms with openssl support. The library now passes all of the tests and installs correctly. 

I have been looking at this issue: #8 and I have been able to run the 'swtpm_ioctl' and 'swtpm_bios' commands successfully. However, I am having trouble hooking the library up to tcsd. I've been following the commands [here](http://ibmswtpm.sourceforge.net/tpm_tss.html) but tcsd seems to be unable to find a device to open.

I should mention that I am trying to use swtpm outside of QEMU, but I do not think that should cause too many issues.

**Comment by stefanberger** [comment]
The description you followed at the referenced page (http://ibmswtpm.sourceforge.net/tpm_tss.html) describes the interaction with a different implementation of a software TPM. In the case of the this TPM (swtpm project) you may want to follow the previous discussions here: http://ibmswtpm.sourceforge.net/tpm_tss.html

**Comment by stefanberger** [comment]
To run the swtpm with the socket interface you can use the following command lines and start it listening on TCP port 6543:

> mkdir /tmp/mytpm
> swtpm socket --server type=tcp,port=6543 --tpmstate dir=/tmp/mytpm

**Comment by stefanberger** [comment]
@gilhooleyd Did you get it to run ?

**Comment by gilhooleyd** [comment]
Yes, thank you! You were very helpful and it is running now. Recompiling with ssl support was the final step I needed and those other commands for bringing it up and down were very helpful
