### ISSUE TITLE
Encrypt vtpm nvram with sm4 algorithm

### ISSUE THREAD

**Issue by liujiong63** [stefanberger/swtpm#172]
Hi stefanberger,

I know swtpm supports encrypting vtpm nvram with a user input key(aes-128-cbc or aes-256-cbc).
I tried to add sm4 algorithm to encrypt nvram but failed. Checked vtpm device logs and I got "libtpms/tpm2: NV_HEADER_Unmarshal: Invalid magic. Expected 0xab364723, got 0xe81bf1b5".

I've added sm4 algorithm implementation following `swtpm_aes.c` and alter parameter condition checks. In `swtpm_nvfile.c`, I've changed the encryption/decryption algorithm from aes to sm4. Do I need to alter changes in libtpms to achieve sm4 encryption on nvram? Any other suggestions are highly appreciated.

Thanks!

**Comment by liujiong63** [comment]
@stefanberger , debug as you suggested, the data and data length before encryption match with that after decryption. The error log is still "libtpms/tpm2: NV_HEADER_Unmarshal: Invalid magic. Expected 0xab364723, got 0xe81bf1b5". I guess there's some other mechanisms validating the nvram. Haven't figured out what that is.

**Comment by liujiong63** [comment]
Hi stefanberger, thanks for your suggestions. I rechecked the logic in swtpm and succeed encrypting nvram with sm4 algorithm. However, I had to change the "PERSISTENT_ALL_MAGIC" macro defined in "src/tpm2/NVMarshal.c" from original value 0xab364723 to 0x00000000. Otherwise the error message is the same as I posted before. Could you please explain how to compute the value 0xab364723? Is it related with the encryption algorithm? Thanks!

**Comment by stefanberger** [comment]
The 'PERSISTENT_MAGIC_VALUE` is a random number to ensure that we are read the expected byte stream at this point. It cannot be changed.
