### ISSUE TITLE
Cannot use libtpms in custom location 

### ISSUE THREAD

**Issue by deitch** [stefanberger/swtpm#18]
If I install libtpms in custom location, e.g. `configure --prefix=/specialdir`, swtpm fails to configure because it only looks in the standard locations. 

In configure, it looks for the`SEARCH_DIR` by running `gcc ... -Xlinker --verbose` and filtering for `SEARCH_DIR`. As far as I can tell, the response is the default, compiled-into-gcc (well, linker) search location. Nothing will change that: not command-line options (like `-L`), not env vars `LD_LIBRARY_PATH` or `LIBRARY_PATH` or `LIBPATH`.

If I had it compiled, I could point it anywhere for run-time using env vars (or static compilation).

So I can install libtpms wherever I want, but I cannot get swtpms to configure, let alone compile, because it cannot use it to check which crypto library it is using.

**Comment by stefanberger** [comment]
The following modification enables me to configure swtpm like this after having using --prefix-/tmp on libtpms:

`LIBRARY_PATH=/tmp/lib/ CFLAGS="-I/tmp/include" ./configure --prefix=/tmp --with-openssl`

If this is how it is expected to work, I can push this change.


    diff --git a/configure.ac b/configure.ac
    index 12c7532..4f30f63 100644
    --- a/configure.ac
    +++ b/configure.ac
    @@ -352,7 +352,7 @@ AC_MSG_CHECKING([the crypto library libtpms is using])
     dirs=$($CC $CFLAGS -Xlinker --verbose 2>/dev/null | \
            sed -n '/SEARCH_DIR/p' | \
            sed 's/SEARCH_DIR("=\?\(@<:@^"@:>@\+\)"); */\1\n/g')
    -for dir in $dirs; do
    +for dir in $dirs $LIBRARY_PATH; do
       if test -r $dir/libtpms.so; then
         if test -n "`ldd $dir/libtpms.so | grep libcrypto.so`"; then
           libtpms_cryptolib="openssl"

**Comment by deitch** [comment]
I think that would make sense. Since when actually linking you can find libs in non-default paths via `$LIBRARY_PATH`, doesn't it make sense that `configure` should be able to do so as well?

**Comment by stefanberger** [comment]
Pushed.
