### ISSUE TITLE
How does qemu mount `swtpm socket --fd ...` on virtual machine?

### ISSUE THREAD

**Issue by hioking** [stefanberger/swtpm#180]
@stefanberger  hi, stefan, I just encountered this question.
I run this file in `swtpm/tests/test_clientfds.py` and got a process `swtpm socket --fd=3 --ctrl type=unixio,clientfd=5 --pid file=/tmp/w1/file.pid --tpmstate dir=/tmp/w1 `.

So how does  `qemu-system-x86_64 ...`  mount `swtpm socket` above to the virtual machine?

Thanks.

**Comment by stefanberger** [comment]
QEMU uses file descriptor passing (over Unix socket) to pass the data channel file descriptor it wants to use to `swtpm` via the control channel. It is using this command line here:

```
/usr/bin/swtpm socket --daemon \
--ctrl type=unixio,path=/var/run/libvirt/qemu/swtpm/15-Test-VM-swtpm.sock,mode=0600 \
--tpmstate dir=/var/lib/libvirt/swtpm/3c6328aa-1b82-4e67-9c48-d8a9ed9f57cb/tpm2,mode=0600 \
--log file=/var/log/swtpm/libvirt/qemu/Test-VM-swtpm.log \
--tpm2 \
--pid file=/var/run/libvirt/qemu/swtpm/15-Test-VM-swtpm.pid
```

**Comment by hioking** [comment]
ok, I see. 
Thanks a lot.
