### ISSUE TITLE
vTPM implementation TCP/IP sockets

### ISSUE THREAD

**Issue by ferdinan4** [stefanberger/swtpm#181]
Hi Stefan,

I am trying to creating a vTPM and make it works with QEMU emulation, and I guess it is working properly:
**./swtpm socket --tpmstate dir=/tmp/mytpm1 --tpm2 --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock --log level=20**

In fact wiht the seaBIOS  I can access to TPM configuration, I can replicate this with different Virtual machines, only modifiying the tpmstate:

**qemu-system-x86_64 -display sdl -accel kvm   -m 1024 -boot d -bios bios-256k.bin -boot menu=on   -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock   -tpmdev emulator,id=tpm0,chardev=chrtpm   -device tpm-tis,tpmdev=tpm0 freedos-1.0.img

qemu-system-x86_64 -display sdl -accel kvm   -m 1024 -boot d -bios bios-256k.bin -boot menu=on   -chardev socket,id=chrtpm,path=/tmp/mytpm2/swtpm-sock   -tpmdev emulator,id=tpm0,chardev=chrtpm   -device tpm-tis,tpmdev=tpm0 freedos-1.0.img**

The question is, I can use in the guess the IBM TSS in order to test if the TPM is working properly, because the problem is that TSS works only using sockets over TCP, and you said in other issue that with QEMU swtpm only support unixio.

*Another thing, How should I connected both IBM TSS and  your SWTPM in the same host to make tests only over tcp sockets?

I tried:

./swtpm socket --tpmstate dir=/tmp/mytpm3 --tpm2 --ctrl type=tcp,port=2322 --log level=20 --server type=tcp,port=2321

I can see in the log of Swtpm the parameters send by the TSS.However in the tss appears: 

**startup: failed, rc 00000101
TPM_RC_FAILURE - commands not being accepted because of a TPM failure**

Thanks in advance!

**Comment by stefanberger** [comment]
I added a page to the wiki now. Please have a look at it whether this works for you:

https://github.com/stefanberger/swtpm/wiki/Using-the-IBM-TSS-with-swtpm

**Comment by ferdinan4** [comment]
Thankyou so much for the information.

I have tried to follow the page that you added to the wiki. But I do not know why some commands are not working well.

I am working over Docker (same container).

In one terminal i am executing the next command:

**swtpm socket --tpmstate dir=/tmp/myvtpm --tpm2 --ctrl type=tcp,port=2322 --server type=tcp,port=2321 --flags not-need-init**

In the second terminal if I go to the tss/utils.

I can execute some commands such as :
**./startup
./pcrread -ha 10**
count 1 pcrUpdateCounter 21 
 digest length 32
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 


This command works well, nevetheless if I try to follow the command that you  write: **tssstartup** or **tsspcrread -ha 10**, they dont work.

[root@c0af0d837623 utils]# sudo tssstartup 
TSS_Dev_Open: Error opening /dev/tpmrm0
startup: failed, rc 000b0008
TSS_RC_NO_CONNECTION - Failure connecting to lower layer



The same happen when I try to execute **./reg.sh**



[root@c0af0d837623 utils]# ./reg.sh 

Initialize TPM

Power cycle
 ERROR:
TSS_Socket_ReceiveBytes: read EOF
powerup: failed, rc 000b0009
TSS_RC_BAD_CONNECTION - Failure communicating with lower layer



Any idea what is happening?

Thanks in advance!

**Comment by stefanberger** [comment]
I forgot to set `TPM_INTERFACE_TYPE=socsim`. Please try it with this export:

```
export TPM_COMMAND_PORT=2321 TPM_PLATFORM_PORT=2322 TPM_SERVER_NAME=localhost TPM_INTERFACE_TYPE=socsim TPM_SERVER_TYPE=raw
```

**Comment by stefanberger** [comment]
As for getting reg.sh to pass, one would need to apply this patch here to the test suite. The control channels are slightly different for the implementations, so this patch gets around the issue.

```
Index: reg.sh
===================================================================
--- reg.sh	(revision 1477)
+++ reg.sh	(working copy)
@@ -215,6 +215,15 @@
     checkSuccess $?
 }
 
+dopowerup()
+{
+    echo "$1"
+    ${PREFIX}powerup > run.out
+    if [ $? -ne 0 ] && [ -n "$(which swtpm_ioctl)" ]; then
+        swtpm_ioctl --tcp ${TPM_SERVER_NAME}:${TPM_PLATFORM_PORT} -i
+    fi
+}
+export -f dopowerup
 
 export -f checkSuccess
 export -f checkWarning
Index: regtests/inittpm.sh
===================================================================
--- regtests/inittpm.sh	(revision 1478)
+++ regtests/inittpm.sh	(working copy)
@@ -45,9 +45,7 @@
 echo "Initialize TPM"
 echo ""
 
-echo "Power cycle"
-${PREFIX}powerup > run.out
-checkSuccess $?
+dopowerup "Power cycle"
 
 echo "Startup"
 ${PREFIX}startup -c > run.out
@@ -61,9 +59,7 @@
 ${PREFIX}pcrallocate +sha1 +sha256 +sha384 +sha512 > run.out
 checkSuccess $?
     
-echo "Power cycle"
-${PREFIX}powerup > run.out
-checkSuccess $?
+dopowerup "Power cycle"
 
 echo "Startup"
 ${PREFIX}startup -c > run.out
ndex: regtests/testnvpin.sh
===================================================================
--- regtests/testnvpin.sh	(revision 1478)
+++ regtests/testnvpin.sh	(working copy)
@@ -240,9 +240,7 @@
 ${PREFIX}nvwrite -ha 01000000 -hia p -id 0 1 > run.out
 checkFailure $?
 
-echo "Reboot"
-${PREFIX}powerup > run.out
-checkSuccess $?
+dopowerup "Reboot"
 
 echo "Startup"
 ${PREFIX}startup > run.out
@@ -448,9 +446,7 @@
 ${PREFIX}nvwrite -ha 01000000 -hia p -id 0 1 > run.out
 checkFailure $?
 
-echo "Reboot"
-${PREFIX}powerup > run.out
-checkSuccess $?
+dopowerup "Reboot"
 
 echo "Startup"
 ${PREFIX}startup > run.out
Index: regtests/testpcr.sh
===================================================================
--- regtests/testpcr.sh	(revision 1478)
+++ regtests/testpcr.sh	(working copy)
@@ -191,9 +191,7 @@
     ${PREFIX}pcrallocate ${ALLOC[i]} > run.out
     checkSuccess $?
 
-    echo "powerup"
-    ${PREFIX}powerup > run.out
-    checkSuccess $?
+    dopowerup "powerup"
 
     echo "startup"
     ${PREFIX}startup > run.out
ndex: regtests/testshutdown.sh
===================================================================
--- regtests/testshutdown.sh	(revision 1478)
+++ regtests/testshutdown.sh	(working copy)
@@ -97,9 +97,7 @@
 ${PREFIX}shutdown -s > run.out
 checkSuccess $?
 
-echo "Power cycle"
-${PREFIX}powerup > run.out
-checkSuccess $?
+dopowerup "Power cycle"
 
 echo "Startup state"
 ${PREFIX}startup -s > run.out
@@ -193,9 +191,7 @@
 ${PREFIX}shutdown -s > run.out
 checkSuccess $?
 
-echo "Power cycle"
-${PREFIX}powerup > run.out
-checkSuccess $?
+dopowerup "Power cycle"
 
 echo "Startup clear"
 ${PREFIX}startup -c > run.out
@@ -253,9 +249,7 @@
 ${PREFIX}shutdown -c > run.out
 checkSuccess $?
 
-echo "Power cycle"
-${PREFIX}powerup > run.out
-checkSuccess $?
+dopowerup "Power cycle"
 
 echo "Startup clear"
 ${PREFIX}startup -c > run.out
```

**Comment by ferdinan4** [comment]
Hi Stefan!

Thank you so much! Now everything is working. However when I the tested **./reg.sh**, it doesnt give me any information about how is going the tests that it is executing: I don't know if it is because of the variable ${I} it is not updating,  or because it is not working properly.

Initialize Regression Test Keys

Create a platform primary RSA storage key
 INFO:
Create an RSA storage key under the primary key
 INFO:
Create an ECC storage key under the primary key
 INFO:
Create an unrestricted RSA signing key under the primary key
 INFO:
Create an unrestricted ECC signing key under the primary key
 INFO:
Create a restricted RSA signing key under the primary key
 INFO:
Create an RSA decryption key under the primary key
 INFO:
Create a symmetric cipher key under the primary key
 INFO:
Create a sha1 keyed hash key under the primary key
 INFO:
Create a sha256 keyed hash key under the primary key
 INFO:
Create a sha384 keyed hash key under the primary key
 INFO:
Create a sha512 keyed hash key under the primary key
 INFO:

Success - 0 Tests 0 Warnings

**Comment by stefanberger** [comment]
The output looks normal to me.

**Comment by ferdinan4** [comment]
Ok, I guessed that in the Success part  should appear the number of tests executed.

Another newbie question, if I wanna add or modify one algorithm(add new signature algorithm)  to use in the sTPM, I only have to modify the libtpms, is not it? 

I should recompiled the libtpms with the changes introduced.

Thanks in advance

Fernando

**Comment by stefanberger** [comment]
All crypto is handled by libtpms, so yes, you need to make changes there.

**Comment by ferdinan4** [comment]
Thanks 

I close the issue :)
