### ISSUE TITLE
Running entire build inside docker container for easy build

### ISSUE THREAD

**Issue by deitch** [stefanberger/swtpm#19]
I wrote a Dockerfile, script and Makefile so you can run the build anywhere and get built `libtpm*` and the `swtpm*` binaries.

Any interest in a Pull Request for it?

**Comment by stefanberger** [comment]
Unfortunately I would need you to fill out the CLA and send it in (https://github.com/stefanberger/swtpm/blob/master/cla-corporate.doc).

**Comment by deitch** [comment]
A CLA?? Oh, IBM. Big company lawyers, that explains a lot. :-(

Sorry @stefanberger. I really appreciate your work and am trying to contribute back, so more will use it, and I am happy to state here that "this is my work and I am happy to contribute it under BSD license so others can benefit," but contracts to give some gratis assistance? Sigh.

Let's make this easier. I am creating a separate repo to build the image. Released under BSD. Which means you can do with it as you wish. :-)

https://github.com/deitch/swtpm-build

**Comment by stefanberger** [comment]
@deitch I know...

**Comment by deitch** [comment]
So much spoken in so few words....''

I will close this issue. But, if you find that other repo helpful and use it in any way, kindly do let me know.

**Comment by deitch** [comment]
@stefanberger I just updated that repo after a while. It now generates both musl and libc. Your updated wiki helped. 😁 

Feel free to reference it; I noticed you have some Dockerfile builder reference in the wiki.

**Comment by stefanberger** [comment]
I have been running tests with docker containers now for quite some time: https://github.com/stefanberger/swtpm-distro-compile

**Comment by deitch** [comment]
Haha! May yours live long and prosper.
