### ISSUE TITLE
Could not choose TPM version

### ISSUE THREAD

**Issue by gethinpan** [stefanberger/swtpm#190]
Hi,

When I am running `make check`, I got 22 fails, and the log shows that could not choose TPM version, but I still run `make install`. 

And after I run the command as following:

`swtpm socket --tpmstate dir=/tmp/myvtpm --tpm2 --ctrl type=tcp,port=2322 \
   --server type=tcp,port=2321 --flags not-need-init`

I got a same error showing that could not choose TPM version.

any idea?thanks

**Comment by stefanberger** [comment]
Did you compile libtpms with `./configure --with-tpm2 ...` ?

**Comment by gethinpan** [comment]
Thank you for the answer.

**Comment by anatol** [comment]
I wonder if `--with-tpm2` should be default option.

**Comment by stefanberger** [comment]
I'll change it.
