### ISSUE TITLE
Script for SWTPM on a new Fedora image

### ISSUE THREAD

**Issue by gilhooleyd** [stefanberger/swtpm#22]
Hello,

Thank you for your work on a software TPM, this package has been very helpful. It did require a bit of setup. 
To allow my research group to easily use the swTPM package I've created a Vagrantfile that installs it on Fedora 23. The file is located here (https://gist.github.com/gilhooleyd/03f47798eb63ef36d7f80575484fd117)

To install, simply run `vagrant up`, and wait for the provisioning to complete. The system needs to be restarted (`vagrant halt` followed by `vagrant up` again) for the changes to take effect. After that the machine can be accessed by `vagrant ssh` and the normal directions for accessing the SWTPM library follows.

I thought you may find this interesting because I had some trouble finding the documentation to get the system to run correctly, and this may be helpful to others.

Best,
David

**Comment by stefanberger** [comment]
Thanks. I improved the build and install instructions a bit. So that should make it easier to build it: https://github.com/stefanberger/swtpm/blob/master/INSTALL
