### ISSUE TITLE
"FAIL: test_tpm2_derived_keys" of swtpm-0.3.0

### ISSUE THREAD

**Issue by YadongQi** [stefanberger/swtpm#220]
OS: Ubuntu 18.04.4
Kernel:  5.3.0-40-generic # 32~18.04.1-Ubuntu SMP
HW: NUC7i7DNHE

Steps:
**1. Build/Install libtpms-0.7.0:**
```
sudo apt-get -y install automake autoconf libtool libc-dev libssl-dev gawk
wget https://github.com/stefanberger/libtpms/archive/v0.7.0.tar.gz
tar zxvf v0.7.0.tar.gz
cd libtpms-0.7.0
./autogen.sh --with-tpm2 --with-openssl --prefix=/usr
make -j4
make -j4 check
sudo make install
```
**2. Build/Install swtpm-0.3.0:**
```
sudo apt-get -y install net-tools libseccomp-dev libtasn1-6-dev libgnutls28-dev expect
wget https://github.com/stefanberger/swtpm/archive/v0.3.0.tar.gz
tar zxvf v0.3.0.tar.gz
cd swtpm-0.3.0
./autogen.sh --with-openssl --prefix=/usr
make -j4
make -j4 check
sudo make install
```

When do `make check` of swtpm, there is one failure: **`FAIL: test_tpm2_derived_keys`**.
I checked tests/test-suit.log:
>Error: Did not get expected return from creating key
expected:  80 02 00 00 00 71 00 00 00 00 80 00 00 00 00 00 00 5a 00 00 00 32 00 25 00 0b 00 06 04 60 00 00 00 03 00 80 00 43 00 20 91 28 1c bc ac 9d d6 6d 29 33 82 74 05 16 d4 ab 4c 6a 6c 95 cf 60 8e a8 69 43 1f e2 37 13 67 eb 00 22 00 0b 9e 45 d0 46 1f 72 a7 eb 24 67 cf 02 67 5a e1 ee bb ab 29 13 44 ba d1 e1 14 fd 1f 73 33 db 5f 33 00 00 01 00 00
received:  80 01 00 00 00 0a 00 00 02 d6
_test_tpm2_derived_keys: line 23: 12115 Killed                  ${SWTPM_EXE} socket "$@" ${SWTPM_TEST_SECCOMP_OPT} --server type=tcp,port=${SWTPM_SERVER_PORT}${swtpm_server_disconnect} --ctrl type=tcp,port=${SWTPM_CTRL_PORT}
FAIL test_tpm2_derived_keys (exit status: 1)

Is this an known issue or any misconfiguration?

**Comment by stefanberger** [comment]
Please wget the stable-0.3.0 branch: https://github.com/stefanberger/swtpm/archive/stable-0.3.0/stable-0.3.0.tar.gz

Or apply this patch here: https://github.com/stefanberger/swtpm/commit/451735a5dab3069d0e5dcfa744b0ce18e46c14ef.patch

**Comment by stefanberger** [comment]
Does the stable-0.3.0.tar.gz solve the issue for you? If so, please close the issue.

**Comment by YadongQi** [comment]
Thanks, Stefan.

**Comment by stefanberger** [comment]
I now tagged v0.3.1 that has the fix: https://github.com/stefanberger/swtpm/releases/tag/v0.3.1
