### ISSUE TITLE
Windows supported? / Something broken? / Layer 8 problem?

### ISSUE THREAD

**Issue by Apfelwurm** [stefanberger/swtpm#223]
Hey all together,
i need a test environment for Windows bitlocker deployment, so i decided to use Poxmox VE (6.1.8) with QEMU 4.1.1 underlaying.

I sucessfully compiled and installed swtpm and libtpms (had to work around the trousers startup bug but else no problems) and I added a TPM with the following commands:

> mkdir /var/tpm0
> swtpm socket --tpmstate dir=/var/tpm0 --tpm2 --ctrl type=unixio,path=/var/tpm0/swtpm-sock &
> chown -R tss:root /var/tpm0

My vm.conf looks like
>bios: ovmf
>bootdisk: ide0
>cores: 2
>efidisk0: local-lvm:vm-100-disk-1,size=4M
>ide0: local-lvm:vm-100-disk-0,size=80G,ssd=1
>ide2: none,media=cdrom
>memory: 4096
>name: testcl01
>net0: e1000=2E:29:DB:34:B5:B5,bridge=vmbr0,firewall=1
>numa: 0
>ostype: win10
>scsihw: virtio-scsi-pci
>smbios1: uuid=aca5b7cd-e807-4423-a5ba-ef74275ef346
>sockets: 2
>vmgenid: e9e39927-b9dd-4aea-8030-86a415fe8796
>args: -chardev socket,id=chrtpm,path=/var/tpm0/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0`

The Windows 10 i have temporary installed on the vm detects a TPM 2.0 chip in the device manager but prints the following error 
>a protocol error was detected between the driver and the device

Since there is a big chance that my windows configuration (there are many known issues with TPM and W10) is screwed up, i've wondered if my understanding of setting up the vTPM was right or if i did something wrong here.

Thank You!
Alex

**Comment by stefanberger** [comment]
What firmware did you use to start you machine? Does the firmware have TPM 2 support?

**Comment by Apfelwurm** [comment]
Thanks for the super fast reply :) 
I'm currently using OVMF included in Proxmox. I am not able to find how to determinate if they have built it with the TPM2 support. Can you give me an advice how to check this? Thanks!

**Comment by stefanberger** [comment]
When you get into the UEFI menu there should be a TCG/TPM related menu item. I am not sure whether it was built in, though, which may depend on the distro or whoever built UEFI for it. If you cannot check it, I would try to run Linux as a guest OS first to see whether it shows `/dev/tpm0` and '/dev/tpmrm0` or the appropriate messages in `dmsg`. We know that Windows does work with recent version of QEMU and an attached vTPM (swtpm). I am not familiar with the environment you are using and would rather be using a libvirt management stack to attach the vTPM to the VM and to start it.

**Comment by Apfelwurm** [comment]
I Installed a Debian 10 on the vm, the devices are available, dmesg prints the following error:

>[    1.932796] tpm_tis MSFT0101:00: 2.0 TPM (device-id 0x1, rev-id 1)
>[    1.934026] tpm tpm0: A TPM error (256) occurred attempting the self test
>[    1.934057] tpm tpm0: starting up the TPM manually

Thank you!

**Comment by stefanberger** [comment]
The firmware you have does not initialize the TPM 2. Likely that's the reason why Windows shows this error message.

**Comment by Apfelwurm** [comment]
Okay, then i have to look into how to build OVMF with TMP2 support. Thanks for your help!

**Comment by stefanberger** [comment]
This line here used to work for me:

```
build -p OvmfPkg/OvmfPkgX64.dsc -b DEBUG -a X64 -t GCC5 -D TPM2_ENABLE -D TPM2_CONFIG_ENABLE -D SECURE_BOOT_ENABLE -D NETWORK_TLS_ENABLE
```

The recent code likely has changed `TPM2_ENABLE` to `TPM_ENABLE` and likely `TPM_CONFIG_ENABLE`. You may want to grep through the sources.

Good luck!
