### ISSUE TITLE
libtasn1 dependency outdated?

### ISSUE THREAD

**Issue by furtiman** [stefanberger/swtpm#226]
While running `./autogen.sh`, the following occurs:

```
Package libtasn1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtasn1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtasn1' found
configure: error: "Is libtasn1-devel installed? -- could not get libs for libtasn1"
```

The problem is that it seems like the `libtasn1` is not available from `apt-get` anymore, instead the `libtasn1-6` can be installed.

What is the best way to overcome this issue, and is there a plan to replace the dependency?

**Comment by stefanberger** [comment]
I do not see a problem here, at least not on Ubuntu Focal.

I install `libtasn1-dev` using `sudo apt -y install libtasn1-dev` and it selected `libtasn1-6-dev1`. Building worked fine after this and all `make check` also passed fine.

**Comment by furtiman** [comment]
@stefanberger thanks for a prompt response!
I managed to install the dependencies correctly.
Closing the issue
