### ISSUE TITLE
Is there a txz package existing? Id like to use it Slackware which seems to be quite a challenge, thanks

### ISSUE THREAD

**Issue by rezo552** [stefanberger/swtpm#238]

**Comment by stefanberger** [comment]
There is not tgz package unless `make dist` can somehow be configure to create such a type of package. Sorry.

**Comment by rezo552** [comment]
hmm OK, then the other quicker option would be to setup a server and mount the file descriptor's directory over NFS, im just wondering if it would work

**Comment by rezo552** [comment]
> hmm OK, then the other quicker option would be to setup a server and mount the file descriptor's directory over NFS, im just wondering if it would work

just did that but I have some issues with adding arbitrary qemu switches to the libvirt xml domain

**Comment by rezo552** [comment]
> > hmm OK, then the other quicker option would be to setup a server and mount the file descriptor's directory over NFS, im just wondering if it would work
> 
> just did that but I have some issues with adding arbitrary qemu switches to the libvirt xml domain

Hmmm, it seems if you reference the TPM emulator in the XML that requires the swtpm binaries on the same host. As qemu is invoking it, hmmm, this will be difficult

**Comment by rezo552** [comment]
Managed to compile it myself
