### ISSUE TITLE
Unable to compile on Fedora 25 

### ISSUE THREAD

**Issue by ge0rgi** [stefanberger/swtpm#24]
Hello!
I am having trouble compiling on Fedora 25. I compiled `libtpms` from the most recent commit  and in `/usrl/local/lib` i now have the following files
        
    ibtpms.a  libtpms.la  libtpms.so  libtpms.so.0  libtpms.so.0.6.0
However when I try to compile `swtpm` I am getting the following error

    swtpm/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to `TPMLIB_SetDebugPrefix'
    swtpm/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to `TPMLIB_SetDebugPrefix'
    swtpm/.libs/libswtpm_libtpms.so: undefined reference to `TPMLIB_SetDebugFD`

I also tried using the 0.5.2.1 release and making a debug build, but no luck. What do I do wrong?

**Comment by stefanberger** [comment]
What does 'ldconfig -v | grep libtpms' show? Does it show libtpms 0.5.x still being install? This one may have to be removed first.

**Comment by ge0rgi** [comment]
Yes I still seem to have a reference pointing to 0.5.2 I ran `male uninstall` and removed all the libraries from '/usr/local/lib' and ran `sudo ldconfig`. However  `ldconfig -v | grep libtpms` still shows `libtpms.so.0 -> libtpms.so.0.5.2` How do I remove it properly?

**Comment by stefanberger** [comment]
If you previously installed the RPM, remove it using 'dnf remove libtpms' or 'yum remove libtpms' or 'rpm -e libtpms'. Otherwise you may want to try

`
cd /lib64
ls libtpms*
# if the above show libtpms remove it
rm -rf libtpms*
`

**Comment by ge0rgi** [comment]
I had the library in /lib64, removed it. Now I am getting a different error:

     /usr/local/lib/libtpms.so: undefined reference to `va_start'
     /usr/local/lib/libtpms.so: undefined reference to `va_end'

**Comment by stefanberger** [comment]
I pushed an update that should fix it. Please pull and try again.

**Comment by ge0rgi** [comment]
It is compiling now. Is it ok for the test_ctrlchannel, test_ctrlchannel2 and test_commandline tests to fail?

**Comment by stefanberger** [comment]
I have tried this also on Fedora 25. I didn't have the libtpms related problems with va_start and va_end symbols. For me all the tests are passing, so this should also be the case for you. What is the content of  /tests/test_ctrlchannel2.log for example?  Did you configure libtpms with '--with-openssl'?

**Comment by ge0rgi** [comment]
For some strange reason I had to add `/usrl/local/lib` to `ldconfig` otherwise the library was not properly loaded. Thanks for helping out :)
