### ISSUE TITLE
Issue with migration + cuse tpm

### ISSUE THREAD

**Issue by paw3142** [stefanberger/swtpm#26]
When I tried to migrate, it failed with the following error message on the target host (libvirt log):
(error telling me that the vtpm device is missing - note that there is no hw TPM on my machine)
This is using the tpm2 preview for libtpms/swtpm, qemu-tpm (2.6).

Is there a something else that I need to do to make this happen?
---
virsh migrate --live --p2p --verbose guest  qemu+tcp://128.224.56.52/system

2017-03-09 21:47:39.627+0000: 2164: debug : virCommandRunAsync:2448 : About to run LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin
:/usr/bin:/sbin:/bin QEMU_AUDIO_DRV=none /home/afong/TPM/bin/qemu-system-x86_64 -name guest=guest,debug-threads=on -S -object secret,id=m
asterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-3-guest/master-key.aes -machine pc-i440fx-2.6,accel=kvm,usb=off,dump-guest-core=of
f -cpu kvm64 -m 2000 -realtime mlock=off -smp 4,sockets=4,cores=1,threads=1 -uuid 6be4dda6-e775-4f5e-b142-57e5892b2a08 -display none -no-
user-config -nodefaults -chardev socket,id=charmonitor,path=/var/lib/libvirt/qemu/domain-3-guest/monitor.sock,server,nowait -mon chardev=
charmonitor,id=monitor,mode=control -rtc base=utc -no-reboot -boot menu=on,strict=on -device piix3-usb-uhci,id=usb,bus=pci.0,addr=0x1.0x2
 -drive file=/home/afong/TPM/tmp/CentOS-7-x86_64-GenericCloud.qcow2,format=qcow2,if=none,id=drive-virtio-disk0,cache=none,aio=native -dev
ice virtio-blk-pci,scsi=off,bus=pci.0,addr=0x3,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=1 -netdev tap,fd=26,id=hostnet0,vhost=o
n,vhostfd=28 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:0c:44:05,bus=pci.0,addr=0x2 -chardev pty,id=charserial0 -device 
isa-serial,chardev=charserial0,id=serial0 -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x4 -bios /home/afong/TPM/seabios/out/bio
s.bin -tpmdev cuse-tpm,id=tpm-tpm0,path=/dev/tpm0,cancel-path=/dev/null -device tpm-tis,tpmdev=tpm-tpm0,id=tpm0 -msg timestamp=on
error : qemuProcessReportLogError:1792 : internal error: qemu unexpectedly closed the monitor: 2017-03-09T21:47:39.688989Z qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm-tpm0,path=/dev/tpm0,cancel-path=/dev/null: Cannot access TPM device using '/dev/tpm0': No such file or directory
 debug : qemuMonitorIO:743 : Error on monitor internal error: qemu unexpectedly closed the monitor: 2017-03-09T21:47:39.688989Z qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm-tpm0,path=/dev/tpm0,cancel-path=/dev/null: Cannot access TPM device using '/dev/tpm0': No such file or directory
2017-03-09 21:47:39.767+0000: 1863: debug : qemuMonitorIO:774 : Triggering error callback
2017-03-09 21:47:39.767+0000: 1863: debug : qemuProcessHandleMonitorError:338 : Received error on 0x7f4538002fb0 'guest'
2017-03-09 21:47:39.767+0000: 2164: debug : qemuMonitorSend:1021 : Send command resulted in error internal error: qemu unexpectedly closed the monitor: 2017-03-09T21:47:39.688989Z qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm-tpm0,path=/dev/tpm0,cancel-path=/dev/null: Cannot access TPM device using '/dev/tpm0': No such file or directory

**Comment by stefanberger** [comment]
They way I implemented this was that libvirt would start a CUSE TPM when starting the QEMU process on the destination.

**Comment by paw3142** [comment]
Would I be able to access your libvirt changes?
