### ISSUE TITLE
Tss2 VTPM

### ISSUE THREAD

**Issue by prettyDamCool** [stefanberger/swtpm#267]
Tss2 VTPM

When compiled from source, I get this issue:

/tss/utils/./tssgetrandom -by 10

TPM_RC_SIZE - structure is the wrong size Handle number unspecified

But when calling tssgetrandom -by 10, then there is no issue.

The issue is only in a VTPM, the command works in SWTPM

Any idea what this issue might be related to?

**Comment by stefanberger** [comment]
Did you compile this yourself? Try adding -v and have a look at the output. 
```
/tss/utils/./tssgetrandom -by 10 -v
```

or try this:

```
TPM_DEVICE=/dev/tpm0 /tss/utils/./tssgetrandom -by 10 -v
```

**Comment by prettyDamCool** [comment]
Yes I did 
I got the following, I also get the same issue when using 
./createprimary
``
TSS_Command_PreProcessor: Input parameters
        bytesRequested 10
TSS_Execute20: Command 0000017b marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_GetRandom
TSS_Socket_Open: Opening localhost:2321-raw
TSS_Socket_SendCommand: TPM2_GetRandom
 TSS_Socket_SendCommand length 12
 80 01 00 00 00 0c 00 00 01 7b 00 0a 
 TSS_Socket_ReceiveCommand length 22
 80 01 00 00 00 16 00 00 00 00 00 0a 8e cc 1c ab 
 20 26 68 57 75 38 
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute20: Command 0000017b unmarshal
TSS_Socket_Close: Closing localhost-raw
getrandom: failed, rc 00000095
TPM_RC_SIZE - structure is the wrong size Handle number unspecified

**Comment by stefanberger** [comment]
Did you set the environment variables as described here? https://github.com/stefanberger/swtpm/wiki/Using-the-IBM-TSS-with-swtpm

**Comment by prettyDamCool** [comment]
Yes, I have done

**Comment by stefanberger** [comment]
Don't know what's wrong. Cannot recreate the issue since it works fine for me:

```
tssgetrandom  -by 10 -v
TSS_Command_PreProcessor: Input parameters
        TPM2_GetRandom
        bytesRequested 10
TSS_Execute20: Command 0000017b marshal
TSS_Execute_valist: Step 1: initialization
TSS_Execute_valist: Step 5: command encrypt
TSS_Sessions_GetDecryptSession: Found 0 decrypt sessions at 0
TSS_Execute_valist: Step 6 calculate HMACs
TSS_Execute_valist: Step 7 set command authorizations
TSS_Execute_valist: Step 8: process the command
TSS_AuthExecute: Executing TPM2_GetRandom
TSS_Socket_Open: Opening localhost:2321-raw
TSS_Socket_SendCommand: TPM2_GetRandom
 TSS_Socket_SendCommand length 12
 80 01 00 00 00 0c 00 00 01 7b 00 0a 
 TSS_Socket_ReceiveResponse length 22
 80 01 00 00 00 16 00 00 00 00 00 0a 20 15 c1 50 
 a8 0a 54 71 d2 65 
TSS_Execute_valist: Step 9 get response authorizations
TSS_Execute_valist: Step 13: response decryption
TSS_Sessions_GetEncryptSession: Found 0 encrypt sessions at 0
TSS_Execute20: Command 0000017b unmarshal
TSS_Execute20: Command 0000017b post processor
 randomBytes in pass length 10
 20 15 c1 50 a8 0a 54 71 d2 65 
TSS_Socket_Close: Closing localhost-raw
 randomBytes length 10
 20 15 c1 50 a8 0a 54 71 d2 65 
```

You may want to take this to the TSS2 mailing list.

**Comment by prettyDamCool** [comment]
thank you, I can directly call tssgetrandom and other commands, currently have a modified createprimary hence the need to directly call them

**Comment by stefanberger** [comment]
This is really for the TSS2 list. Closing this issue.
