### ISSUE TITLE
migration on cuse + capabilities

### ISSUE THREAD

**Issue by paw3142** [stefanberger/swtpm#27]
I have libvirt setup with hooks to create a cuse tpm on the prepare/start phase,
I'm trying to do a live migration on a tpm2 software only system:

# virsh migrate --live --p2p --verbose guest  qemu+tcp://128.224.56.52/system
error: internal error: unable to execute QEMU command 'migrate': Migration disabled: CUSE TPM lacks necessary capabilities

# swtpm_ioctl -c --tpm-device /dev/tpm0
ptm capability is 0xcbf

At first I thought that I need to setup state blobs for the device, so what I did is in the prepare/start phase
of libvirt's hook, I create a daemon to periodically call swtpm_ioctl --save for all valid state blob names
in files (stopped/end hook kills this daemon):
# file /guest/blob/*
/guest/blob/permanent: PDP-11 UNIX/RT ldp
/guest/blob/savestate: empty
/guest/blob/volatile:  ASCII text

But I still get the migration error message.

Do I need to do something else to make migration work?

**Comment by paw3142** [comment]
I just answered my question. From swtpm, I see that PTM_CAP_GET_STATEBLOB and PTM_CAP_SET_STATEBLOB is not supported in version tpm2. Will this be something supoorted in a future release?

**Comment by stefanberger** [comment]
Support for this would need to be implemented in libtpms. Some day there will hopefully support for this, so far there isn't.
