### ISSUE TITLE
Setting Subject Alternative Name

### ISSUE THREAD

**Issue by benlytle** [stefanberger/swtpm#273]
I see the SAN field referenced in a couple old issues #2 and #23 
Is is still possible to set this field when creating certificates?
I'm running into an application that is looking for this field in the certicate.

Thanks!

**Comment by stefanberger** [comment]
Hi! The specs for the SAN field of an EK are here: https://trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.0_R14_published.pdf

Have a look at section 3.2.9. We are following the specs as closely as possible. The code that sets the field is here:

https://github.com/stefanberger/swtpm/blob/master/src/swtpm_cert/ek-cert.c#L1490

**Comment by benlytle** [comment]
Hey Stefan, thanks for the quick reply!
I took a look, and you're right, seems the code is following the spec.
I did compare the EK cert generated by swtpm_setup with another ek cert generator, found in the [project](https://github.com/bloomberg/spire-tpm-plugin/tree/master/ci/tpm2_ek_cert_generator) I'm working with.
There is a slight difference in implementation it seems (SAN field: id 2.23.133.2.2; TPM part number), and that's likely causing the error. The error I get is "tpm: could not verify cert: x509: unhandled critical extension (2.5.29.17)".

When I use the tpm2_ek_cert_generator for the EK cert, the error does not appear.
I'm no expert on asn1 or x509 (still learning), but could it possibly be a wrong encode of asn1 type for that field?


For reference here are the two EK certs generated against the swtpm in a QEMU environment:

swtpm_setup:
<pre>
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 8 (0x8)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = swtpm-localca
        Validity
            Not Before: Jun 30 13:42:53 2020 GMT
            Not After : Jun 28 13:42:53 2030 GMT
        Subject: CN = unknown
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    ...
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Extended Key Usage:
                2.23.133.8.1
            X509v3 Subject Alternative Name: critical
                DirName:/2.23.133.2.1=id:00001014/2.23.133.2.2=swtpm/2.23.133.2.3=id:20170619
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Directory Attributes:
                0.0...g....1.0...2.0.......
            X509v3 Authority Key Identifier:
                keyid:2C:8B:B7:9C:87:D7:35:72:78:03:7E:48:8A:F1:C9:36:A3:CB:5A:EA

            X509v3 Key Usage: critical
                Key Encipherment
    Signature Algorithm: sha256WithRSAEncryption
            ...
</pre>

tpm2_ek_cert_generator:
<pre>
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            20:85:1a:19:fd:50:1a:ee:f4:94:31:e4:c3:ce:0a:99:15:8f:07:70
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: O = TPM Manufacturer, OU = TPM Manufacturer Root CA, CN = TPM Manufacturer Root CA
        Validity
            Not Before: Jun 29 22:53:40 2020 GMT
            Not After : Jun 29 22:53:40 2030 GMT
        Subject:
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    ...
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DirName:/2.23.133.2.1=id:123456EF/2.23.133.2.2=id:00000000/2.23.133.2.3=id:00020008
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Key Encipherment
    Signature Algorithm: sha256WithRSAEncryption
         ...
</pre>


Thanks again!

**Comment by stefanberger** [comment]
We would have to compare the certificates on the ASN.1 level.

**Comment by benlytle** [comment]
Here's the certificates using the asn1parse command.
The only difference I see is the multiple sets for that field.

### swtpm_setup:
<pre>
    0:d=0  hl=4 l=1011 cons: SEQUENCE
    4:d=1  hl=4 l= 603 cons: SEQUENCE
    8:d=2  hl=2 l=   3 cons: cont [ 0 ]
   10:d=3  hl=2 l=   1 prim: INTEGER           :02
   13:d=2  hl=2 l=   1 prim: INTEGER           :08
   16:d=2  hl=2 l=  13 cons: SEQUENCE
   18:d=3  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
   29:d=3  hl=2 l=   0 prim: NULL
   31:d=2  hl=2 l=  24 cons: SEQUENCE
   33:d=3  hl=2 l=  22 cons: SET
   35:d=4  hl=2 l=  20 cons: SEQUENCE
   37:d=5  hl=2 l=   3 prim: OBJECT            :commonName
   42:d=5  hl=2 l=  13 prim: PRINTABLESTRING   :swtpm-localca
   57:d=2  hl=2 l=  30 cons: SEQUENCE
   59:d=3  hl=2 l=  13 prim: UTCTIME           :200630134253Z
   74:d=3  hl=2 l=  13 prim: UTCTIME           :300628134253Z
   89:d=2  hl=2 l=  18 cons: SEQUENCE
   91:d=3  hl=2 l=  16 cons: SET
   93:d=4  hl=2 l=  14 cons: SEQUENCE
   95:d=5  hl=2 l=   3 prim: OBJECT            :commonName
  100:d=5  hl=2 l=   7 prim: PRINTABLESTRING   :unknown
  109:d=2  hl=4 l= 290 cons: SEQUENCE
  113:d=3  hl=2 l=  13 cons: SEQUENCE
  115:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
  126:d=4  hl=2 l=   0 prim: NULL
  128:d=3  hl=4 l= 271 prim: BIT STRING
  403:d=2  hl=3 l= 205 cons: cont [ 3 ]
  406:d=3  hl=3 l= 202 cons: SEQUENCE
  409:d=4  hl=2 l=  16 cons: SEQUENCE
  411:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Extended Key Usage
  416:d=5  hl=2 l=   9 prim: OCTET STRING      [HEX DUMP]:300706056781050801
  427:d=4  hl=2 l=  82 cons: SEQUENCE
  429:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Subject Alternative Name
  434:d=5  hl=2 l=   1 prim: BOOLEAN           :255
  437:d=5  hl=2 l=  72 prim: OCTET STRING      [HEX DUMP]:3046A444304231163014060567810502010C0B69643A30303030313031343110300E060567810502020C05737774706D31163014060567810502030C0B69643A3230313730363139
  511:d=4  hl=2 l=  12 cons: SEQUENCE
  513:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Basic Constraints
  518:d=5  hl=2 l=   1 prim: BOOLEAN           :255
  521:d=5  hl=2 l=   2 prim: OCTET STRING      [HEX DUMP]:3000
  525:d=4  hl=2 l=  34 cons: SEQUENCE
  527:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Subject Directory Attributes
  532:d=5  hl=2 l=  27 prim: OCTET STRING      [HEX DUMP]:3019301706056781050210310E300C0C03322E3002010002020096
  561:d=4  hl=2 l=  31 cons: SEQUENCE
  563:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Authority Key Identifier
  568:d=5  hl=2 l=  24 prim: OCTET STRING      [HEX DUMP]:301680142C8BB79C87D7357278037E488AF1C936A3CB5AEA
  594:d=4  hl=2 l=  15 cons: SEQUENCE
  596:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Key Usage
  601:d=5  hl=2 l=   1 prim: BOOLEAN           :255
  604:d=5  hl=2 l=   5 prim: OCTET STRING      [HEX DUMP]:0303072000
  611:d=1  hl=2 l=  13 cons: SEQUENCE
  613:d=2  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
  624:d=2  hl=2 l=   0 prim: NULL
  626:d=1  hl=4 l= 385 prim: BIT STRING
</pre>

deeper parsing at the SAN field:
<pre>
   0:d=0  hl=2 l=  70 cons: SEQUENCE
    2:d=1  hl=2 l=  68 cons:  cont [ 4 ]
    4:d=2  hl=2 l=  66 cons:   SEQUENCE
    6:d=3  hl=2 l=  22 cons:    SET
    8:d=4  hl=2 l=  20 cons:     SEQUENCE
   10:d=5  hl=2 l=   5 prim:      OBJECT            :2.23.133.2.1
   17:d=5  hl=2 l=  11 prim:      UTF8STRING        :id:00001014
   30:d=3  hl=2 l=  16 cons:    SET
   32:d=4  hl=2 l=  14 cons:     SEQUENCE
   34:d=5  hl=2 l=   5 prim:      OBJECT            :2.23.133.2.2
   41:d=5  hl=2 l=   5 prim:      UTF8STRING        :swtpm
   48:d=3  hl=2 l=  22 cons:    SET
   50:d=4  hl=2 l=  20 cons:     SEQUENCE
   52:d=5  hl=2 l=   5 prim:      OBJECT            :2.23.133.2.3
   59:d=5  hl=2 l=  11 prim:      UTF8STRING        :id:20170619
</pre>


### tpm2_ek_cert:
<pre>
    0:d=0  hl=4 l= 860 cons: SEQUENCE
    4:d=1  hl=4 l= 580 cons: SEQUENCE
    8:d=2  hl=2 l=   3 cons: cont [ 0 ]
   10:d=3  hl=2 l=   1 prim: INTEGER           :02
   13:d=2  hl=2 l=  20 prim: INTEGER           :20851A19FD501AEEF49431E4C3CE0A99158F0770
   35:d=2  hl=2 l=  13 cons: SEQUENCE
   37:d=3  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
   48:d=3  hl=2 l=   0 prim: NULL
   50:d=2  hl=2 l=  97 cons: SEQUENCE
   52:d=3  hl=2 l=  25 cons: SET
   54:d=4  hl=2 l=  23 cons: SEQUENCE
   56:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
   61:d=5  hl=2 l=  16 prim: UTF8STRING        :TPM Manufacturer
   79:d=3  hl=2 l=  33 cons: SET
   81:d=4  hl=2 l=  31 cons: SEQUENCE
   83:d=5  hl=2 l=   3 prim: OBJECT            :organizationalUnitName
   88:d=5  hl=2 l=  24 prim: UTF8STRING        :TPM Manufacturer Root CA
  114:d=3  hl=2 l=  33 cons: SET
  116:d=4  hl=2 l=  31 cons: SEQUENCE
  118:d=5  hl=2 l=   3 prim: OBJECT            :commonName
  123:d=5  hl=2 l=  24 prim: UTF8STRING        :TPM Manufacturer Root CA
  149:d=2  hl=2 l=  30 cons: SEQUENCE
  151:d=3  hl=2 l=  13 prim: UTCTIME           :200629225340Z
  166:d=3  hl=2 l=  13 prim: UTCTIME           :300629225340Z
  181:d=2  hl=2 l=   0 cons: SEQUENCE
  183:d=2  hl=4 l= 290 cons: SEQUENCE
  187:d=3  hl=2 l=  13 cons: SEQUENCE
  189:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
  200:d=4  hl=2 l=   0 prim: NULL
  202:d=3  hl=4 l= 271 prim: BIT STRING
  477:d=2  hl=2 l= 109 cons: cont [ 3 ]
  479:d=3  hl=2 l= 107 cons: SEQUENCE
  481:d=4  hl=2 l=  81 cons: SEQUENCE
  483:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Subject Alternative Name
  488:d=5  hl=2 l=  74 prim: OCTET STRING      [HEX DUMP]:3048A446304431423014060567810502010C0B69643A31323334353645463014060567810502020C0B69643A30303030303030303014060567810502030C0B69643A3030303230303038
  564:d=4  hl=2 l=   9 cons: SEQUENCE
  566:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Basic Constraints
  571:d=5  hl=2 l=   2 prim: OCTET STRING      [HEX DUMP]:3000
  575:d=4  hl=2 l=  11 cons: SEQUENCE
  577:d=5  hl=2 l=   3 prim: OBJECT            :X509v3 Key Usage
  582:d=5  hl=2 l=   4 prim: OCTET STRING      [HEX DUMP]:03020520
  588:d=1  hl=2 l=  13 cons: SEQUENCE
  590:d=2  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
  601:d=2  hl=2 l=   0 prim: NULL
  603:d=1  hl=4 l= 257 prim: BIT STRING
</pre>

deeper parsing at the SAN field:
<pre>
    0:d=0  hl=2 l=  72 cons: SEQUENCE
    2:d=1  hl=2 l=  70 cons:  cont [ 4 ]
    4:d=2  hl=2 l=  68 cons:   SEQUENCE
    6:d=3  hl=2 l=  66 cons:    SET
    8:d=4  hl=2 l=  20 cons:     SEQUENCE
   10:d=5  hl=2 l=   5 prim:      OBJECT            :2.23.133.2.1
   17:d=5  hl=2 l=  11 prim:      UTF8STRING        :id:123456EF
   30:d=4  hl=2 l=  20 cons:     SEQUENCE
   32:d=5  hl=2 l=   5 prim:      OBJECT            :2.23.133.2.2
   39:d=5  hl=2 l=  11 prim:      UTF8STRING        :id:00000000
   52:d=4  hl=2 l=  20 cons:     SEQUENCE
   54:d=5  hl=2 l=   5 prim:      OBJECT            :2.23.133.2.3
   61:d=5  hl=2 l=  11 prim:      UTF8STRING        :id:00020008
</pre>

**Comment by stefanberger** [comment]
The only difference between the two is the 'id:' part missing before 'swtpm'. The previously referenced spec has an example in the back (pdf page 33) that allows this:

```
Subject alternative name:
TPMManufacturer = id:54534700 (TCG)
TPMModel = ABCDEF123456(part number)
TPMVersion = id:00010023(firmware version)
```

There's not 'id:' in front of the model. So if this is indeed causing the rejection, it's a bug in the verification tool.

**Comment by stefanberger** [comment]
Except it could be that it's verifying the vendor string, which in swtpm case does not match exactly, but the vendor string is "SW   TPM" (with 3 spaces).

**Comment by stefanberger** [comment]
From the spec: "The TPM part number is encoded as a string and is manufacturer-specific.A manufacturer MUST provide  a  way  to  the  user  to  retrieve  the  part  number physically or  logically. This information could   be   e.g.provided   as part   of   the vendor   string in   the   command TPM2_GetCapability(property=TPM_PT_VENDOR_STRING_x; x=1...4)."

I would say that the 'logical' way to conclude that it's a 'swtpm' is that the CA is not a well known CA, but I do not know what the verification tool may be looking for.

**Comment by benlytle** [comment]
I think you're right.
It looks like the verification tool is completely ignoring Critical Extensions, returning the "Unhandled critical extension" error whenever a critical extension is seen. I will take this over to that project.
Thanks for your help in figuring this out!

**Comment by benlytle** [comment]
So I read over the spec again because I was wondering why the verification tool completely disregards critical extensions, by throwing that error.
It seems that the SAN field should not be critical in this case because:
> If the subject field contains an empty sequence, then the issuing CA MUST include a subjectAltName extension that is marked as critical. When including the subjectAltName extension in a certificate that has a non-empty subject distinguished name, conforming CAs SHOULD mark the subjectAltName extension as non-critical.

However, the word "SHOULD" leaves it up to interpretation.
I think the tpm2_ek_generator is actually non-compliant to spec because of the referenced paragraph, and the "Subject" field in their EK is empty.

Along the same lines, "Basic Constraints" and "Key Usage" should be critical as well, as swtpm does.


If you're interested, the verification tool that's being used is https://github.com/google/certificate-transparency-go/blob/741f2412675886c9928db64157290cec87a55fce/x509/verify.go
The offending line is [here](https://github.com/google/certificate-transparency-go/blob/741f2412675886c9928db64157290cec87a55fce/x509/verify.go#L571)

Thanks again!
