### ISSUE TITLE
swtpm doesn't compile under clang/lld 

### ISSUE THREAD

**Issue by salahcoronya** [stefanberger/swtpm#280]
Without --disable-hardening, the following error occurs: 

Making all in swtpm
make[3]: Entering directory '/var/tmp/portage/app-crypt/swtpm-0.3.2/work/swtpm-0.3.2/src/swtpm'
clang -DHAVE_CONFIG_H -I. -I../..    -I../../include -I../../include -I../../include/swtpm -fstack-protector-strong -Wstack-protector  -Wl,-z,relro  -Wl,-z,now    -DHAVE_SWTPM_CUSE_MAIN -O2 -pipe -ggdb -frecord-gcc-switches -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security   -c -o swtpm-main.o `test -f 'main.c' || echo './'`main.c
clang-10: error: -Wl,-z,relro: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang-10: error: -Wl,-z,now: 'linker' input unused [-Werror,-Wunused-command-line-argument]

If --disable-hardening is added, that goes away but then a link error occurs later on: 

/bin/sh ../../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-clang -I../../include -I../../include -I../../include/swtpm -fstack-protector-strong -Wstack-protector    -DHAVE_SWTPM_CUSE_MAIN -O2 -pipe -march=native -frecord-gcc-switches -fno-diagnostics-color -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security    -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -fuse-ld=lld -Wl,--defsym=__gentoo_check_ldflags__=0  -o swtpm swtpm-main.o swtpm-osx.o swtpm-swtpm.o swtpm-swtpm_chardev.o  -L/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs -lswtpm_libtpms    -ltpms  
libtool: link: x86_64-pc-linux-gnu-clang -I../../include -I../../include -I../../include/swtpm -fstack-protector-strong -Wstack-protector -DHAVE_SWTPM_CUSE_MAIN -O2 -pipe -march=native -frecord-gcc-switches -fno-diagnostics-color -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security -Wl,-O1 -Wl,--defsym=__gentoo_check_ldflags__=0 -fuse-ld=lld -Wl,--defsym=__gentoo_check_ldflags__=0 -o .libs/swtpm swtpm-main.o swtpm-osx.o swtpm-swtpm.o swtpm-swtpm_chardev.o  -L/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs -Wl,--as-needed /var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so -lseccomp -ltpms -Wl,-rpath -Wl,/usr/lib64/swtpm
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to EVP_sha512
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to PKCS5_PBKDF2_HMAC
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to SHA512
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to AES_cbc_encrypt
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to AES_set_decrypt_key
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to AES_set_encrypt_key
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to EVP_MD_size
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to EVP_sha256
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to HMAC_CTX_free
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to HMAC_CTX_new
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to HMAC_Final
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to HMAC_Init_ex
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to HMAC_Update
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to RAND_bytes
ld.lld: [0;31merror: [0m/var/tmp/portage/app-crypt/swtpm-0.3.1-r1/work/swtpm-0.3.1/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to SHA256
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Makefile:645: swtpm] Error 1

See https://bugs.gentoo.org/733400 for the full build log.

**Comment by stefanberger** [comment]
I tried it on Fedora 31 with clang-9 and also had to pass `--disable-hardening`, but it ended up linking just fine.

```
$ clang --version
clang version 9.0.0 (Fedora 9.0.0-1.fc31)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ CC=clang ./configure --prefix=/usr --disable-hardening
[...]
with_gnutls     :   yes  (no = swtpm_cert will NOT be built)
with_selinux    :   yes  (no = SELinux policy extenions will NOT be built)
with_cuse       :    no  (no = no CUSE interface)
with_chardev    :   yes  (no = no chardev interface)
with_swtpm_setup:   yes  (no = swtpm_setup will NOT be built)
with_vtpm_proxy :   yes  (no = no vtpm proxy support; Linux only)
with_seccomp    :   yes  (no = no seccomp profile; Linux only)

cryptolib: openssl

CFLAGS=-g -O2  -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security -I/usr/include/p11-kit-1  
HARDENING_CFLAGS=
LDFLAGS=  
LIBSECCOMP_LIBS=-lseccomp 

TSS_USER=tss
TSS_GROUP=tss

$ make
$ make check
$ ldd src/swtpm/.libs/libswtpm_libtpms.so
	linux-vdso.so.1 (0x00007fff03ff7000)
	libtpms.so.0 => /lib64/libtpms.so.0 (0x0000146d2aba8000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x0000146d2a8c1000)
	libseccomp.so.2 => /lib64/libseccomp.so.2 (0x0000146d2a874000)
	libc.so.6 => /lib64/libc.so.6 (0x0000146d2a6ab000)
	libz.so.1 => /lib64/libz.so.1 (0x0000146d2a691000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000146d2a68a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000146d2a666000)
	/lib64/ld-linux-x86-64.so.2 (0x0000146d2ad35000)
```

**Comment by stefanberger** [comment]
You could try this patch:

```
diff --git a/configure.ac b/configure.ac
index c50c3026..64ba07c4 100644
--- a/configure.ac
+++ b/configure.ac
@@ -151,6 +151,8 @@ openssl)
        AC_CHECK_HEADERS([openssl/aes.h],[],
                         AC_MSG_ERROR(Is openssl-devel/libssl-dev installed?))
        AC_MSG_RESULT([Building with openssl crypto library])
+       LIBCRYPTO_LIBS=$(pkg-config --libs libcrypto)
+       AC_SUBST([LIBCRYPTO_LIBS])
        ;;
 esac
 
diff --git a/src/swtpm/Makefile.am b/src/swtpm/Makefile.am
index dd2a63ab..b5f15e3e 100644
--- a/src/swtpm/Makefile.am
+++ b/src/swtpm/Makefile.am
@@ -69,7 +69,8 @@ libswtpm_libtpms_la_LIBADD = \
        $(LIBTPMS_LIBS) \
        $(GLIB_LIBS) \
        $(LIBRT_LIBS) \
-       $(LIBSECCOMP_LIBS)
+       $(LIBSECCOMP_LIBS) \
+       $(LIBCRYPTO_LIBS)
 
 bin_PROGRAMS = swtpm
 if WITH_CUSE
```

**Comment by salahcoronya** [comment]
Yes, that fixes it

**Comment by stefanberger** [comment]
I will apply fixes to master and may backport them to the stable-0.3.0 branch.

**Comment by stefanberger** [comment]
The patches are now applied to master and also the stable-0.3.0 branch. I hope this solve the issue for you.

**Comment by salahcoronya** [comment]
Yes, it does. I've have submitted a PR for an updated ebuild with the referenced patches.
