### ISSUE TITLE
libtpms 0.6 or later is required

### ISSUE THREAD

**Issue by yankunsam** [stefanberger/swtpm#29]
It occurs on upstream/tpm2-preview.
But I have builded and installed libtpms 0.6. And I can build  vtpm1.2 successfully.

**Comment by stefanberger** [comment]
Please use the latest libtpms preview branch, which is currently tpm2-preview.rev142 (https://github.com/stefanberger/libtpms/tree/tpm2-preview.rev142). While work is ongoing in these preview branches, the state files that the TPM 2 may write may not be readable anymore after an update of the libtpms preview branch.
