### ISSUE TITLE
swtpm: Error: Could not choose TPM 2 implementation.

### ISSUE THREAD

**Issue by yankunsam** [stefanberger/swtpm#30]
Here is what I do on a shell:

#!/bin/bash
mkdir /tmp/vtpm0

chown -R tss:root  /tmp/vtpm0
swtpm_setup --tpm2 --tpm-state /tmp/vtpm0  --createek
export TPM_PATH=/tmp/vtpm0
swtpm_cuse -n vtpm0

And here is its output:

Starting vTPM manufacturing as tss:tss @ 2017年04月11日 星期二
20时01分10秒
swtpm: Error: Could not choose TPM 2 implementation.
swtpm: Error: Could not choose TPM 2 implementation.
swtpm: Error: Could not choose TPM 2 implementation.
swtpm: Error: Could not choose TPM 2 implementation.

**Comment by stefanberger** [comment]
Did you use a TPM2 preview branch of libtpms and configure it with './configure --with-tpm2 --with-openssl --prefix=/usr' or similar and install it  (sudo make install) on the system ?

Please also make sure that any previous version of libtpms (such as libtpms 0.5.x) is not on the system anymore and being picked up by swtpm for runtime linking with.

**Comment by yankunsam** [comment]
Thanks for your help,stefanberger. It start successfully.But when run "tpm_version",it also reports "1.2.18.60"

**Comment by stefanberger** [comment]
Make sure that any TPM 2 program or TSS 2 stack you are using is now using /dev/vtpm0 as the device to talk to. I am not sure what tpm_version is and what device it talks to.

**Comment by yankunsam** [comment]
Yes. I use vtpm0 to start a qemu virtual machine and tpm_version is belong to tpm-tools.

swtpm_setup --tpm2 --tpm-state /tmp/vtpm0 --createe

**Comment by yankunsam** [comment]
And the version I got from "/sys/class/tpm/tpm0/caps" is also "1.2".So how should I check its version?

**Comment by abhijitSingh86** [comment]
Hello Guys,
I am facing the same issue. I did all the steps mentioned above and also installed tpm2_tss to access tpm2 but it fails for each command with error message " Failed to initialize tcti context : 0x1".
Please post if any solution exists for this problem.

**Comment by stefanberger** [comment]
@abhijitSingh86 Did you compile and install a tpm2 branch of libtpms, such as tpm2-preview.rev146 branch? Is the installed libtpms the only libtpms on the system? See 2nd comment above.

**Comment by abhijitSingh86** [comment]
Hello @stefanberger 
Thanks for the prompt response.
I installed libtpms from 146 squashed branch and on my machine, I can find only 0.6.0 version. Also, I used tpm2_preview branch of swtpm to build swtpm.
I guess the tpm2 is getting created by looking at /tmp/myvtpm/tpm2-00.permall file.
But, when I start qemu there's another file getting created in tmp i.e. /tmp/myvtpm/tpm-00.permall

Also when I go to into my qemu session and check the /sys/class/tpm/tpm0/device/caps it displays TCG Version as 1.2.
I am trying to figure out but any tips will help me to look in the right direction.

**Comment by stefanberger** [comment]
@abhijitSingh86 You need to start the swtpm with the --tpm2 parameter.

**Comment by abhijitSingh86** [comment]
@stefanberger  Thanks. I made the changes below is my final setup script looks like
mkdir /tmp/myvtpm
chown -R tss:root /tmp/myvtpm
swtpm_setup --tpm2 --tpm-state /tmp/myvtpm --createek
sudo su
export TPM_PATH=/tmp/myvtpm
swtpm_cuse --tpm2 -n "vtpm0"

I am struggling a bit accessing the tpm in the virtual machine, but hopefully, I will find a solution.
Thanks again.

**Comment by stefanberger** [comment]
@abhijitSingh86 Does `dmesg | grep -i tpm` show anything inside the VM?

**Comment by abhijitSingh86** [comment]
@stefanberger 
In start I was getting initialization failure message but, after using latest seabios I am getting below output
[    0.368247] tpm_tis 00:06: 2.0 TPM (device-id 0x1, rev-id 1)
[    0.376049] tpm_tis 00:06: [Firmware Bug]: TPM interrupt not working, polling instead

Now in my virtual machine, I have installed latest tpm2_tss,tpm2_tools,tpm2_abmrd but when trying to start or acquire the tpm device control getting bellow msg.
tpm2_nvlist --tcti=device
ERROR: Failed to initialize device TCTI context: 0xa000a
I believe I missed some settings while installing tpm2-abrmd, I will update you with my findings ones resolved.

**Comment by stefanberger** [comment]
Can you close this issue ?

**Comment by abhijitSingh86** [comment]
Hello @stefanberger  
Yes, this issue should be closed but, I can't close this as I am not the creator of this issue or collaborator in this repo. I am tagging @yankunsam  for closing this.

**Comment by KusumaKP** [comment]
Hi, 
With TPM2 preview, and steps as below as root in ubuntu 14.04 VM

mkdir /tmp/myvtpm
chown -R tss:root /tmp/myvtpm
swtpm_setup --tpm2 --tpm-state /tmp/myvtpm --createek
export TPM_PATH=/tmp/myvtpm
swtpm_cuse --tpm2 -n "vtpm0"

 i get the below in dmesg 

[  150.399657] swtpm[2545]: segfault at 4 ip b76d9738 sp bf8485dc error 4 in libswtpm_libtpms.so.0.0.0[b76d5000+c000]
Any ideas?

**Comment by stefanberger** [comment]
Please try the latest updates for tpm2-preview.rev146 branch of libtpms, compile. and install. Then get the latest of tpm2-preview branch of swtpm, do `make`, `make check`, and `make install`.

**Comment by stefanberger** [comment]
@KusumaKP I just saw that error also. Pushed a fix to master.next, will let it run the tests and the push to master and updated the tpm2-preview branch.
