### ISSUE TITLE
libvirtError:internal error:No usable sysfs TPM cancle file could be found

### ISSUE THREAD

**Issue by yankunsam** [stefanberger/swtpm#31]
Did it support KVM to start  a virt-machine ?

**Comment by stefanberger** [comment]
This is not a swtpm issue. What are you trying to do with libvirt?

**Comment by yankunsam** [comment]
Actually, I want to use virt-manager to create a virtual machine which owns "/dev/tpm0".Because it will be handfule for bridge network .Thanks!
