### ISSUE TITLE
Using SWTPM without virtualization

### ISSUE THREAD

**Issue by Melab** [stefanberger/swtpm#33]
Is there anyway to use SWTPM without a guest-host virtualization setup? Is this anything like the IBM software TPM hosted at SourceForge?

**Comment by stefanberger** [comment]
The SWTPM has different types of interfaces to talk to it. Interfaces include Linux CUSE, TCP or Unix IO sockets, and character device interface. The TCP socket interface can be used as follows and starts a TPM2 instance listening for TCP commands on port 6544 and control channel commands on port 6545:

```
swtpm socket --server type=tcp,port=6544 --ctrl type=tcp,port=6545 --tpm2
```

Control commands can be sent to it using the following command:

```
swtpm_ioctl --tcp localhost:6545 ...
```

**Comment by Melab** [comment]
@stefanberger Are the projects related, seeing as you work at IBM?

**Comment by stefanberger** [comment]
libtpms uses the IBM software TPM 1.2 and TPM 2 at its core. SWTPM uses libtpms.

**Comment by stefanberger** [comment]
@Melab Can we close this issue ?
