### ISSUE TITLE
Are swtpm writes atomic?

### ISSUE THREAD

**Issue by mz-pdm** [stefanberger/swtpm#343]
It would be useful to be able to backup swtpm data while a VM is running. However this requires that swtpm writes to the file system are atomic, in order to avoid races and copying possibly inconsistent data when the VM writes to a TPM device at the same time the swtpm files are copied. Looking into the source code, it looks to me like the data files are truncated and newly written rather than modified atomically and they can be completely deleted in case of errors. Is it really so? If yes, would it be possible to make data modifications atomic?

**Comment by stefanberger** [comment]
I don't know what it would take to make it atomic from the perspective of backup software. Currently the writes are overwriting a file without using a temporary file or so. What happens if the backup software reads a file while swtpm wants to remove it to then be able to rename the temporary file to the permanent file? Do we need some sort of locking? How does backup software deal with other software that may truncate and then rewrite?

**Comment by stefanberger** [comment]
A reference: https://lwn.net/Articles/789600/

**Comment by mz-pdm** [comment]
Wouldn't ``rename`` without manual removal of the original file be atomic and suffice? Copying the file (I don't have anything more sophisticated for the backup purposes on mind) should simply work in such a case.
If manual removal of the original file was needed for some reason then something indicating consistency would be needed. It is OK for our purposes to repeat the copying attempt if we detect temporary inconsistency, e.g. when the file is missing (and we know it should be there). Of course yes, there could be more sophisticated options, such as some sort of locking and/or lock files, or version numbers.
A related interesting question is what to do when writing new data fails. Whether to keep the original file (having at least something) or to delete it (better no data than stale data). 
In any case, always having one copy of consistent data under normal (non-erroneous) circumstances could be also useful for putting swtpm data on a shared storage. If a VM had both disks and swtpm data on a shared storage and the host running the VM crashed then swtpm data would survive, without risk of inconsistency.
I think that simply modifying the writes to write to a temporary file and then renaming it, if possible, might be good enough and would help a lot.

**Comment by mz-pdm** [comment]
Thank you for the reference to the article, that's a good remark. But I don't think it's necessary to bother about fsync much here. As long as the OS is running, we should see consistent file system operations. And if the host crashes, the data is going to be restored from the backup (it's the primary motivation for making the backups), most likely on another host.
There may be issues when using a shared storage as mentioned in my previous comments, but using a shared storage is always sort of risk itself and must be carefully evaluated by the upper layer management software.

**Comment by stefanberger** [comment]
Ok , will look at it soon.

From what I can see it shouldn't affect the AppArmor profile in libvirt and the Seccomp profile. It may affect the SELinux profile, let's see.

**Comment by stefanberger** [comment]
@mz-pdm Here's the PR addressing this issue: https://github.com/stefanberger/swtpm/pull/346

Thanks!

**Comment by mz-pdm** [comment]
Thank you, Stefan, for quickly dealing with the issue!

**Comment by stefanberger** [comment]
I merged the PR. Thanks.
