### ISSUE TITLE
Error message even the proper package is installed

### ISSUE THREAD

**Issue by wbiker** [stefanberger/swtpm#35]
Hi,

I am trying to install qemu-tpm, swtpm and libtpms. At the moment I cannot build swtpm and libtpms because I always get following error when I call ./configure --perfix=/usr:
configure: error: "Could not find AES_CreateContext(). Is nss-softokn-freebl-devel/libnss3-dev installed?"
I am running Ubuntu 16.04 and of course, the libnss3-dev with and without -dev is installed.
Any hint or idea what could be the problem here?
Thanks

**Comment by stefanberger** [comment]
Try using OpenSSL with the following line:

```
./configure --prefix=/usr --with-openssl
```

I am not sure why AES_CreateContext is not visible from the freebl library.

**Comment by wbiker** [comment]
Thanks. That fixed mine problem.
