### ISSUE TITLE
cuse device does not support "--flags not-needed-init"

### ISSUE THREAD

**Issue by anatol** [stefanberger/swtpm#353]
I am trying to use `swtpm` for TPM2 unit tests. I setup a TPM state as 

```log
$ swtpm_setup --tpm-state tpm.state --tpm2 --ecc --display --create-ek-cert --create-platform-cert --lock-nvram
Starting vTPM manufacturing as anatol:anatol @ Mon 12 Oct 2020 08:59:47 AM PDT
TPM is listening on Unix socket.
Successfully created RSA 2048 EK with handle 0x81010001.
  Invoking /usr/share/swtpm/swtpm-localca --type ek --ek b3cd207000008a703c53eb7993f78dc0d415abaccd7f579734b073997b357ce45a327fc092fac4613cc577a3d4842f146794f24d4cd42791009eb37a8a5699c3a0680e7bbc386810ee6237cab6f554fd1daab1ec4b9b74002ca832fa1cdc30d49933a7956ca3424854f58fd1464c2dd8c73f6fcf0ae6dd5dd9597ee089d9a31399199cad7cd30f2581ce01cad5f9dcb595dbfc144a5778affb710af9c164c080e544b5d999439e6c8d0d7d403fc0affae01dd63393a3d7e2bbbf504e136e017e6ac4edb9677eaa2249c923e522a525e31ef17ba1c9552de6dbf52fcc61faa0924492ef8862b60cf4eb4e3e5b2d9f2a9053b449e98ef843fad90c99a5a98e830b --dir tpm.state --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 150 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20170619 --tpm2 --configfile /home/anatol/.config/swtpm-localca.conf --optsfile /home/anatol/.config/swtpm-localca.options
swtpm-localca: Successfully created EK certificate locally.
  Invoking /usr/share/swtpm/swtpm-localca --type platform --ek b3cd207000008a703c53eb7993f78dc0d415abaccd7f579734b073997b357ce45a327fc092fac4613cc577a3d4842f146794f24d4cd42791009eb37a8a5699c3a0680e7bbc386810ee6237cab6f554fd1daab1ec4b9b74002ca832fa1cdc30d49933a7956ca3424854f58fd1464c2dd8c73f6fcf0ae6dd5dd9597ee089d9a31399199cad7cd30f2581ce01cad5f9dcb595dbfc144a5778affb710af9c164c080e544b5d999439e6c8d0d7d403fc0affae01dd63393a3d7e2bbbf504e136e017e6ac4edb9677eaa2249c923e522a525e31ef17ba1c9552de6dbf52fcc61faa0924492ef8862b60cf4eb4e3e5b2d9f2a9053b449e98ef843fad90c99a5a98e830b --dir tpm.state --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 150 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20170619 --tpm2 --configfile /home/anatol/.config/swtpm-localca.conf --optsfile /home/anatol/.config/swtpm-localca.options
swtpm-localca: Successfully created platform certificate locally.
Successfully created NVRAM area 0x1c00002 for RSA 2048 EK certificate.
Successfully created NVRAM area 0x1c08000 for platform certificate.
Successfully created ECC EK with handle 0x81010016.
  Invoking /usr/share/swtpm/swtpm-localca --type ek --ek x=2a055e3a315cb2f434ee69fcc47145d514a945c8ffdf0b7e7dacc06f1e4a067194b0e3d5f6fc0c7dcea6df9027600b8b,y=f6eb13d7c265442c601256bcea94dcfef3e66025907061868f9e55da22e8cfbd858e66266172dd163fa0df31245ac348,id=secp384r1 --dir tpm.state --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 150 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20170619 --tpm2 --configfile /home/anatol/.config/swtpm-localca.conf --optsfile /home/anatol/.config/swtpm-localca.options
swtpm-localca: Successfully created EK certificate locally.
Successfully created NVRAM area 0x1c00016 for ECC EK certificate.
Successfully activated PCR banks sha256,sha1 among sha1,sha256,sha384,sha512.
Successfully authored TPM state.
Ending vTPM manufacturing @ Mon 12 Oct 2020 08:59:48 AM PDT
```

The docs about using `swtpm` is a bit confusing but it looks like I need to use `--flags not-need-init` to avoid overwriting my TPM chip state. So I run `cuse` like this `sudo swtpm cuse -n tpmrm0 --tpm2 --log file=tpm.log --tpmstate dir=tpm.state --flags not-need-init` but it fails with

```
cuse: unrecognized option '--flags'
swtpm: Unknown parameter 'not-need-init'
```

What is the reason socket and chardev allowed to use the state while `cuse` does not? Should `cuse` have `not-need-init` as well?

**Comment by stefanberger** [comment]
`--flags not-need-init` is not to prevent overwriting the state but to not need to run `swtpm_ioctl -i <device name>`. `swtpm` will work with the statefiles it finds in the directory passed using  `--tpmstate dir=<directory>` and will overwrite them when new persistent state needs to be written.

I would not use the CUSE TPM anymore. The `/dev/tpmrm1` you may create with the CUSE TPM in your example will not behave as expected (following how it is named) and will not do the context swapping etc. because it is just a plain character device that has the naming pattern of the resource manager. Instead, the preferred way is to use the tpm_vtpm_proxy module and `swtpm chardev` as follows:

```
# sudo modprobe tpm_vtpm_proxy
# /usr/share/swtpm/swtpm-create-user-config-files     # omit this command if you run the commands as 'root'
# mkdir tpm.state
# swtpm_setup --tpm-state tpm.state --tpm2 --ecc --display --create-ek-cert --create-platform-cert --lock-nvram
# sudo swtpm chardev --vtpm-proxy --tpm2 --log file=tpm.log --tpmstate dir=tpm.state --flags not-need-init
```

The last command will print something like the following.
```
New TPM device: /dev/tpm2 (major/minor = 253/2)
```
This now provides `/dev/tpm2` and `/dev/tpmrm2` devices with the latter created by the kernel internal resource manager and doing the context swapping as expected.

**Comment by anatol** [comment]
Thank you very much. Your recipe with `vtpm` works for me. So based on your advice I am going to use it instead of `cuse` interface.

If `cuse` technology is considered out-of-date then it would be great to document this statement in wiki and man pages.

Also it would be great to have a wiki page dedicated to "how to use swtpm for unit testing" topic. That would show how to setup a tpm2 device + configure `tpm-tools` to use it + examples. Ideally if this device setup does not require "root" permissions.

 Thank you for your help!

**Comment by stefanberger** [comment]
There's an entry here for how to use it with the IBM TSS tools over sockets: https://github.com/stefanberger/swtpm/wiki/Using-the-IBM-TSS-with-swtpm

**Comment by stefanberger** [comment]
@anatol Can we close the issue?

**Comment by anatol** [comment]
Sure, thank you for your help.

**Comment by anatol** [comment]
Slightly off-topic: what is the best place to ask further questions about `swtpm`? Do you have any maillists (telegram/slack/... channel) for user questions?

**Comment by stefanberger** [comment]
I created a user mailing list now here: https://groups.google.com/u/1/g/swtpm-user

**Comment by anatol** [comment]
> I created a user mailing list now here: https://groups.google.com/u/1/g/swtpm-user

Thank you a lot! Is there a chance to make it open, so anyone can join the group without requesting a permission?

**Comment by stefanberger** [comment]
Other mailing lists also require subscription to be able to post. It should be visible to all, though.

**Comment by anatol** [comment]
It might make sense to remove this subscription registration to make the project engaging easier.

Anyway I sent my question a while ago https://groups.google.com/u/1/g/swtpm-user/c/h0mg3RwE3mM I appreciate if you share your opinion on it.

**Comment by roychowdhuryrohit-dev** [comment]
@stefanberger 

On running the command `sudo modprobe tpm_vtpm_proxy`, I am getting the following error.

`modprobe: FATAL: Module tpm_vtpm_proxy not found in directory /lib/modules/5.4.0-73-generic`

I am running my VM on Ubuntu Server 20.04. I want to use swtpm as vTPM (/dev/tpm0 and /dev/tprm0).

**Comment by stefanberger** [comment]
> I am running my VM on Ubuntu Server 20.04. I want to use swtpm as vTPM (/dev/tpm0 and /dev/tprm0).

The CUSE TPM won't create /dev/tpmrm0. Please follow the instructions [here](https://github.com/stefanberger/swtpm/wiki/Using-the-IBM-TSS-with-swtpm#character-device-using-tpm_vtpm_proxy) on how to start it with --vtpm-proxy.

**Comment by roychowdhuryrohit-dev** [comment]
I tried following your instructions. On running the command `sudo modprobe tpm_vtpm_proxy`, I am getting the following error.

`modprobe: FATAL: Module tpm_vtpm_proxy not found in directory /lib/modules/5.4.0-73-generic`

**Comment by stefanberger** [comment]
You likely have to install the package `linux-modules-extra`.

**Comment by roychowdhuryrohit-dev** [comment]
Thanks a lot. It worked flawlessly so far. I almost thought it would require the Hypervisor to support vTPM.
