### ISSUE TITLE
Building swtpm statically with gcc

### ISSUE THREAD

**Issue by benlytle** [stefanberger/swtpm#355]
I've been trying to build swtpm statically for portability.
This is with master swtpm and libtpms; openssl_1_1_1h
I compiled OpenSSL and libtpms statically.
Locations of necessary files:
>/usr/local/lib/pkgconfig/(libcrypto.pc, libtpms.pc)
/usr/local/lib/(libtpms.a, libcrypto.a)

I used this to configure:

>$ CFLAGS="-static" PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"   \\
 ./autogen.sh --with-openssl --with-gnutls --without-cuse --without-seccomp

Configure fails with this error:
>checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking target system type... aarch64-unknown-linux-gnu
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking for debug-enabled build... no
checking for ANSI C header files... (cached) yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... yes
checking return type of signal handlers... void
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for semodule... /usr/sbin/semodule
checking for AES_set_encrypt_key in -lcrypto... yes
checking openssl/aes.h usability... yes
checking openssl/aes.h presence... yes
checking for openssl/aes.h... yes
Building with openssl crypto library
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LIBTPMS... yes
checking for TPMLIB_ChooseTPMVersion in -ltpms... no
configure: error: "libtpms 0.6 or later is required"

Is there something I'm missing?
Also had the same error with `swtpm-0.5` and libtpms `stable-0.7.0`

**Comment by stefanberger** [comment]
I haven't built it statically and the advantage of linking it dynamically is that one can get the updated versions of the dependent libraries, particularly openssl crypto library. The problem is probably related to missing symbols in libtpms.a related to openssl function. You may want to check config.log.

**Comment by stefanberger** [comment]
I have tried this on Fedora. There the troubles are already starting with this part here:

```
[...]
Building with openssl crypto library
checking for EVP_CIPHER_CTX_new in -lcrypto... no
checking for EVP_EncryptInit_ex in -lcrypto... no
[...]
```

This is due to these failures one can find in config.log:
```
[...]
configure:5462: checking for ECDSA_SIG_new in -lcrypto
configure:5487: gcc -o conftest -static -lcrypto -ldl -lpthread   conftest.c -lcrypto  -lcrypto  >&5
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libcrypto.a(b_addr.o): in function `BIO_lookup_ex':
(.text+0xd02): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libcrypto.a(b_sock.o): in function `BIO_gethostbyname':
(.text+0x75): warning: Using 'gethostbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/9/../../../../lib64/libcrypto.a(fips.o): in function `verify_checksums':
(.text+0x516): undefined reference to `dlopen'
/usr/bin/ld: (.text+0x531): undefined reference to `dlsym'
/usr/bin/ld: (.text+0x545): undefined reference to `dladdr'
/usr/bin/ld: (.text+0x554): undefined reference to `dlclose'
/usr/bin/ld: (.text+0x5a9): undefined reference to `dlclose'
/usr/bin/ld: (.text+0x61c): undefined reference to `dlclose'
[...]
```

At least on Fedora there seem to be undefined symbols in OpenSSL's static -lcrypto.

Just to get the updates from OpenSSL it's better to dynamically link...

**Comment by stefanberger** [comment]
Even though I would discourage building swtpm and libtpms statically, which prevents one from getting security fixes to openssl's crypto library for example, it seems to be possible using the following configure lines:

libtpm: `CFLAGS="-static" LIBS="-lcrypto -lssl -ldl -lpthread -lz" ./configure --with-openssl --with-tpm2 --prefix=...`

The final linking stage of `swtpm` is a bit of an issue. The problem then becomes this here:

```
gcc -I../../include -I../../include -I../../include/swtpm -DHAVE_SWTPM_CUSE_MAIN -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security -I/usr/include/p11-kit-1 -Bstatic -o swtpm swtpm-main.o swtpm-osx.o swtpm-swtpm.o swtpm-swtpm_chardev.o -Bstatic  -L/home/stefanb/tmp/swtpm/src/swtpm/.libs /home/stefanb/tmp/swtpm/src/swtpm/.libs/libswtpm_libtpms.a -ltpms -Wl,-Bdynamic,-L/lib64/lcrypto,-Bstatic; ldd swtpm
/usr/bin/ld: cannot find -lgcc_s
/usr/bin/ld: /home/stefanb/tmp/swtpm/src/swtpm/.libs/libswtpm_libtpms.a(libswtpm_libtpms_la-utils.o): in function `change_process_owner':
utils.c:(.text+0x1bd): warning: Using 'initgroups' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /home/stefanb/tmp/swtpm/src/swtpm/.libs/libswtpm_libtpms.a(libswtpm_libtpms_la-options.o): in function `option_value_add':
options.c:(.text+0x5a9): warning: Using 'getgrnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: options.c:(.text+0x4e6): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lgcc_s
collect2: error: ld returned 1 exit status
ldd: ./swtpm: No such file or directory
```

**Comment by stefanberger** [comment]
I do not intend to fix the above-shown issue since these function calls are needed for properly switching to another user when using `--runas`. I find dynamic linking to be more important to get more recent OpenSSL crypto library and distro's may not want to have statically linked crypto code in apps because of this. I am going to close this issue.
