### ISSUE TITLE
LIBTPMS_CFLAGS is ignored by configure

### ISSUE THREAD

**Issue by osresearch** [stefanberger/swtpm#356]
It looks like https://github.com/stefanberger/swtpm/pull/262/commits/97031d658eeb7aa962fc217be66d88e9fabb86bc added support for specifying a separate `LIBTPMS_CFLAGS` to configure, although my checkout of ab40d27 does not add it to the `CFLAGS`.  I added some `echo` commands to ensure that the right variable is being set:

```
% LIBTPMS_LIBS=-L../libtpms/src/.libs LIBTPMS_CFLAGS=-I../libtpms/include  ./configure
....
checking for LIBTPMS... ****** using LIBTPMS_CFLAGS=-I../libtpms/include
***** using pkg_cv_LIBTPMS_CFLAGS=-I../libtpms/include
yes
checking for TPMLIB_ChooseTPMVersion in -ltpms... yes
...
checking Checking the crypto library libtpms is linked to... Package libtpms was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtpms.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtpms' found
configure: WARNING: Could not determine the crypto library libtpms is using, assuming openssl
...

Version to build  : 0.5.0
Crypto library    : openssl

CFLAGS=-g -O2 -I../libtpms/include -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security -I/usr/include/p11-kit-1 
HARDENING_CFLAGS=-fstack-protector-strong -Wstack-protector 
HARDENING_LDFLAGS= -Wl,-z,relro -Wl,-z,now
LDFLAGS= -L../libtpms/src/.libs 
LIBSECCOMP_LIBS=-lseccomp
```

The `LDFLAGS` is correctly passed on, but the `CFLAGS` is lost at some point.

**Comment by osresearch** [comment]
Ah, I had misread the error message -- the problem is not that it is ignored, but that the relative path to the headers doesn't work once `make` descends into the subdirectories.  Passing in an absolute path works.

**Comment by stefanberger** [comment]
Normally we are getting `-ltpms` from pkg-config (PKG_CONFIG_MODULES in configure.ac) like this:

```
# pkg-config libtpms --libs
-ltpms
```

Since you have yours in a non-standard path you have to provide this and the path to the library.
Otherwise please try configuring it like this:

```
 PKG_CONFIG_PATH=<path to libtpms.pc directory> ./configure --prefix=... ...
```

**Comment by osresearch** [comment]
In this case I'm trying to do the same thing as https://github.com/stefanberger/swtpm/commit/97031d658eeb7aa962fc217be66d88e9fabb86bc, where the path to a build directory for libtpms is used and the libtpms package has not been installed, so the `libtpms.pc` file doesn't refer to the correct paths.

In any event, adding an absolute path and `-ltpms` to the `LIBTPMS_LDFLAGS` works, so this is no longer an issue.
