### ISSUE TITLE
Installation of swtpm on an ARM architecture

### ISSUE THREAD

**Issue by ma2teo** [stefanberger/swtpm#357]
Hi @stefanberger ,

I am trying to build and install the swtpm package on my BeagleBone Black.

I am doing a feasibility study of an IoT project for which a TPM is required.
In this first phase of the study I choose to emulate the TPM.
My target board is a BeagleBone Black (armv7, Ubuntu 18.04).
I follow your wiki page, so I start with the installation of libtpms through the procedure https://github.com/stefanberger/libtpms/wiki#build-a-package-on-ubuntu and it works fine.
Then I try to install the swtpm according the procedure https://github.com/stefanberger/swtpm/wiki#build-deb-package-ubuntu-debian , but the second command _dpkg-buildpackage -us -uc -j1_ returns a couple of errors related to _test_swtpm_setup_create_cert_ and _test_tpm2_swtpm_setup_create_cert_ tests. The reason seems the same: timeout after 10 seconds.

At this point I would ask you:
1) Is swtpm adequate for an ARM architecture?;
2) If yes, could you help me to fix these errors?.

Thanks in advance.
Regards.

Attachment: 
[test-suite_arm.log](https://github.com/stefanberger/swtpm/files/5430508/test-suite_arm.log)

**Comment by stefanberger** [comment]
> Then I try to install the swtpm according the procedure https://github.com/stefanberger/swtpm/wiki#build-deb-package-ubuntu-debian , but the second command _dpkg-buildpackage -us -uc -j1_ returns a couple of errors related to _test_swtpm_setup_create_cert_ and _test_tpm2_swtpm_setup_create_cert_ tests. The reason seems the same: timeout after 10 seconds.

Rather than building a package, can you try to compile it locally and run these tests individually from the command line:

```
make
cd tests
./test_swtpm_setup_create_cert
./test_tpm2_swtpm_setup_create_cert
```

A possibility would be that this processor is slow and creating the keys takes too long. 

One way to track this down would be to put a higher number here: https://github.com/stefanberger/swtpm/blob/master/src/swtpm_setup/py_swtpm_setup/swtpm_setup.py#L226

You could also try to remove libtpms 0.8.0 (make uninstall) and use the version from the stable-0.7.0 branch that doesn't have 3072 bit keys, which may be the reason for this.


> 
> At this point I would ask you:
> 
>     1. Is swtpm adequate for an ARM architecture?;

I used to test it on a Raspberry Pi (from 2014) but don't have access to it at the moment. So, yes, it is 'adequate', whatever that means.

> 
>     2. If yes, could you help me to fix these errors?.

Hope the above suggestions helps you track the issue down.

**Comment by ma2teo** [comment]
Hi @stefanberger ,

Thanks for the answers.

About the timeout problem, following your suggestions I have tried several attempts.
First, with timeout equals to 10 seconds, I compile and run the two tests. They return the same problem of timeout.
So I increase the timeout to 60 seconds. Compiling and running the two tests, they work fine. However when I build the Debian package, only one test (test_swtpm_setup_create_cert) is successfully, while the other test (test_tpm2_swtpm_setup_create_cert) continues to fail due to timeout of 60 seconds.
Then I increase the timeout to 180 seconds. Compiling and running the two tests, they still work fine. The building of the Debian package is fine too. At this point I will keep the timeout at this value.

Thanks again,
Regards.

**Comment by stefanberger** [comment]
> Then I increase the timeout to 180 seconds. Compiling and running the two tests, they still work fine. The building of the Debian package is fine too. At this point I will keep the timeout at this value.

I am glad it works but 3 minutes sounds excessively long even for a 32 bit ARM processor.

**Comment by stefanberger** [comment]
Can you remove the local CA's statefile using the following commands (as root) and run the creation of TPM certificates twice and post the output? My suspicion is that the creation of the local CAs takes some time and then creating the keys on top of that takes more time and it doesn't end up finishing in time.
```
rm /var/lib/swtpm-localca
time swtpm_setup --tpmstate . --tpm2 --create-ek-cert --create-platform-cert  --overwrite
time swtpm_setup --tpmstate . --tpm2 --create-ek-cert --create-platform-cert  --overwrite
```

**Comment by ma2teo** [comment]
Hi @stefanberger ,

In the attachment _CreationCertificateLog.txt_ you can find the result of the test that you ask me.

I take advantage of this issue to deepen the installation of the swtpm component.
In my feasibility study, a software stack wants to communicate with the swtpm through the cuse interface.
During the building of the Debian Package, according the https://github.com/stefanberger/swtpm/wiki#build-deb-package-ubuntu-debian procedure, I notice that the cuse interface is disabled:
_with_cuse       :    no  (no = no CUSE interface)_
For this reason I uninstall the swtp Debian packages that I have previously installed. Then I try to install the swtpm according the https://github.com/stefanberger/swtpm/wiki#compile-and-install-on-linux procedure, paying attention to modify the following command:
_./autogen.sh --with-openssl --prefix=/usr **--with-cuse**_
The output of this command shows the enabling of the cuse interface:
_with_cuse       :    yes  (no = no CUSE interface)_
I continue with the command:
_make -j1
make -j1 check_
However the last command fails due to the _Unsupported TPM interface type 'cuse'_ error for most of the tests. In the attachment _test-suiteInstallLinuxProcedure.log_ I report the details for the tests results. So I can’t proceed with the installation of the swtpm.

At this point I would ask what is the correct procedure to install the swtpm with an available cuse interface? What have I overlooked in my way of proceeding?.

Thanks in advance.
Regards


Attachments:
[CreationCertificateLog.txt](https://github.com/stefanberger/swtpm/files/5464621/CreationCertificateLog.txt)
[test-suiteInstallLinuxProcedure.log](https://github.com/stefanberger/swtpm/files/5464625/test-suiteInstallLinuxProcedure.log)

**Comment by stefanberger** [comment]
Following the output log of the `make -j1 check` run the swptm that the test suite is using doesn't have the cuse interface built in. This is strange. From the root directory of the swtpm project, can you run `./src/swtpm/swtpm --help` and see whether this executable has the cuse interface built in, which should be listed next to socket and chardev? This is the executable the test suite should be using unless you set `SWTPM_EXE=<path to swtpm>` and it's not using another executable.

**Comment by stefanberger** [comment]
In regards to the timeout:

```
[...]
Successfully authored TPM state.

Ending vTPM manufacturing @ Fri 30 Oct 2020 09:57:36 AM UTC
real	0m26.611s
user	0m25.042s
sys	0m0.735s
```
The above is from CreationCertificateLog.txt above.

I would say that 30 seconds should be enough time for the first run to create the CA and intermediate CA keys and have the EK certificate created. I would would that your gnutls version already creates 3072 bit keys for the CAs so that we wouldn't jump that that size only later on. 30 second should also allow for some concurrent creation of certificates later on.

**Comment by ma2teo** [comment]
Hi @stefanberger ,

Thanks for your attention to these matters.

About the cuse interface, this is the output of the command _./src/swtpm/swtpm --help_ :

```
TPM emulator with choice of interface.

Usage: /home/ubuntu/Projects/swtpm/swtpm/src/swtpm/.libs/swtpm socket|chardev [options]
       /home/ubuntu/Projects/swtpm/swtpm/src/swtpm/.libs/swtpm -v|--version

Use the --help option to see the help screen for each interface type.
Use the --version options to see version information.
```

Next to socket and chardev it doesn’t appear the cuse interface. So it isn’t explainable because the autogen’s output says that the cuse interface is included.
About the SWTPM_EXE variable, it isn’t set in my environment.
To better understand this situation, I start from an Ubuntu “clean” distribution.
First I build and install libtpms packages ( https://github.com/stefanberger/libtpms/wiki#build-a-package-on-ubuntu ), then I compile and install swtpm library ( https://github.com/stefanberger/swtpm/wiki#compile-and-install-on-linux ) with the addition of the option _--with-cuse_ for the autogen command.
Now the output of the _./src/swtpm/swtpm --help_ command is:

```
Unsupported TPM interface type '–help'.
TPM emulator with choice of interface.

Usage: /home/ubuntu/Projects/swtpm/swtpm/src/swtpm/.libs/swtpm socket|chardev|cuse [options]
       /home/ubuntu/Projects/swtpm/swtpm/src/swtpm/.libs/swtpm -v|--version

Use the --help option to see the help screen for each interface type.
Use the --version options to see version information.
```

This time the output is coherent with the autogen output.
Maybe in the previous attempt the building and installation of the swtpm packages have corrupted the following compiling and installing of the swtpm library, despite the swtpm packages had already been removed. It seems as if something in the operating system has been corrupted.

About the timeout matter, I use the GnuTLS utility certtool to verify the generation of 3072 bits key. It seems to work fine:

```
ubuntu@arm:~/Projects/testKey$ certtool -V --generate-privkey --outfile testKey01.pem
Generating a 3072 bit RSA private key...
ubuntu@arm:~/Projects/testKey$ ls -la
total 16
drwxrwxr-x 2 ubuntu ubuntu 4096 Nov  3 10:34 .
drwxrwxr-x 4 ubuntu ubuntu 4096 Nov  3 10:21 ..
-rw------- 1 ubuntu ubuntu 8167 Nov  3 10:34 testKey01.pem
```

I honestly don't know why the tests failed while building the swtpm package using a 60 seconds timeout. However for now, a 180 seconds timeout doesn’t represent a problem.

Thanks again.
Regards.

**Comment by stefanberger** [comment]
Is there anything you feel we should do for ARM? If so, let me know.

I am running once-a-week tests of swtpm on ARM and other architectures. But Travis probably has more recent ARM processors than what you seem to be using, so they won't run into those timeouts: https://travis-ci.org/github/stefanberger/swtpm-distro-compile

**Comment by ma2teo** [comment]
Hi @stefanberger,

Thanks for your consideration and interest, but in this moment there is nothing that I need.

Thanks again.
Regards.

**Comment by stefanberger** [comment]
A PI user in the other issue is also seeing timeouts. I will probably increase the timeout to 30s. 180s seems excessive, though, even for an old ARM.

**Comment by stefanberger** [comment]
Master now has a patch that increased the timeout to 30s...

**Comment by stefanberger** [comment]
The extension of the timeout to 30s solved the issue for the PI.

**Comment by stefanberger** [comment]
Closing this issue now. If there's anything else we can do for it, we can reopen.
