### ISSUE TITLE
Add option to change template for Intermediate and rootCA

### ISSUE THREAD

**Issue by mwiseman32** [stefanberger/swtpm#358]
Allow options instead of hard coded template in function create_localca_cert. For example instead of having cn=swtpm-localca-rootca allow options to have custom values. Also allow other fields such as organization=. This might best be done by adding or extending the existing .config files. This would permit testing using the swtpm in development and validation in more "real-world" environments.

**Comment by stefanberger** [comment]
I am wondering whether this is necessary. The CAs are created on the fly only if someone doesn't install their own. So if someone is interested in a higher-value CA she will create it elsewhere and install the key of their signing CA before a local CA would be created (on the fly). For 'real-world' environments I would suggest to create a CA elsewhere and install the signingkey etc. on all machines where swtpm_setup is run.

**Comment by mwiseman32** [comment]
Agree this would also work. Thanks.
