### ISSUE TITLE
latest swtpm tests failing with "Error: Could not initialize the cuse TPM"

### ISSUE THREAD

**Issue by ravikumarbhattiprolu** [stefanberger/swtpm#363]
All,
 I have just downloaded v0.5.0 of release and tried building it on Ubuntu 20.04. When I try "make check" 30 test have failed and when I look at tests/test-suite.log one common error for most of the tests is:
Error: Could not initialize the cuse TPM

is there something I am missing here?
regards,
Ravi

**Comment by stefanberger** [comment]
I just tried swtpm stable-0.5.0 on Xenial & Bionic and it worked fine for me. Unfortunately I cannot recreate your issue.
You could try building swtpm on Ubuntu with `--without-cuse` unless you need the CUSE TPM.

**Comment by ravikumarbhattiprolu** [comment]
Thanks for fast reply and resolution. I had cuse libraries installed for other software and configure was picking them. Also debian/control also seems to install cuse(libfuse-devel). I have manually removed those libraries and now it is working.

This issue can be closed.
Regards,
Ravi

Sent from my mobile....
________________________________

**Comment by stefanberger** [comment]
> Thanks for fast reply and resolution. I had cuse libraries installed for other software and configure was picking them. Also debian/control also seems to install cuse(libfuse-devel). I have manually removed those libraries and now it is working.

Odd. It should also work with the CUSE interface built in...
