### ISSUE TITLE
Could you please sign the release tarballs?

### ISSUE THREAD

**Issue by kailiu42** [stefanberger/swtpm#375]
It would be great if future release tarballs could be gpg signed and the public key can be made available so the authenticity can be verified, especially this is a security related software.

**Comment by stefanberger** [comment]
I did that now for this project.

**Comment by kailiu42** [comment]
Could you also make the public key available? I cannot find it in the wiki or other obvious place.

**Comment by kailiu42** [comment]
It would be great if you could clearly state somewhere in this project(wiki, README etc.) that how the pub key used to sign this project could be retrieved. So that we have a "trusted source" for the key.

**Comment by stefanberger** [comment]
I put it now here: https://github.com/stefanberger/swtpm/wiki#my-public-gpg-key

**Comment by kailiu42** [comment]
Verified v0.5.1 source with the key without problem. Will include source verification in the next version update for openSUSE. Thanks!
