### ISSUE TITLE
Partial read support for swtpm-cuse

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [stefanberger/swtpm#376]
This is half a Question, half a bug and half a feature reuest.

Does swtpm-cuse support partial reads of responses as the tpm kernel driver does ?

I think we might have run into this issue here: https://github.com/tpm2-software/tpm2-tss/issues/1918
It looks like the TPM is sending the header twice on two subseuent reads, instead of resuming after the response header.

Some background; with 3.0 we switched to partial read support by default / autodetection.

As a fix on our side: is there a way to distinguish the swtpm-cuse from a real tpm so we could add this to the autodetection code ?

Could you add partial-read support to swtpm ?

**Comment by stefanberger** [comment]
My suggestion would be to use `swtpm chardev --vtpm-proxy` and you get the kernel driver's partial read support immediately.

**Comment by AndreasFuchsSIT** [comment]
Noted, that makes a lot of sense.
Is there still a way for tpm2-tss to detect swtpm-cuse so we handle legacy-users of swtpm-cuse more gracefully ?

**Comment by stefanberger** [comment]
> Is there still a way for tpm2-tss to detect swtpm-cuse so we handle legacy-users of swtpm-cuse more gracefully ?

To avoid partial reads in case swtpm-cuse is being used? It offers the control channel ioctl's on the `/dev/tpm%d` interface, and won't have a `/dev/tpmrm%d`. The former would probably be easier to use for probing, but then maybe it's just a matter of documenting it to steer users away from swptm-cuse.

**Comment by stefanberger** [comment]
I now created PR #394 for support of partial reads. Can you test it?

**Comment by stefanberger** [comment]
I merged the extension. It comes with a test case and should be good to go.
