### ISSUE TITLE
No success running 'make check'

### ISSUE THREAD

**Issue by jorgeventura** [stefanberger/swtpm#382]
I have to use openssl, there is no way to switch to libressl.
The autogen command:

$ ./autogen.sh --without-cuse --with-gnutls --with-openssl --prefix=/us

```
FAIL: test_swtpm_setup_create_cert
PASS: test_tpm2_parameters
FAIL: test_tpm2_samples_swtpm_localca
SKIP: test_tpm2_samples_swtpm_localca_pkcs11
PASS: test_tpm2_swtpm_cert
PASS: test_tpm2_swtpm_cert_ecc
PASS: test_tpm2_swtpm_setup_create_cert
============================================================================
Testsuite summary for swtpm 0.5.1
============================================================================
# TOTAL: 57
# PASS:  47
# SKIP:  8
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
```

**Comment by jorgeventura** [comment]
I have the same issue with the master version 0.6.0.

**Comment by stefanberger** [comment]
What distro are you using? Can you also post `test/test_tpm2_samples_swtpm_localca.log` and `test/test_swtpm_setup_create_cert.log` ?

**Comment by jorgeventura** [comment]
Hi Stefanberger,
I didn't expect your quick reply, I am sorry. I am using Gentoo but the package from Gentoo does not support openssl only libressl for libtpm and swtpm what force me to install directly from tarball.

I am using:
1. gnutls-3.6.15
2. openssl-1.1.1i
3. libtpm-0.8.0 from your repository with no problem, 'make check' just fine
4. swtpm-0.6.0 from your repository, no compilation problem but 'make check' problem

Below is the log that you ask me for.

=======================================
   swtpm 0.6.0: tests/test-suite.log
=======================================

# TOTAL: 57
# PASS:  47
# SKIP:  8
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

SKIP: test_vtpm_proxy
=====================

Need to be root to run this test.
SKIP test_vtpm_proxy (exit status: 77)

SKIP: test_tpm2_vtpm_proxy
==========================

Need to be root to run this test.
SKIP test_tpm2_vtpm_proxy (exit status: 77)

SKIP: test_tpm12
================

SKIP test_tpm12 (exit status: 77)

SKIP: test_tpm2_save_load_state_2
=================================

SWTPM_TEST_IBMTSS2 must be set to run this test.
SKIP test_tpm2_save_load_state_2 (exit status: 77)

SKIP: test_tpm2_save_load_state_3
=================================

SWTPM_TEST_IBMTSS2 must be set to run this test.
SKIP test_tpm2_save_load_state_3 (exit status: 77)

SKIP: test_tpm2_ibmtss2
=======================

SKIP test_tpm2_ibmtss2 (exit status: 77)

SKIP: test_samples_create_tpmca
===============================

Need to be root to run this test.
SKIP test_samples_create_tpmca (exit status: 77)

FAIL: test_swtpm_setup_create_cert
==================================

TPM is listening on Unix socket.
Error: Could not run /home/ventura/tpm/swtpm/src/swtpm_setup/swtpm_setup.
Setup Logfile:
Starting vTPM manufacturing as ventura:ventura @ Sun 20 Dec 2020 12:20:35 AM -00
Successfully created EK.
  Invoking /home/ventura/tpm/swtpm/samples/swtpm-localca --type ek --ek df32bfef4ff0f85ccd7f429e46b1496b85eb0a517bb25737716b83d5dab7d3c67ace609c93e7b5ab183679a9da2c8841de24e9a6ff4c24c9f90d13e52eab63cb3df3d2f03ed5f773209f3962f68642aa945445f87d0af2c103ba8c4a8e2fe4adba67aa6c6c0a93e3e1fc2533f313e75ac1c34095865ddedc7992a26344b23398b566e17291afb70cdb5bbe2e7dae68b92e9980c5a029b87d3fa0bc131db0711e91f807112d9de29cc18c8faf0f3c9f80b3edc244f89caa1704aad376480f6c520ed0986378953e18f5cd1246e9d94a951ff350af7fd17e01881163c208ee14037cf2f8f2785940c79c0d3a9a92c64e859174c118b3dc8a89da0a52f0ba42de49 --dir /tmp/tmp.yvGUvUstTL --logfile /tmp/tmp.yvGUvUstTL/logfile --tpm-spec-family 1.2 --tpm-spec-level 2 --tpm-spec-revision 116 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:00740001 --configfile /tmp/tmp.yvGUvUstTL/swtpm-localca.conf --optsfile /tmp/tmp.yvGUvUstTL/swtpm-localca.options
Creating root CA and a local CA's signing key and issuer cert.
Could not create root-CA
Generating a self signed certificate...
error loading file at --load-privkey: /tmp/tmp.yvGUvUstTL/swtpm-localca-rootca-privkey.pem: Decryption has failed.
Error creating local CA's signing key and cert.
Error returned from command
An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Sun 20 Dec 2020 12:20:36 AM -00
FAIL test_swtpm_setup_create_cert (exit status: 1)

FAIL: test_tpm2_samples_swtpm_localca
=====================================

Creating root CA and a local CA's signing key and issuer cert.
Could not create local CA
Generating a signed certificate...
error loading file at --load-privkey: /tmp/path with spaces.pcCYkb/signingkey.pem: Decryption has failed.
Error creating local CA's signing key and cert.
Error: Test with parameters '--allow-signing' failed.
FAIL test_tpm2_samples_swtpm_localca (exit status: 1)

SKIP: test_tpm2_samples_swtpm_localca_pkcs11
============================================

Could not setup softhsm:
Need p11tool from gnutls
softhsm needs to be v2.3.0 or greater and pkcs11 correctly configured
Need p11tool from gnutls
SKIP test_tpm2_samples_swtpm_localca_pkcs11 (exit status: 77)



Sincerely,
Jorge Ventura

**Comment by stefanberger** [comment]
The problem is obviously here:

```
Creating root CA and a local CA's signing key and issuer cert.
Could not create root-CA
Generating a self signed certificate...
error loading file at --load-privkey: /tmp/tmp.yvGUvUstTL/swtpm-localca-rootca-privkey.pem: Decryption has failed.
Error creating local CA's signing key and cert.
Error returned from command
```

It looks like an issue with gnutls try to access an encrypted private key. Strange is that I am also running gnutls-3.6.15-1 on Fedora 31 but I don't see this issue.

Can you apply the following patch and post one of the log files again?

```
diff --git a/samples/py_swtpm_localca/swtpm_localca.py b/samples/py_swtpm_localca/swtpm_localca.py
index 792f3921..b261be0f 100644
--- a/samples/py_swtpm_localca/swtpm_localca.py
+++ b/samples/py_swtpm_localca/swtpm_localca.py
@@ -212,6 +212,7 @@ def create_localca_cert(lockfile, statedir, signkey, signkey_password, issuercer
             cacert = os.path.join(directory, "swtpm-localca-rootca-cert.pem")

             swtpm_rootca_password = os.getenv("SWTPM_ROOTCA_PASSWORD")
+            logerr(LOGFILE, "swtpm_rootca_password=%s" % swtpm_rootca_password)
             certtool = get_certtool()

             # First the root CA
@@ -253,6 +254,7 @@ def create_localca_cert(lockfile, statedir, signkey, signkey_password, issuercer
                 }
                 if swtpm_rootca_password:
                     certtool_env["GNUTLS_PIN"] = swtpm_rootca_password
+                    cmd.extend(["--password", swtpm_rootca_password])

                 try:
                     proc = subprocess.Popen(cmd, env=certtool_env,
```

**Comment by jorgeventura** [comment]
The log after apply the patch. By the way, I am not running as root. Is this required ?
=======================================
   swtpm 0.6.0: tests/test-suite.log
=======================================

# TOTAL: 57
# PASS:  47
# SKIP:  8
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

SKIP: test_vtpm_proxy
=====================

Need to be root to run this test.
SKIP test_vtpm_proxy (exit status: 77)

SKIP: test_tpm2_vtpm_proxy
==========================

Need to be root to run this test.
SKIP test_tpm2_vtpm_proxy (exit status: 77)

SKIP: test_tpm12
================

SKIP test_tpm12 (exit status: 77)

SKIP: test_tpm2_save_load_state_2
=================================

SWTPM_TEST_IBMTSS2 must be set to run this test.
SKIP test_tpm2_save_load_state_2 (exit status: 77)

SKIP: test_tpm2_save_load_state_3
=================================

SWTPM_TEST_IBMTSS2 must be set to run this test.
SKIP test_tpm2_save_load_state_3 (exit status: 77)

SKIP: test_tpm2_ibmtss2
=======================

SKIP test_tpm2_ibmtss2 (exit status: 77)

SKIP: test_samples_create_tpmca
===============================

Need to be root to run this test.
SKIP test_samples_create_tpmca (exit status: 77)

FAIL: test_swtpm_setup_create_cert
==================================

TPM is listening on Unix socket.
Error: Could not run /home/ventura/tpm/swtpm/src/swtpm_setup/swtpm_setup.
Setup Logfile:
Starting vTPM manufacturing as ventura:ventura @ Sun 20 Dec 2020 02:27:35 AM -00
Successfully created EK.
  Invoking /home/ventura/tpm/swtpm/samples/swtpm-localca --type ek --ek d635ba03374b34a574c48c682c9c26fa0d8a97108490558ef345052de890f84f1688dba0278521f4a2ca54db08efa6306a4cf956b941dedf99d3caa122f6ea91035319de7f7a3f0b11540db4e42e749376c10f2443b29adc71a09473d4d8b36ba0ce081c6c1a4dba7da7250f8abef4229285ec5395916ccae9e1b83edb7c3799ebef386d8c51d27890ab074c3215c11bd20ec23185d98f3d2a71dbac81c62ed9906c12949f72521c8bf94e937c12a1d9fe3a84c551c17e9b91e7a72aec1a72d048957de89b979615b6080b8eebbc2c522478e12de42fcae49a1e42add55a24670dd024108b928adb28f361ce98fa78b888f867cd8336fb240099c5427243c8b1 --dir /tmp/tmp.Ddmjc3mhgH --logfile /tmp/tmp.Ddmjc3mhgH/logfile --tpm-spec-family 1.2 --tpm-spec-level 2 --tpm-spec-revision 116 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:00740001 --configfile /tmp/tmp.Ddmjc3mhgH/swtpm-localca.conf --optsfile /tmp/tmp.Ddmjc3mhgH/swtpm-localca.options
Creating root CA and a local CA's signing key and issuer cert.
swtpm_rootca_password=passwordCould not create local CA
Generating a signed certificate...
error loading file at --load-privkey: /tmp/tmp.Ddmjc3mhgH/signingkey.pem: Decryption has failed.
Error creating local CA's signing key and cert.
Error returned from command
An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Sun 20 Dec 2020 02:27:36 AM -00
FAIL test_swtpm_setup_create_cert (exit status: 1)

FAIL: test_tpm2_samples_swtpm_localca
=====================================

Creating root CA and a local CA's signing key and issuer cert.
swtpm_rootca_password=NoneCould not create local CA
Generating a signed certificate...
error loading file at --load-privkey: /tmp/path with spaces.C3t6L2/signingkey.pem: Decryption has failed.
Error creating local CA's signing key and cert.
Error: Test with parameters '--allow-signing' failed.
FAIL test_tpm2_samples_swtpm_localca (exit status: 1)

SKIP: test_tpm2_samples_swtpm_localca_pkcs11
============================================

Could not setup softhsm:
Need p11tool from gnutls
softhsm needs to be v2.3.0 or greater and pkcs11 correctly configured
Need p11tool from gnutls
SKIP test_tpm2_samples_swtpm_localca_pkcs11 (exit status: 77)

**Comment by jorgeventura** [comment]
I did test using 'make check' as root but the same.

**Comment by jorgeventura** [comment]
Hi Stefanberger,
I found the problem and it was not in your program.
When I installed **_gnutls_** I didn't include _**pkcs11**_ support. That happened because I am installing _**swtpm**_ outside Gentoo package family and the Portage package manager doesn't consider that the pkcs11 support be required. If I try to install the Gentoo package, probably such detail would be considered by the package manager.

Sincerely thank you very much to spend your time with this problem,
Jorge Ventura

**Comment by stefanberger** [comment]
Did you build gnutls from the sources yourself and didn't compile pkcs11 support into it? What was actually failing has nothing to do with pkcs11 support but plain gnutls keys. Anyway, it's good that you could resolve it.

**Comment by jorgeventura** [comment]
Gentoo build every package from tarball and depending on requirements
include or not features optionally available. Because your specific
packages I installed from your repository and gnutls from Gentoo, the
package manager didn't see any reason to include pkcs11. I had to instruct
Gentoo to install gnutls with pkcs11 feature and after that everything
worked fine.
