### ISSUE TITLE
swtpm_cuse missing?

### ISSUE THREAD

**Issue by noyler** [stefanberger/swtpm#383]
Hi there-

I'm new to this project and TPM in general, so forgive me if I've done something idiotic.

I've been piecing together instructions from all over the web to get swtpm running on a new Ubuntu 18 install. I was able to successfully build/install libtpms, swtpm, and qemu. Happy to share those details if you like.

Upon trying to get my first cuse interface created for an eventual Windows VM test, I was able to successfully use swtpm_setup to configure the key store, but when I move on to the swtpm_cuse command, I get a simple "command not found" from the terminal. Similarly, if I try to use `swtpm cuse` as an interface type, I get a message about cuse being an unsupported interface type. I've scoured the man pages and github wiki and see frequent mention of the cuse ability, but when I view the /src directory in github, I don't see swtpm_cuse listed. Perhaps it was missed in the latest release? Or maybe it's been retired and the docs haven't been updated yet?

Thanks in advance for any pointers.

**Comment by stefanberger** [comment]
You have to configure swtpm with `./configure ... --with-cuse` and then likely you will have to install additional libraries. However, the `cuse` interface is deprecated now in favor of using `swtpm chardev --vtpm-proxy ...`. Also, when using it with QEMU (running a Windows VM), you could follow these instructions [here](https://github.com/qemu/qemu/blob/master/docs/specs/tpm.rst) or use [virt-manager](https://virt-manager.org/) for example to build a VM and attach a vTPM to it -- recent versions of virt-manager have support for attaching a vTPM device to a VM.

**Comment by noyler** [comment]
Thanks for the quick response!

Using `--vtm-proxy` created the `/dev/tmp0` interface, so it's just a matter of wrangling QEMU from here to use it properly. Figured I'd give virt-manager a go, which is easy to point at the cuse path, but is unhappy for other reasons. I'll review the instructions you linked and keep pushing forward. Thanks again!

**Comment by stefanberger** [comment]
FYI: QEMU will only use /dev/tpm0 with the passthrough device. My recommendation would be to follow the documentation for QEMU to use libvirt or virt-manager on top of libvirt. The latter two handle the swtpm_setup transparently.
