### ISSUE TITLE
Useless "if" condition in tpm_ioctl.c

### ISSUE THREAD

**Issue by fishilico** [stefanberger/swtpm#392]
**Describe the bug**
In `src/swtpm_ioctl/tpm_ioctl.c`: https://github.com/stefanberger/swtpm/blob/fba278cc4b8850c02e99297c498f82c44845f8c4/src/swtpm_ioctl/tpm_ioctl.c#L991-L1000
The `if (!tpm_device) {` condition is always true, because it is part of an `if (!tpm_device && !tcp_hostname && !unix_path) {` block.

This issue was found by running Cppcheck (http://cppcheck.sourceforge.net/) on `swtpm`'s git `master` tree.

**To Reproduce**
1. `git clone https://github.com/stefanberger/swtpm` (`master` branch)
2. Open `src/swtpm_ioctl/tpm_ioctl.c` in a text editor.
3. Read the code around lines 991-1000.

**Expected behavior**
The condition should not need to be checked again: I expect the code to do `tpm_device = argv[optind];` directly.

**Versions of relevant components**
- swtpm: master (commit fba278cc4b8850c02e99297c498f82c44845f8c4)

**Additional context**
I found this issue by running on Ubuntu 20.10: `sudo apt install cppcheck-gui ; cppcheck-gui swtpm`

**Comment by stefanberger** [comment]
The following command will trigger the error case:

```
$ swtpm_ioctl -i
Error: Missing device name.
```

The device name can be passed with either one of the following command lines:

```
1) $ swtpm_ioctl -i /dev/myvtpm
2) $ swtpm_ioctl -i --tpm-device /dev/myvtpm
```

The code block is there for the first line.

**Comment by stefanberger** [comment]
Also this here works:

```
$ swtpm_ioctl -i --tpm-device /dev/foo /dev/bar
```

In this case the `if (!tpm_device)` causes '/dev/foo' to be used

**Comment by fishilico** [comment]
> `$ swtpm_ioctl -i --tpm-device /dev/foo /dev/bar`
>
> In this case the if (!tpm_device) causes '/dev/foo' to be used

No. This works because of the `if (!tpm_device && !tcp_hostname && !unix_path)` (the condition is false, because `tpm_device` is not `NULL`), not because of the `if (!tpm_device)`.

**Comment by stefanberger** [comment]
PR https://github.com/stefanberger/swtpm/pull/393.
Thanks for reporting!

**Comment by fishilico** [comment]
Thanks. I confirm this looks fine.
