### ISSUE TITLE
Unintended global variable "input" in ctrlchannel.c

### ISSUE THREAD

**Issue by fishilico** [stefanberger/swtpm#395]
**Describe the bug**
In `src/swtpm/ctrlchannel.c`, a `struct input input` global variable is defined, because of the last `input` in this statement: https://github.com/stefanberger/swtpm/blob/5e9e47337e9a435ebaeb5986db003f2df2d7722f/src/swtpm/ctrlchannel.c#L286-L290

This variable seems to be never used, as it is "shadowed" by a variable `struct input *input;` in function `ctrlchannel_recv_cmd` and by variable `struct input input = {0, };` in function `ctrlchannel_process_fd`.

This issue was found by running Cppcheck (http://cppcheck.sourceforge.net/) on swtpm's git master tree.

**Expected behavior**
If the global variable `input` is used, it should be named something else, and probably made `static`. Here the variable is not used so the structure definition should probably be updated to not include it:
```c
struct input {
    uint32_t cmd;
    /* ptm_hdata is the largest buffer to receive */
    uint8_t body[sizeof(ptm_hdata)];
};  // <- remove "input" from here
```

**Versions of relevant components**
- swtpm: since commit https://github.com/stefanberger/swtpm/commit/ec3352ff7f8417c3513a70b3a0d6ea21bdf50c62 (v0.1.0)

**Additional context**
I found this issue by running on Ubuntu 20.10: `sudo apt install cppcheck-gui ; cppcheck-gui swtpm`

**Comment by stefanberger** [comment]
Interestingly I don't find this with cppcheck 2.3 on Fedora 32.

Sent PR #396.

Thanks for reporting.

**Comment by stefanberger** [comment]
... appended a realloc() issue found with cppcheck to the PR

**Comment by fishilico** [comment]
Thanks for your quick replies! I confirm https://github.com/stefanberger/swtpm/commit/6b50772217caa8c9a282bb431185395debe550a4 fixes the issue.
