### ISSUE TITLE
Testing swtpm as a chardev is failing with "Data client disconnected".

### ISSUE THREAD

**Issue by jcfaracco** [stefanberger/swtpm#407]
**Describe the bug**
I'm trying to use [linux-vtpm-tests](https://github.com/stefanberger/linux-vtpm-tests) to test swtpm as a chardev but it is failing even if I try the example from help doc. In other words, I'm trying to execute the command:

    $ sudo ./vtpmctrl --tpm2 --spawn /usr/bin/swtpm chardev --tpm2 --fd %fd --tpmstate dir=/tmp/test/ --pid file=/tmp/test/test.pid --log file=/tmp/test/test.log
    Created TPM device /dev/tpm0; vTPM device has fd 4, major/minor = 10/224.

When I open the log `/tmp/test/test.log`, I see this:

    Data client disconnected    

**To Reproduce**
1. Clone the repository mentioned above (and compile it).
2. Try to run `vtpmctrl` exactly the way I did.
3. Check the log files, pid and other files that can prove the process is running.

**Expected behavior**
The application swtpm running fine as a chardev

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.10

**Versions of relevant components**
- swtpm: upstream
- libtpms: upstream
- gcc: 10.2.0

**Additional comments**
When I run the tests for swtpm (specially `test_ctrlchannel2` and `test_ctrlchannel4`) I don't see any issue.

**Comment by jcfaracco** [comment]
IMHO, there are two possible reasons for this:
- A bug on swtpm (unlikely).
- vtpm tests are deprecated.

**Comment by stefanberger** [comment]
It was a bug in the vtpmctrl help screen. The proper command to run is:

```
./src/vtpmctrl --tpm2 \
  --spawn /bin/swtpm chardev --tpm2 --fd %fd --tpmstate dir=/tmp \
                     --flags not-need-init --locality allow-set-locality

./src/vtpmctrl \
  --spawn /bin/swtpm chardev --fd %fd --tpmstate dir=/tmp \
                     --flags not-need-init --locality allow-set-locality
```
I fixed the help screen.

The `--spawn` is not used by the test cases.

Let me know whether this fixes the issue.

**Comment by jcfaracco** [comment]
Excellent! Your latest commit (with the new help content) fixed the issue. Thanks @stefanberger :-)

**Comment by stefanberger** [comment]
Then we can close this issue, I suppose.
