### ISSUE TITLE
"swptm" misspelling

### ISSUE THREAD

**Issue by fishilico** [stefanberger/swtpm#410]
**Describe the bug**

The project uses "swptm" instead of "swtpm" in several places

**To Reproduce**
1. Run `git grep --heading -i swptm`

```console
$ git grep --heading -i swptm
samples/setup.py
15:    url="https::/github.com/stefanberger/swptm",
src/swtpm/main.h
49:#endif /* _SWPTM_MAIN_H */
src/swtpm_setup/setup.py
15:    url="https::/github.com/stefanberger/swptm",
tests/_test_setbuffersize
52:     echo "Error: The TPM buffersize of the ${SWPTM_INTERFACE} TPM is not 4096."
65:     echo "Error: The TPM buffersize of the ${SWPTM_INTERFACE} TPM is not 4000."
tests/_test_tpm2_encrypted_state
169:    echo "Error: Keyfile $binkeyfile was not removed by ${SWPTM_INTERFACE} TPM."
tests/_test_tpm2_setbuffersize
52:     echo "Error: The TPM buffersize of the ${SWPTM_INTERFACE} TPM is not 4096."
65:     echo "Error: Could not set the buffersize of the ${SWPTM_INTERFACE} TPM to 4000."
tests/test_tpm2_ibmtss2
```

**Expected behavior**
The GitHub URL would use `swtpm` instead of `swptm`. Environment variables would use `SWTPM_...` instead of `SWPTM_...`

**Versions of relevant components**
- swtpm: commit fa1b93904e91ad3737971464794c8c3e0859c7d6

**Additional context**
I was reading some files in `tests/` and stumbled upon https://github.com/stefanberger/swtpm/blob/fa1b93904e91ad3737971464794c8c3e0859c7d6/tests/_test_getcap#L69
I wondered what `ptm` meant and whether it was a misspelling for `tpm`. But this abbreviation seems to be widely used in the project (for example in https://github.com/stefanberger/swtpm/blob/fa1b93904e91ad3737971464794c8c3e0859c7d6/include/swtpm/tpm_ioctl.h). Does it mean something such as "pseudo trusted module"? If yes, it would be nice if it was documented somewhere.

While searching for "ptm" I found occurrences of "swptm", which definitely seemed to be misspellings.

**Comment by stefanberger** [comment]
Thanks for reporting.

As for `ptm`: this is historically from the CUSE TPM implementation that David Safford had started. It probably meant something like what you say - "pseudo trusted module".

**Comment by fishilico** [comment]
Thanks! I confirm the issues are fixed in `master`
