### ISSUE TITLE
Tying HWTPM with SWTPM

### ISSUE THREAD

**Issue by ravikumarbhattiprolu** [stefanberger/swtpm#412]
All, 
We use SWTPM with qemu and it works as expected. We want to create a relation between HWTPM on the host with the swtpm on the qemu guest. One approach we are considering is swtpm periodically getting quote from HWTPM and writing it to it's nvm and client reading this using tpm2_nvread command inside the VM. Is this possible without patching the code? Are there any tools which can do this job?

regards,
Ravi

**Comment by stefanberger** [comment]
I don't know how one would do that without modifying the code. Also, it's not quite clear how to tie the HWTPM and SWTPM together for example for the purpose of attestation. A top-down approach for attestation doesn't work well if the 'down' part could be corrupted and return good information that is not reflecting what the state of the host is for example.
