### ISSUE TITLE
swtpm-localca.conf doesn't interpret $variables anymore

### ISSUE THREAD

**Issue by elmarco** [stefanberger/swtpm#414]
My ~/.config/swtpm-localca.conf had:
```
statedir = $XDG_RUNTIME_DIR/swtpm-localca
```

Which used to work before the python rewrite. Is there any way we could get $XDG paths in the configuration, so we can share more easily custom configurations between users?

**Comment by stefanberger** [comment]
I has to be `${XDG_RUNTIME_DIR}`.

**Comment by elmarco** [comment]
works for me

**Comment by stefanberger** [comment]
`man swtpm-localca.conf`: "Entries may contain shell variables that will be resolved. All shell
variables must be formatted like this: '${varname}'."
