### ISSUE TITLE
swtpm_ioctl can hang

### ISSUE THREAD

**Issue by elmarco** [stefanberger/swtpm#415]
Since commit abadb408a92e23dd2f9088909d7a3f183bf8a847, swtpm no longer listen for extra clients.

This has several consequences, such as swtpm_ioctl hanging, notably when libvirt tries to qemuTPMEmulatorStop() and hangs.

See also https://bugzilla.redhat.com/show_bug.cgi?id=1914643

**Comment by elmarco** [comment]
Maybe qemuTPMEmulatorStop() shouldn't be done by libvirt, but by qemu instead since it holds the control channel.

**Comment by stefanberger** [comment]
I am starting VMs all the time and did not notice any change. Strange. How did you notice?

**Comment by elmarco** [comment]
Just try saving the VM, it will hang libvirt.

**Comment by stefanberger** [comment]
I have done that as well, just yesterday.

**Comment by stefanberger** [comment]
What commands are you using to save a VM? I am doing it from virt-manager level (arrow-down button + menu item save). It works just fine for me.

**Comment by elmarco** [comment]
virsh managedsave vm, or from the virt-manager UI, "save" the vm.

**Comment by stefanberger** [comment]
I cannot reproduce this problem:
```
# virsh dumpxml 2 | grep tpm
    <tpm model='tpm-crb'>
      <alias name='tpm0'/>
    </tpm>
# virsh managedsave 2

Domain 2 state saved by libvirt
```

Libvirt blocks until the state is saved.

**Comment by elmarco** [comment]
hmm, that might be a regresison with libvirt then, not waiting for qemu to finish before doing TPM stop.

Both machines I test on have libvirt/virsh 7.0

**Comment by stefanberger** [comment]
There are two calls to qemuTPMEmulatorStop():

- https://gitlab.com/libvirt/libvirt/-/blob/master/src/qemu/qemu_tpm.c#L770   A cleanup of a left-over before starting a new one.
- https://gitlab.com/libvirt/libvirt/-/blob/master/src/qemu/qemu_tpm.c#L859   As part of teardown of external devices that from the perspective of swtpm has to be called after QEMU has terminated. In the source code I am looking at this seems to be the case (libvirt 6.1).

**Comment by elmarco** [comment]
The order of qemu kill vs TPM stop got changed in:

commit 5cde9dee8c70b17c458d031ab6cf71dce476eea2
Author: Masayoshi Mizuma <m.mizuma@jp.fujitsu.com>
Date:   Wed Nov 11 08:35:24 2020 -0500

    qemu: Move qemuExtDevicesStop() before removing the pidfiles

**Comment by stefanberger** [comment]
I don't think this should be done in this order. There should be no reason to terminate the TPM before QEMU would shut it down itself. We have to terminate top-down and swtpm (down) is logically 'under' QEMU (top).
A possible solution would be to call the termination of devices twice with some sort of flag that allows the TPM to be torn down 'later' rather than 'early'.

**Comment by stefanberger** [comment]
Maybe along these lines here:

```
diff --git a/src/qemu/qemu_extdevice.c b/src/qemu/qemu_extdevice.c
index 8fe7ceaa10..5b92647e88 100644
--- a/src/qemu/qemu_extdevice.c
+++ b/src/qemu/qemu_extdevice.c
@@ -206,6 +206,18 @@ qemuExtDevicesStart(virQEMUDriverPtr driver,
 }


+void
+qemuExtDevicesStopEarly(virQEMUDriverPtr driver,
+                        virDomainObjPtr vm)
+{
+    for (i = 0; i < def->nfss; i++) {
+        virDomainFSDefPtr fs = def->fss[i];
+
+        if (fs->fsdriver == VIR_DOMAIN_FS_DRIVER_TYPE_VIRTIOFS)
+            qemuVirtioFSStop(driver, vm, fs);
+    }
+}
+
 void
 qemuExtDevicesStop(virQEMUDriverPtr driver,
                    virDomainObjPtr vm)
@@ -237,12 +249,7 @@ qemuExtDevicesStop(virQEMUDriverPtr driver,
             virNetDevRunEthernetScript(net->ifname, net->downscript);
     }

-    for (i = 0; i < def->nfss; i++) {
-        virDomainFSDefPtr fs = def->fss[i];
-
-        if (fs->fsdriver == VIR_DOMAIN_FS_DRIVER_TYPE_VIRTIOFS)
-            qemuVirtioFSStop(driver, vm, fs);
-    }
+    qemuExtDevicesStopEarly(driver, vm);
 }


diff --git a/src/qemu/qemu_process.c b/src/qemu/qemu_process.c
index 7feb35e609..b21d1dfa26 100644
--- a/src/qemu/qemu_process.c
+++ b/src/qemu/qemu_process.c
@@ -7659,7 +7659,7 @@ void qemuProcessStop(virQEMUDriverPtr driver,
     /* Do this before we delete the tree and remove pidfile. */
     qemuProcessKillManagedPRDaemon(vm);

-    qemuExtDevicesStop(driver, vm);
+    qemuExtDevicesStopEarly(driver, vm);

     virFileDeleteTree(priv->libDir);
     virFileDeleteTree(priv->channelTargetDir);
@@ -7677,6 +7677,8 @@ void qemuProcessStop(virQEMUDriverPtr driver,

     qemuDomainCleanupRun(driver, vm);

+    qemuExtDevicesStop(driver, vm);
+
     qemuDBusStop(driver, vm);

     vm->def->id = -1;
```

**Comment by stefanberger** [comment]
I'll post a patch cc'ing you. Can you apply it?

**Comment by elmarco** [comment]
> I'll post a patch cc'ing you. Can you apply it?

I may have commit access to libvirt git yes, but my guess is that it will be quickly taken by active maintainers, since it's a bad regression.

**Comment by stefanberger** [comment]
The proper fix has been applied to tip of libvirt's git now: https://github.com/libvirt/libvirt/commit/f30aa2ec74a79f34700915b677f46ec476d2362d

Affected libvirt versions are 6.10 and 7.0.

**Comment by stefanberger** [comment]
Does the patch for libvirt resolve the issue, @elmarco ?

**Comment by elmarco** [comment]
> Does the patch for libvirt resolve the issue, @elmarco ?

Partially. I think we may want to have some reasonable timeout on swtpm_ioctl commands by default.

**Comment by stefanberger** [comment]
PR #417 should address the timeout issue (but also help in hiding bugs in the order in which things are done as was the case with libvirt).

**Comment by stefanberger** [comment]
Can we close this issue now?

**Comment by elmarco** [comment]
I think so, thanks!
