### ISSUE TITLE
cuse: device not found, try 'modprobe cuse' first

### ISSUE THREAD

**Issue by lihanshang** [stefanberger/swtpm#421]
**Describe the bug**
Hi 
I was able to build and install swtpm and about to start the tpm. I was using the command example in man8 of cuse:
```
# ensure that previous swtpm_cuse using /dev/foo is gone

swtpm_ioctl -s /dev/foo

# Start the swtpm with TPM 2 functionality and make it accessible
# through /dev/foo. Have the swtpm_cuse write the TPM's persistent
# state into the given directory.

export TPM_PATH=/tmp/foo
mkdir -p $TPM_PATH

swtpm_cuse -n foo --tpm2

# Send TPM_Init to the TPM; this is absolutely necessary

swtpm_ioctl -i /dev/foo
```
Then I see the error message like in the title:
`cuse: device not found, try 'modprobe cuse' first`

I am using cuse since I assume it will help create a /dev/tpm0 for me(And this is what I am expecting on a HW tpm I guess). Please correct me if it is not. I also check this issue: [#383](https://github.com/stefanberger/swtpm/issues/383). You mentioned that cuse is  being deprecated in favor of using `swtpm chardev --vtpm-proxy`. Can you please guide me to some example so that I can 'start' the tpm with a socket or device in this way? 

I tried run `swtpm chardev --vtpm-proxy` but received the error: `swtpm: Could not open /dev/vtpmx: No such file or directory`

Thank you very much!

**To Reproduce**
1.
2.
3.
4.

**Expected behavior**

**Desktop (please complete the following information):**
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
**Versions of relevant components**
swtpm: master build
libtpms: master build
openssl: 1:1.0.2k-19.el7
gnutls: 3.3.29-9.el7_6

**Additional context**

**Comment by stefanberger** [comment]
Did you try `modprobe cuse` to get the CUSE TPM to work? It should work if you have the CUSE module.

The vtpm proxy device usage is described here: https://github.com/stefanberger/swtpm/wiki/Using-the-IBM-TSS-with-swtpm#character-device-using-tpm_vtpm_proxy  . You will need a (recent) distro that has a module package that provides the tpm_vtpm_proxy kernel model. On Fedora this is the package:

```
$ rpm -q --whatprovides /lib/modules/5.8.18-100.fc31.x86_64/kernel/drivers/char/tpm/tpm_vtpm_proxy.ko.xz 
kernel-core-5.8.18-100.fc31.x86_64
```

**Comment by lihanshang** [comment]
Hi Thanks for the reply.
I actually added `--cap-add SYS_ADMIN --device /dev/cuse \` to the docker run command. This change make the `cuse: device not found, try 'modprobe cuse' first` disappear.

However, on the next step when I try `swtpm_ioctl -i /dev/foo` it gives: `Unable to open device '/dev/foo'` and I check the dir without seeing the device is created. 

Do you know which process actually create the device and why it does not appear? Thank you very much!

**Comment by stefanberger** [comment]
Try it on the host first without the container. You need to get it working there and then you can try to move swtpm into the container and make it working there. Obviously you need to get the cuse kernel module, if that's available for the distro you are using. If it's not available you may need to use another distro. Try it with Fedora for example:
```
$ rpm -q --whatprovides /lib/modules/5.8.18-100.fc31.x86_64/extra/fs/fuse/cuse.ko.xz
kernel-modules-extra-5.8.18-100.fc31.x86_64
```

**Comment by stefanberger** [comment]
Did you install the kernel-modules-extra (or similar) package containing the cuse module?

**Comment by stefanberger** [comment]
This works for me on CentOS 7 when running as root:

```
> rpm -q --whatprovides /lib/modules/3.10.0-1160.15.2.el7.x86_64/kernel/fs/fuse/cuse.ko.xz
kernel-3.10.0-1160.15.2.el7.x86_64
> modprobe cuse
> mkdir /tmp/foo
> swtpm_cuse -n foo --tpm2 --tpmstate dir=/tmp/foo
> swtpm_ioctl --info 7 /dev/foo
{"TPMSpecification":{"family":"2.0","level":0,"revision":162},"TPMAttributes":{"manufacturer":"id:00001014","version":"id:20191023","model":"swtpm"},"TPMFeatures":{"RSAKeySizes":[1024,2048,3072]}}
> swtpm_ioctl -s /dev/foo
> swtpm_ioctl --info 7 /dev/foo
Unable to open device '/dev/foo'.
```

**Comment by stefanberger** [comment]
@lihanshang Did you try this now following the sequence of commands I have shown above?
