### ISSUE TITLE
Endorsement Certificate created with incorrect modulus

### ISSUE THREAD

**Issue by puiterwijk** [stefanberger/swtpm#426]
**Describe the bug**
The Endorsement Certificate that `swtpm_setup --create-ek-cert` is created with an invalid RSA modulus (I have so far only tested with the RSA one).

**To Reproduce**
1. Run swtpm_setup with `--tpm2 --createek ----create-ek-cert`
2. Create the Endorsement Key via the options from "TCG EK Credential Profile for TPM Family 2.0; Level 0" (as implemented by `tpm2_createek`)
3. Retrieve the EK certificate from NV Index `0x01c00002` (as per "TCG EK Credential Profile for TPM Family 2.0; Level 0", section 2.2.1.4 "Low Range", for RSA 2048 EK Certificate
4. Compare the moduli in the key from step 2 and the certificate from step 3

**Expected behavior**
The moduli should be identical: the EK Cert in 0x01c00002 should cover the EK key.

**Seen behaviour**
We are seeing two entirely different moduli

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 32

**Versions of relevant components**
- swtpm: `swtpm-0.5.2-0.20201226gite59c0c1.fc32.x86_64`
- libtpms: `libtpms-0.7.4-0.20201031git2452a24dab.fc32.x86_64`
- openssl: `openssl-1.1.1i-1.fc32.x86_64`
- gnutls: `gnutls-3.6.15-1.fc32.x86_64`

**Additional context**
A script to show this off:
```
#!/usr/bin/bash
certpath=$(mktemp /tmp/script-check-ekcert.XXXXXX)
keypath=$(mktemp /tmp/script-check-ekkey.XXXXXX)

tpm2_nvread 0x01c00002 -o $certpath
tpm2_createek -c - -G rsa -u $keypath -w keylime -P keylime -f pem >/dev/null

# The Modulus of these two keys should be identical
ekcertn=$(openssl x509 -in $certpath -noout -inform der -modulus)
ekkeyn=$(openssl rsa -in $keypath -noout -pubin -modulus)

rm -f $keypath $certpath

if [ "$ekkeyn" == "$ekcertn" ];
then
    echo "Moduli match!"
    exit 0
else
    echo "Moduli do NOT match"
    echo "Key modulus: $ekkeyn"
    echo "Certificate modulus: $ekcertn"
    exit 1
fi
```

I expect to see "Moduli match!", and we see that with a Hardware TPM.
With this system, we see:
```
Moduli do NOT match
Key modulus: Modulus=9380D6900001057FFFEEC7E02BAEBC5B2C5B48383162A9A06496DC1D55BEF2008D3ED9591A73EF63A75F78DABF3DFCB0F4E890C0C63F06F07B3355AAB9B1F5360C8FAEC3938EF2AC33C82327FD459FC7AF48533217C548BEFC9BE5966D21F19A1BD40543B676F2D9A3907D1BE3B39EBC263304A025073FCD14C459F8A9453E8AFF435EDF10E7282821B0F7A22E10C7AE8338A3D338B921A84A22183BF32C5106123146706739915D6D0585D7440E43B9EE44490706FA6613675CDBA486008AE55F26CFD8B789D4FA2F173A2AB570360FA976ADBEEAC5872D497A12FB779FDE3412F55302002DBED9E24C748E34B7C48230E34288B13CB5358CB2EA01F4A4BD83
Certificate modulus: Modulus=C2F42710000075D3BB082A4FB66D6B2426F9AA5595703326123BC7139E3C92B955C8A5AC2510046D16EF86D955B7456FA87534073599807FB027226BB0694410A4AE0BE7177AF57208AC3B6B9365981ED87383FD662BD2F5E88C68D30F73E4E15C9B6AF13241726901B3C130ACD85327545B500A2E607FAC2C996A89B4294A06DC8FE9FE925864080C7AA5175106DE0923391B5174A52BFBE187548082856B528D1D4CB569ACE0EF4ABE3C5D2656EB3A529A25FFE075814AF99FD0D2915DDD41157AC13AEC67F219A99832CBE9F8A31F5E6920F705C29A68E2E8BA5424A67402FCFB3002515B49C2C76DAF445798374D625CFC821C4FC0A2CE5BBDF99E6653E9
```

The script used to run swtpm on this system:
```
#!/usr/bin/env bash

export tpm_dir=/var/vtpm
modprobe tpm_vtpm_proxy

if [ -d ${tpm_dir} ]
then
    echo "Found existing ${tpm_dir}"
    swtpm chardev --tpm2 --vtpm-proxy --tpmstate dir=$tpm_dir -d
else
    echo "Error: Directory ${tpm_dir} does not exists."
    mkdir ${tpm_dir}
    swtpm_setup --tpm2 \
        --tpmstate $tpm_dir \
        --createek --allow-signing --decryption --create-ek-cert \
        --create-platform-cert \
        --display
    swtpm chardev --tpm2 --vtpm-proxy --tpmstate dir=$tpm_dir -d
fi

export TPM2TOOLS_TCTI="device:/dev/tpm0"
```

**Comment by stefanberger** [comment]
You cannot easily use `--allow-signing` unless your tools know how to deal with re-creating the EK using a template. It's a non-standard EK then.

See the issue here: https://github.com/stefanberger/swtpm/issues/424
Also see this patch here: https://github.com/stefanberger/swtpm/commit/ef1407f56dcf611ce73521e093187adfa8a9c40c

**Comment by puiterwijk** [comment]
Right, that makes sense. This was a script I have copied around so often that I forgot where everything came from.
Thanks for the pointers and the documentation notes.
