### ISSUE TITLE
[doc request] An easy way to play with SWTPM using container

### ISSUE THREAD

**Issue by pw4ever** [stefanberger/swtpm#429]
First, thanks for making and maintaining SWTPM, @stefanberger. It is a great way to learn & play with TPM 2.0 even on old platforms without a hwTPM2; the ability to configure/"manufacture" the swTPM (e.g., setting up the EK) is handy.

Although the main focus of SWTPM is for backing a vTPM for a VM, it would be useful if a user can play with it (e.g., with [tpm2-tools](https://github.com/tpm2-software/tpm2-tools)) without going thru the process of setting up a VM.

All the software ingredients are already there; it is just not easy to find instructions on how to get started with SWTPM without setting up a VM.

Hence this issue: **Add a doc somewhere** (perhaps on the Wiki?) for easily setting up a SWTPM instance to play with.

The following is a solution.

With the following Dockerfile,
```
FROM archlinux
MAINTAINER Wei Peng <wei.peng@intel.com>

RUN pacman -Sy; pacman -S --needed --noconfirm tpm2-tools swtpm openssl python python-cryptography gnutls;

ENV HOME="/root" CERTSUBJ="/CN=TPM Endorsement Key" TPMPORT=2321 CTRLPORT=2322 
ENV TPMSTATE="$HOME/tpm01" TPM2TOOLS_TCTI="swtpm:port=$TPMPORT" \
              SWTPM_LOCALCA_DIR="/root/.config/var/lib/swtpm-localca/" \
              ENTRY_SCRIPT="/root/run.sh"

WORKDIR ${HOME}
EXPOSE $TPMPORT $CTRLPORT

RUN /usr/share/swtpm/swtpm-create-user-config-files --overwrite; \
        pushd "$SWTPM_LOCALCA_DIR"; \
        openssl req -x509 -newkey rsa:4096 -nodes -keyout signkey.pem -out issuercert.pem \
            -days 3650 -subj "$CERTSUBJ"; \
        echo 1 > certserial; \
        popd; \
        mkdir -p "$TPMSTATE"; \
        swtpm_setup --tpm2 --tpmstate "$TPMSTATE" --create-platform-cert --overwrite; 

RUN >"$ENTRY_SCRIPT" echo "swtpm socket --tpm2 --tpmstate \"dir=$TPMSTATE\" --daemon \
            --server type=tcp,bindaddr=0.0.0.0,port=\"$TPMPORT\" \
            --ctrl type=tcp,bindaddr=0.0.0.0,port=\"$CTRLPORT\"; \
        swtpm_ioctl --tcp :\"$CTRLPORT\" -i; \
        swtpm_bios --tpm2 --tcp :\"$TPMPORT\"; \
        bash; \
        "; chmod +x "$ENTRY_SCRIPT";

CMD "$ENTRY_SCRIPT"
```

... we can build a `swtpm` container image,
```
docker build -t swtpm:latest .
```
... and then play with it:

- either inside a running container,
```
docker run -it --rm swtpm
```
- ... or directly on the host
```
docker run -dit -p 2321-2322:2321-2322 swtpm
export TPM2TOOLS_TCTI="swtpm:port=2321"
tpm2_getcap getrandom --hex 20
```

**Comment by stefanberger** [comment]
Ok, well for now there's this page here for usage with the IBM TSS for TPM 2: https://github.com/stefanberger/swtpm/wiki/Using-the-IBM-TSS-with-swtpm

I may add another Wiki page for usage with the Intel TSS via the vtpm proxy device or the rather new `TPM2TOOLS_TCTI="swtpm:port=2321"`

**Comment by pw4ever** [comment]
Thanks for pointing to the IBM TSS/TPM2 instructions.

I am rather new (a few weeks) into TPM; so I may have missed something that is well known to a more seasoned community member. But I find it a bit difficult to piece all information together to quickly set up the swTPM to play with.

For example, as I am using Arch Linux, `tpm2-tools` and `swtpm` are already packaged there, so that is where I started digging. Maybe it is my naivete with the TPM tools, even piecing together the steps of making these 2 pieces working together (and is captured in the `Dockerfile` above) is not straightforward.

Also, maybe because it is hosted on sourceforge, [IBM's TPM 2.0 TSS](https://sourceforge.net/projects/ibmtpm20tss/) is not easy to find for a new user.

For example, on Google:
- Searching for `IBM tss` turns up this page [IBM Technology Support Services](https://www.ibm.com/partnerworld/services/technology-support-services)
- Searching for `tpm2 tss`, the first hits are all projects hosted at https://github.com/tpm2-software
- Searching for `ibm tpm software stack`, the first hit is [tpm2-tss](https://github.com/tpm2-software/tpm2-tss).

**Comment by stefanberger** [comment]
I now created an equivalent page for the Intel TSS 2 stack on this wiki: https://github.com/stefanberger/swtpm/wiki/Using-the-Intel-TSS-with-swtpm

I would prefer to keep that wiki page distro-agnostic. It doesn't cover building and installation but starts at the point where swtpm is available.

**Comment by pw4ever** [comment]
> I now created an equivalent page for the Intel TSS 2 stack on this wiki:

Thanks! I wish I had that page when I tried it out on my own :)

> I would prefer to keep that wiki page distro-agnostic.

That makes sense.

The Dockerfile could still be useful, especially for new users to quickly try out SWTPM, on any Docker host; this is distro or even OS agnostic.

I will leave it here just in case someone finds it useful.
