### ISSUE TITLE
Add an event notification mechanism to libtpms/swtpm

### ISSUE THREAD

**Issue by dme** [stefanberger/swtpm#433]
In an environment where a guest VM is provided with access to a TPM device that is implemented using swtpm, it would be useful to be able to monitor the use of the TPM by software running in the VM *without* relying on in-guest software. For example, knowing the values that were extended into particular PCRs is helpful when debugging VMs that are attempting some type of measured boot.

Currently the only mechanism provided to monitor such actions outside of the guest VM is the swtpm log. This is inadequate for several reasons:
- the log has to be enabled,
- the log can grow indefinitely,
- the log is not specifically designed to be parsed (though this isn't too difficult),
- the log parser needs to decode the TPM commands from the binary dump (annoying, given that libtpms already does this),
- control plane software, which typically interacts with QEMU rather than swtpm, may not have access to the log.

An alternative approach would be for swtpm to provide well formatted event notifications (in JSON, for example) to an interested consumer.

swtpm/libtpms currently doesn't have any general event notification mechanism. The changes indicated below add such a mechanism via extension of the existing libtpms callback mechanism, which swtpm uses to send notifications on a file descriptor provided by swtpm's consumer.

The changes include sample changes to QEMU to register a notification file descriptor with swtpm and generate QAPI events based on the notifications received from swtpm.

Currently the changes generate event notifications only as a result of PCR extensions. Hopefully it is relatively straightforward to see how other notifications might be added.

Further to using the information contained in notifications for debugging purposes, having access to information about PCR extensions might also be used to provide assurance to the control plane about the state of a measured boot environment. Some care about the security properties being asserted will be necessary, however.

Three sets of sample changes are provided:
- https://github.com/dme/libtpms/tree/devel/async: add the notification mechanism to the libtpms callbacks, and call any registered callback after PCR extension,
- https://github.com/dme/swtpm/tree/devel/async: use the libtpms notification mechanism, allow our caller to register a notification fd and send any notifications to it,
- https://github.com/dme/qemu/tree/devel/tpmasync: register a notification fd with swtpm, read notifications from it, generate a QAPI event for PCR extensions so notified.

**Comment by stefanberger** [comment]
What kind of debugging are you going to do based on PCR extensions? What PCRs are you intending to monitor for that?

From my own experience I can say that IMA related PCR 10 events alone without the context of the path of the file that was opened or executed are useless once it comes to having to filter out events. PCR 10 values do not give you nearly enough context to know what actually happened and whether you need to filter out the event since something has changed or a modified file was read etc. And obviously there are tons of things executing once you are running an OS and taking measurements. The PCR 0-9 measurements is a fraction of the story. That said, have you tried anything in this direction?

If we were to support notifications then they have to be tuneable, meaning the notifications have to be turned off by default and should only be enabled if the user wants it. There's no reason to report notifications though all the layers if nobody looks at them. There are TPM 2 structures that let one select PCRs to enable and I think it should be based on that, maybe even just a bitmask/hex number in this case to select individual PCRs. And probably it's more efficient to report native data structures to upper layers. So *maybe* it's better not to use JSON but an indicator of event type and then some well known data structure and size indicator specific for that event. Maybe it should be even the whole TPM_2_PCR_Extend command so it's just one notification upwards and not several ones for each PCR extension. Whatever is sent up has to be uniquely parseable.

**Comment by stefanberger** [comment]
Another concern I have is in regards to confidential computing. I am kind of hesitant to legitimize the observability of what may be going on inside of a VM via PCR extend notifications especially if the host owner is not the owner of VM.

**Comment by dme** [comment]
> What kind of debugging are you going to do based on PCR extensions? What PCRs are you intending to monitor for that?

At the moment my interest is in debugging measured boot environments, so only the first 10 PCRs. As for what debugging: when a system reports that the TPM quote of the PCR values is not as expected, I would like to be able to (for example) compare the sequence of extensions seen to those from a known good boot, in order to start narrowing down where the process went awry.

> From my own experience I can say that IMA related PCR 10 events alone without the context of the path of the file that was opened or executed are useless once it comes to having to filter out events. PCR 10 values do not give you nearly enough context to know what actually happened and whether you need to filter out the event since something has changed or a modified file was read etc. And obviously there are tons of things executing once you are running an OS and taking measurements. The PCR 0-9 measurements is a fraction of the story. That said, have you tried anything in this direction?

I agree - at this point I am not interested in IMA.

> If we were to support notifications then they have to be tuneable, meaning the notifications have to be turned off by default and should only be enabled if the user wants it. There's no reason to report notifications though all the layers if nobody looks at them. There are TPM 2 structures that let one select PCRs to enable and I think it should be based on that, maybe even just a bitmask/hex number in this case to select individual PCRs.

I can add a mechanism that allows the upstream caller to request notification of specific PCRs, which can also service as a mechanism to enable/disable the notifications.

> And probably it's more efficient to report native data structures to upper layers. So maybe it's better not to use JSON but an indicator of event type and then some well known data structure and size indicator specific for that event. Maybe it should be even the whole TPM_2_PCR_Extend command so it's just one notification upwards and not several ones for each PCR extension. Whatever is sent up has to be uniquely parseable.

I would rather avoid having to decode the raw TPM commands again in the upper layer if possible, as it seems wasteful and will lead to code duplication (with consequent bug proliferation).

If it's useful to aggregate the notifications for multiple banks when generating the PCR notifications, then that seems like a sensible modification to the current patches.

**Comment by dme** [comment]
> Another concern I have is in regards to confidential computing. I am kind of hesitant to legitimize the observability of what may be going on inside of a VM via PCR extend notifications especially if the host owner is not the owner of VM.

The host owner has access to this data via the swtpm log if required, and by direct examination (or modification) of the swtpm/libtpms software if necessary, so I don't think that this is a reasonable concern.

**Comment by stefanberger** [comment]
> > Another concern I have is in regards to confidential computing. I am kind of hesitant to legitimize the observability of what may be going on inside of a VM via PCR extend notifications especially if the host owner is not the owner of VM.
> 
> The host owner has access to this data via the swtpm log if required, and by direct examination (or modification) of the swtpm/libtpms software if necessary, so I don't think that this is a reasonable concern.

Except now we would add architecture support for monitoring what is going on inside of a machine. No more changes necessary to libtpms/swtpm, we have commands for it and you can monitor the software being started in a secure VM. That's information leakage supported by the architecture.

**Comment by stefanberger** [comment]
> > What kind of debugging are you going to do based on PCR extensions? What PCRs are you intending to monitor for that?
> 
> At the moment my interest is in debugging measured boot environments, so only the first 10 PCRs. As for what debugging: when a system reports that the TPM quote of the PCR values is not as expected, I would like to be able to (for example) compare the sequence of extensions seen to those from a known good boot, in order to start narrowing down where the process went awry.

If you are debugging why can you not turn the log on and monitor the log. Why do we need notifications for that?

**Comment by stefanberger** [comment]
Another method for debugging is to let the machine boot and inspect its TPM log. I don't see that we need code across 3 projects for that. Yet another method is add a log statement to libtpms and dump what's being extended. A one-liner.

**Comment by dme** [comment]
> Except now we would add architecture support for monitoring what is going on inside of a machine. No more changes necessary to libtpms/swtpm, we have commands for it and you can monitor the software being started in a secure VM. That's information leakage supported by the architecture.

Given that, as you point out, this data can be extracted from the swtpm log, I'm not clear on the distinction that you are drawing. The host owner has access to the data in either case.

> If you are debugging why can you not turn the log on and monitor the log. Why do we need notifications for that?

I'd like to have the data logged for systems in service. When one out of ten thousand attempts at measured boot fails, "turn on the log and try again" is not a useful approach for diagnosing the problem.

> Another method for debugging is to let the machine boot and inspect its TPM log. I don't see that we need code across 3 projects for that. Yet another method is add a log statement to libtpms and dump what's being extended. A one-liner.

Given that the host owner may not be the VM owner, we cannot know that any information provided from within the VM has not been tampered with, either deliberately or by accident.

**Comment by stefanberger** [comment]
> > If you are debugging why can you not turn the log on and monitor the log. Why do we need notifications for that?
> 
> I'd like to have the data logged for systems in service. When one out of ten thousand attempts at measured boot fails, "turn on the log and try again" is not a useful approach for diagnosing the problem.

so you are telling me that you are going to be logging everything because you cannot reproduce the failure in a system because that failure is so rare? How are you going to reproduce it afterwards?

**Comment by dme** [comment]
> so you are telling me that you are going to be logging everything because you cannot reproduce the failure in a system because that failure is so rare? How are you going to reproduce it afterwards?

I'm giving an example of a situation where "turn on the log and try again" is a less useful approach. Having data to help diagnose on first failure has proven useful in lots of situations. Of course it's convenient to be able to reproduce a failure, and a record of the PCR extensions that took place might be a significant help in being able to achieve that.

**Comment by elmarco** [comment]
I am not convinced either libtpms/swtpm should provide facilities to help debug guest-side usage issues. It's rather the job of the guest OS than hypervisor. (I am also a bit reluctant that QEMU becomes a bus/proxy for various sub-processes, even though some messages/events will have to be relayed, at least for compatibility reasons)

**Comment by dme** [comment]
Another case where notifications are useful is in managing NVRAM files.

In an environment where host failure occurs, we wish to get VMs running again on a fresh host. Ensuring that the new host has an up-to-date copy of the NVRAM files corresponding to the VM currently involves polling for changes to those files, in order that they can be stored off-host in anticipation of failure. Polling is undesirable (both because it tends to be wasteful and because we can still miss changes if a host fails between polls), and notifications from swtpm that an NVRAM file changed would be more effective.

> I am not convinced either libtpms/swtpm should provide facilities to help debug guest-side usage issues. It's rather the job of the guest OS than hypervisor.

Understood. For me, one of the great benefits of virtualisation is the new opportunities that it provides for debugging. As you say, it's usually possible to debug using the guest OS environment, but when we are looking at debugging firmware, boot loaders and the early parts of the kernel, being able to take advantage of the facilities provided by virtualisation helps hugely.

> (I am also a bit reluctant that QEMU becomes a bus/proxy for various sub-processes, even though some messages/events will have to be relayed, at least for compatibility reasons)

Another option that I considered was to have the control plane talk directly to swtpm. Currently this is not possible - swtpm allows until a single control connection to be active, and that is typically consumed by QEMU. It's also the case that our control plane already knows how to monitor QEMU for other events, so the implementation via QEMU was simpler, but this is a local issue.

**Comment by dme** [comment]
As an alternative approach, would it be acceptable to add a (presumably additional) structured (JSON?) log output option?

This might include the ability to select which log items are output.

**Comment by stefanberger** [comment]
An additional parameter `format` for the `--log option` would be helpful: `swtpm [...] --log file=...,level=...,format=json`
