### ISSUE TITLE
swtpm: command not found

### ISSUE THREAD

**Issue by wangzhankun** [stefanberger/swtpm#434]
I have successfully build and install `swtpm-build-deps` but it shows that `swtpm: command not found` when entering `swtpm` in my terminal.

## Env
- Ubuntu 20.04
- WSL2

## install info
```
(Reading database ... 79152 files and directories currently installed.)
Preparing to unpack swtpm-build-deps_0.6.0~dev1_all.deb ...
Unpacking swtpm-build-deps (0.6.0~dev1) over (0.6.0~dev1) ...
Setting up swtpm-build-deps (0.6.0~dev1) ...
```

**Comment by stefanberger** [comment]
Ubuntu does not currently package swtpm, so please described your build/installation procedure step by step so that someone else can reproduce the issue. What is 'swtpm-build-deps'?

**Comment by wangzhankun** [comment]
I just follow the instructions described in `INSTALL` file, that says `sudo mk-build-deps --install ./debian/control` on ubuntu at 44 line. And I get the `swtpm-build-deps` package and then I install it.

**Comment by wangzhankun** [comment]
But here I find the way to install swtpm.    
https://launchpad.net/~smoser/+archive/ubuntu/swtpm

**Comment by stefanberger** [comment]
I have a similar PPA for some versions of Ubuntu: https://launchpad.net/~stefanberger/+archive/ubuntu/swtpm

I think you should build a libtpms Ubuntu package from teh `stable-0.8` branch using the steps described here: https://github.com/stefanberger/libtpms/wiki#build-a-package-on-ubuntu

You can then follow the swtpm's instructions from the INSTALL script:
 
```
On RHEL or Fedora use either one of the following methods to install
the above dependencies:

[...]

On Ubuntu use the following command:

 - sudo mk-build-deps --install ./debian/control


Use the following sequence to build and install the Software TPM.

./autogen.sh
./configure --prefix=/usr
make
make check
make install
```

**Comment by stefanberger** [comment]
Do these steps help?

**Comment by wangzhankun** [comment]
> But here I find the way to install swtpm.
> https://launchpad.net/~smoser/+archive/ubuntu/swtpm

Here I installed the swtpm successfully and I can use the swtpm. Thanks for your reply.
