### ISSUE TITLE
Not able to launch QEMU with Emulated TPM

### ISSUE THREAD

**Issue by asrinuva** [stefanberger/swtpm#435]
Hi Stefan,

                 I installed libtpm and swtpm from you github repo, i stayed on the master branch.
Goal:

                   I try to launch the QEMU with emulated TPM (swtpm), for that i installed all the dependencies packages and installed the libtpms and swtpm.

finally everything successfully get installed in my host.

In one terminal i launched the swtpm utility and another terminal i try to launch the QEMU with emulated TPM.
but i got the below error:

![image](https://user-images.githubusercontent.com/50193563/116899932-cd360800-ac55-11eb-9fe1-85dde41e8af8.png)

It says only one TPM is choosen.

How to enable the emulated one, currently that type is not supporting.

Or any thing am missing.

Please help me out.

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: Stretch (9)

**Versions of relevant components**
Installed swtpm and libtpms from the master branch

**Comment by stefanberger** [comment]
I guess QEMU compiled by Debian Stretch doesn't support the TPM emulator backend. You would have to build QEMU yourself to get that.

**Comment by asrinuva** [comment]
Thanks @stefanberger , i will try out.

**Comment by asrinuva** [comment]
Hi Stefan,
 
                When i Use New QEMU i can able to launch the images, but QEMU launches for normal kernel images.
When i add TPM related argument in the QEMU command line it stops on the initramfs.
Am passing all the required components like kernel and initrd files, but its hangs on initramfs.
Not able to find /dev/sda and not able to load the kernel.
Below is the log
Starting version 241
[    2.639444] ata_id (1096) used greatest stack depth: 13776 bytes left
Begin: Loading essential drivers ... done.
Begin: Running /scripts/init-premount ... done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... done.
Begin: Waiting for root file system ... Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
done.
Gave up waiting for root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
   - Check rootdelay= (did the system wait long enough?)
 - Missing modules (cat /proc/modules; ls /dev)
ALERT!  /dev/sda does not exist.  Dropping to a shell!
(initramfs) [   37.717791] systemd-udevd (1084) used greatest stack depth: 13736 bytes left

Anything need to be enable in the kernel when build the images.

Please provide your comments.

Many thanks,
Srinuvasan.A

**Comment by stefanberger** [comment]
I don't know what is going on in your initramfs. Does it work with your setup when not passing the TPM parameters to QEMU?

**Comment by asrinuva** [comment]
Yes it is my mistake i removed the existing command line argument that is why it hangs on initramfs.
Now i append the TPM related argument with existing QEMU command line argument now its booting.

From the TPM QEMU document am not able to see any tpm folder inside /dev and dmesg also not showing logs related to TPM.

Can you please guide me how to test or what are all the things need to check after boot the QEMU?

Thanks,
Srinuvasan.A

**Comment by stefanberger** [comment]
swtpm is running when you start QEMU, right? 
Inside the VM `dmesg | grep -i tpm` should show some TPM related driver initialization messages. If nothing is shown then maybe you should try `insmod tpm_tis` or `insmod tpm_crb` in case the drivers need to be loaded manually for some reason and then see whether `dmesg | grep -i tpm` shows something. `/dev/tpm0` should appear once the drivers activate successfully.

**Comment by asrinuva** [comment]
yes stefan, Verified followed things:
![image](https://user-images.githubusercontent.com/50193563/117009101-02e7f900-ad09-11eb-9ede-5c702e23ebcb.png)
![image](https://user-images.githubusercontent.com/50193563/117009173-172bf600-ad09-11eb-8e69-9149261b45a5.png)

I hope we need to enable the TPM related CONFIGS in defconfig when build the kernel.
I think my kernel not enabled the TPM related drivers.
If that is the case what i need to update.

What is the necessary things need to be add before builds the kernel image.

Thanks,
Srinuvasan.A

**Comment by stefanberger** [comment]
This is how a kernel I am using is configured. Try the same.
```
CONFIG_TCG_TPM=y
CONFIG_HW_RANDOM_TPM=y
CONFIG_TCG_TIS_CORE=y
CONFIG_TCG_TIS=y
CONFIG_TCG_TIS_SPI=m
CONFIG_TCG_TIS_SPI_CR50=y
# CONFIG_TCG_TIS_I2C_ATMEL is not set
# CONFIG_TCG_TIS_I2C_INFINEON is not set
# CONFIG_TCG_TIS_I2C_NUVOTON is not set
CONFIG_TCG_NSC=m
CONFIG_TCG_ATMEL=m
CONFIG_TCG_INFINEON=m
# CONFIG_TCG_XEN is not set
CONFIG_TCG_CRB=y
CONFIG_TCG_VTPM_PROXY=m
# CONFIG_TCG_TIS_ST33ZP24_I2C is not set
# CONFIG_TCG_TIS_ST33ZP24_SPI is not set
```

**Comment by asrinuva** [comment]
Okay thanks @stefanberger

**Comment by asrinuva** [comment]
Hi Stefan,

              Now i can able to see the TPM related drivers and PCR's information. So swtpm is running once QEMU boots.

My main intention is to do Boot with TPM (Measured boot), Already i did for secureboot using debian snakeoil keys.
But am new to the TPM boot, can you please guide me how to do this one or any document to follow to achieve this.

Please provide your thoughts.

Many thanks,
Srinuvasan.A

**Comment by stefanberger** [comment]
Measured boot should work automatically when you use a recent vFirmware UEFI/Edk2 or SeaBIOS in an x86 VM. You should have measurements in `/sys/kernel/security/tpm0/binary_bios_measurements`. There are tools out there for decoding these measurement list (https://github.com/tpm2-software/tpm2-tools/blob/master/tools/misc/tpm2_eventlog.c), but this is beyond the scope of this project.

**Comment by asrinuva** [comment]
Thanks lot @stefanberger , Can you please confirm secure boot possible with TPM.
If secure boot with TPM is possible, can you please point me how to load the keys in TPM and do the secure boot.
If anything i need to update on seaBIOS  for TPM secure boot.
I read document it says we can store the keys in TPM secure way, So can you please guide me how to use the TPM to boot the kernel in secure way. 

What are all the test coverage is possible in QEMU TPM?

Can you please provide your thoughts.

Thanks,
Sribuvasan.A

**Comment by stefanberger** [comment]
Secure boot does not work with SeaBIOS but only with UEFI/EDK2, though be aware that there's a kernel bug in Linux that prevent measured boot for 5.9 - 5.12 kernels until those are patched. So you'd need a 5.8 kernel at the moment.

**Comment by asrinuva** [comment]
Yes I agree with that already we experimented on secure boot with UEFI.
Actually am using 4.19 kernel.

I need help on how to store the generated keys on TPM for secureboot.
So by using the signed key from TPM we should boot the machine secure way.

Any documentation on SEcureboot + TPM will be helpful.


TIA,
Srinuvasan.A

**Comment by stefanberger** [comment]
SecureBoot and TPM are independent.

**Comment by asrinuva** [comment]
Okay @stefanberger , How TPM uses in QEMU?
Is it possible to boot the images in QEMU using TPM?
or what are all the applications this TPM uses in QEMU?

Sorry for continuously asking questions?
Any help would be greatly appreciated. 

Thanks,
Srinuvasan.A

**Comment by stefanberger** [comment]
You can use the TPM in QEMU in the same way as you would use the TPM of your laptop or server. You can encrypt data with it, use it for signing etc.

**Comment by asrinuva** [comment]
Okay thanks, can you please provide more information on that signing part or point me any good documentation for QEMU TPM signing usage , i don't have that much idea on that.

Does this signing feature will work for boot in secure way?

Thanks,
Srinuvasan.A

**Comment by stefanberger** [comment]
Here's some documentation regarding signing: https://www.mankier.com/1/tpm2_sign
