### ISSUE TITLE
Binary location for /usr/share/swtpm/swtpm-localca

### ISSUE THREAD

**Issue by elmarco** [stefanberger/swtpm#482]
Installing a binary under `/usr/share` isn't a good idea.

Instead, it would make sense to install it under `bin` (or eventually `libexec`).

For compatibility purposes in the existing path, a simple shell script could do.

**Comment by stefanberger** [comment]
Symbolic link?

**Comment by elmarco** [comment]
> Symbolic link?

I am afraid this might trip some checkers too.

**Comment by stefanberger** [comment]
@elmarco Please have a look at the commit above.

**Comment by elmarco** [comment]
looks ok to me

**Comment by stefanberger** [comment]
I wished we could only call the binary in $bindir, but I am not sure how to do this nicely while still being able to run the tests.

**Comment by stefanberger** [comment]
Is `/usr/bin` rather than `/usr/libexec` fine?
