### ISSUE TITLE
AM_CFLAGS/AM_LDFLAGS no longer used

### ISSUE THREAD

**Issue by elmarco** [stefanberger/swtpm#483]
Since https://github.com/stefanberger/swtpm/commit/47f973ed71a2c6baec58ed5aa6c0106cff64add6 and 7f81d3128804fc4753d263ff39062fb706bc666c, AM_* flags are no longer used.

They were useful, as they allowed to have additional make-time CFLAGS arguments. (AM_* were used for configure time CFLAGS)

**Comment by stefanberger** [comment]
@kloczek

**Comment by stefanberger** [comment]
I have used command lines like this one here:

```
CFLAGS="-fsanitize=address,undefined -g -fno-omit-frame-pointer -fno-sanitize-recover" LIBS="-lasan -lubsan" ./autogen.sh --prefix=/usr --without-seccomp --without-cuse
```

This still works for me.

**Comment by elmarco** [comment]
Yes, configure-time FLAGS are saved, but will be overwritten by make-time CFLAGS. 

The mentionned commits change the build-sys behaviour, and broke some builds.

**Comment by stefanberger** [comment]
Can you be a bit more specific under what condition it breaks?

With the above I get:
```
           CFLAGS = -fsanitize=address,undefined -g -fno-omit-frame-pointer -fno-sanitize-recover  -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security -I/usr/include/p11-kit-1  
 HARDENING_CFLAGS = -fstack-protector-strong -Wstack-protector 
HARDENING_LDFLAGS =  -Wl,-z,relro -Wl,-z,now
          LDFLAGS =  -ltpms  
  LIBSECCOMP_LIBS = 
 JSON_GLIB_CFLAGS = -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -pthread 
   JSON_GLIB_LIBS = -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 
      GLIB_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread 
        GLIB_LIBS = -lglib-2.0 

```

make V=1:

    gcc -DHAVE_CONFIG_H -I. -I..    -I../src/utils -fstack-protector-strong -Wstack-protector  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -fsanitize=address,undefined -g -fno-omit-frame-pointer -fno-sanitize-recover  -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security -I/usr/include/p11-kit-1   -MT swtpm_localca-swtpm_localca.o -MD -MP -MF .deps/swtpm_localca-swtpm_localca.Tpo -c -o swtpm_localca-swtpm_localca.o `test -f 'swtpm_localca.c' || echo './'`swtpm_localca.c


Looks like the CFLAGS I provided made it to the gcc command line.

**Comment by elmarco** [comment]
now run 
make CFLAGS="" and observe the configure-time CFLAGS are lost.

**Comment by kloczek** [comment]
> Since [47f973e](https://github.com/stefanberger/swtpm/commit/47f973ed71a2c6baec58ed5aa6c0106cff64add6) and [7f81d31](https://github.com/stefanberger/swtpm/commit/7f81d3128804fc4753d263ff39062fb706bc666c), AM_* flags are no longer used.
> 
> They were useful, as they allowed to have additional make-time CFLAGS arguments. (AM_* were used for configure time CFLAGS)

AM_* should be used only locally in Makefile.am.
Autoconf should not fiddle in those variables.
External compile, linking flags should be always passed over $CFLAGS, $CXXFLAGS, $LDFLAGS env variables.

**Comment by elmarco** [comment]
> > Since [47f973e](https://github.com/stefanberger/swtpm/commit/47f973ed71a2c6baec58ed5aa6c0106cff64add6) and [7f81d31](https://github.com/stefanberger/swtpm/commit/7f81d3128804fc4753d263ff39062fb706bc666c), AM_* flags are no longer used.
> > They were useful, as they allowed to have additional make-time CFLAGS arguments. (AM_* were used for configure time CFLAGS)
> 
> AM_* should be used only locally in Makefile.am.
> Autoconf should not fiddle in those variables.
> External compile, linking flags should be always passed over $CFLAGS, $CXXFLAGS, $LDFLAGS env variables.

Can you quote autotools manual? My understanding is that flags used at configure time should be retained, and that was working fine with the previous usage of AM_* variables.

**Comment by elmarco** [comment]
I don't see a contradiction with the fact that Makefile.am author can use it to retain the configure-time flags, like it was before.

But if we want to break the existing behaviour, then users will have to adjust.

**Comment by kloczek** [comment]
Please try have look in the ac/am build framework and try to find use AM_* variables like it was in swtpm before.

**Comment by elmarco** [comment]
People use autotools in as many ways as there are projects and versions out there. (fortunately, people are moving away from it!)

Anyway, the previous behaviour was nice, the change broke it. If this is not an accident, then fine, and no thank you.

If this is not, and you judge that AM_ variables are inappropriate, then please help fixing it.

**Comment by kloczek** [comment]
> People use autotools in as many ways as there are projects and versions out there. (fortunately, people are moving away from it!)
> 
> Anyway, the previous behaviour was nice, the change broke it. If this is not an accident, then fine, and no thank you.
> 
> If this is not, and you judge that AM_ variables are inappropriate, then please help fixing it.

That is limited by number of ways how those implementations are used by packaging software.
Below is typical set of variables used for example by rpm
```console
[tkloczko@barrel SPECS]$ rpm -E %set_build_flags

CFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none";
CXXFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none";
FFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules";
FCFLAGS="-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules";
LDFLAGS="-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin";
CC="/usr/bin/gcc"; CXX="/usr/bin/g++"; FC="/usr/bin/gfortran";
AR="/usr/bin/gcc-ar"; NM="/usr/bin/gcc-nm"; RANLIB="/usr/bin/gcc-ranlib";
export CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS CC CXX FC AR NM RANLIB;
```
Very similar set is used on Solaris by IPS, add by *BSD packaging software.
As well if it is possible to use something in some random way it does not say that it should be used.

Not sticking to some standards causing only some issues and does not introduces anything new.
Just look on https://github.com/SSSD/sssd/issues/5575 and how wrong using AM_* variables caused issue which caused that it is not possible to use LTO.

**Comment by stefanberger** [comment]
`git revert 5c5856 ; git revert 7f81d31 ; git revert 47f973e` applied to the tip seems to resolve the issue that CFLAGS passed to make isn't lost anymore when compiling `src/swtpm` but leave us with this complaint here:
```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
configure.ac:588: warning: macro 'AM_CFLAGS' not found in library
configure.ac:591: warning: macro 'AM_LDFLAGS' not found in library
```

**Comment by stefanberger** [comment]
If commit da2d2f39966ce6636c6cfc49767df320b4d08a7c is indeed correct (for this project) then we'll have to do similar for the Maeifle.am in `src/{samples,swtpm_ioctl,utils,swtpm_bios}`'

I have this now in `master.fix_build` branch: https://github.com/stefanberger/swtpm/commits/master.fix_build.

**Comment by stefanberger** [comment]
any comments, anyone?

**Comment by kloczek** [comment]
Comment: to pass additional compile and linker flags should be used $CFLAGS and $LDFALGS env variables like it is all other projects.

**Comment by stefanberger** [comment]
In the above tree (https://github.com/stefanberger/swtpm/commits/master.fix_build) we now seem to loose AM_CFLAGS when passing CFLAGS:

without the CFLAGS passed (notice -g -O2)

```
$ make -C src/utils/ V=1
make: Entering directory '/home/stefanb/dev/swtpm/src/utils'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -fstack-protector-strong -Wstack-protector -D_FORTIFY_SOURCE=2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -g -O2  -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security -I/usr/include/p11-kit-1   -MT libswtpm_utils_la-swtpm_utils.lo -MD -MP -MF .deps/libswtpm_utils_la-swtpm_utils.Tpo -c -o libswtpm_utils_la-swtpm_utils.lo `test -f 'swtpm_utils.c' || echo './'`swtpm_utils.c
```

with the CFLAGS passed `-Wextra` is there but ` -g -O2  -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security` are missing (same behavior in stable-0.6)

```
$ make -C src/utils/ V=1 CFLAGS="-Wextra"
make: Entering directory '/home/stefanb/dev/swtpm/src/utils'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -fstack-protector-strong -Wstack-protector -D_FORTIFY_SOURCE=2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -Wextra -MT libswtpm_utils_la-swtpm_utils.lo -MD -MP -MF .deps/libswtpm_utils_la-swtpm_utils.Tpo -c -o libswtpm_utils_la-swtpm_utils.lo `test -f 'swtpm_utils.c' || echo './'`swtpm_utils.c
```

Is passing CFLAGS supposed to behave this way @elmarco ?

**Comment by elmarco** [comment]
Ideally, make CFLAGS="" should be _additional_ customizable compile-time CFLAGS.

**Comment by stefanberger** [comment]
And how do we do this?

**Comment by kloczek** [comment]
> Ideally, make CFLAGS="" should be _additional_ customizable compile-time CFLAGS.

Those options shoud be passed to the autoconf so:
```
$ CFLAGS="<compile_flags>" LDFLAGS="<linker_flags>" ./configure <autoconf_options>
```
Using $CFLAGS, $LDFLAGS, $CC, $CXX comes froom time when only `make` was used (+30 years).
`make` does not support `$AM_*` -> it should not be used.
Exactly te same set of env varables is used by cmake, meson, scon and few other.

**Comment by elmarco** [comment]
> Those options shoud be passed to the autoconf so:

My point is make time CFLAGS are independant from configure-time CFLAGS.

**Comment by kloczek** [comment]
> My point is make-time CFLAGS are independant from configure-time CFLAGS.

So why you need yet another level of controll?🤔
CFLAGS/LDFLAGS is not enough? In what kind of scenario?🤔

**Comment by elmarco** [comment]
For development reasons, you may legitimately want to tweak the CFLAGS at compile-time only, without having to run through configure each time.

**Comment by kloczek** [comment]
You can generate separated off-tree build dirs with separated CFLAGS:
```csolsole
$ mkdir build-CFLSGS{1,2}
$ cd build-CFLSGS1;  CFLAGS="<compile_flags1>" LDFLAGS="<linker_flags1>" ../configure <autoconf_options1>; make
$ cd ../build-CFLSGS2  CFLAGS="<compile_flags2>" LDFLAGS="<linker_flags2>" ../configure <autoconf_options2>; make
```
Look on my script which I'm using to perform such builds with 5 diffreent set of flags.
https://github.com/kloczek/tvision/blob/master/tests/optimisation.sh
That way is way mopre usefull because it allows preserve resuults of such builds in separated trees.
https://github.com/kloczek/tvision/blob/master/tests/warnings.sh
That script is very simillar and allows generate list of warnings generated by gcc and clang.

**Comment by elmarco** [comment]
> So why you need yet another level of controll?

Additional CFLAGS passed at make-time. You don't break the build, you don't reconfigure. But I have the feeling I keep repeating myself.

**Comment by stefanberger** [comment]
Please verify https://github.com/stefanberger/swtpm/pull/504 , @elmarco and @kloczek

**Comment by stefanberger** [comment]
@elmarco Can we close this issue now?

**Comment by elmarco** [comment]
Yes, thanks!
