### ISSUE TITLE
RFC: Move swtpm-localca(8) and friends from /usr/share/swtpm to /usr/bin

### ISSUE THREAD

**Issue by nchevsky** [stefanberger/swtpm#499]
`swtpm-localca(8)`, which used to be a script but is now a binary, is being installed to `/usr/share/swtpm` along with two other utilities, `swtpm-create-tpmca(8)` and `swtpm-create-user-config-files(8)`, which are still scripts.

Installing `swtpm-localca(8)` to `/usr/share` is conceptually wrong (and triggers fatal Lintian error [arch-dependent-file-in-usr-share](https://lintian.debian.org/tags/arch-dependent-file-in-usr-share)) because, being now a binary, it's architecture-dependent and `/usr/share` is supposed to contain only non-binary, architecture-agnostic files.

👉🏻 `swtpm-localca(8)` should be moved to `/usr/bin`. While the two other scripts are technically OK to leave in `/usr/share/swtpm`, we might as well relocate them too—it's perfectly acceptable to have script executables in `/usr/bin` (e.g. `aclocal(1)`), but the opposite (i.e. binary executables in `/usr/share`) is not.

I'm happy to submit a pull request; just state your preference:

1. relocate all executables from `/usr/share/swtpm` to `/usr/bin` (my recommendation), or
2. relocate only `swtpm-localca(8)` to `/usr/bin`, and leave `swtpm-create-tpmca(8)` and `swtpm-create-user-config-files(8)` in `/usr/share/swtpm`.

**Comment by stefanberger** [comment]
We cannot move `/usr/share/swtpm/swtpm-localca`. There are config files that have been pointing to this file for a long time. I just recently change this and `/usr/bin/swtpm_localca` is now what used to be the binary in `/usr/share/swtpm-localca`. `/usr/share/swtpm_localca` is now a script invoking `/usr/bin/swtpm-localca`.

**Comment by stefanberger** [comment]
The `create_certs_tool` entry in the following file has been pointing to this file for a long time and it's expected to be there by now. So there's no we we can change this.

```
cat /etc/swtpm_setup.conf 
# Program invoked for creating certificates
create_certs_tool= /usr/share/swtpm/swtpm-localca
create_certs_tool_config = /etc/swtpm-localca.conf
create_certs_tool_options = /etc/swtpm-localca.options
```

**Comment by nchevsky** [comment]
> We cannot move `/usr/share/swtpm/swtpm-localca`. There are config files that have been pointing to this file for a long time. I just recently change this and `/usr/bin/swtpm_localca` is now what used to be the binary in `/usr/share/swtpm-localca`. `/usr/share/swtpm_localca` is now a script invoking `/usr/bin/swtpm-localca`.

Ah, gotcha. The wrapper script approach would certainly resolve the [arch-dependent-file-in-usr-share](https://lintian.debian.org/tags/arch-dependent-file-in-usr-share) Lintian warning, so that works for me—but out of curiosity, is there a reason you went with a wrapper rather than a symlink?

**Comment by stefanberger** [comment]
>  is there a reason you went with a wrapper rather than a symlink?

yes, see #482

**Comment by stefanberger** [comment]
It may not be the best of location for an executable but its in good company:
```
# find /usr/share/ -type f -executable -print | xargs ls -l
-rwxr-xr-x. 1 root root     5875 Jan  1  2020 /usr/share/automake-1.16/ar-lib
-rwxr-xr-x. 1 root root     7400 Jan  1  2020 /usr/share/automake-1.16/compile
-rwxr-xr-x. 1 root root    44155 Jan 25 20:32 /usr/share/automake-1.16/config.guess
-rwxr-xr-x. 1 root root    31428 Jan 25 20:32 /usr/share/automake-1.16/config.sub
-rwxr-xr-x. 1 root root    23568 Jan  1  2020 /usr/share/automake-1.16/depcomp
-rwxr-xr-x. 1 root root    15645 Sep  2  2019 /usr/share/automake-1.16/install-sh
-rwxr-xr-x. 1 root root     6106 Jan  1  2020 /usr/share/automake-1.16/mdate-sh
-rwxr-xr-x. 1 root root     6878 Jan  1  2020 /usr/share/automake-1.16/missing
-rwxr-xr-x. 1 root root     3539 Mar 30  2018 /usr/share/automake-1.16/mkinstalldirs
-rwxr-xr-x. 1 root root     5236 Feb 25  2020 /usr/share/automake-1.16/py-compile
-rwxr-xr-x. 1 root root    19467 Jan  1  2020 /usr/share/automake-1.16/tap-driver.sh
-rwxr-xr-x. 1 root root     4642 Jan  1  2020 /usr/share/automake-1.16/test-driver
-rwxr-xr-x. 1 root root     6860 Jan  1  2020 /usr/share/automake-1.16/ylwrap
```

**Comment by nchevsky** [comment]
> It may not be the best of location for an executable but its in good company:
> 
> ```
> # find /usr/share/ -type f -executable -print | xargs ls -l
> -rwxr-xr-x. 1 root root     5875 Jan  1  2020 /usr/share/automake-1.16/ar-lib
> -rwxr-xr-x. 1 root root     7400 Jan  1  2020 /usr/share/automake-1.16/compile
> -rwxr-xr-x. 1 root root    44155 Jan 25 20:32 /usr/share/automake-1.16/config.guess
> -rwxr-xr-x. 1 root root    31428 Jan 25 20:32 /usr/share/automake-1.16/config.sub
> -rwxr-xr-x. 1 root root    23568 Jan  1  2020 /usr/share/automake-1.16/depcomp
> -rwxr-xr-x. 1 root root    15645 Sep  2  2019 /usr/share/automake-1.16/install-sh
> -rwxr-xr-x. 1 root root     6106 Jan  1  2020 /usr/share/automake-1.16/mdate-sh
> -rwxr-xr-x. 1 root root     6878 Jan  1  2020 /usr/share/automake-1.16/missing
> -rwxr-xr-x. 1 root root     3539 Mar 30  2018 /usr/share/automake-1.16/mkinstalldirs
> -rwxr-xr-x. 1 root root     5236 Feb 25  2020 /usr/share/automake-1.16/py-compile
> -rwxr-xr-x. 1 root root    19467 Jan  1  2020 /usr/share/automake-1.16/tap-driver.sh
> -rwxr-xr-x. 1 root root     4642 Jan  1  2020 /usr/share/automake-1.16/test-driver
> -rwxr-xr-x. 1 root root     6860 Jan  1  2020 /usr/share/automake-1.16/ylwrap
> ```
The issue wasn't with executables, but _binary_ executables in `/usr/share`. All the `automake` executables you pasted are scripts, and as such don't break any rules since they're architecture-independent. 🙂

**Comment by nchevsky** [comment]
@stefanberger Now that we have both `/usr/bin/swtpm_localca` (actual program) and `/usr/share/swtpm/swtpm-localca` (wrapper script), we should probably make the manual page accessible by both names by aliasing one to the other.

I have a pull request ready to go but, since the two executables' names are different (`_` vs. `-`), there are decisions to be made:

| Option | `man8/swtpm_localca` | `man8/swtpm-localca` | Pros and cons |
| -------- | ------------------------ | -------------------------| --------------- |
| 1 | Actual `.pod` manpage | `.8` with `.so` alias for `swtpm_localca` | ✔ Consistent with `swtpm_localca` being the actual program and `swtpm-localca` being a wrapper that invokes `swtpm_localca` |
| 2 | `.8` with `.so` alias for `swtpm-localca` | Actual `.pod` manpage (same as now) | ❌ Opposite of and inconsistent with the executables |

And once we've defined the above:

| Option | Name of program documented in the manpage's content | Pros and cons |
| -------- | ----------------------------------------------------------------| --------------- |
| a | `swtpm_localca` | ✔ Consistent with `swtpm_localca` being the actual program<br/>❌ Names of configuration files (`swtpm-localca.conf`, `swtpm-localca.options`) don't match the documented program's `_` name. |
| b | `swtpm-localca`<br/>(same as now) | ❌ Doesn't match the name of the actual program.<br/>✔ Names of configuration files (`swtpm-localca.conf`, `swtpm-localca.options`) match the documented program's `-` name. |

**Comment by stefanberger** [comment]
What would be your preference?

**Comment by nchevsky** [comment]
I'm a purist to a fault, so in theory my preference is for 1.a since it consistently mirrors what it's effectively documenting:

- `swtpm_localca` is the actual program ➡ `swtpm_localca.pod` should be the actual manpage, and its content should refer to the program by its actual physical name, `swtpm_localca` (and screw the mismatched `-` in the names of the config files).
- `swtpm-localca` is a wrapper for `swtpm_localca` ➡ `swtpm-localca.8` should be an alias for `swtpm_localca.pod`.

Now, the `_` vs. `-` inconsistency in filenames does bother me and, ideally, I'd settle on one of the two and rename the rest to match. Perhaps we could compromise on the following?

- Since `/usr/bin/swtpm_localca` is new, unreleased, and not yet referenced by anything other than the `/usr/share/swtpm/swtpm-localca` wrapper, it can still be renamed risk-free.
- If we renamed `/usr/bin/swtpm_localca` to `/usr/bin/swtpm-localca`, then the binary, its wrapper, the manpage with no alias required, and the configuration files would all match. 👍🏻
- Sadly the older `_`-named binaries in `/usr/bin` wouldn't match, but since you already broke that pattern with the executables in `/usr/share/swtpm` I'm guessing hyphens might be your preference going forward and you might not mind too much.

This would result in the following beauty:

```
/etc/swtpm-localca.conf
/etc/swtpm-localca.options
/usr/bin/swtpm-localca (renamed from `swtpm_localca`)
/usr/share/man/man8/swtpm-localca.8
/usr/share/swtpm/swtpm-localca -> /usr/bin/swtpm-localca
```

**Comment by stefanberger** [comment]
>     * Since `/usr/bin/swtpm_localca` is new, unreleased, and not yet referenced by anything other than the `/usr/share/swtpm/swtpm-localca` wrapper, it can still be renamed risk-free.

Agreed.

**Comment by nchevsky** [comment]
@stefanberger Now that we've moved `swtpm_localca`'s sources to `src/`, I look at it alongside all the other `_`-named programs in there and feel it'd be weird to rename just this one to `swtpm-localca`. Even if we don't rename the sources but merely modify the Makefile to have the binary compile to the new name, it doesn't feel quite right to me.

I'm personally leaning toward option **1.a** again, i.e. leaving the `swtpm_localca` program itself untouched, renaming the manpage to match, and aliasing the `swtpm-localca` wrapper's manpage to it. If you'd still like me to rename the program instead, no problem.

BTW, either approach will resolve the [no-manual-page Lintian warning](https://lintian.debian.org/tags/no-manual-page) that's currently being triggered by `swtpm_localca` being installed without a matching manpage.

Sorry for all the back-and-forth! I'll have a pull request ready to go as soon as you voice your final choice.

**Comment by stefanberger** [comment]
Let's have a look at your pr then...

**Comment by nchevsky** [comment]
> Let's have a look at your pr then...

I've prepared two alternative pull requests showing the implementation of each option—take your pick:

1. [Change swtpm-localca to swtpm_localca in manpages](https://github.com/stefanberger/swtpm/pull/505) (implements option 1.a)
2. [Rename swtpm_localca binary to swtpm-localca](https://github.com/stefanberger/swtpm/pull/506) (implements option 3)
