### ISSUE TITLE
Can I use TrouSerS on swtpm emulated TPM device

### ISSUE THREAD

**Issue by yingkailiang** [stefanberger/swtpm#5]
Hi, 

I have set up the swtpm on my ubuntu. I can see /dev/vtpm0 on my machine. I want to run TrouSerS test suit on vtpm. Can I do that?

If I can, when I try to connect tpm device using command "sudo tcsd -f". The error message shows "could not find a device to open!". But I can see /dev/vtpm0 on my machine.

Any suggestion are welcomed. Thanks.

**Comment by stefanberger** [comment]
Unfortunately you cannot tell TrouSerS which device to use. By default it is going to try the following devices /dev/tpm0, /udev/tpm0, and /dev/tpm in that order. If you do not have a hardware TPM on your machine, then you could try to start the CUSE TPM as /dev/tpm0 like this:

swtpm cuse -n tpm0 --tpmstate dir=/tmp
swtpm_ioctl -i /dev/tpm0
TPM_DEVICE=/dev/tpm swtpm_bios
tcsd -f 

That should then provide /dev/tpm0 and be able to start TCSD on that device.

Remember to gracefully shut down this CUSE TPM do:

swtpm_ioctl -s /dev/tpm0

If on the other hand you have a /dev/tpm0 with a hardware TPM, then you may want to try to block its usage by TrouSers by opening a file descriptor on /dev/tpm0 and keeping that file descriptor open while creating the CUSE TPM on /dev/tpm (the 3rd one it's going to try):

exec 100<>/dev/tpm0    # make sure /dev/tpm0 becomes inaccessible
swtpm_cuse -n tpm --tpmstate dir=/tmp
swtpm_ioctl -i /dev/tpm
TPM_DEVICE=/dev/tpm swtpm_bios
tcsd -f 

Make sure that no two emulated TPMs are using the same storage directory for storing their state, here /tmp (from --tpmstate dir=/tmp).

For me the latter worked. And I had to then run the following command to get an EK:

tpm_createek

**Comment by yingkailiang** [comment]
Thanks for your detail explain. I am trying to setup a virtual TPM on virtual machine and I don't have a real TPM device on my OS. Your first solution works fine for me.
