### ISSUE TITLE
[Question or Feature proposal] Is it possible to feed PCR to TPM while connected to qemu?

### ISSUE THREAD

**Issue by jc-lab** [stefanberger/swtpm#511]
I want to change PCR while connected to QEMU. (for PCR change testing)
Is it possible now? Or need a feature implementation?

**To Reproduce**
1.
```
$ swtpm socket --seccomp action=none --tpm2 --tpmstate dir=(datadir) --ctrl type=unixio,path=swtpm.sock
```
2.
```
qemu
-chardev socket,id=chrtpm,path=swtpm.sock
-tpmdev emulator,id=tpm0,chardev=chrtpm
-device tpm-tis,tpmdev=tpm0
```
3.
```
$ swtpm_ioctl --unix ~/swtpm/01.sock -h "abcd"
```
It is not working!

**Comment by stefanberger** [comment]
No it's not possible since only one control channel client is allowed. Also, the VM should be the only one talking to the TPM and nothing else should be able to manipulate PCRs or any other state of the TPM.
