### ISSUE TITLE
[RFE] Offer configure-time option to disable TPM 1.2 support

### ISSUE THREAD

**Issue by andreabolognani** [stefanberger/swtpm#512]
Red Hat is interested in removing TPM 1.2 support from its build of swtpm.

To make that possible without nasty downstream-only hacks, ideally swtpm would gain a `--without-tpm12` or similar configure switch, which results in all code related to TPM 1.2 being compiled out; it would also start reporting whether TPM 1.2 support is present in the binary through its existing introspection facilities, so that libvirt can detect when it's missing and warn users who attempt to use it.

Does this sound like a reasonable feature to add? Do you foresee any big obstacle to implementing it? Assuming the answers are yes and no respectively, @elmarco and I can take a stab at it :)

**Comment by elmarco** [comment]
I started looking at libtpms, there is some bits around NVRAM that are a bit tangled, but the rest looks quite straightforward. I'll try to send a PR soon.

**Comment by andreabolognani** [comment]
@stefanberger @elmarco Do I understand correctly that the ability to disable TPM 1.2 support was introduced in libtpms with https://github.com/stefanberger/libtpms/pull/244 (`--with-tpm1=no` configure option), and swtpm merely exposes that information through its introspection capabilities?

**Comment by elmarco** [comment]
Correct
