### ISSUE TITLE
Does swtpm support live migration?

### ISSUE THREAD

**Issue by littlelearnlive** [stefanberger/swtpm#525]
I used the swtpm and libtpms projects to build my vtpm devices. Nowadys I  deployment the trueted computing enviroment in our cloud platform, and I want to know whether the vtpm created by swtpm supported live migration.
when I chose the live migration choice in our openstack cloud platform, getting a error as follow:

`2021-09-05 16:09:05.825 15688 ERROR nova.virt.libvirt.driver [req-0c94b0e4-c408-4c7a-a4ea-79d01de67d7e 7e1b723ad22347a3bf5d8c189a547fa8 0e9cfd18abe34000aa10822c5f3db72a - default default] [instance: 02e739c0-5786-42a3-bcb2-f97603d43e24] Live Migration failure: internal error: process exited while connecting to monitor: 2021-09-05 08:09:05.670+0000: Domain id=5 is tainted: high-privileges
2021-09-05 08:09:05.670+0000: Domain id=5 is tainted: custom-argv
2021-09-05T08:09:05.739238Z qemu-kvm: -chardev socket,id=chrtpm,path=/var/lib/nova/instances/02e739c0-5786-42a3-bcb2-f97603d43e24/mytpm/swtpm-sock: Failed to connect socket /var/lib/nova/instances/02e739c0-5786-42a3-bcb2-f97603d43e24/mytpm/swtpm-sock: Connection refused: libvirtError: internal error: process exited while connecting to monitor: 2021-09-05 08:09:05.670+0000: Domain id=5 is tainted: high-privileges`

The main error is: Failed to connect socket， Connection refused
Can you give us some advice? Doed the swtpm doesn't support live migration ?

**Comment by stefanberger** [comment]
swtpm supports live migration alongside a QEMU VM that is being live migrated.

**Comment by littlelearnlive** [comment]
> swtpm supports live migration alongside a QEMU VM that is being live migrated.

Thanks for you reply. Did you mean that I can use the qemu-tpm(v2.12), libtpms(v0.9.0) and swtpm(v0.6.0) to complete live migration without any changes to the codes? If so, can you give me some advice to accomplish live migration?  I use the oginal projects to do live migration in openstack platform, but some errors got and I can't konw what went rong.

**Comment by stefanberger** [comment]
I tested live migration now using the BIOS-only VM definition below. It works but something is not quite alright on the libvirt level when a vTPM is attached.

I first migrated this VM without an attached TPM (removed TIS device) back and forth between two hosts (Fedora 34) running exactly the same version of QEMU (5.2.0) and libvirt (7.0.0). I used virt-manager for migration and used direct migration between the two hosts. I had to open port 49152 on both machines (`firewall-cmd --permanent --add-port=49152/tcp; sudo firewall-cmd --reload`) for the migration to work.

Then I attached the TIS device to the VM and started it. I have libtpms v0.9.0 (tip of master branch) and swtpm (v0.7.0, tip of  master branch) on both machines. With this I can migrated the VM back and forth as well but I get and error message regarding a swtpm log file on the destination host if the VM had been there before. I then have to again initiate the migration to be able to actually migrate the VM there. The culprit seems to be that the swtpm's log file has an SELinux label from before the migration and it shouldn't be there. This label would have to be removed first, probably at the time of previous shutdown of the VM when it left that host.

```
domain type='kvm'>
  <name>BIOS-only-VM</name>
  <uuid>ecc221c4-6bb9-423f-ac31-72244fdbb1a1</uuid>
  <metadata>
    <libosinfo:libosinfo xmlns:libosinfo="http://libosinfo.org/xmlns/libvirt/domain/1.0">
        <libosinfo:os id="http://fedoraproject.org/fedora/30"/>
      </libosinfo:libosinfo>
  </metadata>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <vcpu placement='static'>4</vcpu>
  <os>
    <type arch='x86_64' machine='pc-q35-3.1'>hvm</type>
    <boot dev='hd'/>
    <bootmenu enable='yes' timeout='3000'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state='off'/>
    <smm state='on'/>
  </features>
  <cpu mode='host-model' check='partial'/>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <controller type='sata' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'/>
    <controller type='pci' index='1' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='1' port='0x10'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='2' port='0x11'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='3' port='0x12'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='4' port='0x13'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='5' port='0x14'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='6' port='0x15'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x5'/>
    </controller>
    <controller type='pci' index='7' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='7' port='0x16'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x6'/>
    </controller>
    <controller type='pci' index='8' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='8' port='0x17'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x7'/>
    </controller>
    <controller type='pci' index='9' model='pcie-to-pci-bridge'>
      <model name='pcie-pci-bridge'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
    <controller type='usb' index='0' model='piix3-uhci'>
      <address type='pci' domain='0x0000' bus='0x09' slot='0x02' function='0x0'/>
    </controller>
    <interface type='network'>
      <mac address='52:54:00:94:21:ab'/>
      <source network='default'/>
      <model type='rtl8139'/>
      <address type='pci' domain='0x0000' bus='0x09' slot='0x01' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='unix'>
      <target type='virtio' name='org.qemu.guest_agent.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <tpm model='tpm-tis'>
      <backend type='emulator' version='2.0'/>
    </tpm>
    <graphics type='vnc' port='-1' autoport='yes' listen='0.0.0.0'>
      <listen type='address' address='0.0.0.0'/>
    </graphics>
    <video>
      <model type='virtio' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </memballoon>
    <rng model='virtio'>
      <backend model='random'>/dev/urandom</backend>
      <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
    </rng>
  </devices>
</domain>
```

**Comment by stefanberger** [comment]
libvirt 7.0.0 for example is having this issue. The reason for it is this patch here: https://github.com/libvirt/libvirt/commit/5cde9dee8c70b17c458d031ab6cf71dce476eea  This patch caused break of libvirt v6.10.0 and v7.0.0

The issue has been resolve with this patch starting in v7.1.0: https://github.com/libvirt/libvirt/commit/f30aa2ec74a79f34700915b677f46ec476d2362d  

I can migrate a VM with attached swtpm from one host to another using the latest libvirt version and using this command line:

```
virsh migrate --live BIOS-only-VM qemu+ssh://<destination host>/system
```

**Comment by littlelearnlive** [comment]
> 例如，libvirt 7.0.0 就有这个问题。原因是这里的这个补丁：[libvirt/libvirt@ 5cde9de](https://github.com/libvirt/libvirt/commit/5cde9dee8c70b17c458d031ab6cf71dce476eea) 这个补丁导致 libvirt v6.10.0 和 v7.0.0 中的 vTPM 迁移中断
> 
> 从 v7.1.0 开始，此补丁已解决该问题：[libvirt/libvirt@ f30aa2e](https://github.com/libvirt/libvirt/commit/f30aa2ec74a79f34700915b677f46ec476d2362d)
> 
> 我可以使用最新的 libvirt 版本并使用以下命令行将带有附加 swtpm 的 VM 从一台主机迁移到另一台主机：
> 
> ```
> virsh migrate --live BIOS-only-VM qemu+ssh://<destination host>/system
> ```

**Comment by littlelearnlive** [comment]
Thanks so much. And I also have some questions to result.
1) I can't find the swtpm's log file which has an  SELinux label, can you tell me the exact location in swtpm project?
2) Towards your reply, does the qemu-tpm in your github personal homepage  support live migration? we use the qemu-tpm2.12. Besides, can qemu recognize vtpm as a live migration device？
3) Thanks for your advice to use the libvirt 7.1.0 , but we can't use the 7.1.0 version and I haven't had time to use libvirt for live migration, I will try recently.

**Comment by stefanberger** [comment]
> 
> 
> Thanks so much. And I also have some questions to result.
> 
>     1. I can't find the swtpm's log file which has an  SELinux label, can you tell me the exact location in swtpm project?

The SELinux related error only occurs with those buggy libvirt versions since libvirt wasn't able to remove the SELinux label. The location of the log file is: `/var/log/swtpm/libvirt/qemu/BIOS-oly-VM-swtpm.log`.

> 
>     2. Towards your reply, does the qemu-tpm in your github personal homepage  support live migration? we use the qemu-tpm2.12. Besides, can qemu recognize vtpm as a live migration device？
> 

I don't know what versions 2.12 is. But all code related to vTPM support has been upstreamed to the QEMU project. so you should use the git repo of QEMU rather than my repo: https://gitlab.com/qemu-project/qemu

>     3. Thanks for your advice to use the libvirt 7.1.0 , but we can't use the 7.1.0 version and I haven't had time to use libvirt for live migration, I will try recently.

I am sure your openstack setup is using libvirt for VM management and migration. So you have to make sure that the libvirt openstack use has the right version.

**Comment by stefanberger** [comment]
So the answer to the question ''Does swtpm support live migration?" is 'yes'. The restrictions that apply here are related to libtpms not allowing to 'downgrade', meaning you cannot migrate from libtpms 0.8.x to libtpms 0.7.x for example. Does this answer your question?

**Comment by littlelearnlive** [comment]
> So the answer to the question ''Does swtpm support live migration?" is 'yes'. The restrictions that apply here are related to libtpms not allowing to 'downgrade', meaning you cannot migrate from libtpms 0.8.x to libtpms 0.7.x for example. Does this answer your question?

Thanks a lot!
And I also want to ask you for some questions.
We are using  qemu-tpm(v3.0), libtpms(v0.9.0), and swtpm(v0.6.0) to implement the dynamic migration of trusted virtual machines on the openstack platform, but during the dynamic migration of trusted virtual machines, both the source node and the destination node feedback some error messages.
The source node(compute1) reports the error as follows:
![image](https://user-images.githubusercontent.com/35371945/134273225-b0081ac9-76aa-4990-b6fc-b87da35d0869.png)
View the log information of the virtual machine in the /var/log/libvirt/qemu directory:
![image](https://user-images.githubusercontent.com/35371945/134273279-fa6286ef-451b-4f09-9822-fd6ef1636e77.png)
The destination node(compute2) reports the error as follows:
![image](https://user-images.githubusercontent.com/35371945/134273320-5ebbd4b1-9c8f-4959-9943-421e81a68271.png)
Can you give us some advice?

**Comment by stefanberger** [comment]
Please do not use qemu-tpm from my git repo. Please use the upstream QEMU that has the TPM support already in.

Are you trying to migrate a TPM 1.2 or is this  a TPM 2?

Remote diagnostics like this is a bit difficult. Try to remove the state of the vTPM after shutting down the VM. You find the state in /var/lib/libvirt/<uuid of VM>. You may want to remove the entire directory. It shouldn't be necessary to do this, nevertheless this is the best way forward for tying it out again.
