### ISSUE TITLE
tpm2: swtpm asserts during startup in debug build

### ISSUE THREAD

**Issue by pohly** [stefanberger/swtpm#54]
When building swtpm = 2dfd15d22b425c1ca92c9bc9f03c84634e6e344a and libtpms = 14cb73d6658a9baa41a5e2ff542168463b7becf0 with --enable-debug and then running swtpm2 --tpm2, startup fails with an assertion:
```
swtpm: tpmlib.c:127: tpmlib_get_tpm_property: Assertion `res == TPM_SUCCESS' failed.
```

That's because swtpm.c asks for properties which aren't supported by TPM2_GetTPMProperty:
```
421	    TPM_DEBUG("Main: Compiled for %u auth, %u transport, and %u DAA session slots\n",
422	           tpmlib_get_tpm_property(TPMPROP_TPM_MIN_AUTH_SESSIONS),
423	           tpmlib_get_tpm_property(TPMPROP_TPM_MIN_TRANS_SESSIONS),
424	           tpmlib_get_tpm_property(TPMPROP_TPM_MIN_DAA_SESSIONS));
```

**Comment by stefanberger** [comment]
Thanks. These properties aren't defined for TPM 2. Will fix it in the tpm2-preview branch.

**Comment by stefanberger** [comment]
PR https://github.com/stefanberger/swtpm/pull/55 should address this issue.

**Comment by stefanberger** [comment]
@pohly Has this issue been resolved. If so, can you close it?

**Comment by pohly** [comment]
Yes, it's working now.
