### ISSUE TITLE
Cannot start libvirt VMs with TPM using swtpm.

### ISSUE THREAD

**Issue by JooJooBee666** [stefanberger/swtpm#547]
I am unable to boot any VMs that have TPMS enabled, though I was able to compile and install without error.  However, the log indicated in the error message is there, though it is completely empty.

**To Reproduce**
1. Build and install swtpm
2. Went through configuration for [creating a local CA](https://github.com/stefanberger/swtpm/wiki/Creating-a-CA-with-a-Pkcs11-Module)
3. Add to VM Devices for virtual system xml:
```
<tpm model="tpm-tis">
  <backend type="emulator" version="2.0"/>
</tpm>
```

4. Try to start VM.  FAIL!
```
Error starting domain: internal error: Could not run '/usr/local/bin/swtpm_setup'. exitstatus: 126; Check error log '/var/log/swtpm/libvirt/qemu/Win11Insider-swtpm.log' for details.

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 65, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 101, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1329, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: Could not run '/usr/local/bin/swtpm_setup'. exitstatus: 126; Check error log '/var/log/swtpm/libvirt/qemu/Win11Insider-swtpm.log' for details.
```
5. The log for the VM itself is quite useless as well.  The ONLY thing that gets logged is `2021-09-20 19:09:10.192+0000: shutting down, reason=failed`

**Expected behavior**
The VM starts.  I verified that /usr/local/bin/swtpm_setup exists and appears to be functional.  I would also expect there to be something in the referenced log file, but this too was not to be.

**Desktop:**
 - OS: Ubuntu
 - Version: 21.04

**Versions of relevant components**
- swtpm: master
- libtpms: 0.8.6
- openssl: 1.1.1j
- gnutls: 3.7.1
- virsh: 7.0.0

**Additional context**
I also tried to copy all the configs for the certificate items over to /var/lib/swtpm but it didn't help.  Did I miss some steps?  I feel like the documentation on how to set this up is assuming a lot of things.  I also tried to use TPM version 1.2 but the same thing happens.

**Comment by stefanberger** [comment]
Well, on Fedora it works right out of the box when installing just the packages. On Ubuntu without the support of the distro you are up on your own. Also, you may run into issue #484 if you don't use a recent version of libvirt with the AppArmor related patch applied.

There's no need to setup a pkcs11 key for issuing the certs. It should work with the software key that's going to be created on the fly without having to modify any config files. But you may want to install it inot `/usr` rather than `/usr/local`.

Does the log file show anything ? /var/log/swtpm/libvirt/qemu/Win11Insider-swtpm.log

**Comment by stefanberger** [comment]
In other words, the following should get you to be able to run a VM (modulo issue #484; you could otherwise try swtpm's stable-0.6 branch which doesn't need the AppArmor patch in libvirt):

```
./autogen.sh ... --prefix=/usr ...
make
make check
sudo make install
```

**Comment by JooJooBee666** [comment]
>There's no need to setup a pkcs11 key for issuing the certs. It should work with the software key that's going to be created on the fly without having to modify any config files. But you may want to install it into /usr rather than /usr/local.
>
How do I do that?

> Does the log file show anything ? /var/log/swtpm/libvirt/qemu/Win11Insider-swtpm.log
>
No, as I mentioned in the first part of my filing is that the file is there but completely empty.

>In other words, the following should get you to be able to run a VM (modulo issue #484; you could otherwise try swtpm's stable-0.6 branch which doesn't need the AppArmor patch in libvirt):
>
I switched to stable-0.6 and tried again, but I get the same exact message and nothing in the mentioned log...stil :cry:.  I verified I was running stable:
```
$ swtpm --version
TPM emulator version 0.6.1, Copyright (c) 2014-2021 IBM Corp.
```
So I'm guessing this is NOT the same issue?

**Comment by stefanberger** [comment]
Did you install  into `/usr`?

**Comment by JooJooBee666** [comment]
> Did you install into `/usr`?

As I noted in my last comment, how do I do that? :worried:

**Comment by stefanberger** [comment]
Do a `sudo make uninstall` first and then try this (with `--without-selinux` in your case):

```
./autogen.sh --prefix=/usr --without-selinux
make
make check
sudo make install
```

**Comment by JooJooBee666** [comment]
Ok, I see that's what you meant with your initial reply.  I also did the same for libtmps.  Now the VMs are booting.  FYI, I did not use the `--without-selinux` parameter since it compiles fine when it's not being run from a symlinked folder.

Anyhow, thanks for all the help.  Much appreciated! :beers:

**Comment by stefanberger** [comment]
So it works now for you? That's great then!
