### ISSUE TITLE
Cannot install swtpm on Ubuntu 20.04

### ISSUE THREAD

**Issue by elliotmtx** [stefanberger/swtpm#549]
OS: Ubuntu 20.04
I am trying to install swtpm and first I an below prereq step:

sudo apt-get -y install  libfuse-dev libglib2.0-dev libgmp-dev expect libtasn1-dev socat tpm-tools python3-twisted gnutls-dev gnutls-bin  libjson-glib-dev python3-setuptools softhsm2 libseccomp-dev
dpkg-buildpackage -us -uc -j$(nproc)

But it is failing with below error, kindly help

`Job for trousers.service failed because the control process exited with error code.
See "systemctl status trousers.service" and "journalctl -xe" for details.
invoke-rc.d: initscript trousers, action "start" failed.
● trousers.service - LSB: starts tcsd
   Loaded: loaded (/etc/init.d/trousers; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-07-09 12:51:11 EDT; 5ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 9449 ExecStart=/etc/init.d/trousers start (code=exited, status=30)

Jul 09 12:51:11 s3id0n systemd[1]: Starting LSB: starts tcsd...
Jul 09 12:51:11 s3id0n trousers[9449]:  * Starting Trusted Computing daemon tcsd
Jul 09 12:51:11 s3id0n tcsd[9454]: TCSD TDDL[9454]: TrouSerS ioctl: (25) In…vice
Jul 09 12:51:11 s3id0n tcsd[9454]: TCSD TDDL[9454]: TrouSerS Falling back t…ort.
Jul 09 12:51:11 s3id0n trousers[9449]:    ...fail!
Jul 09 12:51:11 s3id0n systemd[1]: trousers.service: Control process exited…s=30
Jul 09 12:51:11 s3id0n systemd[1]: Failed to start LSB: starts tcsd.
Jul 09 12:51:11 s3id0n systemd[1]: trousers.service: Unit entered failed state.
Jul 09 12:51:11 s3id0n systemd[1]: trousers.service: Failed with result 'ex…de'.
Hint: Some lines were ellipsized, use -l to show in full.
dpkg: error processing package trousers (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of tpm-tools:
 tpm-tools depends on trousers; however:
  Package trousers is not configured yet.

dpkg: error processing package tpm-tools (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                          Errors were encountered while processing:
 trousers
 tpm-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by stefanberger** [comment]
Can you try the following?
```
sudo dpkg --purge trousers tpm-tools
sudo apt install -f
```

I will remove tpm-tools and trousers from the dependencies list. They are not needed anymore.

**Comment by elliotmtx** [comment]
After above two commands I ran below, but it is failing saying "**error: Unmet build dependencies: gawk libtpms-dev**"

`sudo apt-get -y install libfuse-dev libglib2.0-dev libgmp-dev expect libtasn1-dev socat python3-twisted gnutls-dev gnutls-bin libjson-glib-dev python3-setuptools softhsm2 libseccomp-dev`

`dpkg-buildpackage -us -uc -j$(nproc)`

`:$ sudo apt-get -y install  libfuse-dev libglib2.0-dev libgmp-dev expect libtasn1-dev socat python3-twisted gnutls-dev gnutls-bin  libjson-glib-dev python3-setuptools softhsm2 libseccomp-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libtasn1-6-dev' instead of 'libtasn1-dev'
Note, selecting 'libgnutls28-dev' instead of 'gnutls-dev'
libfuse-dev is already the newest version (2.9.9-3).
libgmp-dev is already the newest version (2:6.2.0+dfsg-4).
libjson-glib-dev is already the newest version (1.4.4-2ubuntu2).
libtasn1-6-dev is already the newest version (4.16.0-2).
python3-setuptools is already the newest version (45.2.0-1).
socat is already the newest version (1.7.3.3-2).
expect is already the newest version (5.45.4-2build1).
softhsm2 is already the newest version (2.5.0-1build1).
libglib2.0-dev is already the newest version (2.64.6-1~ubuntu20.04.4).
libgnutls28-dev is already the newest version (3.6.13-2ubuntu1.6).
libseccomp-dev is already the newest version (2.5.1-1ubuntu1~20.04.1).
python3-twisted is already the newest version (18.9.0-11ubuntu0.20.04.1).
gnutls-bin is already the newest version (3.6.13-2ubuntu1.6).
The following packages were automatically installed and are no longer required:
  libtpm-unseal1 libtspi1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 114 not upgraded.

$ dpkg-buildpackage -us -uc -j$(nproc)
dpkg-buildpackage: info: source package swtpm
dpkg-buildpackage: info: source version 0.7.0~dev1
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Stefan Berger <stefanb@linux.ibm.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: gawk libtpms-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
`

**Comment by elliotmtx** [comment]
I have installed libtpms from https://github.com/stefanberger/libtpms/wiki, and after that I installed swtpm and its working now.

**Comment by stefanberger** [comment]
I am glad it works for you now.

**Comment by parthghughri** [comment]
> I have installed libtpms from https://github.com/stefanberger/libtpms/wiki, and after that I installed swtpm and its working now.

Thanks for the info. This solution is working for me too.

**Comment by stefanberger** [comment]
If this issue is resolved, please close it.

**Comment by stefanberger** [comment]
I am now trying to solve this swtpm 0.7 issue with PR #573 to turn off the offending fsync() if it doesn't work.

**Comment by Mlocik97** [comment]
I also have problem installing swtpm on Ubuntu 20.04. even when it seems installed correctly, virt-manager throw error:

> libvirt.libvirtError: Unable to find 'swtpm' binary in $PATH

**Comment by stefanberger** [comment]
> I also have problem installing swtpm on Ubuntu 20.04. even when it seems installed correctly, virt-manager throw error:
> 
> > libvirt.libvirtError: Unable to find 'swtpm' binary in $PATH

Is `/usr/bin/swtpm` available? If not, how did you `configure ... --prefix=/usr` the project? Did you maybe forget to `make install` it?

> 
> btw. it would be nice to have this as package (apt / snap)

You have to ask Ubuntu about this.

You can find packages for Bionic here: https://launchpad.net/~stefanberger

**Comment by Mlocik97** [comment]
ok, I'm trying package now, this is what I have now.

```
swtpm/focal 0.6.1-1 amd64
  Libtpms-based TPM emulator

swtpm-dev/focal 0.6.1-1 amd64
  Include files for the TPM emulator's CUSE interface

swtpm-libs/focal 0.6.1-1 amd64
  Common libraries for TPM emulators

swtpm-tools/focal 0.6.1-1 amd64
  Tools for the TPM emulator
```

will try, if it works now.

**Comment by Mlocik97** [comment]
Should I install tools too? or swtpm and libs are enough?

**Comment by Mlocik97** [comment]
```
mlocik97@mlocik97-G5-5590:~$  sudo apt-get -y install swtpm-tools
Načítavajú sa zoznamy balíkov... Hotovo
Vytvára sa strom závislostí           
Načítavajú sa stavové informácie... Hotovo
swtpm-tools je již nejnovější verze (0.6.1-1).
Nasledovné balíky boli nainštalované automaticky a už viac nie sú potrebné:
  libpython2-stdlib libpython2.7-minimal libpython2.7-stdlib python2 python2-minimal python2.7
  python2.7-minimal
Na ich odstránenie použite „sudo apt autoremove“.
0 aktualizovaných, 0 nových nainštalovaných, 0 na odstránenie a 5 neaktualizovaných.
2 iba čiastočne nainštalovaných alebo odstránených.
Po tejto operácii sa na disku použije ďalších 0 B.
Nastavuje sa balík trousers (0.3.14+fixed1-1build1) ...
Job for trousers.service failed because the control process exited with error code.
See "systemctl status trousers.service" and "journalctl -xe" for details.
invoke-rc.d: initscript trousers, action "start" failed.
● trousers.service - LSB: starts tcsd
     Loaded: loaded (/etc/init.d/trousers; generated)
     Active: failed (Result: exit-code) since Wed 2021-10-06 13:23:09 CEST; 4ms ago
       Docs: man:systemd-sysv-generator(8)
    Process: 13653 ExecStart=/etc/init.d/trousers start (code=exited, status=30)

okt 06 13:23:09 mlocik97-G5-5590 systemd[1]: Starting LSB: starts tcsd...
okt 06 13:23:09 mlocik97-G5-5590 trousers[13653]:  * Starting Trusted Computing daemon tcsd
okt 06 13:23:09 mlocik97-G5-5590 trousers[13653]: /etc/init.d/trousers: 32: [: /dev/tpm0: unexpected operator
okt 06 13:23:09 mlocik97-G5-5590 tcsd[13659]: TCSD TDDL[13659]: TrouSerS ioctl: (25) Inappropriate ioctl for device
okt 06 13:23:09 mlocik97-G5-5590 tcsd[13659]: TCSD TDDL[13659]: TrouSerS Falling back to Read/Write device support.
okt 06 13:23:09 mlocik97-G5-5590 tcsd[13659]: TCSD TCS[13659]: TrouSerS ERROR: TCS GetCapability failed with result = 0x1e
okt 06 13:23:09 mlocik97-G5-5590 trousers[13653]:    ...fail!
okt 06 13:23:09 mlocik97-G5-5590 systemd[1]: trousers.service: Control process exited, code=exited, status=30/n/a
okt 06 13:23:09 mlocik97-G5-5590 systemd[1]: trousers.service: Failed with result 'exit-code'.
okt 06 13:23:09 mlocik97-G5-5590 systemd[1]: Failed to start LSB: starts tcsd.
dpkg: chyba při zpracovávání balíku trousers (--configure):
 installed trousers package post-installation script subprocess returned error exit status 1
dpkg: problémy so závislosťami zabránili konfigurácii balíka swtpm-tools:
 swtpm-tools závisí na trousers (>= 0.3.9); aj keď:
  Balík trousers ešte nie je nakonfigurovaný.

dpkg: chyba při zpracovávání balíku swtpm-tools (--configure):
 problémy so závislosťami - po necháva sa nenakonfigurované
Nezapíše sa správa apport, pretože chybová správa indikuje, že je to chyba v nadväznosti na predošlé zlyhanie.
         Vyskytli sa chyby počas spracovania:
 trousers
 swtpm-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Mlocik97** [comment]
I tried it again, got same error, but when I did apt search swtpm, it wrote it's installed so I tried to run VM with TPM, and it works. Even tho I got that error in terminal. :shrug:

**Comment by stefanberger** [comment]
The problem may be that, unless you get to fix this package, it may not let you install new packages... `apt install -f` really should fix this for you with /dev/tpm0 temporarily removed.
