### ISSUE TITLE
tpm_ioctl.c: (uint32_t)-1 ?

### ISSUE THREAD

**Issue by pohly** [stefanberger/swtpm#56]
In src/swtpm_ioctl/tpm_ioctl.c:do_save_state_blob(), the result of write() gets casted to uint32_t to avoid signed/unsigned comparison (commit 768d657b695e8760a017dbe61de4ed437b80d3b8):

```
         numbytes = write(file_fd, pgs.u.resp.data, recvd_bytes);
        if ((uint32_t)numbytes != recvd_bytes) {
             fprintf(stderr,
                     "Could not write to file '%s': %s\n",
                     filename, strerror(errno));
```

I wonder how that'll affect the case where write() returns -1. It'll still work, won't it?

It might be cleaner to do ```if(numbytes != (ssize_t)recvd_bytes)``` but it's probably not worth a patch.

I ran across this because meta-security had that as fix (without upstreaming it!), which I noticed while trying to update the build recipe.

**Comment by stefanberger** [comment]
`recvd_bytes` is positive when it is compared against `numbytes`. It shouldn't be able to cause a problem. Another solution would be to check for `numbytes < 0 || (uint32_t)numbytes != recvd_bytes`.

**Comment by pohly** [comment]
My concern isn't about ``recvd_bytes``, my worry is about  ``numbytes``. Checking that for ``< 0`` addresses that worry. But I still think casting ``recvd_bytes`` is simpler. Anyway, I don't have strong opinions about this.

We can also just close the issue.

**Comment by stefanberger** [comment]
I'll patch it.

**Comment by stefanberger** [comment]
https://github.com/stefanberger/swtpm/commit/182fbb20d6cda10fdf9fb72a3001705d0ddb0a10 adds the comparison against < 0.

**Comment by stefanberger** [comment]
Thanks for reporting this. If the problem is solved, please close the issue.

**Comment by pohly** [comment]
Looks good to me.
