### ISSUE TITLE
Unable to integrate SWTPM with qemu ARM v7 (vexpress-a9) machine.

### ISSUE THREAD

**Issue by Harshavardhanvalluri** [stefanberger/swtpm#561]
I'm trying to integrate SWTPM with qemu for vexpress-a9 machine, I'm getting the following error when I start the machine.

**ERROR**
qemu-system-arm -M vexpress-a9 -smp 1 -m 256 -kernel zImage -dtb vexpress-v2p-ca9.dtb -drive file=rootfs.ext2,if=sd,format=raw -append "console=ttyAMA0,115200 rootwait root=/dev/mmcblk0"  -net nic,model=lan9118 -net user  -chardev socket,id=chrtpm,path=/tmp/emulated_tpm/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis-device,tpmdev=tpm0 -nographic
pulseaudio: set_sink_input_volume() failed
pulseaudio: Reason: Invalid argument
pulseaudio: set_sink_input_mute() failed
pulseaudio: Reason: Invalid argument
qemu-system-arm: Option '-device tpm-tis-device' cannot be handled by this machine

But when I check the device support list it displays tpm-tis-device is supported.

To confirm I have tested the SWTPM with x86 machine using the following method : Ref link : https://tpm2-software.github.io/2020/10/19/TPM2-Device-Emulation-With-QEMU.html. There it display /dev/tpm* as expected.

Please let me know if qemu ARM vexpress-a9 guest machine supports SWTPM emulator. If not what is the alternate method that can be used to emulate TPM for vexpress-a9 guest machine.

**Comment by stefanberger** [comment]
This post here describes a way to get vTPM and QEMU started: https://github.com/stefanberger/swtpm/issues/493#issuecomment-885221109

**Comment by stefanberger** [comment]
> qemu-system-arm: Option '-device tpm-tis-device' cannot be handled by this machine

Maybe that's related to this machine `vexpress-a9` and it's not working in this case, possibly related to the bus that the device is using.

**Comment by Harshavardhanvalluri** [comment]
Hi @stefanberger

Thanks for immediate response.

I have tried the above mentioned method https://github.com/stefanberger/swtpm/issues/493#issuecomment-885221109, it works fine there.  So I have tried the below command to boot the vexpress-a9 machine in virt machine mode using the following command. 

COMMAND : qemu-system-arm \
                      -M virt -m 256 -nographic -smp 1 -kernel ./zImage \
                      -append "rootwait root=/dev/vda console=ttyAMA0" \
                      -netdev user,id=eth0 -device virtio-net-device,netdev=eth0 \
                      -drive file=rootfs.ext2,if=none,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 \
                      -chardev socket,id=chrtpm,path=/tmp/emulated_tpm/swtpm-sock \
                      -tpmdev emulator,id=tpm0,chardev=chrtpm \
                      -device tpm-tis-device,tpmdev=tpm0 -no-acpi

After using this command the virt machine starts with v7 CPU without displaying any error. But later it does not populate the /dev/tpm* after boot up. Can you please let me know what might be the reason.

**Comment by stefanberger** [comment]
I am not doing much with ARM ... Is the tpm_tis driver active or built into the kernel?

What does `lsmod | grep tpm` show?
What does `dmesg | grep -i tpm` show?
Does `sudo modprobe tpm_tis` do anything?
Is the tpm_tis built into the kernel? `sudo cat /proc/kallsyms | grep tpm_tis`

**Comment by Harshavardhanvalluri** [comment]
Hi @stefanberger ,

I'm able to integrate SWTPM emulator with QEMU for ARM v7 CPU. After comparing the kernel config of aarch64 machine and vexpress machine .I found out that the issue was tpm-tis driver in kernel is not enable. After enabling the driver in the kernel I was able to see the following devices populated :
root@am335x-evm:~# ls -l /dev/tpm*
crw-------    1 root     root       10, 224 Jan  1  1970 /dev/tpm0
crw-------    1 root     root      253, 65536 Jan  1  1970 /dev/tpmrm0

Thanks for the support @stefanberger

**Comment by stefanberger** [comment]
good to hear!
