### ISSUE TITLE
swtpm master: fails to build with libtpms master

### ISSUE THREAD

**Issue by pohly** [stefanberger/swtpm#57]
Commit f1389afb87767caf7aea108593337acf41d7f106 starts using TPMLIB_TPMVersion, which is not yet in libtpms master (was added later, for the TPM2 preview code).

Should that particular commit perhaps get reverted on the master branch and be added back specifically on the TPM2 preview branch?

**Comment by stefanberger** [comment]
If we just remove the switch statement and re-introduce for the tpm2-preview branch, that should be enough. I'll fix it.

**Comment by stefanberger** [comment]
https://github.com/stefanberger/swtpm/commit/4f4f2f0a7e3195f6df8d235d58630a08e69403d8 should fix this now.

**Comment by stefanberger** [comment]
Thanks for reporting this. If the problem is solved, please close the issue.

**Comment by pohly** [comment]
Yes, that fixes it.
