### ISSUE TITLE
Cant install on POP OS 21.04

### ISSUE THREAD

**Issue by andersonrochabh** [stefanberger/swtpm#584]
Hi Stefanberger!

I'am trying install the swtpm but the test fail: "**FAIL: test_commandline**"

**FAIL: test_commandline**
======================

Test 1 failed: TPM did not open port 11234
**FAIL test_commandline (exit status: 1)**

**test-suite.log:**

=======================================
   swtpm 0.7.0: tests/test-suite.log
=======================================

# TOTAL: 67
# PASS:  59
# SKIP:  7
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_commandline
======================

Test 1 failed: TPM did not open port 11234
FAIL test_commandline (exit status: 1)

SKIP: test_tpm12
================

SKIP test_tpm12 (exit status: 77)

SKIP: test_tpm2_save_load_state_2
=================================

SWTPM_TEST_IBMTSS2 must be set to run this test.
SKIP test_tpm2_save_load_state_2 (exit status: 77)

SKIP: test_tpm2_save_load_state_2_linear
========================================

SWTPM_TEST_IBMTSS2 must be set to run this test.
SKIP test_tpm2_save_load_state_2_linear (exit status: 77)

SKIP: test_tpm2_save_load_state_2_block
=======================================

SWTPM_TEST_IBMTSS2 must be set to run this test.
SKIP test_tpm2_save_load_state_2_block (exit status: 77)

SKIP: test_tpm2_save_load_state_3
=================================

SWTPM_TEST_IBMTSS2 must be set to run this test.
SKIP test_tpm2_save_load_state_3 (exit status: 77)

SKIP: test_tpm2_ibmtss2
=======================

SKIP test_tpm2_ibmtss2 (exit status: 77)

SKIP: test_samples_create_tpmca
===============================

Could not find tpmtool in PATH
SKIP test_samples_create_tpmca (exit status: 77)

**Comment by stefanberger** [comment]
Please run the test again. Otherwise please post the `tests/test_commandline.log`

**Comment by stefanberger** [comment]
A guess would be that something else is using that port.

```
 sudo netstat -napt | grep 11234
```

**Comment by stefanberger** [comment]
You can try to still `make install` swtpm even though this one test doesn't work hoping that it will not affect anything that you do with it after.
