### ISSUE TITLE
swtpm make error when using libtpms-tpm2-preview.rev142 and .rev146

### ISSUE THREAD

**Issue by acmer29** [stefanberger/swtpm#59]
I got a error in making swtpm after using new libtpms. The terminal output is below:
```
ctrlchannel.c: In function ‘ctrlchannel_process_fd’:
ctrlchannel.c:785:22: error: implicit declaration of function ‘TPMLIB_SetBufferSize’; did you mean ‘TPMLIB_GetVersion’? [-Werror=implicit-function-declaration]
         buffersize = TPMLIB_SetBufferSize(buffersize,
                      ^~~~~~~~~~~~~~~~~~~~
                      TPMLIB_GetVersion
cc1: all warnings being treated as errors
Makefile:663: recipe for target 'libswtpm_libtpms_la-ctrlchannel.lo' failed
make[3]: *** [libswtpm_libtpms_la-ctrlchannel.lo] Error 1
```
I got this error in using libtpms-tpm2-preview.rev142 as well as libtpms-tpm2-preview.rev146.

**Comment by stefanberger** [comment]
You will need libtpms/tpm2-preview.rev146 for this. Did you run a `make install` after buidling it? Once that is done /usr/include/libtpms/tpm_library.h should look like this around line 144:
```

uint32_t TPMLIB_SetBufferSize(uint32_t wanted_size,
                              uint32_t *min_size,
                              uint32_t *max_size);
```

**Comment by acmer29** [comment]
Thank you for your immediate reply, it seems that I forget to add 'prefix=/usr' when running ./configure in using libtpms/tpm2-preview.rev146, the problem is fixed.

**Comment by stefanberger** [comment]
Now you may have to clean up duplicate installs on your system from the one without `--prefix=/usr`.
