### ISSUE TITLE
failed to build rpm package

### ISSUE THREAD

**Issue by bettswang123** [stefanberger/swtpm#591]
**Describe the bug**
I git clone this master project. I want to build an rpm package,but failed.
when I run 'rpmbuild -ta swtpm-*.tar.gz' , It return to me like this :

----------------------------------------------------------------------------------
swtpm_setup.c:1178:31: note: 'swtpm_has_tpm2' was declared here
     gboolean swtpm_has_tpm12, swtpm_has_tpm2;
                               ^~~~~~~~~~~~~~
swtpm_setup.c:1019:5: error: 'swtpm_has_tpm12' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     printf("{ \"type\": \"swtpm_setup\", "
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            "\"features\": [ %s%s\"cmdarg-keyfile-fd\", \"cmdarg-pwdfile-fd\", \"tpm12-not-need-root\""
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            ", \"cmdarg-write-ek-cert-files\", \"cmdarg-create-config-files\""
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            "%s ], **"**
            ~~~~~~~~
            "\"version\": \"" VERSION "\" "
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            "}\n",
            ~~~~~~
            swtpm_has_tpm12 ? "\"tpm-1.2\", " : "",
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            swtpm_has_tpm2  ? "\"tpm-2.0\", " : "",
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            param);
            ~~~~~~
-------------------------------------------------------------------------------------------------------------------------------- 

**To Reproduce**
Steps to reproduce the behavior:
1. git clone https://github.com/stefanberger/swtpm.git
2. cd swtpm/
3. dnf builddep swtpm.spec
4. ./autogen.sh
5. make dist
6. rpmbuild -ta swtpm-*.tar.gz

**Expected behavior**
A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**
 - OS:  CentOS
 - Version: 8.4

**Versions of relevant components**
- swtpm: master
- libtpms: 0.8.6
- openssl: 1.1.1g
- gcc: 8.4.1
- make: 4.2.1
- rpmbuild: 4.4.13

**Comment by stefanberger** [comment]
Thanks for this bug report. PR #593 should fix it.

**Comment by stefanberger** [comment]
I merged that PR Into master now. Please try it.

**Comment by bettswang123** [comment]
I have a new issue, when I run "rpmbuild -ta swtpm-*.tar.gz". There are some errors or warnings in the rpm-build process.

**Here they are:**
/usr/share/selinux/devel/include/services/container.if:13: Error: duplicate definition of container_runtime_domtrans(). Original definition on 13.
/usr/share/selinux/devel/include/services/container.if:40: Error: duplicate definition of container_runtime_run(). Original definition on 40.
/usr/share/selinux/devel/include/services/container.if:61: Error: duplicate definition of container_runtime_exec(). Original definition on 61.
...
...
/usr/share/selinux/devel/include/services/container.if:13: Error: duplicate definition of container_runtime_domtrans(). Original definition on 13.
/usr/share/selinux/devel/include/services/container.if:40: Error: duplicate definition of container_runtime_run(). Original definition on 40.
/usr/share/selinux/devel/include/services/container.if:61: Error: duplicate definition of container_runtime_exec(). Original definition on 61.
/usr/share/selinux/devel/include/services/container.if:80: Error: duplicate definition of container_read_state(). Original definition on 80.
...
...
libtool: warning: 'libswtpm_libtpms.la' has not been installed in '/usr/lib64/swtpm'
...
libtool: warning: remember to run 'libtool --finish /usr/lib64/swtpm'
...
FAIL: test_tpm2_file_permissions
...
Testsuite summary for swtpm 0.7.0
============================================================================
# TOTAL: 69
# PASS:  57
# SKIP:  11
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[3]: *** [Makefile:732: test-suite.log] Error 1
make[3]: Leaving directory '/root/rpmbuild/BUILD/swtpm-0.7.0/tests'
make[2]: *** [Makefile:840: check-TESTS] Error 2
make[2]: Leaving directory '/root/rpmbuild/BUILD/swtpm-0.7.0/tests'
make[1]: *** [Makefile:1376: check-am] Error 2
make[1]: Leaving directory '/root/rpmbuild/BUILD/swtpm-0.7.0/tests'
make: *** [Makefile:476: check-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.aInz31 (%check)

**Comment by stefanberger** [comment]
Can you close this issue?
