### ISSUE TITLE
Cannot run swtpm on Ubuntu 21.04

### ISSUE THREAD

**Issue by mvivarelli** [stefanberger/swtpm#592]
Because binary for swtmp are not available for 21.04 i followed yuor wiki "Compile on Ubuntu (21.04)"
Despite some warnings I was able to compile and install.
Then I followed https://getlabsdone.com/how-to-install-windows-11-on-kvm/ and built the VM
When I started the VM I got an error in starting swtmp.
Looking at the logfile I found:
"Could not find certtool in PATH"
Looking at the source code I found the problem and corrected "just for me" setting the absolute path of the tool
You can see this in the image attached.
After that I recompile and now I'm happily running Win 11.

Maurizio
![swtpm](https://user-images.githubusercontent.com/30519989/137472076-e8fb4c3b-ff3e-4be8-b561-f00d3e7fd8b3.png)

**Comment by stefanberger** [comment]
> could the problem be related to the user the script run under?

I don't see why this would be a problem. What is the $PATH of the user? Does it not include /usr/bin or /bin?

**Comment by stefanberger** [comment]
Has this issue been resolved in the meantime?

**Comment by mvivarelli** [comment]
Hi Stefan,

a few days ago I installed SWTPM on a fresh Ubuntu 21.10 partition and
it worked out of the box

so maybe that was a problem of my previous 21.04 installation

Regards

Maurizio

-----Original Message-----
From: Stefan Berger ***@***.***>
Reply-To: stefanberger/swtpm
***@***.***>
To: stefanberger/swtpm ***@***.***>
Cc: mvivarelli ***@***.***>, Author ***@***.***>
Subject: Re: [stefanberger/swtpm] Cannot run swtpm on Ubuntu 21.04
(#592)
Date: Thu, 16 Dec 2021 05:25:12 -0800

Has this issue been resolved in the meantime?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mvivarelli** [comment]
yes
