### ISSUE TITLE
Replace tpm private key 

### ISSUE THREAD

**Issue by yingkailiang** [stefanberger/swtpm#6]
Hi, 

I know in real TPM, the private key is sit inside TPM. I am wondering for the software emulated TPM, is the private key also hard coded inside swtpm source code or swtpm will randomly generate a new private key everytime the swtpm is installed? 
Can I dump out the private key somewhere from my machine after I setup the swtpm? Or can I dump out the private key in swtpm source code?

Because I want to design a lab task for graduate students to understand private key sit inside TPM and somehow replace with a new private key. I am not sure whether it is doable with the software emulated TPM.

Thanks in advance for any suggestion

**Comment by stefanberger** [comment]
I supposed you would want to dump the endorsement key? There's no predefined way of doing that using an exposed API call or something like that. However, the swtpm will write the permanent state into a file and the permanent state contains the endorsement key. You would have to reverse engineer that file format to find the key.

**Comment by yingkailiang** [comment]
Thanks for your reply.
Where is the file which contains permanent state is located? And what is the name of that file?

**Comment by stefanberger** [comment]
When you pass --tpmstate dir=<path> as option to 'swtpm' for example then that file will <path>/tpm-00.permall

**Comment by yingkailiang** [comment]
I got it and thanks for your reply.

**Comment by marcoguerri** [comment]
In case it might be useful for somebody else in the future, I wanted to do exactly this, extract private portion of Endorsement Key from state file. I put up some code and documentation on how to do this in https://github.com/marcoguerri/swtpm-env/tree/main/ek.
