### ISSUE TITLE
not able to install qemu_tpm to run swtpm

### ISSUE THREAD

**Issue by abhijitSingh86** [stefanberger/swtpm#60]
Hello Stefan,
I am trying to install the swtpm, I did all the installation but qemu_tpm is throwing an error with ucontext structure. I am using ubuntu 17.10.
 Please mention which branch to use for tpm2.0 for qemu-tpm. For libtpm and swtpm I did it from correct br.
Also, what are the default authorization values in created TPM, I have one installation present which is a bit old with swtpm and in that, I am not able to clear the TPM with PLATFORM auth with a blank password.

**Comment by stefanberger** [comment]
For libtpms use branch tpm2-preview.rev146. For swtpm use branch tpm2-preview. For QEMU please use the upstream repository or the tpm-next branch of my qemu-tpm git repo.

Are you using QEMU with SeaBIOS? In SeaBIOS we change the ownership of the PLATFORM auth and set it to a random password in the firmware.

**Comment by stefanberger** [comment]
The reason why we are changing the PLATFORM auth can be found in this document here: https://trustedcomputinggroup.org/wp-content/uploads/PC-ClientSpecific_Platform_Profile_for_TPM_2p0_Systems_v51.pdf 

Section 10: "If  the  TPM  is  visible, Platform Firmware  MUST  change  platformAuth  to  a  random value  prior  to  executing  3rd party  code,  e.g.  non - manufacturer controlled UEFI applications."

**Comment by abhijitSingh86** [comment]
Thanks for your reply. 
I will check the qemu master branch installation and will update you.
I have one more silly question, Whenever I am trying to access the /dev/tpm0 in my guest machine I need to use sudo. For commands its not a problem, but with programs which internally invoke another program passing sudo is not feasible. Is it possible to get access to the device without sudo. Meanwhile I am searching on internet if i get a fix, I will update this question.

**Comment by stefanberger** [comment]
If you cannot use the code without sudo and it refuses to run when started as a normal user, then it may need high privileges for some reason.

**Comment by abhijitSingh86** [comment]
Yes, I guessed the same but I have a use case to execute. I am using a c program and using the API from TSS stack and invoking the OpenSSL engine to perform the operation using TPM. The problem my application written in C works fine with sudo, the problem is with OpenSSL engine which is loaded by code and it doesn't get the sudo privilege.

**Comment by abhijitSingh86** [comment]
Hello Stefan,
I have installed the master branch from qemu source, but I am still not able to mount the vTpm. below are some trial commands
qemu-system-x86_64 --enable-kvm  -m 4048 -smp 2 -boot d -bios bios.bin -boot menu=on -tpmdev cuse-tpm,id=tpm1,path=/dev/vtpm0 -device tpm-tis,tpmdev=tpm1 -hda ubuntu.qcow2
qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm1,path=/dev/vtpm0: Parameter 'type' expects a TPM backend type
Supported TPM types (choose only one):
 passthrough   Passthrough TPM backend driver
    emulator   TPM emulator backend driver

qemu-system-x86_64 --enable-kvm  -m 4048 -smp 2 -boot d -bios bios.bin -boot menu=on -tpmdev cuse-tpm,id=tpm1,path=/dev/vtpm0,type=emulator -device tpm-tis,tpmdev=tpm1 -hda ubuntu.qcow2
qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm1,path=/dev/vtpm0,type=emulator: Invalid parameter 'path'

qemu-system-x86_64 --enable-kvm  -m 4048 -smp 2 -boot d -bios bios.bin -boot menu=on -tpmdev cuse-tpm,id=tpm1,path=/dev/vtpm0,type=passthrough -device tpm-tis,tpmdev=tpm1 -hda ubuntu.qcow2
qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm1,path=/dev/vtpm0,type=passthrough: tpm_passthrough: Could not guess TPM cancel path

**Comment by stefanberger** [comment]
There's no cuse-tpm upstream.

Have a look at this document starting at line 156: https://github.com/qemu/qemu/blob/master/docs/specs/tpm.txt

**Comment by abhijitSingh86** [comment]
Thanks :)

**Comment by abhijitSingh86** [comment]
Final Script

mkdir /tmp/mytpm1
swtpm socket --tpmstate dir=/tmp/mytpm1 --tpm2   --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock   --log level=20 &

qemu-system-x86_64 -smp 2  --enable-kvm   -m 1024 -boot d -bios bios.bin -boot menu=on   -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock   -tpmdev emulator,id=tpm0,chardev=chrtpm   -device tpm-tis,tpmdev=tpm0 ubuntuBackup.qcow2
