### ISSUE TITLE
Enabling SHA512 in TPM 2 will break compatibility

### ISSUE THREAD

**Issue by stefanberger** [stefanberger/swtpm#62]
I updated the TPM 2 code and it can be compiled with TPM 2 support now. However, enabling this would break backwards compatibility since previous state did not write SHA512 related data and thus the TPM 2 would not initialize. TPM 2 is currently in 'preview' and I think if we ever wanted to enable it, we have to do it now, because later on it cannot be done anymore.

Thoughts?

**Comment by stefanberger** [comment]
I applied the patch enabling SHA512 yesterday.

**Comment by ricardoas** [comment]
Hi!
I noticed today it stopped working with https://github.com/tpm2-software/tpm2-tss (tried the last two rc)... but I'm still figuring out if this is related. Until now, I saw that `tpm2_pcrlist` was affected....

**Comment by stefanberger** [comment]
@ricardoas Not sure what you mean by 'affected'. tpm2_pcrlist works fine for me on Fedora 28 with all 4 PCR banks (sha1,256,384,512). I have tpm2-tools-3.0.3-3 installed there. Maybe an older version of these tools cannot deal with that many PCR banks.

**Comment by ricardoas** [comment]
I compiled:
* https://github.com/tpm2-software/tpm2-tools from master
* https://github.com/tpm2-software/tpm2-abrmd from master too and
* https://github.com/tpm2-software/tpm2-tss/releases/tag/2.0.0_rc2

This combination worked fine with https://github.com/stefanberger/libtpms/commit/8371a4f4cd5efcd5565e14916c0956a86bf5ea62 and https://github.com/stefanberger/swtpm/commit/643eff62f078f8f1e4fae921c6691f6f81bf3459

but when I recompile libtpms with https://github.com/stefanberger/libtpms/commit/37f24d5c7b3513045abcc4a0d283b9f25b75d039 I got the error below on tpm2_pcrlist:

When I ran tpm2_pcrlist I got:

```
WARNING:marshal:src/tss2-mu/tpml-types.c:197:Tss2_MU_TPML_PCR_SELECTION_Unmarshal() count too big
ERROR: Tss2_Sys_GetCapability(0x80011) - sys:Response is malformed
ERROR: Unable to run tpm2_pcrlist
```

I have not tried tpm2-tools 3.0.3 nor 3.0.4, only compiling directly from master, and it was fine until now.

**Comment by ricardoas** [comment]
I asked for help in [tpm2-tools list](https://lists.01.org/pipermail/tpm2/2018-May/000680.html) and they suspect it is something on the tools side... I'm adding more details [here](https://github.com/tpm2-software/tpm2-tools/issues/1021).

I'm sorry for bothering you!
