### ISSUE TITLE
SELinux module lacking few rules

### ISSUE THREAD

**Issue by kkaarreell** [stefanberger/swtpm#632]
**Describe the bug**

I am using custom systemd unit file to start swtpm (not using qemu/libvirt scenario). Having that, I have noticed some AVCs suggesting that the SELinux module could be extended. I am running Fedora34 and Fedora35.

Below you can find the unit file I am using for testing purposes.

```
[Unit]
Description=swtpm TPM Software emulator

[Service]
Type=fork
ExecStartPre=/usr/bin/mkdir -p /var/lib/tpm/swtpm
ExecStartPre=/usr/bin/swtpm_setup --tpm-state /var/lib/tpm/swtpm --createek --decryption --create-ek-cert --create-platform-cert --lock-nvram --overwrite --display --tpm2
ExecStart=/usr/bin/swtpm socket --tpmstate dir=/var/lib/tpm/swtpm --log level=4 --ctrl type=tcp,port=2322 --server type=tcp,port=2321 --flags startup-clear --tpm2

[Install]
WantedBy=multi-user.target

```

At first, I have allowed transition from `init_t` domain to `swtpm_t` so that `swtpm` command can be started by systemd properly.
I did this by adding 
```
init_daemon_domain(swtpm_t, swtpm_exec_t)
```
Additionally, since swtpm is communicating using TCP I had to allow listening on tcp_socket and binding to an unreserved port (I am using ports 2321 and 2322). 
```
allow swtpm_t self:tcp_socket { accept listen };
allow swtpm_t unreserved_port_t:tcp_socket name_bind;
```
Instead of allowing unreserved ports the policy could define and allow connection to `swtpm_port_t` which one could then assign to specific port numbers.

Finally, I do not see any rule allowing `swtpm_t` to write files related to `--tpm-state` destination. I am using `/var/lib/tmp` in my setup which has type `tcsd_var_lib_t`. Hence 
```
allow swtpm_t tcsd_var_lib_t:dir { add_name remove_name write };
allow swtpm_t tcsd_var_lib_t:file { create getattr lock open read rename setattr unlink write };
```
Maybe not something one would always use but I assume there should be some preferred location where write access is allowed.

Disclaimer: I am not SELinux expert, my approach can be wrong.

**To Reproduce**
1. use unit file provided above (or similar) to start swtpm
2. notice that swtpm runs in `init_t` domain since domain transition is not allowed
3. even when running as `swtpm_t` there are AVCs due to a setup used

**Expected behavior**
No AVCs, systemd can start swtpm through unit file, listening on tcp port is allowed

**Desktop (please complete the following information):**
 - OS:  Fedora
 - Version 34, 35

**Versions of relevant components**
- swtpm:  swtpm-0.6.0-3.20210607gitea627b3.fc35, swtpm-0.6.0-1.20210607gitea627b3.fc34
- libtpms: libtpms-0.9.0-0.20211004gitdc4e3f6313.fc35.0 , libtpms-0.8.6-0.20210910git7a4d46a119.fc34.0.

**Log files**

AVC denials while running in permissive mode:
```
# ausearch -m avc
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.852:545): avc:  denied  { name_bind } for  pid=19490 comm="swtpm" src=2322 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.852:546): avc:  denied  { listen } for  pid=19490 comm="swtpm" laddr=127.0.0.1 lport=2322 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:system_r:swtpm_t:s0 tclass=tcp_socket permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.852:547): avc:  denied  { write } for  pid=19490 comm="swtpm" name=".lock" dev="vda1" ino=264785 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.853:548): avc:  denied  { open } for  pid=19490 comm="swtpm" path="/var/lib/tpm/swtpm/.lock" dev="vda1" ino=264785 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.853:549): avc:  denied  { lock } for  pid=19490 comm="swtpm" path="/var/lib/tpm/swtpm/.lock" dev="vda1" ino=264785 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.853:550): avc:  denied  { read } for  pid=19490 comm="swtpm" name="tpm2-00.permall" dev="vda1" ino=264793 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.853:551): avc:  denied  { setattr } for  pid=19490 comm="swtpm" name="tpm2-00.permall" dev="vda1" ino=264793 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.854:552): avc:  denied  { getattr } for  pid=19490 comm="swtpm" path="/var/lib/tpm/swtpm/tpm2-00.permall" dev="vda1" ino=264793 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.855:553): avc:  denied  { write } for  pid=19490 comm="swtpm" name="swtpm" dev="vda1" ino=264783 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=dir permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.856:554): avc:  denied  { add_name } for  pid=19490 comm="swtpm" name="TMP2-00.permall" scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=dir permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.856:555): avc:  denied  { create } for  pid=19490 comm="swtpm" name="TMP2-00.permall" scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.856:556): avc:  denied  { remove_name } for  pid=19490 comm="swtpm" name="TMP2-00.permall" dev="vda1" ino=264784 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=dir permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.856:557): avc:  denied  { rename } for  pid=19490 comm="swtpm" name="TMP2-00.permall" dev="vda1" ino=264784 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:38 2021
type=AVC msg=audit(1636664438.856:558): avc:  denied  { unlink } for  pid=19490 comm="swtpm" name="tpm2-00.permall" dev="vda1" ino=264793 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:object_r:tcsd_var_lib_t:s0 tclass=file permissive=1
----
time->Thu Nov 11 16:00:39 2021
type=AVC msg=audit(1636664439.027:560): avc:  denied  { accept } for  pid=19490 comm="swtpm" laddr=127.0.0.1 lport=2321 scontext=system_u:system_r:swtpm_t:s0 tcontext=system_u:system_r:swtpm_t:s0 tclass=tcp_socket permissive=1
```

**Comment by stefanberger** [comment]
We currently have [swtpm_svirt.te](https://github.com/stefanberger/swtpm/blob/master/src/selinux/swtpm_svirt.te) for the libvirt use case. I think we should not put the rules you need into this policy... it feels like we would possibly soften this policy unnecessarily. And then someone else may come up with different labels than `tcsd_var_lib_t` than what you seem to be using. That said, my guess is there should be a different policy.
```
allow swtpm_t tcsd_var_lib_t:dir { add_name remove_name write };
allow swtpm_t tcsd_var_lib_t:file { create getattr lock open read rename setattr unlink write };
```

What is your use case?

**Comment by kkaarreell** [comment]
I am not suggesting to update swtpm_svirt.te selinux module. As said above, I am not using the qemu/libvirt setup. I am using swtpm to emulate TPM directly on a running (tested) system and also I am using tpm2-abrmd to talk to swtpm. I am using this system setup while testing keylime (remote attestation).
You can find my configuration task at
https://github.com/RedHat-SP-Security/keylime-tests/blob/swtpm/setup/configure_tpm_emulator/test.sh#L59
Btw, not to get confused, in my configuration task I am running swtpm in a permissive domain and dontauditing AVCs since swtpm is no my concern in the test itself.

**Comment by kkaarreell** [comment]
> ```
> allow swtpm_t tcsd_var_lib_t:dir { add_name remove_name write };
> allow swtpm_t tcsd_var_lib_t:file { create getattr lock open read rename setattr unlink write };
> ```
> What is your use case?

In this specific case I am using /var/lib/tpm directory. I do not have extra reason to use this one and I am not suggesting to allow the access. My point was that if swtpm running as `swtpm_t` is supposed to store runtime data (like lockfile) at some (preferred?) location it should be allowed to write there. I do not suggest any particular location, I am just wondering that there is no such selinux rule in the swtpm.te policy. What is the common/suggested location for `--tpm-state`?

**Comment by stefanberger** [comment]
> I do not suggest any particular location, I am just wondering that there is no such selinux rule in the swtpm.te policy. What is the common/suggested location for `--tpm-state`?

In the libvirt scenario the location is labeled by libvirt matching the label radomly generated by libvirt in the domain XML:
```
  <seclabel type='dynamic' model='selinux' relabel='yes'>
    <label>system_u:system_r:svirt_t:s0:c43,c638</label>
    <imagelabel>system_u:object_r:svirt_image_t:s0:c43,c638</imagelabel>
  </seclabel>
```

```
# pwd
/var/lib/libvirt/swtpm/7f1889f5-bf19-4a29-b03e-21710573321d/tpm2
# ls -lZ .
total 8
-rw-------. 1 tss tss system_u:object_r:svirt_image_t:s0:c43,c638 6125 Nov  5 07:35 tpm2-00.permall
```

You can then find this process here:

```
# ps auxZ | grep swtpm | grep c638
system_u:system_r:svirt_t:s0:c43,c638 tss 926267  0.0  0.0   9216  3856 ?        Ss   Nov05   0:00 /usr/bin/swtpm socket --daemon [...] --tpmstate dir=/var/lib/libvirt/swtpm/7f1889f5-bf19-4a29-b03e-21710573321d/tpm2,mode=0600 [...]
[...]
```

**Comment by kkaarreell** [comment]
And what would be the location for the non-libvirt scenario?

**Comment by stefanberger** [comment]
> And what would be the location for the non-libvirt scenario?

Every user gets to decide...

**Comment by stefanberger** [comment]
If you have some SELinux related rules to add to the policy , please send me a PR. Other we just close this issue.
