### ISSUE TITLE
--key options for swtpm

### ISSUE THREAD

**Issue by dwaraka1982** [stefanberger/swtpm#638]
We are using TPM2.0 by starting the "swtpm" using one of the below options

--key file=

--key pwdfile=

Both these keys including the migration key is AES. Do we have any option to start the swtpm using a asymmetric key like RSA or only AES is supported for now ?

**Comment by stefanberger** [comment]
Only symmetric keys are supported.

**Comment by dwaraka1982** [comment]
Ok thanks for the confirmation, i will close this issue now..
