### ISSUE TITLE
Could not find swtpm_cert in PATH when trying to create a Win 11 VM in KVM/QEMU (Pop!_OS 21.10)

### ISSUE THREAD

**Issue by exoric-the-fox** [stefanberger/swtpm#643]
**Describe the bug**

Hello,
I am unable to create a Windows 11 VM using TPM 2.0 in virt-manager using KVM/QEMU.
When creating the VM, I am prompted : "Unable to complete install: 'internal error: Could not run '/usr/bin/swtpm_setup'. exitstatus: 1; Check error log '/var/log/swtpm/libvirt/qemu/win11-swtpm.log' for details."

That swtpm log says "Could not find swtpm_cert in PATH.". (See full attached log file for details)

**To Reproduce**

1. Download and compile libtmps and swtpm
2. Create a new VM in kvm/qemu using virt-manager and attach the official Windows 11 ISO
3. Add a TPM2.0 software emulated CRB mode device to the virtual machine
4. Try to run the virtual machine

**Expected behavior**
The VM was expected to be able to emulate TPM 2.0 and start.

**Desktop :**
 - OS: Pop!_OS 
 - Version : 21.10

**Versions of relevant components**
- swtpm: 0.8.0
- libtpms: master
- openssl: 1.1.1l
- gnutls: 3.7.1

**Log files**

swtpm log file :
[win11-swtpm.log](https://github.com/stefanberger/swtpm/files/7920605/win11-swtpm.log)

**What I tried**

-Added read/write perm to everyone for the /var/lib/swtpm-localca directory, I was then able to use swtpm_setup --create-config-files.
-swtpm_setup --create-config-files : It generated the files but unfortunately it didn't solve the issue.

**Comment by stefanberger** [comment]
What is the output of `which swtpm_cert` on your system?

Can you run your configure line again and paste the full output here? Maybe swtpm_cert was not compiled.

**Comment by exoric-the-fox** [comment]
Hi stefan, 

You were right, swtpm_cert was not being compiled.
I tried to go too fast the first time and forgot to install some dependencies, anyway I installed them, recompiled everything and it works now ! Thanks for your time !

**For anyone that might have the same issue in the future :** Please make sure you installed every dependencies stated in the 'INSTALL'  guide file.
