### ISSUE TITLE
undefined reference to 'TPMLIB_GetInfo' and 'TPMLIB_SetState'

### ISSUE THREAD

**Issue by lm-bhaskins** [stefanberger/swtpm#65]
I need to build a version of swtpm that supports TPM2. I am using using the swtpm-tpm2-preview.v2 branch from today. As far as libtpms, I am using the libtpms-tpm2-preview.rev146.v2 branch from today. The following error is occurring when I am trying to do a compile/build:

`libtool: link: gcc -I../../include -I../../include/swtpm -fstack-protector-strong -Wstack-protector -Wl,-z -Wl,relro -Wl,-z -Wl,now -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse -DHAVE_SWTPM_CUSE_MAIN -g -O2 -Wreturn-type -Wsign-compare -Wswitch-enum -Wmissing-prototypes -Wall -Werror -Wformat -Wformat-security -o .libs/swtpm swtpm-main.o swtpm-swtpm.o swtpm-swtpm_chardev.o swtpm-cuse_tpm.o -pthread -pthread  -L/os/files/swtpm-tpm2-preview.v2/src/swtpm/.libs /os/files/swtpm-tpm2-preview.v2/src/swtpm/.libs/libswtpm_libtpms.so -lfuse -lgthread-2.0 -lglib-2.0 -ltpms -lcrypto -pthread
swtpm-cuse_tpm.o: In function 'ptm_ioctl':
/os/files/swtpm-tpm2-preview.v2/src/swtpm/cuse_tpm.c:1211: undefined reference to 'TPMLIB_GetInfo'
/os/files/swtpm-tpm2-preview.v2/src/swtpm/.libs/libswtpm_libtpms.so: undefined reference to 'TPMLIB_SetState'
`

The missing references appear to be defined correctly in the header files.

What am I doing wrong?

**Comment by stefanberger** [comment]
Do you have an older version of libtpms on your system that libtool is trying to link with?

**Comment by lm-bhaskins** [comment]
That was it. I forgot about the libtpms files in /usr/lib64 left by a previous build.
