### ISSUE TITLE
Problem with Ubuntu 22.04 and old version in PPA (0.6.0)

### ISSUE THREAD

**Issue by SferaDev** [stefanberger/swtpm#650]
**Describe the bug**

The version available on the PPA (0.6.0) does not work with Ubuntu 22.04. However, compiling ``master`` 0.8.0 and manually installing it makes it work again. Opening this issue so the PPA is updated for 22.04 before is released as LTS in April.

**To Reproduce**
1. Update to Ubuntu 22.04 Jammy Jellyfish
2. Try to use swtpm with virsh (KVM)

**Desktop:**
 - OS: Ubuntu
 - Version: 22.04

**Log files**

```
Creating root CA and a local CA's signing key and issuer cert.
Could not create root-CA:Can't load ./.rnd into RNG
805B35DCB57F0000:error:12000079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:106:Filename=./.rnd
Cannot write random bytes:
805B35DCB57F0000:error:12000079:random number generator:RAND_write_file:Cannot open file:../crypto/rand/randfile.c:240:Filename=./.rnd

Error creating local CA's signing key and cert.
swtpm-localca exit with status 256:
An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Wed 16 Feb 2022 06:12:07 PM CET
```

**Additional context**
No need to change anything on the code 0.8.0 works just fine but is not available to be installed from the PPA.

**Comment by stefanberger** [comment]
It's here now: https://launchpad.net/~stefanberger/+archive/ubuntu/swtpm-jammy

ppc64el libtpms build failed due to what seems to be a false positive reported by the compiler...

**Comment by SferaDev** [comment]
Thanks @stefanberger
