### ISSUE TITLE
cannot config with static libtpms

### ISSUE THREAD

**Issue by braindevices** [stefanberger/swtpm#661]
**Describe the bug**
If the libtpms is static, the configure cannot recognize it:
```
configure:9999: checking pkg-config is at least version 0.9.0
configure:10002: result: yes
configure:10012: checking for LIBTPMS
configure:10019: $PKG_CONFIG --exists --print-errors "libtpms"
configure:10022: $? = 0
configure:10036: $PKG_CONFIG --exists --print-errors "libtpms"
configure:10039: $? = 0
configure:10079: result: yes
configure:10085: checking for TPMLIB_ChooseTPMVersion in -ltpms
configure:10110: gcc -o conftest -g -O2 -I/tmp/tmp-libroot/include   -L/tmp/tmp-libroot/lib -ltpms conftest.c -ltpms   >&5
/usr/bin/ld: /tmp/tmp-libroot/lib/libtpms.a(libtpms_la-tpm_library.o): in function `TPMLIB_OpenSSL_Base64Decode':
/tmp/libtpms/src/tpm_library.c:319: undefined reference to `BIO_free'
/usr/bin/ld: /tmp/libtpms/src/tpm_library.c:339: undefined reference to `BIO_free_all'
/usr/bin/ld: /tmp/libtpms/src/tpm_library.c:312: undefined reference to `BIO_f_base64'
/usr/bin/ld: /tmp/libtpms/src/tpm_library.c:312: undefined reference to `BIO_new'
/usr/bin/ld: /tmp/libtpms/src/tpm_library.c:317: undefined reference to `BIO_new_mem_buf'
/usr/bin/ld: /tmp/libtpms/src/tpm_library.c:322: undefined reference to `BIO_push'
/usr/bin/ld: /tmp/libtpms/src/tpm_library.c:323: undefined reference to `BIO_set_flags'
/usr/bin/ld: /tmp/libtpms/src/tpm_library.c:331: undefined reference to `BIO_read'
/usr/bin/ld: /tmp/libtpms/src/tpm_library.c:339: undefined reference to `BIO_free_all'
/usr/bin/ld: /tmp/tmp-libroot/lib/libtpms.a(libtpms_tpm12_la-tpm_crypto.o): in function `TPM_OpenSSL_PrintError':
/tmp/libtpms/src/tpm12/tpm_crypto.c:1500: undefined reference to `ERR_get_error_line_data'
...
```
I do not know if this is the problem of libtpms or the swtpm.

**To Reproduce**
1. cd libtpms
2. git checkout v0.9.2
2. ./autogen.sh --with-tmp2 --with-openssl --prefix=/tmp/tmp-libroot --disable-shared
3. make -j4 all
4. make insntall
5. cd ../swtpm
6. git checkout v0.7.1
6. ./autogen.sh

**Expected behavior**
configuration should be ok.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version  20.04

**Versions of relevant components**
- swtpm: 0.7.1
- libtpms: 0.9.2

**Comment by braindevices** [comment]
but I think this is rather a swtpm problem because the symbols definitely exists already:
```
$ readelf -a tmp-libroot/lib/libtpms.a | grep BIO_free
000000000741  004d00000004 R_X86_64_PLT32    0000000000000000 BIO_free - 4
000000000748  004e00000004 R_X86_64_PLT32    0000000000000000 BIO_free_all - 4
00000000087d  004e00000004 R_X86_64_PLT32    0000000000000000 BIO_free_all - 4
    77: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND BIO_free
    78: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND BIO_free_all
```

**Comment by braindevices** [comment]
this can be a tpms problem or a swtpm problem basically it will need `-lssl` and `-lcrypto`, which I think should be define in libtpms.pc

**Comment by braindevices** [comment]
add `LIBS='-lssl -lcrypto'` configure can pass now.  I think the problem is in swtpm configure also. I try to add ssl and crypto in the libtpms.pc file
```
Libs: -L${libdir} -ltpms -lssl -lcrypto
```
But during configure it use:
```
gcc -o conftest -g -O2 -I/tmp/tmp-libroot-static/include   -L/tmp/tmp-libroot-static/lib -ltpms -lssl -lcrypto conftest.c -ltpms 
```
The `configure` use hard coded `LIBS="-ltpms  $LIBS"` instead of LIBS=`$LIBTPMS_LIBS $LIBS`

**Comment by stefanberger** [comment]
Please have a look at https://github.com/stefanberger/swtpm/issues/355 . The issues with static linking are still the same. Distros want swtpm to be linked dynamically.

**Comment by braindevices** [comment]
Nope. Even libtpms I'd static, the swtpms is still be able to dynamically link to crypto and SSL. This is s what I am doing. You just missing required libs in libtpms.pc and the swtpms configure.

**Comment by stefanberger** [comment]
I assigned it the won't fix label now because 

- I don't see it as very useful to link swtpm with a static libtpms especially in case when bugs are fixed in libtpms that shouldn't require and update to swtpm
- I also don't know how to fix it
