### ISSUE TITLE
user swtpm-localca.conf has no effect

### ISSUE THREAD

**Issue by braindevices** [stefanberger/swtpm#662]
**Describe the bug**
according to the man page
>Users may write their own configuration into ${XDG_CONFIG_HOME}/swtpm-localca.conf or if XDG_CONFIG_HOME is not set
> it may be in ${HOME}/.config/swtpm-localca.conf.

However after put the file in `~/.config/swtpm-localca.conf`
```
statedir = ${HOME}/swtpm_localca
signingkey = ${HOME}/swtpm_localca/signkey.pem
issuercert = ${HOME}/swtpm_localca/issuercert.pem
certserial = ${HOME}/swtpm_localca/certserial
```
The swtpm still fail, looking at the log we can see it is still using the /etc/swtpm-localca.conf

I think it is better to describe in the document that the localca conf is actually controlled by `swtpm_setup.conf`'s `create_certs_tool_config`

**To Reproduce**
as above

**Expected behavior**
should pickup the user conf

**Desktop (please complete the following information):**
 - OS:  ubuntu
 - Version 20.04

**Versions of relevant components**
- swtpm: 0.7.1
- libtpms: 0.9.2

```
Successfully created RSA 2048 EK with handle 0x81010001.
  Invoking /usr/bin/swtpm_localca --type ek --ek <key> --dir /tmp/swtpm_setup.certs.<random> --logfile /home/user/.cache/libvirt/qemu/log/test-swtpm.log --vmid test:<uuid> --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /etc/swtpm-localca.conf --optsfile /etc/swtpm-localca.options

```

**Comment by stefanberger** [comment]
Does PR #666 resolve this issue? It should now resolve `${HOME}` as expected.

**Comment by stefanberger** [comment]
There are also PRs #667 and #668 now

**Comment by stefanberger** [comment]
When I use your config file with the broken v0.7.1 and I get the following output when run as non-root users:

```
$ swtpm_setup --tpm2 --tpmstate . HOME--create-ek-cert --overwrite --create-platform-cert
Starting vTPM manufacturing as stefanb:stefanb @ Wed 23 Feb 2022 08:33:19 AM EST
TPM is listening on Unix socket.
Successfully created RSA 2048 EK with handle 0x81010001.
  Invoking /usr/share/swtpm/swtpm-localca --type ek --ek  [...] --dir /tmp/swtpm_setup.certs.8FQVH1 --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /home/stefanb/.config/swtpm-localca.conf --optsfile /home/stefanb/.config/swtpm-localca.options
swtpm-localca: Creating swtpm-localca dir '${HOME}/.config/var/lib/swtpm-localca'.
swtpm-localca: Creating root CA and a local CA's signing key and issuer cert.
swtpm-localca: Successfully created EK certificate locally.
  Invoking /usr/share/swtpm/swtpm-localca --type platform --ek [...] --dir /tmp/swtpm_setup.certs.8FQVH1 --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /home/stefanb/.config/swtpm-localca.conf --optsfile /home/stefanb/.config/swtpm-localca.options
```
It has that nasty bug of creating a `${HOME}` directory wherever I start it from but from what I see it uses the signing key it created there.

The output from your swtpm_setup run seems to come from starting it with libvirt. In libvirt there is system and session mode. A user's swtpm configuration is only relevant for session mode and only in this case will it use the user's swtpm_setup configuration files. In system mode it will use root's configuration files. 
Here's a link that explains the differences of these modes in libvirt: https://wiki.libvirt.org/page/FAQ#What_is_the_difference_between_qemu:.2F.2F.2Fsystem_and_qemu:.2F.2F.2Fsession.3F_Which_one_should_I_use.3F

**Comment by stefanberger** [comment]
@braindevices, does the above explanation about libvirt's session mode versus system mode resolve the issue?

**Comment by stefanberger** [comment]
I suppose the issue has been resolved after all this time.
