### ISSUE TITLE
environment varialbe in swtpm-localca.conf is not resolved

### ISSUE THREAD

**Issue by braindevices** [stefanberger/swtpm#663]
**Describe the bug**
the document described:
> Entries may contain environment variables that will be resolved. All environment variables must be formatted like
> this: '${varname}'

However, if we put line in swtpm-localca.conf, swtpm_localca will fail with:
```
Creating swtpm-localca dir '${HOME}/swtpm_localca'.
Could not create directory for 'statedir': Permission denied
swtpm_localca exit with status 1: 
An error occurred. Authoring the TPM state failed.
```

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 20.04

**Versions of relevant components**
- swtpm: 0.7.1
- libtpms: 0.9.2

**Comment by stefanberger** [comment]
Thanks for reporting this issue. Some functionality got lost during the port from python to C. Can you try the code in PR #666 ?
