### ISSUE TITLE
document about swtpm_setup.conf is wrong

### ISSUE THREAD

**Issue by braindevices** [stefanberger/swtpm#664]
**Describe the bug**
> swtpm_setup(8)  
> If this parameter is not provided, the default configuration file will be used. The search order for the
           default configuration file is as follows. If the environment variable XDG_CONFIG_HOME is set,
           ${XDG_CONFIG_HOME}/swtpm_setup.conf will be used if available, otherwise if the environment variable HOME is
           set, ${HOME}/swtpm_setup.conf will be used if available. If none of the previous ones are available,
           /etc/swtpm_setup.conf will be used.

However, the actual location should be `${HOME}/.config/swtpm_setup.conf` as described in `swtpm_setup.conf(8)`

**Versions of relevant components**
- swtpm: 0.7.1

**Comment by stefanberger** [comment]
Please have a look at PR #666.
