### ISSUE TITLE
swtpm --daemon fails with relative path for --tpmstate

### ISSUE THREAD

**Issue by osresearch** [stefanberger/swtpm#671]
**Describe the bug**
Invoking `swtpm --daemon` with a relative path for `--tpmstate dir=./foo` exits successfuly, but when `tpm2-tools` tries to connect to it produces a "`commands not being accepted because of a TPM failure`" error.

**To Reproduce**
This works:
```
swtpm socket \
  --daemon \
  --tpmstate dir=/tmp \
  --server type=unixio,path=/tmp/swtpm-sock \
  --ctrl type=unixio,path=/tmp/tpm-sock.ctrl \
  --flags not-need-init,startup-clear \
  --tpm2
TPM2TOOLS_TCTI=swtpm:path=/tmp/swtpm-sock tpm2 pcrread sha256:0
  sha256:
    0 : 0x0000000000000000000000000000000000000000000000000000000000000000
```
but invoking it with a relative path for the `--tpmstate dir` produces an odd error when invoked with `--daemon`:
```
# mkdir ./tpm-state
# swtpm socket \
  --daemon \
  --tpmstate dir=./tpm-state \
  --server type=unixio,path=/tmp/swtpm-sock \
  --ctrl type=unixio,path=/tmp/tpm-sock.ctrl \
  --flags not-need-init,startup-clear \
  --tpm2
# echo $?
0
# TPM2TOOLS_TCTI=swtpm:path=/tmp/swtpm-sock tpm2 pcrread sha256:0
WARNING:esys:src/tss2-esys/api/Esys_GetCapability.c:303:Esys_GetCapability_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_GetCapability.c:107:Esys_GetCapability() Esys Finish ErrorCode (0x00000101) 
ERROR: Esys_GetCapability(0x101) - tpm:error(2.0): commands not being accepted because of a TPM failure
ERROR: Unable to run pcrread
```

Running it with a relative path and putting it into the background with the shell also works.
```
mkdir ./tpm-state
swtpm socket \
  --tpmstate dir=./tpm-state \
  --server type=unixio,path=/tmp/swtpm-sock \
  --ctrl type=unixio,path=/tmp/tpm-sock.ctrl \
  --flags not-need-init,startup-clear \
  --tpm2 &
[1] 2057740
TPM2TOOLS_TCTI=swtpm:path=./tpm-state/swtpm-sock tpm2 pcrread sha256:0
  sha256:
    0 : 0x0000000000000000000000000000000000000000000000000000000000000000
```

**Expected behavior**
These three invocations should all work.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Versions of relevant components**
- swtpm: 0.7.1
- libtpms: 0.9.1
- openssl: 1.1.1f

**Additional context**

**Comment by stefanberger** [comment]
Thanks for reporting this issue. I had to use the command line with sockets since my installations don't seem to have support for the Unix path in the swtpm tcti, yet. 

```
swtpm socket 
  --tpmstate dir=./tpm-state \
  --tpm2 \
  --ctrl type=tcp,port=2322 \
  --server type=tcp,port=2321 \
  --flags not-need-init,startup-clear \
  --daemon
TPM2TOOLS_TCTI=swtpm:port=2321 tpm2_pcrread sha256:0
```

PR #672 should fix the issue. If you could give it a try that would be helpful.
