### ISSUE TITLE
Compilation fails on macOS

### ISSUE THREAD

**Issue by zanderp25** [stefanberger/swtpm#676]
**Describe the bug**
While installing, i get this error: 
```
cuse_tpm.c:57:10: fatal error: 'fuse/cuse_lowlevel.h' file not found
#include <fuse/cuse_lowlevel.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
i'm not sure how to include that, as i can't install libfuse on mac, but i do have macFuse installed

**To Reproduce**
1. set compiler includes for openssl ( `export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"; export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"` )
2. install libtpms in /usr/local/ (succeeds)
3. ` ./autogen.sh --with-openssl --prefix=/usr/local --with-tss-user=zanderp25 --with-tss-group=zanderp25`
4. make (fails)

**Expected behavior**
Successful compilation

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 12.3

**Versions of relevant components**
- swtpm: [646cf41](https://github.com/stefanberger/swtpm/commit/646cf413b174f8efe2c28562aa4a2163a85528e1)
- libtpms: [bd42b67](https://github.com/stefanberger/libtpms/commit/bd42b67edb977c5b2d042a72f272bd8c029af2b0)
- openssl: 3.0.2
- gnutls: 3.7.4
- ...:

**Log files**
n/a

**Additional context**
n/a

**Comment by stefanberger** [comment]
Please add `--without-cuse` to the `autogen.sh` command line or `configure` command lines.

**Comment by zanderp25** [comment]
That partially worked, now it's giving me this error:
```
ld: library not found for -lgnutls
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by stefanberger** [comment]
Can you post the output of `autogen.sh`?

**Comment by zanderp25** [comment]
[autogen.sh.output.txt](https://github.com/stefanberger/swtpm/files/8318090/autogen.sh.output.txt)

**Comment by stefanberger** [comment]
Does this modification get it to link with gnutls now? 

```
index 66c93c6..6891bf7 100644
--- a/configure.ac
+++ b/configure.ac
@@ -318,7 +318,7 @@ if test "x$with_gnutls" != "xno"; then
     GNUTLS_CFLAGS=$(pkg-config gnutls --cflags)
     CFLAGS="$CFLAGS $GNUTLS_CFLAGS $GNUTLS_LDFLAGS"
     AC_CHECK_LIB([gnutls], [gnutls_load_file], [
-                 GNUTLS_LIBS=-lgnutls
+                 GNUTLS_LIBS=$(pkg-config gnutls --libs)
              ],
              [if test "x$with_gnutls" = "xyes"; then
                  AC_MSG_ERROR([GNUTLS >= 3.1.0 library not found: libgnutls.so])
```

**Comment by stefanberger** [comment]
I had this working on a mac by passing `LDFLAGS="-L/Users/stefanb/homebrew/lib ..." ./configure [...]`. The above change should make this additional LDFLAG unnecessary.

**Comment by zanderp25** [comment]
So just run the `./autogen.sh` without the LDFLAGS using that commit, right?

**Comment by stefanberger** [comment]
You should be able to checkout the master.next branch and at least the GNUTLS liking problem should be solved with it. You can also cherry-pick https://github.com/stefanberger/swtpm/commit/37e661b75956b063a1cc09ff2cf582474fe4b019 .

**Comment by zanderp25** [comment]
hm... new error... 
```
[...]
  "_g_strsplit", referenced from:
      _main in swtpm_localca-swtpm_localca.o
      _split_cmdline in libswtpm_utils.a(libswtpm_utils_la-swtpm_utils.o)
  "_g_strstr_len", referenced from:
      _resolve_string in libswtpm_utils.a(libswtpm_utils_la-swtpm_utils.o)
ld: symbol(s) not found for architecture arm64
```
if i run it through Rosetta it shows this: 
```
[...]
ld: warning: ignoring file /usr/local/lib/libtpms.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
ld: warning: ignoring file /opt/homebrew/opt/openssl@3/lib/libcrypto.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
```

**Comment by stefanberger** [comment]
You are building some files for arm64 and others for x86_64... that cannot work.

g_strsplit is documented here: https://www.manpagez.com/html/glib/glib-2.46.1/glib-String-Utility-Functions.php#g-strsplit
g_strstrlenis documented here: https://www.manpagez.com/html/glib/glib-2.46.1/glib-String-Utility-Functions.php#g-strstr-len

Maybe you need to update the install glib on your system? I have that working on my mac.... so these symbols shouldn't be a problem.

**Comment by stefanberger** [comment]
On my system I have:

```
$ brew list --version glib
glib 2.70.2
```

**Comment by zanderp25** [comment]
I have 2.70.4 apparently
```
❯ brew list --version glib
glib 2.70.4
```

**Comment by stefanberger** [comment]
Try `make clean` followed by `make`. If this doesn't work do

```
git clean -xdf
./autogen.sh --prefix=... [...]
make
make check
```

**Comment by stefanberger** [comment]
I use this command line to configure it (using master.next branch with the fixes at the moment) with openssl 1.1:

```
./autogen.sh \
  --prefix=/Users/stefanb/homebrew \
  --with-tss-user=stefanb \
  --with-tss-grouo=staff \
  CFLAGS=-I/Users/stefanb/homebrew/opt/openssl/include \
  LDFLAGS=-L/Users/stefanb/homebrew/opt/openssl/lib \
  PKG_CONFIG_PATH=/Users/stefanb/homebrew/lib/pkgconfig/
```

**Comment by zanderp25** [comment]
it seems to be complaining about a faulty crypto library now
```
configure: error: Faulty openssl crypto library
```
I'm using a shell script file for the autogen.sh that has this:
```
LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
PKG_CONFIG_PATH=/opt/homebrew/lib/pkgconfig
./autogen.sh \
    --prefix=/usr/local \
    --with-tss-user=zanderp25 \
    --with-tss-group=staff \
    --without-cuse
```
I tried openssl@1.1 as well

**Comment by stefanberger** [comment]
What about using `PKG_CONFIG_PATH=/usr/local/opt/openssl@3/lib/pkgconfig:/opt/homebrew/lib/pkgconfig` .

`brew reinstall openssl@3` tells me to use a specific `PKG_CONFIG_PATH` for openssl 3.0.2.

**Comment by zanderp25** [comment]
That didn’t seem to work...

**Comment by zanderp25** [comment]
Ah... never mind... It seems to have fixed it with `export` lol

**Comment by stefanberger** [comment]
Does it work now ?

**Comment by zanderp25** [comment]
`autogen.sh` seems to be working, but `make`/`ld` is complaining about missing symbols again...

here's the full output: [make.out.txt](https://github.com/stefanberger/swtpm/files/8336767/make.out.txt)

**Comment by stefanberger** [comment]
```
ld: warning: ignoring file /usr/local/lib/libglib-2.0.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/libintl.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

Again, this cannot work with a mix of x86_64 and arm64.

**Comment by zanderp25** [comment]
i'm not sure why it is on x86_64 though

**Comment by zanderp25** [comment]
Update: I deleted all the refrences to the x86_64 files, and it seems to be successful

**Comment by stefanberger** [comment]
> Update: I deleted all the refrences to the x86_64 files, and it seems to be successful

So it compiles and the tests are passing?

**Comment by zanderp25** [comment]
Correct
