### ISSUE TITLE
integer wraparound in tlv functions

### ISSUE THREAD

**Issue by setharnold** [stefanberger/swtpm#678]
https://github.com/stefanberger/swtpm/blob/2579038d766a6793ee1e739f16658a5b643e16e9/src/swtpm/tlv.c#L138

Hello, in `tlv_data_find_tag()` there's a check for `td->tlv.length` being slightly out of bounds; what happens if it is large enough that adding it to `offset` causes an integer wraparound?

```
        td->tlv.length = be32toh(td->tlv.length);
        if (offset + td->tlv.length > buffer_len)
            return NULL;
```

`tlv_data_append()` does something similar.

Are these tlv functions working on entirely trusted data?

Thanks

**Comment by stefanberger** [comment]
Thanks for reporting this one. Yes, there may be an integer wrap-around occurring in this function that can then cause crashes when reading from memory locations. Please have a look at the PR that for now only resolves the issue in `tlv_data_find_tag()`.

**Comment by stefanberger** [comment]
> Are these tlv functions working on entirely trusted data?

I would say they work on data that are as trusted as the pflash files for EFI code and variables and the virtual machine image(s)... they should be susceptible to malicious root only.

**Comment by setharnold** [comment]
Cool, that's good news. The pull request looks good to me.

Thanks for the quick turnarounds!
