### ISSUE TITLE
Use tcti-swtpm of tpm2-tss instead of splicing TPM commands in swtpm_setup

### ISSUE THREAD

**Issue by JerryDevis** [stefanberger/swtpm#683]
Hi, @stefanberger. Currently, in swtpm_setup, it sends some TPM commands to the swtpm process by splicing commands. 
https://github.com/stefanberger/swtpm/blob/47638ebc36ce5b18d562b508b84442a49f274420/src/swtpm_setup/swtpm.c#L690-L767
If we want to add another feature, it needs to splicing a new TPM commands again.
However, swtpm-tcti has been supported in tpm2-tss. Whether to consider calling TPM commands through the swtpm-tcti in the future？

**Comment by stefanberger** [comment]
> Currently, in swtpm_setup, it sends some TPM commands to the swtpm process by splicing commands.

What is 'splicing commands' ? 

Any communication between swtpm_setup and swtpm has to be done in such a way that nothing else on the host can interfere while swtpm is being setup, meaning the usage of file descriptors to communicate between swtpm_setup and swtpm is a requirement. I have no intentions to rewrite this part of swtpm_setup just to use another way of doing it.

**Comment by stefanberger** [comment]
Also, swtpm today runs on all BSDs and Cygwin and if the dependency, in this case swtpm-tcti, is not available on these platforms swtpm_setup wouldn't run anymore... we won't go down this road.
