### ISSUE TITLE
Unable to start vtpm vm through libvirt xml file

### ISSUE THREAD

**Issue by MIBc** [stefanberger/swtpm#7]
I have made a /dev/vptm0 device through our documentation and start a vm using qemu-system-x86_64 command. Then, I have a try to start vtpm vm through libvirt xml. But I meet an error which I can't solve it. The error is "**qemu-system-x86_64: -tpmdev cuse-tpm,id=tpm0,path=/dev/vtpm0: Cannot access TPM device using '/dev/vtpm0': Operation not permitted**".
I edit a test.txt file and use "virsh domxml-from-native qemu-argv" command to create libvirt xml file.
The contents of test.txt file and commands I used is as follows:
**test.txt**
LC_ALL=C PATH=/usr/local/bin HOME=/root LOGNAME=root /usr/local/bin/qemu-system-x86_64 -display sdl -enable-kvm -m 1024 -boot c -bios /root/tpm-test/seabios-tpm/out/bios.bin -boot menu=on -tpmdev cuse-tpm,id=tpm0,path=/dev/vtpm0 -device tpm-tis,tpmdev=tpm0 /tmp/tpm-test/centos.img

virsh domxml-from-native qemu-argv test.txt > my.xml
virsh create my.xml.
After excute these operations, the error above-mentioned occured.

**Comment by stefanberger** [comment]
You will have to start the CUSE TPM manually _every time_ before you start the VM with libvirt. So please try running the following commands. The reason is that when QEMU terminates, the CUSE TPM gets an 'END' signal and also terminates. Also make sure that every vTPM instance associated with a VM gets a different directory for its state files assigned.

`# mkdir /tmp/vtpm0`
`# swtpm cuse --tpmstate dir=/tmp/vtpm0 -n vtpm0`
`# virsh start <domain name>`

I hope this helps.

We have a driver for libvirt that automates the CUSE TPM life-cycle, manages the storage directories for the vTPM etc., but QEMU support has not been accepted, so we haven't published the driver.

**Comment by MIBc** [comment]
@stefanberger    I haven't started the vm through virsh command. When I try to start vm, it will always **Cannot access TPM device using '/dev/vtpm0': Operation not permitted.** At this time, the /dev/vtpm0 is existent.  
Actually, I want to start vm through a libvirt xml file. But I found the libvirt xml could't support cuse-tpm, so I tried to  create a xml file automatically by using "**virsh domxml-from-native qemu-argv**". When I start ed this xml file, the error occured.

**Comment by stefanberger** [comment]
My guess is that this has something to do with cgroups and missing setup for device access. I issued the following command and then it worked. Of course this is not a long term solution. I also have SELinux disabled on my Fedora system so that device labeling for /dev/vtpm0 doesn't get into the way.  As I said, we have a driver for libvirt that solves all these issues.

`umount /sys/fs/cgroup/devices`

```
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>biosonly-cuse-qemu-cmdline</name>
  <uuid>f2b98719-d76b-47b0-8eb7-8f57dda176ac</uuid>
  <memory unit='KiB'>1048576</memory>
  <currentMemory unit='KiB'>1048576</currentMemory>
  <vcpu placement='static'>1</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-2.1'>hvm</type>
    <boot dev='hd'/>
    <bootmenu enable='yes'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <pae/>
  </features>
  <cpu mode='custom' match='exact'>
    <model fallback='allow'>core2duo</model>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <pm>
    <suspend-to-mem enabled='yes'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-system-x86_64</emulator>
    <controller type='ide' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </controller>
    <controller type='usb' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <console type='pty'>
      <target type='virtio' port='0'/>
    </console>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='vnc' port='-1' autoport='yes' listen='127.0.0.1'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
    <video>
      <model type='cirrus' vram='16384' heads='1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='dynamic' model='selinux' relabel='yes'/>
  <qemu:commandline>
    <qemu:arg value='-tpmdev'/>
    <qemu:arg value='cuse-tpm,id=tpm-tpm0,path=/dev/vtpm0,cancel-path=/dev/null'/>
    <qemu:arg value='-device'/>
    <qemu:arg value='tpm-tis,tpmdev=tpm-tpm0,id=tpm0'/>
  </qemu:commandline>
</domain>
```

**Comment by MIBc** [comment]
@stefanberger  Very thank you for your response. I try the command "umount /sys/fs/cgroup/devices", but I occured another. I think you answker may be right. May be there are some error in my xml file. I'm wondering where can I get you driver for libvirt and how to use it.

**Comment by stefanberger** [comment]
The driver for the CUSE TPM is not public currently.
