### ISSUE TITLE
autogen fails checking for python on ubuntu 18.04

### ISSUE THREAD

**Issue by ricardoas** [stefanberger/swtpm#71]
Hi @stefanberger,

`./autogen.sh` is failing when I run on a new ubuntu 18.04 server with the following error:

```
checking for python... no
configure: error: python is required: python2 or python3 package
```

I think the cause is that there is no `python` alias... I solved it by installing python 2.7 with `apt install python` but I thought it was worth mentioning here.

**Comment by stefanberger** [comment]
`python` is needed for running the test cases successfully. It's intentional that this error now appears in `configure` otherwise we get it during `make check`.

**Comment by stefanberger** [comment]
Can we close this issue ?

**Comment by stefanberger** [comment]
Since python 2 is at the end of its life and due to the packaging for Fedora we now require python 3 for running the tests. The python executable has to be `python3` now.

**Comment by stefanberger** [comment]
Closing this issue for now assuming pythin3 can be installed on 18.04.
