### ISSUE TITLE
tpm_tools requirement for  tpm2-preview.X

### ISSUE THREAD

**Issue by safayetahmedatge** [stefanberger/swtpm#72]
When building tpm2-preview.X, "./configure" fails when  tpm_nvdefine is not found in the environment.

https://github.com/stefanberger/swtpm/blob/b999ed21fe1f594402d7266ac6bf3bd8bd945670/configure.ac#L171

tpm tools are not listed in the required-package list in INSTALL. Also, the tpm-tools are intended for TPM1.2 and the purpose of this dependency in the tpm2-X branches is not entirely clear.

**Comment by stefanberger** [comment]
The tpm2-preview* branches *add* TPM 2 support to swtpm. Since they don't *remove* TPM 1.2 support, TPM 1.2 support tools are still needed.
