### ISSUE TITLE
clearing the tpm results on a 0x000009a2 error

### ISSUE THREAD

**Issue by flixman** [stefanberger/swtpm#738]
**Describe the bug**
When accessing swtpm from qemu, I am trying to clear the platform by executing

```shell
# tpm2_clear -c platform
WARNING:esys:src/tss2-esys/api/Esys_Clear.c:291:Esys_Clear_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_Clear.c:97:Esys_Clear() Esys Finish ErrorCode (0x000009a2) 
ERROR: Esys_Clear(0x9A2) - tpm:session(1):authorization failure without DA implications
ERROR: Unable to run tpm2_clear
```

**Desktop (please complete the following information):**
 - OS guest: debian-11.4
 - OS host: arch

**Versions of relevant components**
- swtpm: 0.7.3-1
- libtpms: 0.9.5-1
- openssl: 1.1.1n-0+deb11u3
- tpm2-tools (in the guest system): 5.0-2

**Comment by stefanberger** [comment]
This is unlikely to be a bug. The firmware is supposed to change the password for the platform hierarchy to a random password and throw that password away.   So, you cannot clear the platform hierarchy unless you know the password, which you won't know.

SeaBIOS: https://github.com/coreboot/seabios/blob/master/src/tcgbios.c#L923

**Comment by stefanberger** [comment]
EDK2: https://github.com/tianocore/edk2/blob/master/SecurityPkg/Library/PeiDxeTpmPlatformHierarchyLib/PeiDxeTpmPlatformHierarchyLib.c#L181-L186

**Comment by flixman** [comment]
Hey @stefanberger, thank you for your answer... But then I do not see how can I clear the platform. Do I have to do it throught the edk2 efi?

**Comment by stefanberger** [comment]
The VM has to reset which resets the TPM 2 and clears the platform hierarchy password.

**Comment by flixman** [comment]
Do you mean: there is a setting on EFI that resets the tpm2? I have not been able to see it, but I will give it another try. Thank you!

**Comment by flixman** [comment]
But then... How do I clear the platform hierarchy and how do I prevent that from happening again after the next reboot? i am completely lost, my apologies if these are dumb questions.

**Comment by stefanberger** [comment]
Per TCG's firmware specification users don't control the platform hierarchy.

**Comment by stefanberger** [comment]
Here's the spec for this: https://trustedcomputinggroup.org/wp-content/uploads/PC-ClientSpecific_Platform_Profile_for_TPM_2p0_Systems_v21.pdf

section 10: 1->b->ii

**Comment by flixman** [comment]
So then... I should just run tpm2_clear? I have used it like that and swtpm seems to work as expected, but I am still experimenting/learning about the whole setup. Thank you very much!
