### ISSUE TITLE
swtpm_cuse.8 does not exist and cannot be created

### ISSUE THREAD

**Issue by entrope** [stefanberger/swtpm#751]
**Describe the bug**
Running "dpkg-buildpackage -us -uc" with git commit e5fdd1c181d0414ad27a0f4f72c49020fbc1ac6e fails.

swtpm/man/man8/Makefile.am lists swtpm_cuse.8 as a static man page, but it does not exist in the repository.

**To Reproduce**
1. Clone the repository.
2. Run `git checkout e5fdd1c181d0414ad27a0f4f72c49020fbc1ac6e`.
3. Run `dpkg-buildpackage -us -uc`.

**Expected behavior**
Successful build, resulting in .deb file(s) being created..

**Desktop (please complete the following information):**
 - OS: Debian 
 - Version testing (as of 17 Sep 2022)

**Versions of relevant components**
- swtpm: commit e5fdd1c181d0414ad27a0f4f72c49020fbc1ac6e
- libtpms: pre-0.10.0, commit stefanberger/libtpms@0c2bc32a21e2c7218faa8cd6d5cf31b13835e6d5
- openssl: 3.0.5-2 (standard Debian package)
- gnutls: 3.7.7-2 (standard Debian package)

**Log files**
See additional context for the specific error message.

**Additional context**
```
Making all in man8
make[4]: Entering directory '/home/mdpoole/src/swtpm/man/man8'
make[4]: *** No rule to make target 'swtpm_cuse.8', needed by 'all-am'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/mdpoole/src/swtpm/man/man8'
```

**Comment by stefanberger** [comment]
PR #752  should resolve the issue. Thanks for reporting.
