### ISSUE TITLE
swtpm doesn't exit on connection close when started with clientfd

### ISSUE THREAD

**Issue by DaanDeMeyer** [stefanberger/swtpm#753]
**Describe the bug**

I expected swtpm to exit when started with the --terminate flag, but it doesn't exit even after closing the connection.

**To Reproduce**
1. Configure swtpm as a socket activated service as follows:

```
# /etc/systemd/system/swtpm.socket
[Unit]
Before=sockets.target

[Socket]
ListenStream=/run/swtpm.socket
Accept=yes
SocketMode=0666

# /etc/systemd/system/swtpm@.service
[Service]
Type=exec
RuntimeDirectory=swtpm-%i
StandardInput=socket
ExecStart=swtpm socket --tpm2 --tpmstate dir=${RUNTIME_DIRECTORY} --ctrl type=unixio,clientfd=0 --terminate
```

```
systemctl daemon-reload
```

2. Start swtpm.socket

```
systemctl start swtpm.socket
systemctl status swtpm.socket
```

2. Start an instance of the swtpm service as follows by connecting to it with socat:

```
socat - UNIX-CONNECT:/run/swtpm.socket
```

4. Verity that the swtpm instance has correctly started (in another terminal)

```
systemctl status swtpm\*
```

5. Disconnect from the socat progam (Ctrl+C)
6. Check the status of the swtpm instance again
```
systemctl status swtpm\*
```

**Expected behavior**

The swtpm instance shuts down after closing the socket connection. In reality, it doesn't shut down and keeps waiting for new connections, even if the --terminate flag is specified.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 36

**Versions of relevant components**
- swtpm: `TPM emulator version 0.7.3, Copyright (c) 2014-2021 IBM Corp.`

**Comment by stefanberger** [comment]
It's not the loss of the control channel connection that would terminate it, but the loss of the data channel connection. I would not anticipate a user to hold the control channel open for sending an CMD_INIT and much later then for CMD_SHUTDOWN. Maybe that's an omission in the documentation.

**Comment by DaanDeMeyer** [comment]
Could a new option be added to support this use case? I would basically like a way to tell swtpm to shut down when there are no more client connections.

**Comment by stefanberger** [comment]
I am going to clarify the existing option via PR #754.

You can send a shutdown signal to the process as well via the control channel. That doesn't need a new option.

**Comment by stefanberger** [comment]
>  would basically like a way to tell swtpm to shut down when there are no more client connections.

What are 'no more clients' and what is 'i the client [that] misbehaves'?

You can run `swptm_ioctl -s --unix /path/to/socket | --tcp :<tcp-socket>` once you know that there are no more clients. You do that as root and the malicious clients are presumably non-root.

**Comment by DaanDeMeyer** [comment]
> What are 'no more clients' and what is 'if the client [that] misbehaves'?

No more clients means that the last client closed its connection and the server will be waiting in accept() for a new one. A misbehaving client in this case is one that doesn't send a shutdown signal before closing the connection.

> You can run swptm_ioctl -s --unix /path/to/socket | --tcp :<tcp-socket> once you know that there are no more clients. You do that as root and the malicious clients are presumably non-root.

This is great for manually shutting down swtpm, but I'm looking to do so automatically. I can't easily write tooling that checks whether swtpm still has a client or not and sends that command when it doesn't have any clients anymore.

What I want to achieve is to have swtpm start on a client connecting to a unix socket (this is handled by systemd socket activation as shown above) and for swtpm to shut down automatically when the client closes the socket (In other words, when swtpm sees POLHUP on the clientfd socket) without intervention required from my side.

**Comment by DaanDeMeyer** [comment]
I don't need to use `clientfd` for this btw. I would also be very happy with a `-ctrl type=stdio` option where swtpm uses stdin/stdout to communicate with a client and shuts down when `stdin` is closed.

**Comment by stefanberger** [comment]
> > What are 'no more clients' and what is 'if the client [that] misbehaves'?
> 
> No more clients means that the last client closed its connection and the server will be waiting in accept() for a new one. A misbehaving client in this case is one that doesn't send a shutdown signal before closing the connection.

You mean the last client didn't send the CMD_SHUTDOWN ? Who is going to then terminate `socat` to shut down swtpm and why can that something that terminates `socat` not instead run `swtpm_ioctl` r send a SIGTERM to swtpm ? 

> 
> > You can run swptm_ioctl -s --unix /path/to/socket | --tcp : once you know that there are no more clients. You do that as root and the malicious clients are presumably non-root.
> 
> This is great for manually shutting down swtpm, but I'm looking to do so automatically. I can't easily write tooling that checks whether swtpm still has a client or not and sends that command when it doesn't have any clients anymore.

Again, same question as above. Why are you trying to keep socat running and then terminate it to terminate swtpm rather than using an existing tool to shut down swtpm the usual way? Why does this not work ?

> 
> What I want to achieve is to have swtpm start on a client connecting to a unix socket (this is handled by systemd socket activation as shown above) and for swtpm to shut down automatically when the client closes the socket (In other words, when swtpm sees POLHUP on the clientfd socket) without intervention required from my side.

When the client closes the **data channel** socket you mean? In your command line above I don't see `--server type=unix,...` that the clients presumably are using but you are showing the `--ctrl type=unix,... ` socket that clients would NOT be using to send TPM commands. I would assume clients are not just sending control channel commands (CMD_INIT, CMD_SHUTDOWN, etc) but they are send TPM commands, right? And you would want `--terminate` to apply to the Unix data channel? Client**s** in this case are opening the Unix socket only once and then are re-using that socket to send all commands and then in the end the Unix socket is being closed and that's when the TPM should automatically shut down?

**Comment by stefanberger** [comment]
I have tried your systemd config file above and it doesn't work for me. Nothing starts... I have also tried then with this command line but it doesn't start it, either.
```
swtpm socket --tpm2 --tpmstate dir=/tmp --ctrl type=tcp,port=2322 --server type=tcp,port=2321 --flags not-need-init
```

**Comment by DaanDeMeyer** [comment]
I added some extra missing instructions. I can confirm it's working on my end though. Even without the systemd stuff, if I start swtpm as listed in the qemu documentation [here](https://qemu.readthedocs.io/en/latest/specs/tpm.html#the-qemu-tpm-emulator-device), everything works. They only configure `--ctrl` as well, and don't configure `--server` at all. swtmp is supposed to work without a server right?

Unless there's some default socket that swtmp listens on for data connections, the qemu documentation starts swtmp with only the --ctrl option and everything works. Is swtmp actually using two sockets in the qemu scenario or just one?

**Comment by stefanberger** [comment]
> They only configure `--ctrl` as well, and don't configure `--server` at all. swtmp is supposed to work without a server right?

That is because QEMU creates the data channel socketpair and passes one of the file descriptors to swtpm via Unix control channel and a special swtpm command [PTM_SET_DATAFD] SCM_RIGHTS. Swtpm then uses that file descriptor for reading the TPM commands from QEMU. Typically one needs `--server`, though.

**Comment by DaanDeMeyer** [comment]
> That is because QEMU creates the data channel socketpair and passes one of the file descriptors to swtpm via Unix control channel and a special swtpm command [PTM_SET_DATAFD] SCM_RIGHTS. Swtpm then uses that file descriptor for reading the TPM commands from QEMU. Typically one needs --server, though.

So my usecase is specific to the qemu one, I have no need for --server and would like the lifetime of swtmp to be limited to the lifetime of the control connection. Whenever POLHUP is received on the control connection, I'd like for swtmp to shut down. This allows me to ensure that even if qemu doesn't properly send shutdown to its control socket before closing it, that swtmp will still shut down correctly.

**Comment by stefanberger** [comment]
I didn't realize you started swtpm via QEMU. Nothing in the bug description hints at that.

> I understand that this is extremely specific to this use case though, since there's no requirement that the control connection outlives the data connection, it's only by chance that qemu keeps the control connection open (because it needs to properly shut down the TPM and such before exiting).

> So my usecase is specific to the qemu one

Are you assuming a broken QEMU that doesn't get to send CMD_SHUTDOWN? Why?

**Comment by DaanDeMeyer** [comment]
> I didn't realize you started swtpm via QEMU. Nothing in the bug description hints at that.

Apologies for that, I didn't realize what qemu was doing was something unique and not the usual way of using swtpm.

> Are you assuming a broken QEMU that doesn't get to send CMD_SHUTDOWN? Why?

Software has bugs, things happen, qemu could get SIGKILLED and not have the chance to send CMD_SHUTDOWN, etc. I'd prefer not having to rely on qemu behaving correctly to avoid lingering swtpm processes on my system and CI systems that I'm using it on.

**Comment by stefanberger** [comment]
I also don't quite understand how systemd will recognize that VM-A again is using the swptm versus VM-B vs. VM-C etc. and can then re-use the state of the TPM 2 from the previous time that VM-A used swtpm. TPMs are stateful and VMs I would think expect things to be consistent and use the TPM 2 with the state it had previously, including keys in it. Also we are running swtpm_setup when we start swtpm via libvirt. Your scripts don't do that. I am no sure whether systemd really is a good use for starting swtpm when used with VMs.

**Comment by DaanDeMeyer** [comment]
> I also don't quite understand how systemd will recognize that VM-A again is using the swptm versus VM-B vs. VM-C etc. and can then re-use the state of the TPM 2 from the previous time that VM-A used swtpm. TPMs are stateful and VMs I would think expect things to be consistent and use the TPM 2 with the state it had previously, including keys in it. Also we are running swtpm_setup when we start swtpm via libvirt. Your scripts don't do that. I am not sure whether systemd really is a good use for starting swtpm when used with VMs.

Generally the VMs we use for testing are completely stateless, we throw away all changes on shutdown. So throwing away the TPM state on swtpm shutdown after a VM shuts down is actually a feature for us. So we want a unique instance os swtpm for each VM and we want the state to be ephemeral, as soon as the swtpm instance shuts down, we want its state to be removed as well.

For our usage of TPM, the running swtpm_setup does not seem to be required, the only thing systemd does with the TPM is measuring hashes into PCR banks, that seems to work fine in qemu without running swtpm_setup. If it's required though, it's easy to add an `ExecStartPre=swtpm_setup` call to the unit that would run the setup tool before invoking swtpm.

If I had to summarize, what we want is an ephemeral instance of swtpm per qemu VM that we launch whose lifetime is tied to the lifetime of the VM. A new instance of swtpm is started when qemu tries to connect to the socket we pass it (via systemd socket activation), and it's lifetime is tied to the lifetime of the VM. The swtpm has its own state that is removed when the VM is shut down. As soon as the control socket that is passed to the swtpm instance is closed, we'd like for swtpm to shut down as well. That way, everything is nicely tied together and we're guaranteed that swtpm won't start before the VM is started and won't exist anymore after the VM shuts down. The only thing required would be the two units I listed above, and the command line options we'd use to launch qemu with TPM support would be limited to the following:

```
-chardev socket,id=chrtpm,path=/run/swtpm.socket
-tpmdev emulator,id=tpm0,chardev=chrtpm
-device tpm-tis,tpmdev=tpm0
```

**Comment by stefanberger** [comment]
So from what I can see nothing needs to be done... Your socat test didn't test the reaction to a lost data channel but to a lost control channel.

If I modify QEMU to not send the CMD_SHUTDOWN like this:

```
iff --git a/backends/tpm/tpm_emulator.c b/backends/tpm/tpm_emulator.c
index 49cc3d749d..1ed96bd80e 100644
--- a/backends/tpm/tpm_emulator.c
+++ b/backends/tpm/tpm_emulator.c
@@ -990,7 +990,7 @@ static void tpm_emulator_shutdown(TPMEmulator *tpm_emu)
 {
     ptm_res res;
 
-    if (!tpm_emu->options->chardev) {
+    if (1 || !tpm_emu->options->chardev) {
         /* was never properly initialized */
         return;
     }
```

And then follow the instructions here: https://github.com/qemu/qemu/blob/master/docs/specs/tpm.rst#the-qemu-tpm-emulator-device

I can then start swtpm in one terminal like this and it will NOT terminate upon QEMU termination:

```
swtpm socket --tpmstate dir=/tmp/mytpm1   --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock   --log level=20
```

I can now start QEMU like this:

```
/build/qemu-system-x86_64 -display sdl -accel kvm   -m 1024 -boot d -bios bios-256k.bin -boot menu=on   -chardev socket,id=chrtpm,path=/tmp/mytpm1/swtpm-sock   -tpmdev emulator,id=tpm0,chardev=chrtpm   -device tpm-tis,tpmdev=tpm0
```

When I terminate QEMU via CTRL-C swtpm will keep running and print out: `Data client disconnected`   That's expected at this point.

I can now re-start swtpm with the `--terminate` flag:
```
swtpm socket --tpmstate dir=/tmp/mytpm1   --ctrl type=unixio,path=/tmp/mytpm1/swtpm-sock   --log level=20 --terminate
```

When I restart QEMU and press CTRL-C QEMU ends and swtpm also terminates WITHOUT having received CMD_SHUTDOWN. So that seems to already do what you want.

**Comment by DaanDeMeyer** [comment]
Sure, but it's perfectly possible that qemu is SIGKILLED after connecting to the control socket but before it has the chance to set up the data channel. If that's the case swtpm won't shut down when qemu exits.

**Comment by stefanberger** [comment]
PR #756 should resolve the issue with the automatic shutdown upon control channel connection loss.
