### ISSUE TITLE
tss2_provision Failure

### ISSUE THREAD

**Issue by dsburns** [stefanberger/swtpm#761]
**Describe the bug**
tss2_provision fails to initialize FAPI datastore

**To Reproduce**
1. Setup the SW TPM using instructions found [here](https://github.com/stefanberger/swtpm/wiki/Certificates-created-by-swtpm_setup#tpm-2-certificates)
2. Run the SW TPM 
```
swtpm chardev --vtpm-proxy --tpmstate dir=~/vtpm2 --tpm2 --ctrl type=tcp,port=2322
```
3. Provision the FAPI datastore
```
export TPM2TOOLS_TCTI="swtpm:port=2321"
tpm2_startup -c
tss2_provision
```

**Expected behavior**
tss2_provision succesfully configures FAPI datastore

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Versions of relevant components**
- swtpm: TPM emulator version 0.8.0, Copyright (c) 2014-2022 IBM Corp. and others

**Log files**
```
ERROR:fapi:src/tss2-fapi/ifapi_curl.c:186:ifapi_curl_verify_ek_cert() ErrorCode (0x00060025) No certificate downloaded 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:831:Fapi_Provision_Finish() ErrorCode (0x00060025) Verify EK certificate 
ERROR:esys:src/tss2-esys/esys_iutil.c:390:iesys_handle_to_tpm_handle() Error: Esys invalid ESAPI handle (ff). 
ERROR:esys:src/tss2-esys/esys_iutil.c:1111:esys_GetResourceObject() Unknown ESYS handle. ErrorCode (0x0007000b) 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:138:Esys_FlushContext_Async() flushHandle unknown. ErrorCode (0x0007000b) 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x0007000b) 
ERROR:fapi:src/tss2-fapi/fapi_util.c:1139:ifapi_session_clean() Cleanup session failed. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:169:Fapi_Provision() ErrorCode (0x00060025) Provision 
Fapi_Provision(0x60025) - fapi:No certificate
```

**Additional context**

**Comment by stefanberger** [comment]
To get the certs run swtpm setup before starting swtpm:
```
swtpm_setup --tpmstate ~/vtpm2 --create-ek-cert --create-platform-cert --tpm2 --overwrite
```

**Comment by stefanberger** [comment]
`tpm2_provision` seems to be hardcoded to use /dev/tpmrm0, which on my system doesn't exist... (old, has a TPM 1.2)

```
# TPM2TOOLS_TCTI="device:/dev/tpm1" tss2_provision

** (process:3157132): WARNING **: 13:30:13.032: Failed to create connection with service: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-tabrmd.so.0
ERROR:tcti:src/tss2-tcti/tcti-device.c:452:Tss2_Tcti_Device_Init() Failed to open specified TCTI device file /dev/tpmrm0: No such file or directory
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:154:tcti_from_file() Could not initialize TCTI file: libtss2-tcti-device.so.0
ERROR:tcti:src/tss2-tcti/tcti-device.c:503:Tss2_Tcti_Device_Init() timeout waiting for response from fd 7
ERROR:sys:src/tss2-sys/api/Tss2_Sys_Execute.c:113:Tss2_Sys_ExecuteFinish() Unsupported device. The device is a TPM 1.2
ERROR:esys:src/tss2-esys/api/Esys_Startup.c:216:Esys_Startup_Finish() Received a non-TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Startup.c:78:Esys_Startup() Esys Finish ErrorCode (0x00080001)
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:236:Fapi_Initialize_Finish() Esys_Startup FAILED! Response Code : 0x80001
Fapi_Initialize(0x80001) - sys:Catch all for all errors not otherwise specified
```

Your `export TPM2TOOLS_TCTI="swtpm:port=2321"` only works when you use `swtpm socket` NOT when using `swtpm chardev --vtpm-proxy`

**Comment by dsburns** [comment]
There was a mistake in my original post.  I am specify the TCTI device with `export TPM2TOOLS_TCTI="device:/dev/tpm0"`.  However, this doesn't even matter because the simulator creates /dev/tpm0 which is the default TCTO device in the code:
```
user@guest-vm:~/repos/external/swtpm$ sudo swtpm chardev --vtpm-proxy --tpmstate dir=~/vtpm2 --tpm2 --ctrl type=tcp,port=2322
New TPM device: /dev/tpm0 (major/minor = 10/224)
```

I did create the certificates before running the simulator (step 2 creates certs and step 3 runs the simulator in my original notes on reproducing).

I know the SW TPM is initialized property because I can execute tpm2_xzy commands against it.  Any other ideas?

Thanks!

**Comment by dsburns** [comment]
I noticed in your comment above you're testing against a real TPM.  Are you able to build and run the software TPM?  If so, can you confirm you also see this error message when running tss2_provision?
```
ERROR:fapi:src/tss2-fapi/ifapi_curl.c:186:ifapi_curl_verify_ek_cert() ErrorCode (0x00060025) No certificate downloaded
```

**Comment by dsburns** [comment]
I found a way to bypass the EK certificate check by appending `"ek_cert_less": "yes"` to the _fapi-config.json_ file.  This fixed the issue.
