### ISSUE TITLE
NV Index Extend Registers: Values not retained across reboots with Orderly bit set

### ISSUE THREAD

**Issue by sughoshg** [stefanberger/swtpm#771]
I configure a NV Index register for Extend functionality. Also set the Orderly attribute at the time of the register creation. However, even after issuing the tpm2_shutdown command, the value in the register cannot be read after platform reboot. If the Orderly attribute is not set at the time of register creation, the value can be read after the platform reboot.

As per my understanding, setting Orderly attribute means that the value of the register would get stored to the NV region on an orderly shutdown(issuing tpm2_shutdowm command). What am I missing here. Is there some reason why the Orderly attribute does not work for the Extend register. However, one thing to note is that the extended values in the register do sustain across reboots without the Orderly bit set.

My setup
Host - Ubuntu 22.04
Target Hardware - Qemu Virt(Arm64)
Target OS -Debian 11(bullseye)
swtpm version on the host - 0.6.3 <--- This is the package available on the Ubuntu 22.04(installed through package manager).

A) NV Index Extend Register created without the Orderly attribute

1) Creation of the nv index extend register
sudo tpm2_nvdefine -C o -a "nt=extend|ownerread|policywrite|ownerwrite|writedefine" 1
nv-index: 0x1000001

2) extend the register
echo "Hello World" | sudo tpm2_nvextend -C o -i- 1

3) read the value from the register
sudo tpm2_nvread -C o 1 | xxd -p -c 32
WARN: Reading full size of the NV index
9640e4e7a3e6864e6bed54b048331fc872b972cad45dad6c874b57101e1aea1b

4) reboot

5) Read the nv index register after reboot
sudo tpm2_nvread -C o 1 | xxd -p -c 32
WARN: Reading full size of the NV index
9640e4e7a3e6864e6bed54b048331fc872b972cad45dad6c874b57101e1aea1b <--- Same value read

B) NV Index Extend Register created with the Orderly attribute

1) Define a nv index extend register with orderly attribute
sudo tpm2_nvdefine -C o -a "nt=extend|ownerread|ownerwrite|policywrite|writedefine|orderly" 2
nv-index: 0x1000002

2) extend the register
echo "Hello World" | sudo tpm2_nvextend -C o -i- 2

3) read the value from the register
sudo tpm2_nvread -C o 2 | xxd -p -c 32
WARN: Reading full size of the NV index
9640e4e7a3e6864e6bed54b048331fc872b972cad45dad6c874b57101e1aea1b

4) reboot

5) Read the nv index register after reboot
sughosh@debian:~$ sudo tpm2_nvread -C o 2 | xxd -p -c 32
WARN: Reading full size of the NV index
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x0000014a)
ERROR: Esys_NV_Read(0x14A) - tpm:error(2.0): an NV Index is used before being initialized or the state saved by TPM2_ShutdownSTATE could not be restored
ERROR: Failed to read NVRAM area at index 0x1000002
ERROR: Unable to run tpm2_nvread

I get the same result even if I issue the tpm2_shutdown command before reboot. So my doubt is that with the Orderly attribute set, should the contents of the register not get preserved across a clean shutdown. Or am I missing some detail from the spec which results in this behaviour.

**Comment by stefanberger** [comment]
This seems expected for the orderly NVRAM location since the WRITTEN flag has been reset after the TPM 2's reset + TPM2_Startup() here:

https://github.com/stefanberger/libtpms/blob/df1c3e98d697f3c1f09262d2ba161a7db784d6cc/src/tpm2/NVDynamic.c#L1497-L1503

**Comment by sughoshg** [comment]
Thanks for pointing me to the code. I understand that the NV register read is not being allowed since the TPMA_NV_WRITTEN bit has been cleared on a TPM2 reset. I can indeed read the register if i do an extend operation.

But what I understand from the definition of the TPMA_ORDERLY bit is that the register contents should get preserved when a TPM2_Shutdown has been issued. However, on reset, if I try to extend the register with the same value, I get the same value that was present before the reset. So it is as though the register has been reset on reboot.

Just to illustrate my point

1) Define the NV Index register with the orderly bit set
sudo tpm2_nvdefine -C o -a "nt=extend|ownerread|policywrite|ownerwrite|writedefine|orderly" 1
nv-index: 0x1000001

2) extend the register
echo "Hello World" | sudo tpm2_nvextend -C o -i- 1

3) read the value from the register
sudo tpm2_nvread -C o 1 | xxd -p -c 32
WARN: Reading full size of the NV index
9640e4e7a3e6864e6bed54b048331fc872b972cad45dad6c874b57101e1aea1b

4) reboot

5) Try to read the NV Index register after reboot. This will fail since the TPMA_NV_WRITTEN value has been cleared
sughosh@debian:~$ sudo tpm2_nvread -C o 1 | xxd -p -c 32
[sudo] password for sughosh:
WARN: Reading full size of the NV index
WARNING:esys:src/tss2-esys/api/Esys_NV_Read.c:315:Esys_NV_Read_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_NV_Read.c:105:Esys_NV_Read() Esys Finish ErrorCode (0x0000014a)
ERROR: Esys_NV_Read(0x14A) - tpm:error(2.0): an NV Index is used before being initialized or the state saved by TPM2_ShutdownSTATE could not be restored
ERROR: Failed to read NVRAM area at index 0x1000001
ERROR: Unable to run tpm2_nvread

6) Extend the NV Index register(same value as that used in step 2)
echo "Hello World" | sudo tpm2_nvextend -C o -i- 1

7) Read the NV Index register back
sughosh@debian:~$ sudo tpm2_nvread -C o 1 | xxd -p -c 32
WARN: Reading full size of the NV index
9640e4e7a3e6864e6bed54b048331fc872b972cad45dad6c874b57101e1aea1b <-- This is the same value as read in step 3

So my question is, even if the register is not being allowed to be read with the TPMA_NV_WRITTEN bit cleared, should the contents of the register not be preserved, even for an Orderly attribute, if the TPM2_Shutdown command had been issued? And if the register contents were preserved, the extend operation after the reboot should change the value of the register as against its value prior to reboot. Basically, I am just trying to understand the use of the Orderly bit. Or am I getting something wrong here.

**Comment by stefanberger** [comment]
Since the code is the spec of the TPM 2 I think you would have to ask the TCG whether this is maybe a bug. I can only read and interpret the code and from that perspective it's 'expected behavior.'

In the code snippet I pointed you to the `STARTUP_TYPE type` is set to `SU_RESET`, which comes from [here](https://github.com/stefanberger/libtpms/blob/master/src/tpm2/StartupCommands.c#L204-L206)  and then calls `NvEntityStartup` [here]( https://github.com/stefanberger/libtpms/blob/master/src/tpm2/StartupCommands.c#L280)

**Comment by sughoshg** [comment]
hi Stefan,
I think the implementation is as per the description in the TPM 2 spec, section 37.2.6.5. Basically, I just wanted to ensure that with the Orderly attribute set, the NV Index Extend register would actually mimic the PCR behaviour. Which I think is the case, based on my understanding of the relevant description in the spec. Thanks for pointing me to the relevant code.
