### ISSUE TITLE
libvirt cannot start swtpm in ubuntu 22.04 after upgrade swtpm to 0.8.0

### ISSUE THREAD

**Issue by braindevices** [stefanberger/swtpm#775]
**Describe the bug**

```
Error starting domain: internal error: Could not start 'swtpm'. exitstatus: 1, error: 

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 108, in tmpcb
    callback(*args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/libvirtobject.py", line 57, in newfn
    ret = fn(self, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/object/domain.py", line 1384, in startup
    self._backend.create()
  File "/usr/lib/python3/dist-packages/libvirt.py", line 1353, in create
    raise libvirtError('virDomainCreate() failed')
libvirt.libvirtError: internal error: Could not start 'swtpm'. exitstatus: 1, error: 

```

**Required: To Reproduce (without these steps your issue may be deleted)**

Steps to reproduce the behavior/issue showing all commands on command line, needed XML or JSON (if necessary), etc.:

 1. create a vm in libvirt 8.0
 2. add TPM
  ```
   <tpm model="tpm-tis">
    <backend type="emulator" version="2.0"/>
   </tpm>
  ```
 4. then start the VM
 5. `sudo swtpm_setup --tpmstate /tmp/mytpm --createek --create-platform-cert --overwrite` works fine.

**Expected behavior**

start without problem

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Version 22.04

**Versions of relevant components**
- swtpm: TPM emulator version 0.8.0, Copyright (c) 2014-2022 IBM Corp. and others
- libtpms: 0.9.5-1
- openssl: OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
- gnutls: 3.7.3-4ubuntu1.1
- libvirt: 8.0
- qemu: 6.2

**Log files**
there is no new logs in neither /var/log/swtpm/libvirt/qemu nor /var/log/libvirt/qemu
So I do not know the actual command line for swtpm command to debug. Can you suggest any command line that I can continue the debug to see what exactly wrong in there.

**Comment by stefanberger** [comment]
You may want to investigate AppArmor related issues reported here: https://github.com/stefanberger/swtpm/issues/770

**Comment by braindevices** [comment]
that is true:
```
audit: type=1400 audit(1670865762.546:515): apparmor="DENIED" operation="mknod" profile="swtpm" comm="swtpm" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000

```
thanks

**Comment by braindevices** [comment]
add following local rules to `/etc/apparmor.d/local/usr.bin.swtpm ` the vm start again:
```
/run/user/*/libvirt/qemu/run/swtpm/*.sock rwk,
owner /run/user/*/libvirt/qemu/run/swtpm/*.pid rwk,

```

**Comment by braindevices** [comment]
So basically the new libvirt changed the temp file locations to user based place to get better privacy in a multi-user environment.

**Comment by stefanberger** [comment]
The title of this issue states that the upgrade to swtpm 0.8.0 is at fault here. However, it seems more like it's an AppArmor/libvirt issue. So you must have upgraded your libvirt installation as well.

**Comment by stefanberger** [comment]
Now that Issue #770 is closed after an updated of libvirt in Ubuntu, can you check whether this also resolved this issue here, @braindevices ?

**Comment by braindevices** [comment]
@stefanberger I don't have time to test. But since this is more like a duplicates of #770. I think we can close it now. I will reopen if the problem remains in new installation.

**Comment by braindevices** [comment]
@stefanberger if you can point me the commit that solve #770, I shall highly appreciate your kindness. so far I cannot find any recent change in master about the usr.bin.swtpm

**Comment by braindevices** [comment]
ah, ok, you meant they actually change the libvirt. I misread the previous comment. Sorry

**Comment by stefanberger** [comment]
Yes, libvirt changed, so you would have to run an update on your Ubuntu machine to get the new libvirt version.
