### ISSUE TITLE
How to use SWTPM as a service

### ISSUE THREAD

**Issue by syrizw** [stefanberger/swtpm#777]
I was able to build and run SWTPM as in the forum
https://stackoverflow.com/questions/71220170/how-to-install-start-using-swtpm-on-linux

However, I have another service that may depend upon SWTPM depending whether it contains a TPM or not.
If not, then this needs to be started prior to the launch of the service in its own process.

How can I do that?

**Comment by stefanberger** [comment]
I am not sure I follow you. What is 'it' in 'it contains a TPM or not.'

Maybe this is useful to you: If you want to start a VM with an attached vTPM then you can use libvirt for this: https://libvirt.org/formatdomain.html#tpm-device

**Comment by syrizw** [comment]
Apologies. I will rephrase.
In my case, I have multiple generations of hardware (Industrial PCs) that may or may not contain a TPM.
In case they contain TPM, then I can simply use the hardware TPM. Since it is hardware, it is available since boot, so no issues.
In case they are legacy and don't contain a TPM, I want to use SWTPM to emulate a TPM. However, for this, I have to run SWTPM prior to the linux service (systemd service) that will need it. How do I do this?

**Comment by syrizw** [comment]
Thanks a lot for the support.
I looked at the documentation and that is very close to what I want. The only issue in that I have a systemd service that need access to TPM and thus I have to run this (in a background process or as daemon) before the depending service starts. I don't know how I can do that.
