### ISSUE TITLE
take-ownership leaves swtpm in non-functional state

### ISSUE THREAD

**Issue by mxraw** [stefanberger/swtpm#786]
I am observing the following strange behavior:

1. I setup SWTPM with 
```
swtpm_setup --tpmstate $TPM_STATE_DIR --create-ek-cert \
    --create-platform-cert --lock-nvram \
    --take-ownership --ownerpass "ooo" --srkpass "sss"
```
2. I start swtpm with
```
swtpm socket \
    --log file=/var/log/swtpm.log,level=4 \
    --tpmstate dir=$TPM_STATE_DIR \
    --server type=tcp,port=$TPM_COMMAND_PORT \
    --ctrl type=tcp,port=$TPM_PLATFORM_PORT \
    --flags not-need-init,startup-state \
    --daemon
```

Now, I would expect to have a working environment with taken ownership. But this is not the case:
* Trousers fails to start:
```
# tcsd -f -e
TCSD TDDL ioctl: (25) Inappropriate ioctl for device
TCSD TDDL Falling back to Read/Write device support.
TCSD TCS ERROR: TCS GetCapability failed with result = 0x1c
```
* Because tpm-tools work through trousers, none of them work obviously.

So I would assume that there is some command missing, either through swtpm_bios or swtpm_ioctl, but I am at a complete loss as what that could be.

Searching the trousers mailing list I found this gem of advice[^1]:

> This 0x1c error code indicates the TPM selftest failed and has shutdown, according to the spec, you need to reboot the machine. By reboot here I mean a full power cycle, you must shutdown it, and then power it on again. Have you returned from a suspend?

That doesn't make sense to me, as I just started swtpm and I assume it goes through the correct power-up sequence.

---------------------

Of course I could change the flag to start-clear and trousers would come up successfully. But then swtpm_setup --take-ownership doesn't work, because as the TPM Spec Part 1, 9.5 duly notes:

> The clear process performs the following tasks:
> Invalidate the SRK. 

... which is obviously not something anyone would want after issuing swtpm_setup --take-ownership. And ineed, with startup-clear:

```
# tpm_changeownerauth -s
Tspi_Context_LoadKeyByUUID failed: 0x00002020 - layer=tcs, code=0020 (32), Key not found in persistent storage
```
as one would expect.  

[^1]: https://trousers-users.narkive.com/zwtXNmNA/tpm-activation-and-tcsd-problems-getcapability-failed-with-result-0x1c

**Comment by stefanberger** [comment]
You may want to try this command line here to start tcsd and have it use a TCP socket to talk to swtpm.

https://github.com/stefanberger/swtpm/blob/346b3d62653681f371fee1cac75a8e8805f60473/tests/test_samples_create_tpmca#L164

Let me know how this goes.

**Comment by mxraw** [comment]
This doesn't change anything, as expected.

I was reading the Spec some more and as far as I understand it, at least some parts of the SRK are actually stored on disk, inside what is called the 'TCS persistent storage area', which is provided by tcsd.

If I use --taker-ownership, which happens during virtual 'manufacturing' stage of the TPM and doesn't even require trousers, where is this data going?

**Comment by stefanberger** [comment]
> This doesn't change anything, as expected.

Did you see that tcsd was previously with your command line talking to swtpm at all? If not, do these environment variables help?

You can also avoid having `swtpm_setup` take ownership of the TPM and do that later on once the tcsd is talking to swtpm.

**Comment by mxraw** [comment]
Apologies, I should've been more specific above, SWTPM+Trousers actually works as excpected when I do not use --take-ownership and instead use take_ownership from tpm-tools. This is not a communication issue between SWTPM and Trousers, although from the error message it maybe appears to be. Perhaps the combination of --flags startup-state and --take-ownership leaves SWTPM in a state in which it is unable to communicate with Trousers.

**Comment by stefanberger** [comment]
> For my workflow this is precisely what I want to do, though.

I am not sure whether the file that trousers expects to be around after previously having taken ownership with its own tool can be faked in some way. Create an empty file maybe? I am not sure whether it will work. Otherwise you may need to to use other TPM 1.2 tools (there are some other IBM TPM 1.2 tools around [here](https://sourceforge.net/p/ibmtpm20tss/tss/ci/master/tree/utils12/)) or use swtpm_setup in way that tpm_takeownership then can work with.

**Comment by mxraw** [comment]
> I am not sure whether the file that trousers expects to be around after previously having taken ownership with its own tool can be faked in some way.

Yeah, that's likely the problem. For that to work, SWTPM would need to take some 'trousers compatibility' argument to --take-ownership, something like --trousers-dir and then do whatever trousers does to the files therein. 

I guess that answers my question. I didn't like the answer but thanks anyway. ;-)
