### ISSUE TITLE
`CMD_SET_DATAFD` uses ancillary data (`struct msghdr::msg_control`) even on TCP/IP sockets

### ISSUE THREAD

**Issue by dimakuv** [stefanberger/swtpm#792]
**Describe the bug**

There is a redundant use of ancillary data (`struct msghdr::msg_control`) when doing `recvmsg()` on a TCP/IP socket.

Ancillary data is meaningful only on Unix Domain Sockets (what you call UnixIO). It makes no sense on TCP/IP sockets. This was detected on [Gramine](https://github.com/gramineproject/gramine/) that emulates `recvmsg()` and currently does *not* support ancillary data. That's why I uses the TCP/IP socket interface for control plane of `swtpm`, but still hit the "unsupported syscall" error in Gramine.

Here are the relevant code snippets:

- https://github.com/stefanberger/swtpm/blob/185832c8d4be95fa9305279240ca33b7403cfc91/src/swtpm/ctrlchannel.c#L500-L506
- https://github.com/stefanberger/swtpm/blob/185832c8d4be95fa9305279240ca33b7403cfc91/src/swtpm/ctrlchannel.c#L345
- https://github.com/stefanberger/swtpm/blob/185832c8d4be95fa9305279240ca33b7403cfc91/src/swtpm/ctrlchannel.c#L810-L822

If we look closely at this code, we notice two things:

- This `recvmsg(...with ancillary data...)` is called **even on TCP/IP sockets**, where it is simply ignored.
- The ancillary data is used only in one command case (`CMD_SET_DATAFD`).

**Required: To Reproduce (without these steps your issue may be deleted)**

Steps to reproduce the behavior/issue showing all commands on command line, needed XML or JSON (if necessary), etc.:

 1. Run `gramine-sgx swtpm --ctrl type=tcp,port=2320` in one window.
 2. Run `swtpm_ioctl --tcp localhost:2320 -i` in another window.
 3. Gramine refuses connection with `-ENOSYS` due to the bug above.

**Expected behavior**

`recvmsg()` should **not** use ancillary data fields (`msg_control` and `msg_controllen`) for TCP/IP sockets. Also, `CMD_SET_DATAFD` command should be disallowed for TCP/IP sockets.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Versions of relevant components**
- swtpm: v0.8.0
- libtpms: v0.9.6

**Additional context**

A bit similar discussion was here: https://github.com/stefanberger/swtpm/issues/112

See also my workaround in Gramine: https://github.com/gramineproject/gramine/pull/1210

**Comment by stefanberger** [comment]
With swtpm running on Linux, several BSDs, macOS, and Cygwin and neither one of them failing due to this issue, I am wondering whether actually this is a feature of the recvmsg() API to ignore the ancillary data ? I mean I don't mind fixing it but there are obviously several OSes out there that don't mind the additional parameter and other applications could exist as well...

**Comment by stefanberger** [comment]
... IOW I can write a patch to clean up the fields set in the struct msghdr but I think I would only help you mask a problem in Gramine.  PR #793

**Comment by stefanberger** [comment]
The issue with PR #793 turns out to be that SO_DOMAIN is non-standard and not supported everywhere, so on some platforms it's not so easily possible, if at all, to determine the domain of an inherited file descriptor, which would necessarily have to work as well since fd-passing via command line is supported.  So I'd rather not apply PR #793.

**Comment by dimakuv** [comment]
@stefanberger That's fair. I actually (re-)implemented Gramine's support for such a case: https://github.com/gramineproject/gramine/pull/1210

I will close this issue, since this will be resolved on the Gramine side. And I agree, the change to `swtpm` became non-trivial. Feel free to close PR #793.

**Comment by stefanberger** [comment]
@dimakuv Thanks. I closed the PR.
