### ISSUE TITLE
swtpm not found when installed out of PATH

### ISSUE THREAD

**Issue by BMBurstein** [stefanberger/swtpm#795]
If I configure, make and install with `--prefix=<some dir not in the PATH>`, swtpm_setup fails to find the swtpm executable. It is only looking in the $PATH. The only way is to pass the swtpm executable path to the `--tpm` switch.

I think that it should find swtpm in the configured install location (either instead of or in addition to the $PATH)

**Comment by BMBurstein** [comment]
It is worse. I can't even use --tpm for this. If I pass --tpm, it finds `swtpm`. But then it calls `swtpm_localca` using the configured prefix (this is good!). The problem is that `swtpm_localca` then looks for `swtpm_cert` only in the PATH, which again fails, and there is no way to even pass a corrected path

**Comment by stefanberger** [comment]
If you have a patch to fix it, let me know. Otherwise it's really not high priority at the moment.

**Comment by stefanberger** [comment]
There's a PR now: #796

**Comment by BMBurstein** [comment]
Thank you

**Comment by BMBurstein** [comment]
> > Thank you
> 
> I suppose this means that it works for you.

I didn't test it yet, but thank you for the effort either way

**Comment by stefanberger** [comment]
From what I can see I will have to revert the patch and users will have to set PATH since otherwise the test will pick up /usr/bin/swtpm_cert for example rather than the one in the path.

**Comment by arianvp** [comment]
How about we swap the order?  First look in `PATH` and *then* `BINDIR` ?  that should fix the tests *and* solve the issue of @BMBurstein  no?
