### ISSUE TITLE
Could not run '/usr/bin/swtpm_setup'

### ISSUE THREAD

**Issue by mikyjet06** [stefanberger/swtpm#797]
I am trying to setup a Windows 11 KVM on Ubuntu 22.04 I have totally purged libvirtd and installed it again. Than I installed swtpm and swtpm-tools. I still get this error. I am a very inexperienced linux user, so any advice would help a lot. I have TPM setup in virt-manager 
Type: emulated 
Model: TIS 
Version: 2.0 
When trying to run the VM I get an error saying:

`Error starting domain: internal error: Could
not run '/usr/bin/swtpm_setup'.
exitstatus: 1; Check error log
'/home/mikyjet/.cache/libvirt/qemu/log/
win11-swtpm.log' for details`

When runnin `cat /home/mikyjet/.cache/libvirt/qemu/log/
win11-swtpm.log`

I get this back:
`Starting vTPM manufacturing as mikyjet:mikyjet @ Fri 14 Apr 2023 11:15:13 AM CEST
swtpm process terminated unexpectedly.
Could not start the TPM 2.
An error occurred. Authoring the TPM state failed.
Ending vTPM manufacturing @ Fri 14 Apr 2023 11:15:13 AM CEST
`

If you have an idea why this happens, please respond.

**Comment by stefanberger** [comment]
I reported this bug now to Ubuntu here: https://bugs.launchpad.net/ubuntu/+source/swtpm/+bug/2016744

**Comment by lvoytek** [comment]
Thanks for letting me know! Apparently the upload got stuck in the SRU process at some point. I'll get it going again asap. Here's my original bug report for it: https://bugs.launchpad.net/ubuntu/+source/swtpm/+bug/1992377

**Comment by mikyjet06** [comment]
I really had no idea how to sync an AppArmor profile, so I cloned the newest repo and followed the instructions in INSTALL. It seems that all is working well now. I thought that by installing swtpm-tools with apt-get I would get the newest but seems that I was wrong. Anyway, the Windows 11 machine is now installing and getting ready to be up and running. Thank you for your help.

**Comment by stefanberger** [comment]
> Thanks for letting me know! Apparently the upload got stuck in the SRU process at some point. I'll get it going again asap. Here's my original bug report for it: https://bugs.launchpad.net/ubuntu/+source/swtpm/+bug/1992377

It may be worth it updating swtpm to a more recent version on the way, particularly if @DATAROOTDIR@ creates issues (though I wouldn't know why it would not be replaced during `configure`).
