### ISSUE TITLE
TPM self test failed

### ISSUE THREAD

**Issue by MIBc** [stefanberger/swtpm#8]
When I create a vm with tpm device using swtpm. It occurs "TPM self test failed" occasionally. The detailed message is
"tpm_tis 00:06: 1.2 TPM (device-id 0x1, rev-id 1)
 tpm_tis 00:06: A TPM error (28) occurred continue selftest
 tpm_tis 00:06: TPM self test failed". 
I have tried shutdown and boot vm for several times. The problem still appear. How can I deal with the problem, and ensure tpm device appear in vm? 
My  experiment environment is CentOS7.

**Comment by stefanberger** [comment]
Can you show the command line you are using to start swtpm and QEMU? Can you also show the contents of the directory where the swtpm stores its state in? If there are files in this directory, can you try using a different directory and try again?

**Comment by MIBc** [comment]
Command:
# modprobe cuse
# mkdir /tmp/myvtpm0
# chown -R tss:root  /tmp/myvtpm0
# swtpm_setup --tpm-state /tmp/myvtpm0  --createek
# swtpm_cuse  -n vtpm0 --tpmstate  dir=/tmp/myvtpm2
# chmod 777 /dev/vtpm0
# umount /sys/fs/cgroup/devices
# qemu-system-x86_64 -display sdl -enable-kvm  \
    -m 1024 -boot c -bios $SEABIOS/bios.bin -boot menu=on -tpmdev \
    cuse-tpm,id=tpm0,path=/dev/vtpm0 \
    -device tpm-tis,tpmdev=tpm0 <MY IMG PATH> 
# ls -al /tmp/myvtpm0
drwxrwxrwx   2 tss  root 4096 Jun 23 17:36 .
drwxrwxrwt. 14 root root 4096 Jun 23 22:14 ..
-rw-r--r--   1 tss  tss  1169 Jun 23 17:36 tpm-00.permall
I have created a new directory to store swtpm state file. The appearance still exists.

**Comment by MIBc** [comment]
>  # ls

**Comment by stefanberger** [comment]
You may have a typo there in 'swtpm_cuse -n vtpm0 --tpmstate dir=/tmp/myvtpm2' -- that should be /tmp/myvtpm0. I followed your steps with either /tmp/myvtpm2 while that dir not exist or /tmp/myvtpm with that directory existing and could not recreate the problem.

How did you build libtpms and swtpm ? Did you git pull the latest from the master branches ? Which crypto library are you using with libtpms and swtpm ?

**Comment by stefanberger** [comment]
Can you try to run the following two commands once the CUSE TPM has been started:

swtpm_ioctl -i /dev/vtpm0; echo $?
swtpm_bios --tpm-device /dev/vtpm0 -c -cs -u; echo $?

Both should complete without errors.

**Comment by MIBc** [comment]
Thanks for your patient advices. I will try it.

**Comment by MIBc** [comment]
Both libtpms and swtpm are master branch.
When I execute "swtpm_bios --tpm-device /dev/vtpm0 -c -cs -u; echo $?". The result is:
TPM_Startup(0x01) returned error code 0x0000001c
TSC_PhysicalPresence(CMD_ENABLE) returned error code 0x0000001c
TSC_PhysicalPresence(PRESENT) returned error code 0x0000001c
TPM_PhysicalEnable returned error code 0x0000001c
TPM_PhysicalSetDeactivated returned error code 0x0000001c
TPM_ContinueSelfTest returned error code 0x0000001c
TSC_PhysicalPresence(CMD_ENABLE) returned error code 0x0000001c
TSC_PhysicalPresence(NOT_PRESENT|LOCK) returned error code 0x0000001c
128

**Comment by stefanberger** [comment]
Does 'sudo make -j8 check' on the swtpm project work?

**Comment by MIBc** [comment]
My  experiment environment  is on a vm. The result of "make -j8 check"is  as follow:
FAIL: test_hashing
PASS: test_locality
PASS: test_wrongorder
FAIL: test_volatilestate
PASS: test_getcap
PASS: test_hashing2
FAIL: test_save_load_state
FAIL: test_commandline
PASS: test_init
FAIL: test_save_load_state_2
FAIL: test_migration_key
FAIL: test_save_load_encrypted_state_2
PASS: test_swtpm_cert
FAIL: test_migration_key_2
FAIL: test_save_load_encrypted_state
FAIL: test_swtpm_setup_create_cert
FAIL: test_parameters
PASS: test_resume_volatile
FAIL: test_ctrlchannel
FAIL: test_swtpm_bios
FAIL: test_ctrlchannel2

**Comment by stefanberger** [comment]
What Linux distribution and version are you using ? Do you have a different version or different distribution where you could try it ?

**Comment by silenceli** [comment]
I meet this issue too as MIBc said.
env:
host os:

**Comment by stefanberger** [comment]
I built the libtpms and openssl and with 'make check -j1' I see one error that is due to the error reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1126097 . It occurs in the last test case in 'test_parameters'. I built libtpms and swtpm with openssl (--with-openssl). In case you build RPMs, for libtpms I edited dist/libtpms.spec.in (before running configure) to use the crypto_subsystem openssl rather than freebl.

I see these errors also when using the freebl library version 3.16.2.3-14.2 (nss-softkn-*-3.16.2.3-14.2.el7_2.x86_64). In a backtrace it shows that on Centos the freebl function TPM_SHA1Delete() function causes an abort and was called from libtpms's TPM_SHA1_Check() . When building with the same source code on Fedora 23 with freebl 3.23.0-1.0.fc23.x86_64 (nss-softokn-*-3.23.0-1.0.fc23.x86_64) the errors do not occur.

**Comment by stefanberger** [comment]
Actually the problem is related to this report I filed in 8/2015: https://bugzilla.redhat.com/show_bug.cgi?id=1249720

I do not know why I saw crashes yesterday.
So the best way to work around this FreeBL problem is to compile libtpms and swtpm with openssl. With the latest git head one can build libtpms with openssl library rpm using the following command lines

./bootstrap.sh
./configure
make dist
mkdir -p ~/rpmbuild/SOURCES
cp libtpms-0.6.0.tar.gz ~/rpmbuild/SOURCES
rpm-build -ba --define 'crypto_subsystem openssl' dist/libtpms.spec

After that the resulting packages in ~/rpmbuild/RPMS/x86_64/ can be installed. One just has to pay attention that no other libtpms library installations are anywhere in the filesystem (/lib/ for example). Run 'ldconfig -v' to find them.

**Comment by stefanberger** [comment]
With the latest version of swtpm, one can now also build RPMs where swtpm uses openssl (assuming that libtpms also uses openssl):

./bootstrap.sh
./configure --with-openssl
make dist
mkdir -p ~/rpmbuild/SOURCES
cp swtpm-0.x.y.tar.gz ~/rpmbuild/SOURCES
rpm-build -ba --define 'crypto_subsystem openssl' dist/swtpm.spec

Then install all the swtpm packages.

**Comment by MIBc** [comment]
I will try it. Thank you very much.

**Comment by MIBc** [comment]
When I use "rpm-build -ba --define 'crypto_subsystem openssl' dist/swtpm.spec"
make[3]: Entering directory `/root/rpmbuild/BUILD/swtpm-0.1.0/tests'
PASS: test_init
PASS: test_getcap
FAIL: test_hashing
PASS: test_locality
FAIL: test_hashing2
PASS: test_wrongorder
FAIL: test_volatilestate
FAIL: test_save_load_encrypted_state
FAIL: test_save_load_encrypted_state_2
PASS: test_encrypted_state
FAIL: test_save_load_state
FAIL: test_migration_key
FAIL: test_save_load_state_2
FAIL: test_commandline
FAIL: test_ctrlchannel
FAIL: test_ctrlchannel2
FAIL: test_migration_key_2
FAIL: test_parameters
FAIL: test_resume_volatile
PASS: test_swtpm_cert
FAIL: test_swtpm_bios
FAIL: test_swtpm_setup_create_cert
make[4]: Entering directory `/root/rpmbuild/BUILD/swtpm-0.1.0/tests'
make[4]: Nothing to be done for `all'.
make[4]: Leaving directory `/root/rpmbuild/BUILD/swtpm-0.1.0/tests'
============================================================================
Testsuite summary for swtpm 0.1.0
============================================================================
# TOTAL: 22
# PASS:  6
# SKIP:  0
# XFAIL: 0
# FAIL:  16
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/root/rpmbuild/BUILD/swtpm-0.1.0/tests'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/root/rpmbuild/BUILD/swtpm-0.1.0/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/root/rpmbuild/BUILD/swtpm-0.1.0/tests'
make: *** [check-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.LNTg31 (%check)
It seems the command "make -j2 check" is  executed.
Will the swtpm be normal ,if all tests are passed?
In addition, my system has installed openssl.

**Comment by stefanberger** [comment]
Did you update the swtpm and libtpms checkouts to the tip of the tree? Otherwise the 'crypto_subsystem openssl'  parameter has no effect. You have to build and install libtpms with openssl crypto library first.

Can you cut and paste the contents of tests/test_ctrlchannel.log ?

**Comment by MIBc** [comment]
I have executed "make uninstall" and downloaded the lastest code both libtpms and swtpm. Everything is fine, but when execute "rpm-build -ba --define 'crypto_subsystem openssl' dist/swtpm.spec" it still exposed that problem above. The content of test_ctrlchannel.log is: 
Error: Unknown command: 0x0000ffff
OK
Error: Unknown command: 0x0000ffff
  SWTPM_IO_Read: through paramSize length 6
 00 C1 00 00 00 0C 
 SWTPM_IO_Read: length 12
 00 C1 00 00 00 0C 00 00 00 99 00 01 
 SWTPM_IO_Write: length 10
 00 C4 00 00 00 0A 00 00 00 1C 
Error: Did not get expected result from TPM_Startup(ST_Clear)
expected:  00 c4 00 00 00 0a 00 00 00 00
received:  00 c4 00 00 00 0a 00 00 00 1c

**Comment by stefanberger** [comment]
On CentOS 7.2 I can only recreate this problem when using FreeBL, but the test suite passes without errors when using OpenSSL (./configure --prefix=/usr --with-openssl).

Actually, when using FreeBL I run ./tests/test_ctrchannel from the shell several times and get different results. This reflects the error report here https://bugzilla.redhat.com/show_bug.cgi?id=1249720 where some of the tests occasionally pass and sometimes they fail or they fail at different places.

**Comment by MIBc** [comment]
@stefanberger, just taking tests/test_hashing as the example. I build swtpm with openssl, and then run individual case (test_hashing) multiple times, the result is wired (as mentioned in below paste). So, how to explain the test result?

[root@test tests]# bash test_hashing
root     16315  0.0  0.0 267684  2116 ?        Ssl  20:05   0:00 /root/ljw/swtpm/src/swtpm/.libs/lt-swtpm_cuse -n xxxx
root     19198  0.0  0.0 125856  2736 ?        Ssl  20:24   0:00 /root/ljw/swtpm/src/swtpm/.libs/lt-swtpm_cuse -n vtpm-test-hashing
root     26596  0.0  0.0 268260  4048 ?        Ssl  Jul02   0:00 /bin/swtpm_cuse -n vtpm0 --tpmstate dir=/tmp/myvtpm2
Error: Did not get expected result from TPM_Startup(ST_Clear)
expected:  00 c4 00 00 00 0a 00 00 00 00
received:  00 c4 00 00 00 0a 00 00 00 1c
[root@test tests]# bash test_hashing
root     16315  0.0  0.0 267684  2116 ?        Ssl  20:05   0:00 /root/ljw/swtpm/src/swtpm/.libs/lt-swtpm_cuse -n xxxx
root     19249  0.0  0.0 125856   688 ?        Ssl  20:24   0:00 /root/ljw/swtpm/src/swtpm/.libs/lt-swtpm_cuse -n vtpm-test-hashing
root     26596  0.0  0.0 268260  4048 ?        Ssl  Jul02   0:00 /bin/swtpm_cuse -n vtpm0 --tpmstate dir=/tmp/myvtpm2
OK
