### ISSUE TITLE
On Fedora the libseccomp-devel was missing in dependencies to build

### ISSUE THREAD

**Issue by dombrowa** [stefanberger/swtpm#808]
**Describe the bug**

On Fedora the libseccomp-devel was missing in the dependencies to build the code

configure: error: "Is libseccomp-devel installed? -- could not get cflags for libseccomp"

**Required: To Reproduce (without these steps your issue may be deleted)**

    git clone https://github.com/stefanberger/swtpm.git
    pushd swtpm
    # Install dependencies using dnf (RHEL, Fedora)
    sudo dnf -y install libtasn1-devel expect socat python3-twisted fuse-devel glib2-devel gnutls-devel gnutls-utils gnutls json-glib-devel
    ./autogen.sh --with-openssl --prefix=/usr
    make -j4
    # Depending on how many CPUs you have, choose the -j parameter
    # carefully for the next command. The tests work on Raspberry PI 2
    # for example but only if run with '-j1', otherwise timeouts may
    # occur.
    make -j4 check
    sudo make install

**Expected behavior**

No error regarding missing libs to compile

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 37

**Versions of relevant components**
- swtpm:
- libtpms:
- openssl:
- gnutls:
- ...:

**Log files**
Please attach any log files. If using a VM and it was started with libvirt, attach the logfile  found in `/var/log/swtpm/libvirt/qemu/VM-NAME-swtpm.log`.

**Additional context**
The package to install was
sudo dnf install libseccomp-devel

**Comment by dombrowa** [comment]
Most people use default, and as such without customization, the default
configure results in a failed compile.

**Comment by dombrowa** [comment]
It is not a bug, but a feature.

**Comment by stefanberger** [comment]
On Linux it forces the user to install seccomp devel support...
