### ISSUE TITLE
About 0.8.1 release

### ISSUE THREAD

**Issue by chenrui333** [stefanberger/swtpm#817]
👋 it looks like 0.8.1 did not get marked as latest release, raise this issue for awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/139652

**Comment by stefanberger** [comment]
The reason may be that I had not created the release here on github. Now it's here: https://github.com/stefanberger/swtpm/releases/tag/v0.8.1

**Comment by stefanberger** [comment]
That's interesting. homegrew infrastructure reacts to me creating a release page not to me tagging the repo.
