### ISSUE TITLE
To delete

### ISSUE THREAD

**Issue by iulko** [stefanberger/swtpm#832]
To Delete

**Comment by stefanberger** [comment]
Since I am not working on VirtualBox I am afraid but I cannot help you with this.

swtpm for example tries to mitigate file corruption issues by using a temporary file where the current state is written into and then the file is renamed to its usual/final filename.

**Comment by iulko** [comment]
> Since I am not working on VirtualBox I am afraid but I cannot help you with this.
> 
> swtpm for example tries to mitigate file corruption issues by using a temporary file where the current state is written into and then the file is renamed to its usual/final filename.

Sorry, I know this bug is not your but of Virtualbox.
But I saw that virtualbox is using your library to emulate TPM, thats why I thought maybe you could have some idea how to fix the permall. Like some way to try to export it to a fresh not corrupted file or something like that. I have valuable data encrypted with it thats why I was desperate enaught to write here :(

**Comment by stefanberger** [comment]
> > Since I am not working on VirtualBox I am afraid but I cannot help you with this.
> > swtpm for example tries to mitigate file corruption issues by using a temporary file where the current state is written into and then the file is renamed to its usual/final filename.
> 
> Sorry, I know this bug is not your but of Virtualbox. But I saw that virtualbox is using your library to emulate TPM, thats why I thought maybe you could have some idea how to fix the permall. Like some way to try to export it to a fresh not corrupted file or something like that. I have valuable data encrypted with it thats why I was desperate enaught to write here :(
> 
> A way do decrypt it to readable form would be a bit helpfull I guess.

I cannot fix a corrupted file, either.
Are they just using libtpms or also swtpm?

**Comment by iulko** [comment]
libtpms I guess, sorry im not that knowlegable but thats what they wrote on forum and looking at the code but also swtpm in other parts.
The corruption can be possibly something silly as I see that file is closed and opened proper way looking at begining and end of the file in corrupted and comapring to a working file.

**Comment by stefanberger** [comment]
I would suggest to ask the VirtualBox folks whether they can also work with two files (temporary file being renamed to permanent file) to mitigate corruption issues.

**Comment by iulko** [comment]
I will make sure to let them know to make this happen so other people dont suffer this.
But my problem will still be here so:

I'm willing to compensate you in crypto (1000$) for your time up front if you help me fix the file or check if its salvagable. I dont know if its a faux pas to offer but im desperate.

Anyway sorry for taking your time with this.

**Comment by stefanberger** [comment]
Send me the file and I can have a look at it. You can donate the money in case of success.

**Comment by iulko** [comment]
OK, here is the file, let me know when you got it so I can delete it, even tho I dont think anything of value is there as its just keys witchout data

[permall.zip](https://github.com/stefanberger/swtpm/files/13348699/permall.zip)

**Comment by stefanberger** [comment]
Got it.

**Comment by stefanberger** [comment]
It  will be a while until I get to looking at it,though.

**Comment by iulko** [comment]
> It will be a while until I get to looking at it,though.

No problem, thanks

**Comment by stefanberger** [comment]
I tried to read the file and it read just fine with libtpms v0.9.6. Did you maybe downgrade to an older version of VirtualBox from a more recent one and with this you could have downgraded to a previous version of libtpms that cannot read the more recent format. I am don't know what versions of libtpms they may have used.

**Comment by iulko** [comment]
> I tried to read the file and it read just fine with libtpms v0.9.6 and the TPM 2 also started up properly. Did you maybe downgrade to an older version of VirtualBox from a more recent one and with this you could have downgraded to a previous version of libtpms that cannot read the more recent format. I am don't know what versions of libtpms they may have used.

Yes, on Virtualbox 7.0.12 it gets loaded properly but still no TPM2 option in UEFI. Maybe the file lack some variable that is needed. Is there a way to convert the file to more user friendly format?

**Comment by stefanberger** [comment]
> > I tried to read the file and it read just fine with libtpms v0.9.6 and the TPM 2 also started up properly. Did you maybe downgrade to an older version of VirtualBox from a more recent one and with this you could have downgraded to a previous version of libtpms that cannot read the more recent format. I am don't know what versions of libtpms they may have used.
> 
> Yes, on Virtualbox 7.0.12 it gets loaded properly but still no TPM2 option in UEFI. Maybe the file lack some variable that is needed. Is there a way to convert the file to more user friendly format so I can compare variables with working permall? Or export them to new file, maybe there is some problem with lines, enconding or idk

There's no way to convert the file into another format. The file format seems just fine otherwise libtpms wouldn't be able to read it, so there's nothing wrong with lines, encoding etc.

Are you saying that under normal conditions there's TPM2 support in UEFI but with this file there isn't?

> 
> I will also try run the file in Qemu

It won't load with swtpm since swtpm adds its own header in front of it. What you have is a plain libtpms state file.

**Comment by iulko** [comment]
> There's no way to convert the file into another format. The file format seems just fine otherwise libtpms wouldn't be able to read it, so there's nothing wrong with lines, encoding etc.

I see, than it have to be something about variables or lack of them

> 
> Are you saying that under normal conditions there's TPM2 support in UEFI but with this file there isn't?

Yes, exacly, the menu options dissapears completly "TCG2"

So my last ditch idea is to provide you with working permall that have also bitlocker enabled, maybe you could see if something is missing, some variables

[permall_good.zip](https://github.com/stefanberger/swtpm/files/13358067/permall_good.zip)

**Comment by stefanberger** [comment]
> > There's no way to convert the file into another format. The file format seems just fine otherwise libtpms wouldn't be able to read it, so there's nothing wrong with lines, encoding etc.
> 
> I see, than it have to be something about variables or lack of them
> 
> > Are you saying that under normal conditions there's TPM2 support in UEFI but with this file there isn't?
> 
> Yes, exacly, the menu options dissapears completly "TCG2"
> 
> So my last ditch idea is to provide you with working permall that have also bitlocker enabled, maybe you could see if something is missing, some variables
> 
> [permall_good.zip](https://github.com/stefanberger/swtpm/files/13358067/permall_good.zip)

The problems is none of the (TPM2/TSS2) tools I would be using with swtpm would work with this plain file that cannot be read by swtpm...

**Comment by iulko** [comment]
> > > There's no way to convert the file into another format. The file format seems just fine otherwise libtpms wouldn't be able to read it, so there's nothing wrong with lines, encoding etc.
> > 
> > 
> > I see, than it have to be something about variables or lack of them
> > > Are you saying that under normal conditions there's TPM2 support in UEFI but with this file there isn't?
> > 
> > 
> > Yes, exacly, the menu options dissapears completly "TCG2"
> > So my last ditch idea is to provide you with working permall that have also bitlocker enabled, maybe you could see if something is missing, some variables
> > [permall_good.zip](https://github.com/stefanberger/swtpm/files/13358067/permall_good.zip)
> 
> The problems is none of the (TPM2/TSS2) tools I would be using with swtpm would work with this plain file that cannot be read by swtpm...

Ahh I get it libtpms files cannot be read by swtpm tools... well im running out of ideas, I will be back if I think of something

**Comment by iulko** [comment]
Issue to delete
