### ISSUE TITLE
Openstack 2023.1 - Not Working

### ISSUE THREAD

**Issue by noelashford** [stefanberger/swtpm#836]
Hello, I managed (with pain as the kolla-ansible images are missing swtpm) to get it installed, but then the instructions seem broken somehow and its widely NOT supported seemingly... ? 

https://docs.openstack.org/nova/latest/admin/emulated-tpm.html 

There is no such thing as a resource provider & setting it anyways manually causes the VM to not load - is there a working guide out there? Any idea on the issue ?

**Comment by stefanberger** [comment]
> There is no such thing as a resource provider & setting it anyways manually causes the VM to not load - is there a working guide out there? Any idea on the issue ?

I cannot help you with this. You would have to ask around in the OpenStack community.

**Comment by noelashford** [comment]
I had tried that - was a last ditch effort here as the Openstack community hasn't had responses on this in over a year nor a bug assigned etc. Seems to be dropped.

**Comment by stefanberger** [comment]
Closing this issue since swtpm project cannot solve this issue.
