### ISSUE TITLE
Disable test dependencies for normal build

### ISSUE THREAD

**Issue by jarkkojs** [stefanberger/swtpm#843]
Allow to build the image without socat and expect as they are required only for tests. This will make the project compatible with embedded build systems such as Yocto and BuildRoot.

**Comment by jarkkojs** [comment]
Have not used Yocto for this, only BuildRoot but usually they have somewhat matching issues, so this should help in both environments.

**Comment by jarkkojs** [comment]
OK, th

> > Have not used Yocto for this, only BuildRoot but usually they have somewhat matching issues, so this should help in both environments.
> 
> Yocto/meta-security already builds it: https://layers.openembedded.org/layerindex/recipe/319192/ I may add a `--without-test` option to configure.

A configure option would be good enough for BuildRoot. I.e. it does not require too much drift. So +1 for that.

**Comment by stefanberger** [comment]
PR #844

**Comment by jarkkojs** [comment]
> PR #844

Can you also point this out in the associated email thread in BuildRoot mailing list. I'll try this now and comment to the pull request, thanks!
