### ISSUE TITLE
Tool dependencies and development branch for vTPM 2.0 instance

### ISSUE THREAD

**Issue by mrcdb** [stefanberger/swtpm#85]
I am trying to compile and deploy the an swtpm instance based on TPM 2.0 specifications, and I cannot find on the wiki which is the suggested development branch for `swtpm` and  `libtpms`.  I see that there are multiple preview branches on both projects, and I would suggest to improve the Wiki (or README) to make it clearer for testers.

**Comment by stefanberger** [comment]
Everything is in the master branches now.

**Comment by mrcdb** [comment]
Thanks for the quick response. The thread can be closed now.
