### ISSUE TITLE
swtpm-selinux scriptlet uses /usr/sbin/rm, which does not exist

### ISSUE THREAD

**Issue by VGerris** [stefanberger/swtpm#854]
**Describe the bug**

swtpm-selinux-0.8.1-11.fc40.noarch scriplet uses /usr/sbin/rm which does not exist :
/var/tmp/rpm-tmp.Ry1Vom: line 13: /usr/sbin/rm: No such file or directory

**Required: To Reproduce (without these steps your issue may be deleted)**

Steps to reproduce the behavior/issue showing all commands on command line, needed XML or JSON (if necessary), etc.:

 1. sudo dnf update where new version is : 
 2.   Upgrading        : swtpm-selinux-0.8.1-11.fc40.noarch                                                                                                  12/132 
  Running scriptlet: swtpm-selinux-0.8.1-11.fc40.noarch                                                                                                  12/132 
/var/tmp/rpm-tmp.Ry1Vom: line 13: /usr/sbin/rm: No such file or directory
/var/tmp/rpm-tmp.Ry1Vom: line 13: /usr/sbin/rm: No such file or directory
/var/tmp/rpm-tmp.Ry1Vom: line 13: /usr/sbin/rm: No such file or directory

**Expected behavior**
No errors in scriptlet output 

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 40

**Versions of relevant components**
- swtpm:
-  swtpm-selinux-0.8.1-11.fc40.noarch 
  Upgrading        : swtpm-libs-0.8.1-11.fc40.x86_64                                                                                                     10/132 
  Upgrading        : swtpm-0.8.1-11.fc40.x86_64 
- gnutls:
- ...:

**Additional context**

Happened today on Fedora 40 where package was installed and upgraded.
Suggestion is to change it :
$ which rm
/usr/bin/rm

to /usr/bin/rm

**Comment by stefanberger** [comment]
Problem discussed here: https://bugzilla.redhat.com/show_bug.cgi?id=2283639

I pushed a new version of the package to stable. It should be available soon/tomorrow.

**Comment by VGerris** [comment]
great, thank you. I couldn't find it in the source code, nor the packaging scripts, was trying to make a PR. I am glad it is resolved, I will close this then.
Thank you!
