### ISSUE TITLE
Installation process on host fails if host has a TPM 2.0

### ISSUE THREAD

**Issue by mrcdb** [stefanberger/swtpm#88]
The dependency on `tpm-tools`, hence on `trousers`, generates an error when installing the dependencies required to build and install `swtpm` on a host machine equipped with TPM 2.0. The `tcsd` daemon (belonging to TSS 1.2) starts with the following error:
```
invoke-rc.d: initscript trousers, action "start" failed.
● trousers.service - LSB: starts tcsd
   Loaded: loaded (/etc/init.d/trousers; generated)
   Active: failed (Result: exit-code) since Wed 2018-11-07 14:41:14 UTC; 6ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 690 ExecStart=/etc/init.d/trousers start (code=exited, status=137)

Starting LSB: starts tcsd...
* Starting Trusted Computing daemon tcsd
/etc/init.d/trousers: 32: [: /dev/tpm0: unexpected operator
      ...fail!
trousers.service: Control process exited, code=exited status=137
trousers.service: Failed with result 'exit-code'.
Failed to start LSB: starts tcsd.
dpkg: error processing package trousers (--configure):
 installed trousers package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of tpm-tools:
 tpm-tools depends on trousers; however:
  Package trousers is not configured yet.

dpkg: error processing package tpm-tools (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 trousers
 tpm-tools
```

Is `tpm-tools` required in the build and installation of `swtpm` or only when instantiating a vTPM 1.2? Can I skip this dependency with no problem?

**Comment by mrcdb** [comment]
I see that `tpm-tools` is a dependency for `swtpm-tools` project. Can I skip the compilation of this project (I think it would still be unusable if I virtualise only TPM 2.0 devices, right?).

**Comment by stefanberger** [comment]
Solutions for you would be to either locally modify the dependencies or ignore the configuration error. The more long-term solution is to file a bug report with Ubuntu and tell them to not start the tcsd daemon automatically if there's no TPM 1.2 on the system. I can do the latter.

**Comment by mrcdb** [comment]
A workaround for the moment would be to mask the `trousers` service before it is installed by `tpm-tools`. This can be done as follows (as the service is not yet installed):
```
# ln -s /dev/null /etc/systemd/system/trousers.service
```
A subsequent call to `apt install tpm-tools` succeeds on a TPM 2.0 equipped host now.

**Comment by stefanberger** [comment]
I filed the following bug now with Debian: https://bugs.launchpad.net/ubuntu/+source/trousers/+bug/1802133

I certainly hope that they will react.

**Comment by mrcdb** [comment]
Fine. The issue can be closed now.
