### ISSUE TITLE
Help with installation, v 0.10 not found

### ISSUE THREAD

**Issue by ramrattle** [stefanberger/swtpm#886]
Hi,
I'm using ubuntu 22.04 to compile the repo, it gives the below error

configure: error: "libtpms >= 0.10 required or no libtpms.pc found; please set PKG_CONFIG_PATH to the directory where libtpms.pc is located"

I'm seeing the that  https://github.com/stefanberger/libtpms/releases has only version upto 0.9.6, how do I get version 0.10?

I tried Upgrade which also shows below message, meaning 0.10 is not there.

Can you please help me with this? have I configured the path wrongly or 0.10 is a typo for 0.1.0 in the code?

apt-get install libtpms-dev
libtpms-dev is already the newest version (0.9.3-0ubuntu1.22.04.1).

**Comment by stefanberger** [comment]
> Can you please help me with this? have I configured the path wrongly or 0.10 is a typo for 0.1.0 in the code?

Until libtpms v0.10 is released you will have to git clone its repo and build it yourself.

**Comment by stefanberger** [comment]
libtpms v0.10 is now available on my Ubuntu PPA for Noble, Jammy, and Focal: https://launchpad.net/~stefanberger
swtpm v0.10 is also available from there.

**Comment by ramrattle** [comment]
Appreciate the support and follow up !!
