### ISSUE TITLE
swtpm_setup use block device as it's state file

### ISSUE THREAD

**Issue by liyang2018** [stefanberger/swtpm#895]
hello,everyone, swtpm_setup has already support block device as tpm state file. if so, how to use block device as tpm state file? thanks

**Comment by stefanberger** [comment]
swtpm_setup says this in the man page:

```
       --tpm-state <dir> or --tpmstate <dir>
           Path  where the TPM’s state will be written to; this is a mandatory argument.  Prefix with dir:// to use directory
           backend, or file:// to use linear file.
```

wwtpm man page say this:

```
       --tpmstate dir=<dir>[,mode=<0...>]|backend-uri=<uri>
           Use the given path rather than using the environment variable TPM_PATH.

           If dir is specified, the TPM state files will be written to the dir with the given file mode bits. This value must
           be given as an octal number starting with a ’0’.  The default value is 0640.

           If   backend‐uri   is   specified,   the   TPM   state   data   will   be   stored   to   the   URI.     Currently
           backend-uri=dir://<path_to_dir>  and  backend-uri=file://<path_to_dir> are available. For ’dir://’, the URI should
           specify the path to the directory where files are stored. If path_to_dir starts  with  a  ’/’  then  the  path  is
           interpreted as an absolute path, otherwise it is a path relative to the current directory.  For ’file://’, the URI
           should  specify a single file or block device where TPM state will be stored. A blockdevice must exist already and
           be big enough to store all state. (since v0.7)
```

If you used file:// with swtpm_setup you have to use backend-uri=file://<path_to_dir> with swtpm later on.

**Comment by liyang2018** [comment]
Thank you for the answer! according swtpm man page, i create a linear lv:

 [root@localhost cloud]# lvcreate -L 2G lytest 
WARNING: ext3 signature detected on /dev/lytest/lvol0 at offset 1080. Wipe it? [y/n]: y
  Wiping ext3 signature on /dev/lytest/lvol0.
  Logical volume "lvol0" created.

but when i use swtpm_setup to initialize this lv as a tpmstate file, i get an error:

[root@localhost cloud]# swtpm_setup --tpmstate file:///dev/lytest/lvol0 --tpm2 --create-ek-cert --overwrite --create-platform-cert
Error: file:///dev/lytest/lvol0 is not a directory that user root could access.

am I missing something? please help me.

**Comment by stefanberger** [comment]
What version of swtpm are you using?

**Comment by liyang2018** [comment]
sorry, it's my mistakes, swtpm* version: 
[root@localhost cloud]# swtpm_setup --version 
TPM emulator setup tool version 0.3.3

[root@localhost cloud]# swtpm --version 
TPM emulator version 0.3.3, Copyright (c) 2014 IBM Corp.

[root@localhost cloud]# rpm -qa|grep swtpm 
swtpm-0.3.3-7.oe2203sp3.x86_64
swtpm-libs-0.3.3-7.oe2203sp3.x86_64
swtpm-tools-0.3.3-7.oe2203sp3.x86_64

**Comment by stefanberger** [comment]
> Thanks you very much!

You're welcome. We can probably close this issue now.
