### ISSUE TITLE
Where are the UUIDs stored in the Ubuntu?

### ISSUE THREAD

**Issue by PenguinKingNo1** [stefanberger/swtpm#9]
Hi,

I'm using swtpm and it works well. I also use TrouSers to play with the emulated TPM. 

But I cannot find where the UUIDs for registered keys are stored in the OS. 

So for example one day I created a key with UUID 001 using TPM1, then I cannot use that UUID for other keys when I use TPM1. That makes sense. But when I delete all files about TPM1 and set up a new TPM, say TPM2, that UUID 001 still cannot be used. I think this is not good because each time I change a new TPM I cannot use the UUIDs once used by previous devices, even though the previous devices are never used again.

Could you tell me where the UUID are stored in the Ubuntu System? 

Thanks so much!

**Comment by stefanberger** [comment]
I think it would be ~/.trousers/ . If not , please as on the TrouSerS mailing list.
