### ISSUE TITLE
Build failed if use openssl version 1.1.1

### ISSUE THREAD

**Issue by DingXinX** [stefanberger/swtpm#91]
When I compile swtpm, it has the following dependency: swtpm => tpm-tools => trousers => openssl. If I use openssl -1.0.2, then all (include trousers/tpm-tools/swtpm) can build well. But if we upgrade openssl from openssl-1.0.2 to openssl-1.1.1, then I met the following issue when build for trousers: 
--------------------------------------------------------------------------------------------------
mv -f .deps/libtrousers_la-trousers.Tpo .deps/libtrousers_la-trousers.Plo
crypto/openssl/hash.c: In function 'Trspi_Hash':
crypto/openssl/hash.c:59:13: error: storage size of 'md_ctx' isn't known
  EVP_MD_CTX md_ctx;
             ^~~~~~
crypto/openssl/hash.c:59:13: warning: unused variable 'md_ctx' [-Wunused-variable]
crypto/openssl/hash.c: In function 'Trspi_HashInit':
crypto/openssl/hash.c:115:32: error: invalid application of 'sizeof' to incomplete type 'EVP_MD_CTX' {aka 'struct evp_md_ctx_st'}
  if ((ctx->ctx = malloc(sizeof(EVP_MD_CTX))) == NULL)
                                ^~~~~~~~~~
crypto/openssl/symmetric.c: In function 'Trspi_Encrypt_ECB':
crypto/openssl/symmetric.c:55:17: error: storage size of 'ctx' isn't known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/openssl/symmetric.c:55:17: warning: unused variable 'ctx' [-Wunused-variable]
crypto/openssl/symmetric.c: In function 'Trspi_Decrypt_ECB':
crypto/openssl/symmetric.c:102:17: error: storage size of 'ctx' isn't known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/openssl/symmetric.c:102:17: warning: unused variable 'ctx' [-Wunused-variable]
crypto/openssl/symmetric.c: In function 'Trspi_SymEncrypt':
crypto/openssl/symmetric.c:258:17: error: storage size of 'ctx' isn't known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/openssl/symmetric.c:258:17: warning: unused variable 'ctx' [-Wunused-variable]
crypto/openssl/symmetric.c: In function 'Trspi_SymDecrypt':
crypto/openssl/symmetric.c:332:17: error: storage size of 'ctx' isn't known
  EVP_CIPHER_CTX ctx;
                 ^~~
crypto/openssl/symmetric.c:332:17: warning: unused variable 'ctx' [-Wunused-variable]
make[2]: *** [Makefile:415: libtrousers_la-hash.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:429: libtrousers_la-symmetric.lo] Error 1
crypto/openssl/rsa.c: In function 'Trspi_RSA_Encrypt':
crypto/openssl/rsa.c:71:5: error: dereferencing pointer to incomplete type 'RSA' {aka 'struct rsa_st'}
  rsa->n = BN_bin2bn(publicKey, keysize, rsa->n);
     ^~
make[2]: Leaving directory '/builddir/build/BUILD/trousers-TROUSERS_0_3_7/src/trspi'
make[2]: *** [Makefile:422: libtrousers_la-rsa.lo] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/trousers-TROUSERS_0_3_7/src'
make[1]: *** [Makefile:358: all-recursive] Error 1
make: *** [Makefile:396: all-recursive] Error 1
-------------------------------------------------------------------------------------------------------

**Comment by stefanberger** [comment]
You should probably get the latest version of TrouSerS from the git repo.

This error here seems to hint at you using an older version:
```
crypto/openssl/hash.c: In function 'Trspi_Hash':
crypto/openssl/hash.c:59:13: error: storage size of 'md_ctx' isn't known
EVP_MD_CTX md_ctx;
```

`md_ctx` is now a pointer:

```
TSS_RESULT
Trspi_Hash(UINT32 HashType, UINT32 BufSize, BYTE* Buf, BYTE* Digest)
{
        EVP_MD_CTX *md_ctx;
        unsigned int result_size;

```

**Comment by stefanberger** [comment]
Since this is TrouSerS related, I am going to close this issue now.
