### ISSUE TITLE
Configuration of swtpm

### ISSUE THREAD

**Issue by qemu-enjoyer** [stefanberger/swtpm#939]
I made a virtual machine using virt-manager and Libvirt+QEMU with an emulated TPM CRB 2.0, but the guest OS sees the TPM manufacturer as IBM and the signing cert as SW%20%20%20TPM and I wanted to know if changing this was possible?

I looked at the project's wiki but it didn't help much. Libvirt itself also doesn't provide any instructions on doing this, which is why I'm creating the issue here.

Thanks in advance.

**Comment by stefanberger** [comment]
That screenshot you are showing most likely reflects the TPM's data where also IBM is written into it. Current libtpms master branch:
```
src/tpm2/VendorInfo.c:73:#define MANUFACTURER    "IBM"
```

**Comment by qemu-enjoyer** [comment]
After following your instructions it now works as expected, thank you so much!

![image](https://github.com/user-attachments/assets/9035f9d4-ac4a-47e3-b93b-2e5c955fa41d)

**Comment by qemu-enjoyer** [comment]
Hey, this might be kind of unrelated but I couldn't find an answer for it on the kernel mailing list or any patches for it that would work and I thought maybe you'd know since you're somewhat involved with the kernel.

In KVM virtual machines there's no support for MBEC (mode-based execution control) which makes windows perform terribly (~80% downgrade in performance) when memory integrity/HVCI is enabled (because it's having to emulate the functionality of MBEC with something called Restricted User Mode/RUM that Microsoft made) compared to baremetal which doesn't happen when only Hyper-V is enabled with nested VMX in the VM.

I found a patch on the kernel mailing list that adds MBEC support to KVM but it doesn't implement it for L1 and L2 which I guess is why windows still doesn't report MBEC as available even after applying the patch.

Would you happen to know any fixes for this? Thanks in advance.

**Comment by stefanberger** [comment]
> Would you happen to know any fixes for this? Thanks in advance.

I am not familiar with this issue, so no, I don't any fixes.

**Comment by qemu-enjoyer** [comment]
Oh, I see. Well thank you for your help anyway.
