### ISSUE TITLE
test_tpm2_swtpm_cert_ecc case fail when upgrade gnutls to 3.6.3

### ISSUE THREAD

**Issue by DingXinX** [stefanberger/swtpm#97]
When run "make check" under swtpm (gnutls version: 3.6.3), test_tpm2_swtpm_cert_ecc case fails, log as follows:
FAIL: test_tpm2_swtpm_cert_ecc
==============================

Test 1: OK
Test 2: OK
Could not set public EK on CRT: The request is invalid.
Error: /home/bob/workdir/source_code/swtpm/src/swtpm_cert/swtpm_cert returned error code.
FAIL test_tpm2_swtpm_cert_ecc (exit status: 1)

But in gnutls version for 3.4.10, this case is correct. So I need to ask your help to see whether there is a better way to solve, in gnutls (3.6.3).

**Comment by stefanberger** [comment]
This is the same error message we had with gnutls when it did not work.

**Comment by stefanberger** [comment]
Here's the bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1612803. It was a bug in gnutls that has since been fixed.
